apps/explorer/src/main.tsx, package.json, yarn.lock
Add sentry for the block explorer (env variables are configured for this in netlify)
=> Explorer: add sentry

apps/explorer/.env, apps/explorer/src/app/lib/flags.ts, apps/explorer/src/app/routes/router-config.tsx
=> Explorer: allow flagging of nice to have routes

apps/explorer/src/app/components/nav/index.tsx
=> frontend-monorepo-43 Nav Styles

.github/workflows/test.yml
=> add workflow for lint, build and format

apps/explorer/src/app/app.spec.tsx, apps/explorer/src/app/components/nav/index.tsx, apps/explorer/src/app/routes/router-config.tsx
Based on @candida-d's feedback
=> allow nav text to be different to route name

apps/explorer-e2e/src/integration/home-page.feature, apps/explorer-e2e/src/support/pages/base-page.js, apps/explorer-e2e/src/support/step_definitions/common.step.js
Additional Cypress tests for the search functionality on Block explorer
Closes #66
=> Additional search tests added

apps/explorer/src/app/App.scss
=> frontend-monorepo-137 Remove top white border

apps/explorer/src/app/components/blocks/block-data.tsx, apps/explorer/src/app/routes/blocks/id/index.tsx
=> frontend-monorepo-134 Ensure displayed ids are using mono font

apps/trading/.env, apps/trading/.env.devent, apps/trading/.env.mainnet, apps/trading/.env.stagnet1, apps/trading/.env.stagnet2, apps/trading/.env.testnet, apps/trading/lib/web3-connectors.ts
- Remove stray semicolons for .env files
- Remove typo when referencing env var i napp
=> Fix/Typos in Infura env var

apps/explorer/src/app/app.tsx
=> Feat/181 Remove bottom app border

libs/ui-toolkit/src/components/input/input.tsx
=> Fix / 120 input hasError fix

libs/ui-toolkit/src/components/input/input.tsx
=> Feat / 200 remove input rounded edges on ios

libs/network-stats/README.md
=> Feat/190 Add env vars details to stats readme

apps/trading/pages/markets/trade-grid.tsx, libs/react-helpers/src/lib/generic-data-provider.ts, libs/trades/.babelrc, libs/trades/.eslintrc.json, libs/trades/README.md, libs/trades/jest.config.js, libs/trades/package.json, libs/trades/project.json, libs/trades/src/index.ts, libs/trades/src/lib/__generated__/TradeFields.ts, libs/trades/src/lib/__generated__/Trades.ts, libs/trades/src/lib/__generated__/TradesSub.ts, libs/trades/src/lib/trades-container.tsx, libs/trades/src/lib/trades-data-provider.ts, libs/trades/src/lib/trades-table.spec.tsx, libs/trades/src/lib/trades-table.tsx, libs/trades/src/setup-tests.ts, libs/trades/tsconfig.json, libs/trades/tsconfig.lib.json, libs/trades/tsconfig.spec.json, tsconfig.base.json, workspace.json
- Adds lib/trades, with trades-container, trades-table and trades-data-provider
- Renders out trades-container on the trading page
- Also adds the accounts table to the trading page
Note this just displays the latest 50 trades. I have created #218 to capture the next iteration
=> Feat/152 Trade list MVP

libs/market-list/src/lib/markets-container.tsx, libs/order-list/src/lib/order-list-manager.tsx, libs/positions/src/lib/positions-manager.tsx
=> Fix/177 Check that grid api is defined before using getRowNode

apps/explorer/src/app/components/blocks/block-data.tsx, apps/explorer/src/app/components/header/header.tsx, apps/explorer/src/app/components/jump-to-block/index.tsx, apps/explorer/src/app/components/search/search.spec.tsx, apps/explorer/src/app/components/search/search.tsx, apps/explorer/src/app/components/txs/txs-per-block.tsx, apps/explorer/src/app/routes/blocks/id/block.spec.tsx, apps/explorer/src/app/routes/blocks/id/block.tsx, apps/explorer/src/app/routes/parties/home/index.tsx, apps/explorer/src/app/routes/route-names.tsx, apps/explorer/src/app/routes/router-config.tsx, apps/explorer/src/app/routes/txs/id/tx-details.tsx
=> Resolve circular dependency in tests

apps/explorer/src/app/components/txs/txs-per-block.tsx
=> Feat / 232 collapse block with no txs

apps/explorer-e2e/src/integration/asset-page.feature, apps/explorer-e2e/src/integration/blocks-page.feature, apps/explorer-e2e/src/integration/home-page.feature, apps/explorer-e2e/src/integration/markets-page.feature, apps/explorer-e2e/src/integration/network-page.feature, apps/explorer-e2e/src/integration/transactions-page.feature, apps/explorer-e2e/src/integration/validators-page.feature, apps/explorer-e2e/src/support/pages/base-page.js, apps/explorer-e2e/src/support/step_definitions/common.step.js, apps/explorer/src/app/components/header/header.tsx
Added tests in mobile resolution to cover toggle menu navigation
Closes #69
=> Additional tests in mobile resolution

libs/ui-toolkit/src/components/input/input.tsx
=> Fix/233 Improved input legibility for placeholder and typed text

apps/explorer-e2e/cypress.json, apps/explorer-e2e/src/integration/home-page.feature, apps/explorer-e2e/src/support/pages/home-page.js, apps/explorer-e2e/src/support/pages/transactions-page.js, apps/explorer-e2e/src/support/step_definitions/home-page.step.js, libs/network-stats/src/components/promoted-stats-item/promoted-stats-item.tsx, libs/network-stats/src/components/stats-manager/stats-manager.tsx, libs/network-stats/src/components/table-row/table-row.tsx
Adds test for the state/home page on block explorer
Closes #109
=> Test added for stats page

README.md, apps/explorer/.env.vegacapsule
Closes https://github.com/vegaprotocol/vegacapsule/issues/58
=> feat: add .env file for vegacapsule in the explorer app and instruction to setup explorer app with vegacapsule

README.md
When following existing instructions I needed a little extra help. Added a set up section to readme with the steps I needed
=> Update README with set up instructions

libs/ui-toolkit/src/components/transaction-dialog/transaction-dialog.stories.tsx, libs/ui-toolkit/src/components/transaction-dialog/transaction-dialog.tsx
- Prevents error message overflowing the container.
- Adds story for transaction-dialog
Closes #268
=> Fix/268 Overflow error text

apps/trading/lib/assets.ts
Addresses: https://github.com/vegaprotocol/frontend-monorepo/pull/263#discussion_r858719566
=> Allow any unknown asset query to be used with ERC20Asset type guard

apps/token/src/lib/web3-connectors.ts, apps/trading/lib/web3-connectors.ts, libs/web3/src/lib/types.ts, libs/web3/src/lib/web3-connect-dialog.spec.tsx, libs/web3/src/lib/web3-connect-dialog.tsx, libs/web3/src/lib/web3-provider.spec.tsx, libs/web3/src/lib/web3-provider.tsx
- I believe this fixes an 'unexpected account change error'
- Uses types from @web3-react
- Changes connector setup to match their default example
=> Tidy web3 connector types

apps/trading-e2e/src/integration/markets-page.feature, apps/trading-e2e/src/support/pages/markets-page.ts, apps/trading-e2e/src/support/step_definitions/trading-page.step.ts
Small fix to see if it fixes a market test failing in CI
=> Fix for failing test in CI

apps/trading-e2e/src/support/pages/markets-page.ts
Market test which should had been fixed is still failing. This PR adds some additional check before and after clicking on market which should hopefully make the test pass more reliably.
=> Updated fix for failing market test

apps/token/src/hooks/use-get-user-tranche-balances.ts, apps/token/src/hooks/use-tranches.ts, apps/token/src/routes/claim/index.tsx, apps/token/src/routes/home/token-details/token-details.tsx, apps/token/src/routes/redemption/redemption.tsx, apps/token/src/routes/tranches/index.tsx
Closes #400
Tranches query is too big to run in browser, we are now serving this from a JSON file that is generated on CI. This means data can be up to 23 hours out of date.
Related to #401
=> fix: use static tranches data

apps/trading-e2e/src/support/pages/base-page.ts
Increase timeout for failing test in CI
=> fix: increase timeout

apps/explorer/.env, apps/explorer/.env.capsule, apps/explorer/.env.devnet, apps/explorer/.env.mainnet, apps/explorer/.env.stagnet1, apps/explorer/.env.stagnet2, apps/explorer/.env.testnet, apps/token/.env, apps/token/.env.devnet, apps/token/.env.mainnet, apps/token/.env.stagnet1, apps/token/.env.stagnet2, apps/token/.env.testnet, libs/network-switcher/src/hooks/use-environment.tsx
Closes #540 
Fixes `NX_VEGA_NETWORKS` variables in token and explorer apps
The block explorer couldn't parse the stringified json with escaped characters, removed the backslashes from it.
=> fix: network env var escaping

apps/explorer-e2e/src/integration/transactions-page.feature
Currently there's a lot of noise from tests not finding any transactions. This PR sets these 2 tests to ignore until transactions are seeded in Capsule. 
Linked to: #523
=> test: ignore tx tests

apps/token/.env, apps/token/src/components/locked-progress/locked-progress.tsx, apps/token/src/i18n/translations/dev.json, apps/token/src/routes/governance/components/current-proposal-status/current-proposal-status.tsx, apps/token/src/routes/governance/components/vote-details/use-user-vote.tsx, apps/token/src/routes/governance/components/vote-details/vote-buttons.tsx, apps/token/src/routes/governance/components/vote-details/vote-details.tsx, apps/token/src/routes/redemption/tranche-item.tsx, apps/token/src/routes/staking/disassociate/disassociate-page.tsx, apps/token/src/routes/staking/staking-form.tsx
Closes #585
Release changes were recently made on TFE. Port these required changes over to Token.
#585 contains the TFE repo's commit hashes if you want to see the original changes
=> Feat/585 Port changes from TFE to Token

apps/token-e2e/src/data/vegaToken.json
=> test: fix token address to capsule

libs/wallet/src/connect-dialog/connect-dialog.spec.tsx
Addresses comment from #668, which was merged due to time constraints.
=> test: tidy up test

libs/order-list/src/lib/components/mocks/generate-orders.ts
N/A fixes an issue with safari crashing out
=> fix: safari crashing because of date value

apps/token-e2e/src/integration/staking.cy.js, apps/token-e2e/src/integration/vesting.cy.js, apps/token-e2e/src/locators/common.locators.js, apps/token-e2e/src/locators/staking.locators.js, apps/token-e2e/src/locators/vesting.locators.js, apps/token/src/routes/staking/connect-to-vega.tsx, apps/token/src/routes/staking/staking.tsx
Relates to  #477 
Adding tests to validate elements visible on staking page when Vega & Eth wallets are not connected.
Validators section skipped as it will be reimplemented in the near future.
=> test(token): added validations for staking page without wallets connected

apps/simple-trading-app/src/app/components/deal-ticket/baubles-decor.tsx, apps/simple-trading-app/src/app/components/deal-ticket/deal-ticket-container.tsx, apps/simple-trading-app/src/app/components/header/comet.tsx, apps/simple-trading-app/src/app/components/header/video.tsx, apps/simple-trading-app/src/app/components/icons/star.tsx, libs/tailwindcss-config/src/vega-custom-classes.js
Closes #530
Add a few decorative animations
Add side container with css's and svg's
=> feat: [console-lite] - trade screen - bunch of animations

apps/token/src/index.html
N/A
Description for Token was the same as stats for some reason. Adjust this to be the same as in the old repo.
=> chore: add better title based on old repo contents

libs/environment/src/utils/validate-environment.ts, libs/network-info/src/network-info.tsx, tools/utils/setup-environment.ts
Netlify doesn't expose git when building, need to fix this in the env setup.
=> fix: use netlify git env vars

apps/token/src/components/web3-connector/web3-connector.tsx
Closes N/A
White text on disconnected page
=> fix: white text on disconnect screen

apps/explorer-e2e/cypress.config.js, apps/explorer-e2e/src/integration/home.cy.js, libs/network-info/src/network-info.tsx
Closes #675 
Additional test to check git info is displayed
=> test: additional test for git info

.github/workflows/capsule-cypress-manual-trigger.yml, apps/token-e2e/cypress.config.js
=> Fix manual workflow

apps/token/src/lib/type-policies/proposal.spec.tsx, apps/token/src/lib/type-policies/proposal.ts, apps/token/src/routes/governance/__generated__/ProposalFields.ts, apps/token/src/routes/governance/proposal-fragment.ts, apps/token/src/routes/governance/proposal/__generated__/Proposal.ts, apps/token/src/routes/governance/proposals/__generated__/Proposals.ts, apps/token/src/routes/governance/test-helpers/generate-proposals.ts
N/A
Removes use of rationale field from proposals to support incentivized testing
=> chore: remove rationale field from proposals query

apps/simple-trading-app-e2e/src/integration/market-selector.test.ts
Fix for failing simple app test where Cypress was finding more than one element to click
=> fix: failing simple app test

apps/simple-trading-app-e2e/src/integration/market-list.test.ts, apps/simple-trading-app-e2e/src/support/mocks/generate-filters.ts
Fix failing int test when testnet is down
Add fixtures and interception for data queries
=> chore: [console-lite] - fix failing int tests

apps/trading-e2e/src/support/mocks/generate-market-list.ts, apps/trading-e2e/src/support/mocks/generate-market.ts, apps/trading-e2e/src/support/mocks/generate-markets.ts
Update broken mocks used by Cypress tests
=> fix: update mocks

apps/token-e2e/.env, apps/token/.env, apps/trading-e2e/.env, apps/trading/.env, libs/environment/README.md, libs/environment/src/utils/compile-environment.ts, libs/environment/src/utils/validate-environment.ts, libs/wallet/src/connect-dialog/connect-dialog.spec.tsx, libs/wallet/src/rest-connector-form.tsx
Closes #865
Allow a custom default URL by using the environement system
=> feat: allow default wallet url to be configured

libs/deal-ticket/src/components/deal-ticket.spec.tsx, libs/deal-ticket/src/components/time-in-force-selector.tsx
Closes #876
Add explicit labels on time in force. 
https://docs.vega.xyz/docs/mainnet/graphql/enums/order-time-in-force
=> feat: #876 add explicit time in force labels

apps/token/src/routes/governance/components/proposals-list-item/proposals-list-item-details.tsx
Closes #881
When building the proposals list, I left a testing message of 'testing testing 123' in the code. Doh. Removed it.
=> Fix/881: Removed testing message in proposals list voteStatus

apps/token-e2e/src/integration/flow/staking-flow.cy.js, apps/token-e2e/src/integration/flow/token-association-flow.cy.js, apps/token-e2e/src/support/wallet-teardown.functions.js
There were few changes in the implementation of validators table on Staking page & some staking helper function names changes. This PR is to adjust our tests to these changes. Staking flows are put out of scope for now as it require more work to make it work properly. A ticket will be created to cover that.
=> test: fix staking functions and association tests

apps/token-e2e/src/integration/view/wallet-vega.cy.js, apps/token/src/components/vega-wallet/vega-wallet.tsx, libs/wallet/src/manage-dialog/manage-dialog.tsx
Closes #762 
Tests for vega wallet widget in Token app.
=> test(token): validations added for vega wallet widget

.github/workflows/capsule-cypress-nightly copy.yml, .github/workflows/capsule-cypress-nightly.yml
=> test: maybe passing true as string would work

.github/workflows/capsule-cypress-night-run.yml
Adding night runs again and keeping fingers crossed that it would work properly now.
=> test: add night runs again

apps/token/src/routes/rewards/home/__generated__/Rewards.ts, apps/token/src/routes/rewards/home/index.tsx, apps/token/src/routes/rewards/home/reward-info.tsx
Closes #573
Use reward type from the API and not a hard coded string.
=> feat: show correct reward type

apps/explorer/src/app/routes/network-parameters/network-parameters.tsx
N/A
Fixes incorrect decimal formatting for a couple of network param fields
=> fix: formatting on governance.proposal.market network params

libs/positions/src/lib/positions-table.spec.tsx, libs/positions/src/lib/positions-table.tsx
Closes #521 
Adds a tooltip to the PNL header of the positions column.
=> feat: pnl tooltip

apps/token-e2e/cypress.config.js, apps/token-e2e/src/integration/flow/staking-flow.cy.js, apps/token-e2e/src/integration/view/staking.cy.js, apps/token-e2e/src/support/staking.functions.js, apps/token/src/routes/staking/validator-table.tsx
Closes #868 & #884 
Adds some additional tests and ACs. Fix broken flow tests from the validator list changes.
=> Test/868 staking ACs

apps/token/src/components/heading/heading.tsx, apps/token/src/routes/governance/components/proposals-list/proposals-list.spec.tsx, apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx
Closes #971
Provides a link to the governance proposal form from the proposals list
=> Feat/971: Add link to the make proposal form

apps/token/src/i18n/translations/dev.json, apps/token/src/routes/governance/components/proposal-votes-table/proposal-votes-table.tsx
From feedback
Show total supply in vote information breakdown
=> chore: show total supply on governance page

apps/token/src/components/eth-wallet/eth-wallet.tsx, apps/token/src/components/nav/nav.tsx, apps/token/src/components/vega-wallet/vega-wallet.tsx, apps/token/src/routes/claim/claim-form/claim-form.tsx, apps/token/src/routes/claim/complete.tsx, apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx, apps/token/src/routes/governance/proposal/index.tsx, apps/token/src/routes/governance/proposals/index.tsx, apps/token/src/routes/governance/propose/index.tsx, apps/token/src/routes/home/index.tsx, apps/token/src/routes/redemption/home/redemption-information.tsx, apps/token/src/routes/redemption/index.tsx, apps/token/src/routes/redemption/redemption.tsx, apps/token/src/routes/redemption/tranche-table.tsx, apps/token/src/routes/redemption/tranche/index.tsx, apps/token/src/routes/router-config.tsx, apps/token/src/routes/routes.ts, apps/token/src/routes/staking/associate/associate-page-container.tsx, apps/token/src/routes/staking/associate/associate-transaction.tsx, apps/token/src/routes/staking/disassociate/disassociate-page-container.tsx, apps/token/src/routes/staking/disassociate/disassociate-transaction.tsx, apps/token/src/routes/staking/stake-success.tsx, apps/token/src/routes/staking/staking-node.tsx, apps/token/src/routes/staking/staking-nodes-container.tsx, apps/token/src/routes/staking/staking.tsx, apps/token/src/routes/tranches/tranche.tsx, apps/token/src/routes/tranches/tranches.tsx, apps/token/src/routes/withdraw/index.tsx
Lazy load child routes, main.js size drop by 10% from  from 4541KB to 4103KB
=> chore: extract routes from routes, lazy load all child routes

.gitignore, libs/deal-ticket/src/components/deal-ticket.spec.tsx, libs/deal-ticket/src/components/deal-ticket.tsx, libs/deal-ticket/src/components/time-in-force-selector.tsx
Closes #940 
re-select field so that GTC is default on limit  orders and IOC on market orders.
=> feat: reselct field so that GTC is default on limit

apps/trading-e2e/src/integration/deposit.cy.ts
Closes #647 
Additional UI test for disconnecting Eth wallet from the deposit page
=> test: remove eth wallet test

apps/explorer/src/app/routes/network-parameters/network-parameters.tsx, apps/token/src/routes/governance/components/vote-details/vote-progress.tsx, apps/token/src/routes/governance/hooks/use-vote-information.ts
Closes #954 
Changed percentage displays to show correctly
=> Fix/954: Token & Explorer decimals

apps/explorer-e2e/src/integration/node-switcher.cy.js
Node switcher tests are failing due to a bug with afterEach hook.
=> fix: failing test due to cypress bug

apps/token-e2e/src/integration/flow/staking-flow.cy.js
=> test: disable check

.github/workflows/capsule-cypress.yml, vegacapsule/config.hcl
Needed as a precoursor to other issues
Uses a custom vegacpasule config to allow us to edit specific netowrk parameters
=> chore: use custom vega capsule file

apps/simple-trading-app-e2e/src/integration/market-selector.test.ts, apps/simple-trading-app-e2e/src/integration/market-trade.test.ts, apps/simple-trading-app/src/app/components/deal-ticket/baubles-decor.tsx, apps/simple-trading-app/src/app/components/deal-ticket/deal-ticket-container.tsx
Closes #914 
Add wallet connect before making a trade.
- refactored container component to add wallet connect
- added new e2e test
- fixed broken e2e tests
=> feat(console-lite): add wallet connect dialog before trading steps

libs/market-depth/src/lib/orderbook.tsx
Closes #816 
Fix alignment best static bid and ask price lines
=> feat(#816): fix orderbook alignment

apps/trading-e2e/src/integration/deposit.cy.ts
Fix intermittent failing deposit test
=> chore: fix deposits test

apps/stats-e2e/src/integration/app.test.ts
Stats test is sometimes timing out just before the site loads, increase time out to 10 seconds
=> chore: increase timeout

libs/orders/src/lib/components/order-list/order-list.tsx
=> fix: do not show edit/cancel buttons on order partially filled

apps/explorer-e2e/src/integration/node-switcher.cy.js
Testnet is once again not working, changed url to stagnet which should hopefully be more stable
=> chore: change to stagnet url

apps/console-lite-e2e/src/integration/market-list.test.ts
Closes #1165
The test seems to be a little bit harmful for the capsule cypress 
Remove bigger one, decrease numebr of events
=> feat: [console-lite] - improve simple-market-list int tests

libs/environment/src/components/network-switcher/network-switcher.tsx
Closes #N/A
fix awkward height override
from:
to:
=> fix: force height for ns dropdown items

apps/token/src/components/wallet-card/wallet-card.tsx, apps/token/src/i18n/translations/dev.json, apps/token/src/lib/format-number.spec.ts, apps/token/src/lib/format-number.ts, apps/token/src/routes/governance/components/proposal-votes-table/proposal-votes-table.tsx, apps/token/src/routes/staking/disassociate/disassociate-page.tsx, libs/react-helpers/src/lib/format/number.spec.ts, libs/react-helpers/src/lib/format/number.ts
Closes #1137
Changed options description to identify what the select option origin is.
Format number housekeeping included.
=> fix: included origin of token, moved formatters

apps/token-e2e/src/integration/flow/token-association-flow.cy.js, apps/token-e2e/src/support/staking.functions.js, apps/token/src/routes/staking/disassociate/disassociate-page.tsx
Disassociation tests were updated to handle token dropdown.
=> test: dissassociation tests reworked to current implementation

apps/token/src/lib/decimals.test.ts, apps/token/src/routes/claim/lib/is-restricted.test.ts, apps/token/src/routes/home/token-details/token-details-circulating.test.ts
Closes N/A
Make tests use the same function (it) rather than being inconsistent (it/test).
=> chore: make test names consistent

apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts
Update deal ticket tests which are failing due to change in d.p. for order prices
=> chore: update failing deal ticket tests

apps/token/src/config/links.ts, apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx
Closes #908 
Added short description about governance and link to `vega.xyz/governance` page
=> feat: link to governance (908)

libs/accounts/src/lib/accounts-table.tsx, libs/fills/src/lib/fills-table.tsx, libs/orders/src/lib/components/order-list/order-list.tsx, libs/trades/src/lib/trades-table.tsx
Closes #661
Make number values right-aligned.
=> fix: #661 prices and number values right-aligned

apps/trading-e2e/src/integration/trading-fills.cy.ts
Closes #938 
Adds test for fills tab on the trading page using the same assertion and mocks as the fills on the portfolio page
=> test: trading fills tab on accounts

apps/trading-e2e/src/integration/trading-collateral.cy.ts, apps/trading-e2e/src/integration/trading-positions.cy.ts, apps/trading-e2e/src/support/mocks/generate-accounts.ts, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx
Closes #473 
- Additional margin level assertions
- Additional account collateral test
- Re-add missing vega wallet test id
=> test: margin positions and collateral tests added

apps/token-e2e/cypress.config.js, apps/token-e2e/src/integration/flow/staking-flow.cy.js, apps/token-e2e/src/support/common.functions.js, apps/token-e2e/src/support/staking.functions.js, apps/token-e2e/src/support/wallet-teardown.functions.js
Closes #1205 
Now that we can handles staking with vesting tokens within vegacapsule 
- increase coverage of existing overnight flow tests to encompass this functionality
- Plus some flake fixes 
=> Test/1205 increase coverage of staking tests 

libs/ui-toolkit/src/components/form-group/form-group.tsx
Re-adds classname to form group
=> chore: readd classname to formgroup

libs/ui-toolkit/src/components/loader/loader.stories.tsx, libs/ui-toolkit/src/components/loader/loader.tsx
Fixes the loader component in large mode
=> chore: fix large loader dimensions

apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/global.cy.ts
Try fix intermittent failing tests due to esocket timeout
=> chore: try fix esocket timeout error in ci

apps/explorer/src/app/routes/network-parameters/network-parameters.spec.tsx, apps/explorer/src/app/routes/network-parameters/network-parameters.tsx
Closes #1200 
Makes capitalisation match the network params capitalisation
=> fix: network parmaeter casing

apps/trading-e2e/src/integration/trading-orders.cy.ts, apps/trading-e2e/src/support/mocks/generate-orders.ts
Closes #1149 
Add test for bug fix as well as checking partially filled order is rendered correctly
=> test: add test for partially filled order view

libs/ui-toolkit/src/components/select/select.tsx, libs/ui-toolkit/src/utils/shared.ts
=> feat(#1235): fix select element dropdoen background

README.md, package.json
- Minor change to README.md to include directions for starting capsule
- Adjust PACKAGE.JSON scripts to launch bootstrap
=> test: update package json and readme for vegacapsule

apps/trading/components/navbar/navbar.tsx, apps/trading/components/risk-notice-dialog/risk-notice-dialog.spec.tsx, apps/trading/components/risk-notice-dialog/risk-notice-dialog.tsx, apps/trading/components/vega-wallet-container/vega-wallet-container.tsx, apps/trading/pages/_app.page.tsx, apps/trading/pages/index.page.tsx, apps/trading/pages/markets/[marketId].page.tsx, apps/trading/pages/markets/index.page.tsx, apps/trading/pages/markets/trade-grid.tsx, apps/trading/stores/global.ts, tools/executors/next/build/impl.ts
Simplifies global store by using a single update function and remove vega prefixes (everything is vega). Also ensure each use of the global store only retrieves the state required to avoid superfluous re-renders.
=> chore: refactor global store

apps/token/src/components/token-input/token-input.tsx, apps/token/src/routes/staking/associate/associate-page.tsx, apps/token/src/routes/staking/staking-node.tsx
Fixes broken layout for associate, disassociate and node pages
=> fix: styles on staking and nodes page

apps/token/.env, apps/token/src/routes/governance/components/proposal/proposal.spec.tsx, apps/token/src/routes/governance/components/proposal/proposal.tsx, apps/token/src/routes/governance/proposal/proposal-container.tsx
Closes #1090
Fix votes not being registered in the token frontend site.
The polling logic was not functioning as expected. We should move this to being a subscription along with all the other polling logic in the token site at a later date now that data node supports WSS. However this is outside the scope of this fix and I chose to keep things consistent for now.
=> fix: polling not working on governance page

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml
Change both night run and manual runs to checkout front end for capsule
=> test: checkout front end changes to cypress workflows

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml
Add missing working directories to nightly and manual-trigger workflows
=> chore: fix test manual and nightly workflows

libs/ui-toolkit/src/components/dialog/dialog.tsx
Closes #1277 
fix broken dialog vertical positioning
=> fix: more dialog patches

.husky/commit-msg
N/A
As per conversation on slack, make test and build only run on CI
=> chore: remove build and test precommit checks

README.md
=> fix: readme with new env var for type gen

libs/deal-ticket/src/components/deal-ticket/market-selector.tsx
Closes #1289
Adjust some css for better looking after design update
=> feat: [console-lite] - fast fix small css on market selector

apps/trading-e2e/cypress.config.js, apps/trading-e2e/src/integration/home.cy.ts
Home tests are still failing intermittently. 
- Add mock to before step consistent with market tests
- Increase timeouts to 20 seconds
=> chore: attempt to fix home tests

apps/liquidity-provision-dashboard/project.json
Adds build-netlify command to lp dashboard
=> chore: add netlify build command for lp dashboard

apps/token/src/routes/governance/components/proposal-detail-header/proposal-header.spec.tsx, apps/token/src/routes/governance/components/proposal-detail-header/proposal-header.tsx
N/A
Do not truncate description
=> fix: remove shortening of description content

.eslintrc.json, apps/token/src/components/vega-wallet/hooks.ts, apps/token/src/lib/url-connector.ts, libs/cypress/src/lib/eip1193-bridge.ts, libs/market-list/src/lib/components/markets-container/markets-container.tsx, libs/web3/src/lib/web3-connect-dialog.tsx
Adds eslint rule to prevent multi line if statements without braces
=> chore: set curly eslint rule to multi line

libs/wallet/src/wallet-types.ts
Closes #1350 
Renames settlementPriceDecimals to settlementDataDecimals in new market and update market proposal types
=> chore: update wallet types to align with protos

apps/trading-e2e/src/integration/market-info.cy.ts, libs/market-list/src/lib/utils/market-utils.spec.tsx, libs/market-list/src/lib/utils/market-utils.ts
https://vegaprotocol.slack.com/archives/C8WS7M50E/p1663673365339369?thread_ts=1663673045.575679&cid=C8WS7M50E
=> fix: total fees calculation

apps/trading-e2e/src/integration/market-info.cy.ts, apps/trading-e2e/src/support/mocks/generate-market-info-query.ts, libs/market-info/src/components/market-info/__generated__/MarketInfoQuery.ts, libs/market-info/src/components/market-info/info-market-query.ts, libs/market-info/src/components/market-info/info-market.tsx
Closes #1302
Add back risk factors after API updates.
=> fix: add back risk factors

libs/orders/src/lib/components/order-data-provider/order-data-provider.ts
Closes N/A
Testnet has been restarted. If no orders are in the list the error below appears.
=> Fix/order data provider error - in Release/Testnet

apps/trading-e2e/.env, apps/trading-e2e/cypress.config.js, apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/global.cy.ts, apps/trading-e2e/src/integration/home.cy.ts, apps/trading-e2e/src/integration/market-info.cy.ts, apps/trading-e2e/src/integration/markets.cy.ts, apps/trading-e2e/src/integration/trading-accounts.cy.ts, apps/trading-e2e/src/integration/trading-collateral.cy.ts, apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, apps/trading-e2e/src/integration/trading-fills.cy.ts, apps/trading-e2e/src/integration/trading-orders.cy.ts, apps/trading-e2e/src/integration/trading-positions.cy.ts, apps/trading-e2e/src/integration/trading-trades.cy.ts, apps/trading-e2e/src/integration/withdraw.cy.ts, libs/cypress/src/index.ts, libs/cypress/src/lib/commands/mock-gql.ts, libs/fills/src/lib/fills-table.spec.tsx, libs/market-info/src/components/market-info/info-market.tsx, package.json, yarn.lock
=> chore: mock gql subscriptions

.github/workflows/capsule-cypress.yml
Fix vegawallet network in workflow
=> fix: use fairground network for vega wallet if capsule is not run

apps/trading/components/trading-mode-tooltip/trading-mode-tooltip.tsx, apps/trading/pages/markets/trade-grid.tsx, libs/market-info/src/components/market-info/info-market.tsx
Closes #1424
Allows opening LP view in a new tab.
=> fix: view liquidity provision anchor

.github/workflows/capsule-cypress.yml
yarn install must be run before using nx
=> fix: need to yarn install before nx usage

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, .github/workflows/capsule-cypress.yml
Revert back to github runner because of error in cache
=> chore: revert hosted runner

apps/explorer/src/app/components/header/header.tsx
Minor styling changes after https://github.com/vegaprotocol/frontend-monorepo/pull/1487
Added dark class to navbar
N/A
N/A
=> fix(explorer): theme dark nav

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, .github/workflows/capsule-cypress.yml
vega version in vegacapsule changed to 0.56.0
=> test: vega in vegacapsule version changed to 0.56.0

apps/trading-e2e/src/integration/market-info.cy.ts, libs/market-info/src/components/market-info/info-market.tsx
Closes #1506
Add risk parameters. Move risk factors below. 
=> feat: 1506 add risk parameters

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, .github/workflows/capsule-cypress.yml
Update vega binaries to v0.57.0
=> chore: update vega binaries to v0.57.0

apps/token/src/routes/governance/components/vote-details/use-user-vote.tsx
Closes #1365 
We were not cancelling the timeout property for vote not being seen by the network. This caused it to incorrectly report even if the vote was successful.
=> fix: vote not seen being incorrectly reported

apps/trading-e2e/src/integration/global.cy.ts
One test was blocking all runners without returning any result. it's disabled and will be investigated.
=> fix: disabled test

apps/token/src/i18n/translations/dev.json, apps/token/src/routes/home/index.tsx, apps/token/src/routes/home/token-details/token-details.tsx
Closes #1015 
Relabel total staked as associated with Vega key
=> chore: relabel total associated

apps/console-lite-e2e/src/support/mocks/commons.ts, apps/console-lite-e2e/src/support/mocks/generate-deal-ticket.ts, apps/console-lite-e2e/src/support/mocks/generate-market-positions.ts
Minor changes to mocks for console-light tests - using real id's
=> test: fix mocks for console light to include id

.github/workflows/capsule-cypress-manual-trigger.yml
=> chore: fix smoke flag meaning

.github/workflows/capsule-cypress.yml
Fix running capsule in PR workflow
=> fix: fix capsule workflow

.github/workflows/capsule-cypress-manual-trigger.yml
=> chore: env setup fixed

apps/console-lite-e2e/src/integration/market-trade.test.ts, apps/console-lite/src/app/components/portfolio/accounts/use-column-definitions.tsx, libs/accounts/src/lib/accounts-data-provider.ts
it fixes console-lite-e2e tests
=> fix: console-lite e2e tests

libs/deal-ticket/src/components/deal-ticket/deal-ticket-limit-amount.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx
Closes #1379 
Disables scrolling to change price and size in deal ticket
=> feat: disable scrolling to change value for size and price fields

.github/workflows/capsule-cypress-night-run.yml
Run night suite manually as well.
=> chore: run nightly run on demand

libs/wallet/src/connect-dialog/connect-dialog.tsx
- Moves custom url entry above buttons
- Adds separator line for hosted wallet from desktop/cli
- Adjusts wording
=> feat: adjust wallet styles and translations

apps/console-lite-e2e/src/support/index.js, apps/token-e2e/src/support/index.js, apps/trading-e2e/src/integration/withdraw.cy.ts, apps/trading-e2e/src/support/index.js, apps/trading/components/select-market/select-market-columns.tsx, apps/trading/pages/markets/trade-grid.tsx, libs/accounts/src/lib/accounts-table.spec.tsx, libs/accounts/src/lib/accounts-table.tsx, libs/accounts/src/lib/breakdown-table.spec.tsx, libs/deal-ticket/src/components/deal-ticket-validation/use-order-validation.spec.tsx, libs/deal-ticket/src/components/deal-ticket-validation/use-order-validation.tsx, libs/fills/src/lib/fills-table.spec.tsx, libs/ui-toolkit/src/components/radio-group/radio-group.tsx, libs/wallet/src/vega-transaction-dialog/vega-transaction-dialog.tsx
- Moves the sparkline so it appears after change cell in the market dropdown
- Change validation to refer to size rather than amount
- Put sparkline after 24hr change in markets dropdown
- Fix radio selected state
- Remove orange border from vega tx pending state
- Combine deposit and withdraw buttons into single cell
Radio before:
Radio after:
=> chore: misc quick wins

apps/explorer/.env, apps/explorer/.env.devnet, apps/explorer/.env.mainnet, apps/explorer/.env.stagnet3, apps/explorer/.env.testnet, apps/explorer/.env.vegacapsule, apps/explorer/src/app/components/txs/txs-infinite-list-item.spec.tsx, apps/explorer/src/app/components/txs/txs-infinite-list-item.tsx, apps/explorer/src/app/components/txs/txs-infinite-list.spec.tsx, apps/explorer/src/app/components/txs/txs-infinite-list.tsx, apps/explorer/src/app/config/env.ts, apps/explorer/src/app/routes/router-config.tsx, apps/explorer/src/app/routes/txs/home/index.tsx, apps/explorer/src/app/routes/types/block-explorer-response.d.ts
Closes #397 
Added infinite scrolling list of transactions
- Added block explorer response type and url to env
- Changed render in routes config
- Refactored txs-infinite-list-item and tests
=> feat(explorer): add txs infinite scroll list

apps/token-e2e/cypress.config.js, apps/token-e2e/src/integration/flow/token-association-flow.cy.js, libs/cypress/src/lib/commands/vega-wallet-import.ts
Closes #1684 
Update ACs for token association
=> chore: acs updated for token association

apps/token/src/routes/staking/node-list.spec.tsx, apps/token/src/routes/staking/node-list.tsx, apps/token/src/routes/staking/staking.tsx
Closes #1541
Hides the top third of validators by ranking score by default
=> Feat/1541: Hide top third of validators to promote decentralisation

apps/console-lite/src/app/components/portfolio/accounts/accounts.tsx, libs/accounts/src/lib/accounts-manager.tsx, libs/fills/src/lib/use-fills-list.ts, libs/market-depth/src/lib/depth-chart.tsx, libs/orders/src/lib/components/order-list-manager/use-order-list-data.ts, libs/positions/src/lib/use-positions-data.tsx, libs/trades/src/lib/trades-container.tsx
=> fix(1649): don't use old data on re render when data update from provider is handled by component

apps/token/src/routes/governance/components/propose/proposal-form-vote-and-enactment-deadline.spec.tsx
Unit tests were failing in different time zone (GMT+1)
=> chore: fixed failing tests in different TZ and locale

apps/token-e2e/src/integration/flow/governance-flow.cy.js, apps/token-e2e/src/integration/flow/governance-forms-flow.cy.js, apps/token-e2e/src/integration/view/governance.cy.js
Closes #1705 
Add and update existing ACs for governance proposals
=> chore: updated acs for governance

apps/token/.env.stagnet3, apps/trading-e2e/.env, apps/trading/.env, apps/trading/.env.devnet, apps/trading/.env.mainnet, apps/trading/.env.stagnet1, apps/trading/.env.stagnet3, apps/trading/.env.testnet
- Adds missing env vars so .env files can be used in place of manually added env vars
- Alphabetizes them to making diffing easier
=> chore: add missing env vars and alphabeticise them

libs/assets/src/lib/asset-details-table.tsx
Closes #1731
Updates asset tooltips to remove incorrect info.
Solely copy changes to one txs file.
=> chore: update tooltips for asset limits

apps/token/src/components/eth-wallet/eth-wallet.tsx
N/A
Pending transactions button was styled incorrectly
=> style: pending transactions styling

apps/console-lite-e2e/.env, apps/token/.env, apps/trading-e2e/.env, apps/trading/.env, libs/types/.env
n07 is being down most of the time recently which makes testing difficult
=> fix: change n07 to n06

apps/token/jest.config.ts
N/A
Was investigating code coverage for token and wanted an overall picture. This PR adds code coverage to untested files as well.
=> chore: run coverage on untested files

apps/trading/pages/portfolio/accounts-container.tsx
- Fixes deposit button from blocking the bottom account rows
- Updates to only render a single deposit dialog in the accounts tab
Before:
After:
=> fix: deposit button blocking account rows

apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/wallet/src/connect-dialog/connect-dialog-elements.tsx, libs/wallet/src/connect-dialog/connect-dialog.tsx, libs/wallet/src/connect-dialog/json-rpc-connector-form.tsx, libs/wallet/src/constants.ts, libs/wallet/src/index.ts
Closes #1641 
Add button for connect with vega wallet directly from deal ticket
Use vega wallet dialog store for open a connection dialog
=> feat: add connect vega wallet button to the deal ticket

libs/fills/src/lib/fills-data-provider.ts, libs/orders/src/lib/components/order-data-provider/order-data-provider.ts, libs/react-helpers/src/lib/generic-data-provider.spec.ts, libs/react-helpers/src/lib/generic-data-provider.ts, libs/react-helpers/src/lib/get-nodes.ts, libs/react-helpers/src/lib/pagination.ts, libs/trades/src/lib/trades-data-provider.ts
Closes #1765 
Improve derivedDataProvider paginated data handling
- pass isInsert to callback if any dependency has isInsert
- create generic paginatedCombineDelta and paginatedCombineInsertionData functon to handle updats in orders, fills and trades
- add unit tests
=> chore: generic data provider improvments

apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/global.cy.ts, apps/trading-e2e/src/integration/home.cy.ts, apps/trading-e2e/src/integration/market-info.cy.ts, apps/trading-e2e/src/integration/market-summary.cy.ts, apps/trading-e2e/src/integration/markets.cy.ts, apps/trading-e2e/src/integration/trading-accounts.cy.ts, apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, apps/trading-e2e/src/integration/trading-fills.cy.ts, apps/trading-e2e/src/integration/trading-orders.cy.ts, apps/trading-e2e/src/integration/trading-positions.cy.ts, apps/trading-e2e/src/integration/trading-trades.cy.ts, apps/trading-e2e/src/integration/withdraw.cy.ts, apps/trading-e2e/src/support/index.js, apps/trading-e2e/src/support/mocks/generate-statistics.ts, apps/trading-e2e/src/support/trading.ts, libs/environment/src/index.ts
ChainId mock is fixed, added Statistics request mock and some refactor.
=> chore: fix chainId mock

apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
Closes #1792 
Change some details in view
less words in the button
no additional css on the button
remove get wallet link
=> chore: improve connect wallet button in deal ticket

apps/token/src/lib/format-number.ts, libs/react-helpers/src/lib/format/number.ts
=> fix: do no allow min or max fraction digits to go out of range

libs/network-stats/src/components/stats-manager/__generated__/NetworkStats.ts, libs/network-stats/src/components/stats-manager/stats-manager.tsx, libs/network-stats/src/config/stats-fields.ts
Closes #1780 
Reference uptime from statistics.genesisTime
N/A
N/A
=> fix(explorer): fix uptime to reference genesisTime field

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx
Adds the key alias to the pubkey dropdown
=> fix: add key alias to dropdown

libs/network-stats/src/components/stats-manager/__generated__/NetworkStats.ts, libs/network-stats/src/components/stats-manager/stats-manager.tsx, libs/network-stats/src/config/stats-fields.ts
Closes #1382 
Cherry picked commit to fix uptime
N/A
N/A
=> fix(stats-manager): fix uptime pointing to incorrect field (#1328)

apps/multisig-signer/.env.sandbox, apps/multisig-signer/src/app/components/add-signer-form/add-signer-form.tsx, apps/multisig-signer/src/app/components/remove-signer-form/remove-signer-form.tsx
We needed to await the result of useLazyQuery in a different manner to ensure the bundle data was arriving in time.
=> Multisig-signer: Ensuring we await the data from useLazyQuery properly

apps/token/src/i18n/translations/dev.json, apps/token/src/routes/staking/node/validator-table.tsx
N/A
Status was not displayed on the node page, it should be so this PR fixes that.
=> feat: add status to node page

apps/trading-e2e/src/integration/market-info.cy.ts
chore: remove unnecessary it.only in test
=> chore: remove unnecessary it.only in test

apps/token/src/routes/governance/components/propose/proposal-form-vote-and-enactment-deadline.spec.tsx, apps/token/src/routes/governance/components/propose/proposal-form-vote-and-enactment-deadline.tsx, libs/network-stats/src/config/stats-fields.ts, libs/react-helpers/src/lib/format/date.ts
Use getTimeFormat and getDateTimeFormat from @vegaprotocol/react-helpers instead of toLocaleTimeString and toLocaleTimeString
Mock  getDateTimeFormat in test
=> chore: improve data time formatting in token app

apps/trading/components/navbar/navbar.tsx
Closes #576 
Adds a link to the governance page on token
- Was able to remove the state from NavLink as the useEffect in navbar.tsx handles the client/server rendering mismatch
- Changed yellow border to be rendered with a span so that the text of the links is more easily vertically centered, with governance off to the right it look out of line compared to the pubkey dropdown
=> feat: add governance link to navbar

.github/workflows/cypress-live-test.yml
Added project path to workflow.
=> chore: fix live test workflow

apps/explorer/.env.sandbox
Related to #1744 
Added new sandbox env vars
N/A
N/A
=> chore(explorer): add sandbox env vars

apps/explorer/.env.devnet, apps/explorer/.env.stagnet1, apps/explorer/.env.stagnet3, apps/explorer/.env.testnet
Related to #1885 
Add newly provisioned BE api urls to .env files
N/A
N/A
=> chore(explorer): update BE api urls

libs/market-info/src/components/market-expires/market-expires.spec.tsx, libs/market-info/src/components/market-expires/market-expires.tsx
Closes #1842 
set expiry to date time format
=> fix: 1842 set expiry to date time format

apps/trading-e2e/src/integration/markets.cy.ts, apps/trading/components/select-market/select-market-columns.tsx, apps/trading/components/select-market/select-market.spec.tsx, apps/trading/components/select-market/select-market.tsx, libs/deal-ticket/src/components/trading-mode-tooltip/trading-mode-tooltip.tsx
=> feat: 1651 market select snags

scripts/get-queries.js
Closes #1901
The script for generating queries was failing, there were also a number of situation where a query could be missed. This PR fixes both of these issues.
=> fix: get queries script

apps/console-lite-e2e/.env, libs/positions/src/lib/positions-manager.tsx, libs/positions/src/lib/positions-table.tsx
=> chore(#1932): make positions table fill available space

apps/token/src/routes/staking/home/node-list.tsx
Closes #1912
Pins the validator column of the table on the left hand side, and gives the cells some extra spacing.
=> Feat/1912: visual improvements to validator table

apps/trading/pages/portfolio/index.page.tsx, libs/ledger/.babelrc, libs/ledger/.eslintrc.json, libs/ledger/README.md, libs/ledger/jest.config.ts, libs/ledger/package.json, libs/ledger/project.json, libs/ledger/src/index.ts, libs/ledger/src/lib/LedgerEntries.graphql, libs/ledger/src/lib/__generated___/LedgerEntries.ts, libs/ledger/src/lib/ledger-container.tsx, libs/ledger/src/lib/ledger-entries-data-provider.ts, libs/ledger/src/lib/ledger-entries.mock.ts, libs/ledger/src/lib/ledger-manager.tsx, libs/ledger/src/lib/ledger-table.tsx, libs/ledger/tsconfig.json, libs/ledger/tsconfig.lib.json, libs/ledger/tsconfig.spec.json, libs/react-helpers/src/lib/time.ts, libs/types/src/global-types-mappings.ts, tsconfig.base.json, workspace.json
Closes #1387 
Adds new portfolio tab 'Ledger entries' with listing of all (500) system transactions.
=> feat: ledger entries

apps/console-lite/src/app/components/portfolio/accounts/accounts.tsx, apps/trading/pages/portfolio/accounts-container.tsx, apps/trading/pages/portfolio/index.page.tsx, libs/accounts/src/lib/accounts-manager.spec.tsx, libs/accounts/src/lib/accounts-manager.tsx, libs/fills/src/lib/use-fills-list.spec.ts, libs/fills/src/lib/use-fills-list.ts, libs/orders/src/lib/components/order-list-manager/use-order-list-data.spec.ts, libs/orders/src/lib/components/order-list-manager/use-order-list-data.ts, libs/trades/src/lib/trades-container.tsx
Closes #1947 
Use `updateOnInit` directive instead of taking data property from `useDataProvider` in list views
=> chore: fix update results from dataProvider when variable change

apps/token/src/routes/governance/components/propose/proposal-form-terms.spec.tsx, apps/token/src/routes/governance/components/propose/proposal-form-terms.tsx, apps/token/src/routes/governance/propose/freeform/propose-freeform.tsx, apps/token/src/routes/governance/propose/network-parameter/propose-network-parameter.tsx, apps/token/src/routes/governance/propose/new-asset/propose-new-asset.tsx, apps/token/src/routes/governance/propose/new-market/propose-new-market.tsx, apps/token/src/routes/governance/propose/propose.tsx, apps/token/src/routes/governance/propose/raw/propose-raw.tsx, apps/token/src/routes/governance/propose/update-asset/propose-update-asset.tsx, apps/token/src/routes/governance/propose/update-market/propose-update-market.tsx
=> Fix/1831: External link component used for proposals docs/explorer links

apps/token/src/lib/abbreviate-number.test.ts, apps/token/src/lib/abbreviate-number.ts, apps/token/src/lib/bignumber.test.ts, apps/token/src/lib/deterministic-shuffle.test.ts, apps/token/src/lib/deterministic-shuffle.ts
Closes #1916
I timeboxed some unit test writing. This PR adds some. There is one failing test in this branch, which I agreed with @dexturr needs to be fixed - but fixed by someone on the team.
=> Add some (not very important) unit test coverage for token

.github/workflows/capsule-cypress.yml
Fix jobs that are not triggered.
=> fix: output path fixed to trigger jobs

.github/workflows/cypress-liquidity-provision-dashboard-e2e.yml
fix: add missing yarn install in provision workflow
=> fix: add missing yarn install in provision workflow

.github/workflows/lint_pr.yml
Adds a workflow to enforce pr titles using commitlint/cli
=> ci: add check for pr title

.github/workflows/capsule-cypress-night-run.yml, .github/workflows/cypress-console-lite-e2e.yml, .github/workflows/cypress-explorer-e2e.yml, .github/workflows/cypress-liquidity-provision-dashboard-e2e.yml, .github/workflows/cypress-stats-e2e.yml, .github/workflows/cypress-token-e2e.yml, .github/workflows/cypress-trading-e2e.yml, .github/workflows/tests-dispatcher.yml
Should fix the issue with required jobs in PR.
=> chore: change condition check directly in test job

apps/trading/project.json, tools/executors/next/executor.json, tools/executors/next/export/impl.ts, tools/executors/next/export/schema.json, tools/executors/next/tsconfig.json
Adds a custom nx executor so we can export the next app with a targeted env from a .env file
=> chore: add custom export executor for next app

apps/explorer/src/app/hooks/use-txs-data.ts, apps/explorer/src/app/routes/txs/home/index.tsx
=> fix(explorer): reduce limit of transactions from 100 to 20

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, .github/workflows/capsule-cypress.yml, apps/token-e2e/src/integration/flow/withdrawal-flow.cy.js
Fixes some tests currently failing because of the changes to withdrawal assets only showing what is in the wallet. 
Also update capsule to v0.62
=> chore(test updates): fix withdrawal tests

apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts
Closes #659 
Tests for auction trading modes are added.
=> test: add orders for market in auction

apps/explorer/.env.mainnet, apps/explorer/src/index.html
Closes #2012
- chore(explorer): add urls for mainnet explorer api
- fix(explorer): remove white bg on dark theme
=> fix(#2012): fix mainnet block explorer

libs/deposits/src/lib/deposit-form.tsx, libs/ui-toolkit/src/components/dialog/dialog.tsx
=> fix(1854): view asset launches deposit

.github/workflows/lint_pr.yml
=> ci: fix verify workflow tirggers

apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts
Fixes few tests in deal ticket.
=> fix: deal ticket dates set to next day

apps/token-e2e/src/integration/flow/governance-flow.cy.js, apps/token-e2e/src/integration/flow/governance-forms-flow.cy.js, apps/token-e2e/src/support/governance.functions.js
Closes #2072 & #1837
A bunch of tests needed to be refactors because proposalEvent is no longer used.
Also includes fixes and additional tests for the min/max deadline fix
=> test(2072): proposal deadline changes

apps/token-e2e/src/integration/flow/governance-flow.cy.js, apps/token-e2e/src/integration/flow/staking-flow.cy.js
Closes #[2027]
Update smoke tests for token to increase coverage for staking and proposals
=> chore(2027): update smoke tests

apps/trading-e2e/src/integration/markets.cy.ts, apps/trading/client-pages/markets/proposed.tsx, apps/trading/components/constants.ts, libs/environment/src/hooks/use-environment.tsx
Closes #2105 
Small fixes in the view of proposed markets
=> chore: market proposal selector - small view improvements

apps/trading-e2e/src/integration/trading-positions.cy.ts, libs/positions/src/lib/positions-manager.tsx, libs/positions/src/lib/positions-table.spec.tsx, libs/positions/src/lib/positions-table.tsx, libs/positions/src/lib/use-positions-data.tsx, libs/ui-toolkit/src/components/progress-bar/grid-progress-bar.tsx
Closes #2107 
Position notional size is off. 
After
=> fix: positions table fixes notional dp

apps/explorer/src/app/app.tsx, apps/explorer/src/app/components/main/index.tsx
=> feat(2141): explorer footer should be at the bottom of the page

libs/ledger/src/lib/ledger-table.tsx, libs/liquidity/src/lib/liquidity-table.tsx, libs/types/src/global-types-mappings.ts
Closes #2101 
Converts type mappings to objects so that keys are typed based on the schema.
=> chore(#2101): convert type mappings to objects with typed keys based on schema

apps/liquidity-provision-dashboard/src/app/components/dashboard/intro/intro.tsx, apps/token/.env.mainnet, apps/token/src/routes/governance/components/propose/proposal-form-terms.tsx, apps/token/src/routes/governance/propose/freeform/propose-freeform.tsx, apps/token/src/routes/governance/propose/network-parameter/propose-network-parameter.tsx, apps/token/src/routes/governance/propose/new-asset/propose-new-asset.tsx, apps/token/src/routes/governance/propose/new-market/propose-new-market.tsx, apps/token/src/routes/governance/propose/propose.tsx, apps/token/src/routes/governance/propose/raw/propose-raw.tsx, apps/token/src/routes/governance/propose/update-asset/propose-update-asset.tsx, apps/token/src/routes/governance/propose/update-market/propose-update-market.tsx, libs/orders/src/lib/utils.ts, libs/react-helpers/src/lib/links/links.ts
=> feat(1824): update docs links to new URL structure (remove '/docs')

apps/multisig-signer/src/app/app.tsx, apps/multisig-signer/src/app/config/contracts/contracts-provider.tsx
Multisig app was broken, this fixes it
=> fix: multisig app

apps/token/src/app.tsx
=> fix: withdrawals dialog broken

libs/positions/src/lib/use-positions-data.spec.tsx, libs/positions/src/lib/use-positions-data.tsx
Closes #2142 
Filter out or remove all positions with openVolume === '0'. Add unit tests
=> fix(2142): remove position after close

apps/trading-e2e/src/integration/market-summary.cy.ts, apps/trading-e2e/src/support/mocks/generate-proposals.ts, apps/trading/client-pages/market/trade-grid.tsx, apps/trading/components/header/header.tsx, apps/trading/components/select-market/select-market.tsx, libs/assets/src/lib/asset-details-dialog.tsx, libs/governance/src/components/asset-proposal-notification.tsx, libs/governance/src/components/index.ts, libs/governance/src/components/market-proposal-notification.tsx, libs/governance/src/index.ts, libs/governance/src/lib/proposals-data-provider/Proposals.graphql, libs/governance/src/lib/proposals-data-provider/__generated___/Proposals.ts, libs/governance/src/lib/proposals-hooks/index.ts, libs/governance/src/lib/proposals-hooks/use-update-proposal.spec.ts, libs/governance/src/lib/proposals-hooks/use-update-proposal.ts, libs/market-info/src/components/market-info/info-market.tsx, libs/ui-toolkit/src/components/index.ts, libs/ui-toolkit/src/components/notification/index.ts, libs/ui-toolkit/src/components/notification/notification.stories.tsx, libs/ui-toolkit/src/components/notification/notification.tsx
Closes #581
Closes #1930 
I've created a new ui-toolkit component "Notification" (with intent) that may be re-used for any kind of no-toast (in-line) notification scenario.
https://user-images.githubusercontent.com/1980305/203769336-379a7b25-2d2f-40b4-859c-50bed4e43674.mov
=> feat: view proposed market and asset change

.github/workflows/capsule-cypress.yml, apps/explorer-e2e/src/integration/parties.cy.js, apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, apps/trading-e2e/src/integration/trading-portfolio.cy.ts, libs/deal-ticket/src/hooks/use-order-margin.ts
=> chore: add regression tagged tests to PR runs

libs/market-depth/src/lib/orderbook.tsx, libs/positions/src/lib/positions-table.tsx, libs/react-helpers/src/lib/format/number.tsx
* fix: positions table fixes notional dp (#2144)
* fix: update decimals on position notional size
* fix: normalize values
* fix: fix positions unit tests
* fix: remove liquidation price
* fix: positions linting issue
* fix: remove liquidation price test
* fix: remove total summary row
* fix: remove comments
* fix: cypress test to not show trailing 0s
* fix: add back liq. price est as cell only
* fix: remove not used params
* chore: merge with release/testnet
* fix: orderbook dp
* Update libs/positions/src/lib/positions-table.spec.tsx
Details of technical implementation that …
=> fix: orderbook decimal places issue  (#2235)

README.md, apps/console-lite-e2e/cypress.config.js, apps/token-e2e/src/integration/flow/governance-flow.cy.js, apps/token-e2e/src/integration/view/wallet-vega.cy.js, apps/token-e2e/src/support/wallet-vega.functions.js, apps/trading-e2e/cypress.config.js, apps/trading-e2e/src/integration/global.cy.ts, apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, apps/trading-e2e/src/support/mocks/generate-chain-id.ts, apps/trading-e2e/src/support/mocks/generate-statistics.ts, libs/cypress/src/lib/commands/vega-wallet-connect.ts, libs/types/src/global-types-mappings.ts, libs/wallet/src/connect-dialog/connect-dialog.spec.tsx, libs/wallet/src/connect-dialog/connect-dialog.tsx, libs/wallet/src/connectors/rest-connector.ts
Closes #2050 
Changes connection dialog to render a single button which connects over localhost
=> feat(#2050): support new desktop wallet release

apps/trading/components/navbar/navbar.tsx
Closes #2245 
Fixes governance link in navbar
=> fix: governance navbar link

apps/trading/components/navbar/navbar.tsx, libs/market-depth/src/lib/orderbook.tsx, libs/positions/src/lib/positions-table.tsx, libs/react-helpers/src/lib/format/number.tsx
Back merging release/testnet with hotfixes for testnet
=> chore: back merge release/testnet

.github/ISSUE_TEMPLATE/---bug.md, .github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/user-story.md
Adds title prefix to issue templates
=> chore: update issue templates with title prefix

apps/token-e2e/cypress.config.js, vegacapsule/config.hcl, vegacapsule/node_set_templates/default/data_node_full_snapshots.tmpl, vegacapsule/node_set_templates/default/tendermint_full.tmpl, vegacapsule/node_set_templates/default/tendermint_validators.tmpl, vegacapsule/node_set_templates/default/vega_full.tmpl, vegacapsule/node_set_templates/default/vega_validators.tmpl
Fixes failing capsule build in CI
=> chore: update capsule files

apps/trading/client-pages/market/trade-grid.tsx, apps/trading/components/last-24h-price-change/last-24h-price-change.tsx, apps/trading/components/last-24h-volume/last-24h-volume.tsx, apps/trading/components/market-mark-price/market-mark-price.tsx, apps/trading/components/market-trading-mode/market-trading-mode.tsx, apps/trading/components/select-market/select-market-columns.tsx, apps/trading/components/select-market/select-market.spec.tsx, apps/trading/components/select-market/select-market.tsx, libs/ledger/src/lib/ledger-manager.tsx, libs/market-list/src/lib/markets-provider.ts
Closes #2220
Live update of active market in market dropdown
Use ready for live update components from market header.
=> chore(2220): partial live update of market dropdown

apps/token-e2e/src/integration/flow/staking-flow.cy.js, apps/token-e2e/src/integration/view/staking.cy.js, apps/token-e2e/src/support/staking.functions.js
Fixes for failing smoke/regression Token tests blocking the pipeline.
=> test(token test fixes): fix failing smoke tests

apps/trading/components/navbar/navbar.tsx, libs/market-depth/src/lib/orderbook.tsx, libs/positions/src/lib/positions-table.tsx, libs/react-helpers/src/lib/format/number.tsx, libs/withdraws/src/lib/use-create-withdraw.spec.tsx, libs/withdraws/src/lib/use-withdrawal-event.ts
back merging release/testnet after hotfix for withdrawals
=> chore: back merge release/testnet after hotfix

libs/accounts/src/lib/Accounts.graphql, libs/accounts/src/lib/__generated__/Accounts.ts, libs/accounts/src/lib/accounts-data-provider.spec.ts
Removes unnecessary field from accounts query
=> fix: accounts subscription

apps/token-e2e/src/integration/flow/staking-flow.cy.js, apps/token-e2e/src/support/staking.functions.js
Additional fixes for staking flow tests
=> chore: fixes for staking flow tests

apps/explorer/jest.config.ts, libs/accounts/src/lib/accounts-manager.tsx, libs/orders/src/lib/components/order-list-manager/use-order-list-data.spec.ts, libs/react-helpers/src/lib/pagination.ts
Closes #2311 
Fix bug with empty rows
=> fix: fix empty rows on empty collateral list

apps/trading-e2e/src/integration/live-env.cy.ts
=> chore: fix live env tests

apps/explorer/src/app/components/render-fetched/index.tsx, apps/explorer/src/app/components/search/search.tsx, apps/explorer/src/app/components/txs/details/tx-order.tsx, apps/explorer/src/app/components/txs/txs-per-block.tsx, apps/explorer/src/app/routes/parties/id/error/party-id-error.tsx, apps/explorer/src/app/routes/parties/id/index.tsx, apps/explorer/src/app/routes/txs/id/index.tsx
- feat(explorer): clearer errors on parties and txs
Closes #1887. Also fixes an unfiled issue where the block page would fail to load in transactions.
Tidies up some of the errors that you can get on search to clarify if it looks like a user error. This can be improved
further when vegaprotocol/vega#7040 is fixed.
=> fix(explorer): improve search errors

apps/trading/pages/client-router.tsx
Adds a very simple not found page for console, rather than just rendering a blank screen
=> feat: add not found catchall page for console

apps/trading-e2e/src/integration/home.cy.ts, apps/trading/components/select-market/select-market-columns.tsx, libs/ui-toolkit/src/components/price-change/price-change-cell.tsx
Closes #2158 
Add width styles to market table cells for lock the width and make ellipsis when text inside is too long
-
-
=> fix: lock widths of market table cells - make it resistant to long values

apps/token/src/components/vega-wallet/hooks.ts, libs/assets/src/lib/assets-data-provider.ts, libs/deposits/src/lib/deposit-form.tsx, libs/deposits/src/lib/use-deposit-balances.ts, libs/deposits/src/lib/use-submit-approval.ts, libs/deposits/src/lib/use-submit-deposit.tsx, libs/deposits/src/lib/use-submit-faucet.ts, libs/react-helpers/src/index.ts, libs/react-helpers/src/lib/is-asset-erc20.ts, libs/web3/src/lib/use-token-contract.ts, libs/withdraws/src/lib/withdraw-form.tsx
N/A
Noticed our dependency graph was looking weird for token.
- Removed types that needed not be there
- Better type interference on util
- Remove dependency on assets from web3 lib
- Remove dependency on assets from token
=> fix: token dependency graph

apps/token/src/components/vega-wallet/hooks.ts
Poll delegations less frequently
=> chore: poll delegations less frequently

apps/trading-e2e/src/integration/global.cy.ts, apps/trading-e2e/src/integration/markets.cy.ts, apps/trading/components/navbar/navbar.tsx, libs/ui-toolkit/src/components/nav/nav.tsx
Closes #2036 
Add new entry to the _navbar_. Do small fix for better look on mobile devices
Add  conditional  horizontal scrollbar
=> feat(2036): add markets to the navbar

apps/token-e2e/src/integration/flow/governance-flow.cy.js, apps/token-e2e/src/support/governance.functions.js
Fixes test failing in the PR run. Test got broken after it got re-added into develop.
=> chore: fix failing governance test

apps/trading-e2e/src/integration/markets.cy.ts, libs/deal-ticket/src/components/trading-mode-tooltip/trading-mode-tooltip.tsx
Closes #2409 
adjust margin in tooltips on market table
-
=> chore(2409): fix too big margin in tooltips

libs/network-stats/src/components/stats-manager/stats-manager.tsx, libs/network-stats/src/config/stats-fields.ts
=> chore: remove validating nodes

apps/trading/pages/toasts-manager.tsx, libs/governance/src/lib/proposals-hooks/Proposal.graphql, libs/governance/src/lib/proposals-hooks/__generated__/Proposal.ts, libs/governance/src/lib/proposals-hooks/index.ts, libs/governance/src/lib/proposals-hooks/use-update-network-paramaters-toasts.tsx, libs/governance/src/lib/proposals-hooks/use-update-network-parameters-toasts.spec.tsx, libs/ui-toolkit/src/components/toast/use-toasts.ts
=> feat: view proposed network changes (579)

apps/trading-e2e/src/integration/trading-orders.cy.ts, apps/trading-e2e/src/support/encode-transaction.ts, apps/trading-e2e/src/support/order-list.ts, libs/wallet/src/connectors/vega-connector.ts
7003-MORD
e2e tests for amend order - price and cancel orders
=> chore: 7003 mord amend and cancel e2e tests

apps/token/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, apps/token/src/routes/staking/home/validator-tables/validator-tables.tsx
Closes #2441 
Prevent flcikering in some cases of the validators table.
We are loading 2 sets of data, which created a race condition, causing flickering.
=> fix: flickering

apps/trading-e2e/src/integration/global.cy.ts, apps/trading-e2e/src/integration/home.cy.ts, apps/trading-e2e/src/integration/markets.cy.ts, apps/trading/client-pages/home/home.tsx, apps/trading/client-pages/liquidity/liquidity.tsx, apps/trading/client-pages/market/market.tsx, apps/trading/client-pages/markets/markets.tsx, apps/trading/components/constants.ts, apps/trading/components/navbar/navbar.tsx, apps/trading/components/select-market/select-market-columns.tsx, apps/trading/components/welcome-dialog/welcome-landing-dialog.tsx, apps/trading/pages/client-router.tsx, libs/environment/src/hooks/use-links.ts
=> chore: console dapp routes for skeleton page (2361)

CODEOWNERS
Adds core as codeowners for any .graphql file to help mitigate the addition of potentially troublesome queries
=> chore: add core as codeowners for graphql file changes

apps/trading-e2e/src/integration/trading-orders.cy.ts
Closes #2470 
Cover 7003-MORD-007-7003 and MORD-008-MORD  e2e tests
=> chore: cover 7003-MORD-007-7003 and MORD-008-MORD e2e tests

apps/trading-e2e/src/integration/trading-orders.cy.ts
#2364 
Cover 7003-MORD-e2e-tests order list - fields
=> chore: cover 7003-MORD e2e tests order list - fields

libs/environment/src/components/node-switcher/node-stats.tsx, libs/environment/src/components/node-switcher/node-switcher.spec.tsx, libs/environment/src/components/node-switcher/node-switcher.tsx, libs/environment/src/hooks/use-environment.spec.tsx, libs/environment/src/hooks/use-nodes.spec.tsx, libs/environment/src/hooks/use-nodes.tsx, libs/environment/src/types.ts, libs/environment/src/utils/validate-node.tsx
Closes #2439 
Rename SSL check to Subscription in the environment library.
=> fix: env ssl to subscription

apps/token-e2e/src/integration/view/governance.cy.js, apps/trading-e2e/src/integration/market-info.cy.ts, apps/trading-e2e/src/integration/market-summary.cy.ts, apps/trading-e2e/src/integration/markets.cy.ts, libs/environment/src/hooks/use-links.ts, libs/governance/src/lib/proposals-list/use-column-defs.tsx, libs/react-helpers/src/lib/links/links.ts
Fix governance links to `/proposals`
=> fix: governance links to proposals

apps/trading-e2e/src/integration/market-info.cy.ts, apps/trading-e2e/src/integration/market-summary.cy.ts, apps/trading-e2e/src/integration/markets.cy.ts, libs/environment/src/hooks/use-links.ts, libs/governance/src/lib/proposals-list/use-column-defs.tsx, libs/react-helpers/src/lib/links/links.ts
* fix: governance links to proposals
* fix: fix proposals link in governance.cy.js
* fix: fix link for https://vega.xyz/governance
=> fix: fix governance links to proposals (#2478)

apps/trading/components/liquidity-supplied/liquidity-supplied.tsx, libs/liquidity/src/lib/utils/liquidity-utils.spec.tsx, libs/liquidity/src/lib/utils/liquidity-utils.ts
Closes #2456 
Show indicator of liquidity status
=> feat(#2456): liquidity supplied status indicator

apps/trading-e2e/src/integration/trading-orders.cy.ts
Closes #2364
tests will be added after the proper implementation is prepared for those three remaining requirements.
=> chore: cover7003 mord e2e tests

apps/explorer-e2e/README.md, apps/token-e2e/README.md
Adds README.md files for token-e2e and explorer-e2e to help with capsule and wallet setup
=> chore: add readmes for token and explorer e2e

libs/wallet/src/connectors/vega-connector.ts
N/A
- Fixed incorrect types for market proposals
- Improved types in some places with some unions
=> chore: fix and improve types for market proposal

apps/console-lite-e2e/src/integration/market-selector.test.ts, apps/console-lite-e2e/src/integration/market-trade.test.ts, apps/console-lite-e2e/src/integration/portfolio-page.test.ts, apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/market-summary.cy.ts, apps/trading-e2e/src/integration/trading-accounts.cy.ts, apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, apps/trading-e2e/src/integration/trading-fills.cy.ts, apps/trading-e2e/src/integration/trading-orders.cy.ts, apps/trading-e2e/src/integration/trading-portfolio.cy.ts, apps/trading-e2e/src/integration/trading-positions.cy.ts, apps/trading-e2e/src/integration/withdraw.cy.ts, libs/cypress/src/index.ts, libs/cypress/src/lib/commands/vega-wallet-connect.ts
Vega wallet config is set in local storage at the beginning of tests.
=> chore: change connect vega wallet to set vega wallet config in local storage

libs/assets/src/lib/asset-details-table.tsx, libs/ui-toolkit/src/components/dialog/dialog.tsx
=> fix: asset dialog overflow (2488)

apps/multisig-signer/src/app/components/web3-connector/web3-connector.tsx, apps/token/src/components/web3-connector/web3-connector.tsx, libs/deposits/src/lib/deposit-form.tsx, libs/web3/src/lib/constants.ts, libs/web3/src/lib/web3-container.spec.tsx, libs/web3/src/lib/web3-container.tsx, libs/withdraws/src/lib/withdrawal-feedback.tsx
=> chore: chain id to name (714)

apps/trading-e2e/src/integration/trading-orders.cy.ts
#2486 
Cover ac 7003-MORD-016 by e2e test
=> chore: cover ac 7003-MORD-016 by e2e test

.github/workflows/capsule-cypress.yml, .github/workflows/test.yml, apps/explorer/.env.mirror
Closes #2510 
Adds a mirror environment configuration to explorer in `main`
=> chore(explorer): add mirror env

vegacapsule/genesis.tmpl
Network parameter was renamed.
=> chore: update market.liquidity.stakeToCcyVolume in genesis file

apps/token-e2e/src/integration/flow/withdrawal-flow.cy.js, apps/token-e2e/src/integration/view/home.cy.js, apps/token-e2e/src/integration/view/vesting.cy.js, apps/token-e2e/src/integration/view/withdraw.cy.js, apps/token-e2e/src/support/common.functions.js, apps/token-e2e/src/support/staking.functions.js, apps/token/src/app.tsx, apps/token/src/components/nav/nav-draw.tsx, apps/token/src/components/nav/nav-dropdown.tsx, apps/token/src/components/nav/nav-link.tsx, apps/token/src/components/nav/nav.spec.tsx, apps/token/src/components/nav/nav.tsx, apps/token/src/routes/home/index.tsx, apps/token/src/routes/redemption/home/redemption-information.tsx, apps/token/src/routes/redemption/redemption.tsx, apps/token/src/routes/redemption/tranche-table.tsx, apps/token/src/routes/redemption/tranche/index.tsx, apps/token/src/routes/router-config.tsx, apps/token/src/routes/routes.ts, apps/token/src/routes/token/index.tsx, libs/ui-toolkit/src/components/index.ts, libs/ui-toolkit/src/components/nav-dropdown/dropdown-menu.stories.tsx, libs/ui-toolkit/src/components/nav-dropdown/dropdown-menu.tsx, libs/ui-toolkit/src/components/nav-dropdown/index.ts, libs/ui-toolkit/src/components/nav/nav.tsx
Closes #2093
Adds token subnav.
=> feat(2093): token sub nav

apps/token-e2e/src/integration/flow/governance-flow.cy.js
Closes #2432 
Minor test updates for proposal details change in #2432
=> chore: update proposal detail tests

libs/cypress/src/lib/capsule/contants.ts, libs/cypress/src/lib/capsule/create-market.ts, libs/cypress/src/lib/capsule/ethereum-setup.ts, libs/cypress/src/lib/capsule/ethereum-wallet.ts, libs/cypress/src/lib/capsule/get-ethereum-config.ts, libs/cypress/src/lib/capsule/get-markets.ts, libs/cypress/src/lib/capsule/get-party-stake.ts, libs/cypress/src/lib/capsule/get-proposal.ts, libs/cypress/src/lib/capsule/get-vega-asset.ts, libs/cypress/src/lib/capsule/propose-market.ts, libs/cypress/src/lib/capsule/request.ts, libs/cypress/src/lib/capsule/vote.ts, libs/cypress/src/lib/capsule/wallet-client.ts, libs/cypress/src/lib/commands/create-market.ts, libs/cypress/src/lib/utils.ts
N/A
- Tidies up market creation script which had code not intended to be merged and was a bit messy and not DRY overall
- Removes global supressions of Cypress's logging of fetch/xhr requests
=> chore: tidy market setup scripts

apps/explorer/src/app/app.tsx, apps/explorer/src/app/components/footer/footer.tsx
Closes #2675
Shrinks the footer and removes a misleading infura reference. Now it's more like `trading`.
=> feat(explorer): reduce footer noise

libs/ui-toolkit/src/components/toggle/toggle.tsx
Closes #2562
Adds focus outline on toggle elements.
https://user-images.githubusercontent.com/1980305/213483570-272ad767-daf5-4c9d-82fe-8cdeb3371a96.mov
=> chore: focus on toggle (2562)

apps/token-e2e/src/integration/flow/governance-forms-flow.cy.js, apps/token-e2e/src/integration/flow/staking-flow.cy.js, apps/token-e2e/src/integration/flow/withdrawal-flow.cy.js, apps/token-e2e/src/integration/view/pubkey-view.cy.js, apps/token-e2e/src/support/staking.functions.js, apps/token-e2e/src/support/wallet-vega.functions.js, libs/cypress/src/index.ts, libs/cypress/src/lib/commands/add-connect-public-key.ts, libs/ui-toolkit/src/components/viewing-as-user/index.tsx, libs/wallet/src/connect-dialog/view-connector-form.tsx
Closes #2639 
Adds some additional E2E tests for view using public key functionality
=> test(#2639): e2e view public key tests

apps/token/src/routes/staking/node/stake-failure.tsx, apps/token/src/routes/staking/node/staking-form-tx-statuses.tsx, apps/token/src/routes/staking/node/staking-form.tsx
N/A
Show correct error message when staking fails
=> fix: show error message correctly

apps/trading/client-pages/market/index.ts, apps/trading/client-pages/market/market.tsx, libs/accounts/src/lib/use-account-balance.tsx, libs/react-helpers/src/hooks/use-data-provider.spec.ts, libs/react-helpers/src/hooks/use-data-provider.ts
=> feat: call update with null data from useDataProvider hook on variables change

.github/workflows/cypress-run.yml
chore: fix skip cache typo in workflow
=> chore: fix skip cache typo in workflow

libs/accounts/src/lib/use-market-account-balance.tsx, libs/positions/src/lib/use-market-margin.tsx, libs/positions/src/lib/use-market-position-open-volume.tsx
N/A
Fixes a render loop which fires off a bunch of queries in the deal ticket estimates component
Removes stored value from deps array of callback function to prevent fresh functions being created on every update
=> fix: dont use current value in update callback for estimate queries

libs/market-depth/src/lib/orderbook.tsx, libs/ui-toolkit/src/components/checkbox/checkbox.tsx
Closes #2668 
Uses the checkbox from the ui-toolkit for the order book show full prices checkbox
Before
After
=> chore(#2668): use ui-toolkit checkbox for orderbook

apps/trading-e2e/cypress.config.js, apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/global.cy.ts, apps/trading-e2e/src/integration/withdraw.cy.ts, apps/trading-e2e/src/support/ethereum-wallet.ts, apps/trading/lib/hooks/use-vega-transaction-toasts.tsx, libs/web3/src/lib/ethereum-transaction-dialog/ethereum-transaction-dialog.tsx, libs/withdraws/src/lib/withdrawals-table.tsx
#2587 
#2585 
Added e2e tests flow for deposit and withdrawal in capsule.
=> chore: deposit and withdrawal capsule e2e tests

apps/token/src/routes/staking/node-list.tsx
N/A
Add hardcoded logos for validators who missed them
=> chore: add logo map override for incorrectly specified validator logos

apps/trading/lib/hooks/use-ethereum-transaction-toasts.tsx
=> feat: fix EthTxCompletedToastContent

libs/ui-toolkit/src/components/select/select.tsx
**BEFORE:**
**AFTER:**
https://user-images.githubusercontent.com/1980305/214832407-3bda5987-6545-4697-9d2c-a8fb4e6e2079.mov
=> fix: select position

apps/trading-e2e/src/integration/navbar.cy.ts, apps/trading-e2e/src/integration/wallets.cy.ts
Relates to #2593 
Splitting `global.cy.ts` into `wallet.cy.ts` and `navbar.cy.ts` as they cover different functionalities.
=> chore: 2593 trading-e2e refactor - split global.cy

libs/candles-chart/src/lib/Chart.graphql, libs/candles-chart/src/lib/__generated__/Chart.ts, libs/candles-chart/src/lib/chart.mock.ts, libs/candles-chart/src/lib/data-source.ts
Closes #2722 
Volume charts position dp fix.
=> fix: volume charts position dp

apps/trading/components/select-market/select-market.tsx, apps/trading/lib/hooks/use-ethereum-transaction-toasts.tsx, libs/positions/src/lib/margin-data-provider.ts, libs/positions/src/lib/positions-data-providers.spec.ts, libs/positions/src/lib/positions-data-providers.ts, libs/positions/src/lib/use-market-margin.tsx, libs/positions/src/lib/use-market-position-open-volume.tsx
Closes #2634
When user has no position yet and creates new order positions table is not updated.
=> feat: fix positions and margins providers update

libs/positions/src/lib/positions-table.spec.tsx, libs/positions/src/lib/positions-table.tsx
=> fix: hide close button if openVolume is zero

libs/trades/src/lib/Trades.graphql, libs/trades/src/lib/__generated__/Trades.ts, libs/trades/src/lib/trades-table.spec.tsx, libs/trades/src/lib/trades-table.tsx, libs/trades/src/lib/trades.mock.ts
Closes N/A
Fix trades grid colors. 
=> fix: trades grid colors

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/trading-orders.cy.ts, libs/cypress/src/lib/capsule/propose-market.ts
Closes #2730 
1. Capsule tests refactor:
- removed reload() for deposit
- splitted up tests 
2. Increase deposit ac:
- 1001-DEPO-006
- 1001-DEPO-005
=> chore: capsule tests refactor and increase deposit ac

.github/workflows/lint_pr.yml, commitlint.config-ci.js, package.json, yarn.lock
N/A
Lints PR titles with commit lint using nx scopes
=> chore(ci): add nx scope linting for pr title

libs/assets/src/lib/asset-option.tsx, libs/assets/src/lib/index.ts, libs/deposits/src/lib/deposit-form.tsx, libs/ui-toolkit/src/components/dialog/dialog.tsx, libs/ui-toolkit/src/components/select/select.tsx, libs/withdraws/src/lib/withdraw-form.tsx
=> fix(trading): asset option on mobile got overflown

.github/workflows/cypress-run.yml
Closes #2786 
Fixed issue with grepTags not correctly getting used by Cypress
=> test(ci): fix tags in cypress workflow

apps/token/src/components/locked-progress/locked-progress.tsx, apps/token/src/hooks/use-animate-value.ts, apps/token/src/routes/tranches/tranche-progress.tsx, apps/token/src/routes/tranches/vesting-chart.tsx, apps/trading/pages/styles.css, libs/react-helpers/src/lib/grid/flash-cell.tsx, libs/react-helpers/src/lib/grid/size.tsx, libs/react-helpers/src/lib/grid/vol-cell.tsx, libs/tailwindcss-config/src/theme.js, libs/tailwindcss-config/src/vega-custom-classes.js, libs/ui-toolkit/src/components/button/button.tsx, libs/ui-toolkit/src/components/toggle/toggle.tsx, libs/ui-toolkit/src/primitives/colors.stories.mdx
=> chore(ui-toolkit): new colour palette

apps/trading-e2e/src/integration/markets.cy.ts, libs/deal-ticket/src/components/trading-mode-tooltip/trading-mode-tooltip.tsx, libs/governance/src/lib/proposals-hooks/Proposal.graphql, libs/governance/src/lib/proposals-hooks/__generated__/Proposal.ts
Closes #2524 
Add sub-statuses of Opening auction trading mode to the tooltips
Add new gql query for proposal of the market
=> chore(trading): add sub statuses of opening auction trading mode

apps/trading/components/market-trading-mode/market-trading-mode.tsx, libs/market-list/src/lib/market-data-provider.ts
Closes #2758 
Market data pulled was static. Trading mode tooltip was not updating.
=> fix(trading): market data and auction time not updating

apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-limit-amount.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.spec.tsx, libs/deal-ticket/src/hooks/use-fee-deal-ticket-details.tsx, libs/market-info/src/components/fees-breakdown/fees-breakdown.tsx
Closes N/A
Fix symbol on order estimates
=> fix(trading): fix symbol on order estimates

libs/positions/src/lib/positions-table.tsx
Closes #2826 
Remove price flash cell from PNL 
=> fix(trading): remove price flash cell from PNL

apps/trading/.env.validator-testnet
Addresses tasks console setup for #2066
Adds .env.validator-testnet for Console
=> chore(trading): add validator testnet env file

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/withdraw.cy.ts
Closes #2731 
Increased withdraw ac test coverage
=> chore(trading): increase withdraw ac test coverage

apps/token/src/routes/staking/home/validator-tables/shared.tsx
=> feat(governance): remove some performance info from validator mouseover

apps/trading/components/accounts-container/accounts-container.tsx, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx, apps/trading/lib/hooks/use-vega-transaction-toasts.tsx, apps/trading/pages/dialogs-container.tsx, libs/accounts/src/lib/index.ts, libs/accounts/src/lib/transfer-container.tsx, libs/accounts/src/lib/transfer-dialog.tsx, libs/accounts/src/lib/transfer-form.spec.tsx, libs/accounts/src/lib/transfer-form.tsx, libs/react-helpers/src/hooks/use-network-params.spec.tsx, libs/react-helpers/src/hooks/use-network-params.ts, libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.tsx, libs/ui-toolkit/src/components/select/select.tsx, libs/ui-toolkit/src/utils/intent.tsx, libs/wallet/src/connectors/vega-connector.ts, libs/wallet/src/use-vega-transaction-store.tsx, libs/wallet/src/utils.ts
Closes #2615 
Adds a dialog to initiate transfer transactions, which can be opened from the collateral table
- Adds new transfer dialog and transfer form components
- Adds new wallet types and normalize function for transfer payloads
=> feat(trading): key to key transfers

apps/trading/lib/hooks/use-ethereum-transaction-toasts.tsx, apps/trading/lib/hooks/use-ethereum-withdraw-approval-toasts.tsx, apps/trading/lib/hooks/use-vega-transaction-toasts.spec.tsx, apps/trading/lib/hooks/use-vega-transaction-toasts.tsx, apps/trading/pages/toasts-manager.tsx, libs/governance/src/lib/proposals-hooks/use-update-network-paramaters-toasts.tsx, libs/governance/src/lib/proposals-hooks/use-update-network-parameters-toasts.spec.tsx, libs/tailwindcss-config/src/theme.js, libs/ui-toolkit/src/components/progress-bar/progress-bar.tsx, libs/ui-toolkit/src/components/toast/toast.module.css, libs/ui-toolkit/src/components/toast/toast.stories.tsx, libs/ui-toolkit/src/components/toast/toast.tsx, libs/ui-toolkit/src/components/toast/toasts-container.spec.tsx, libs/ui-toolkit/src/components/toast/toasts-container.stories.tsx, libs/ui-toolkit/src/components/toast/toasts-container.tsx, libs/ui-toolkit/src/components/toast/use-toasts.spec.tsx, libs/ui-toolkit/src/components/toast/use-toasts.ts, libs/wallet/src/use-vega-transaction-store.tsx, libs/web3/src/lib/use-ethereum-transaction-store.tsx, libs/web3/src/lib/use-ethereum-withdraw-approvals-manager.tsx, libs/web3/src/lib/use-ethereum-withdraw-approvals-store.tsx, libs/withdraws/src/lib/withdrawals-table.tsx, package.json, yarn.lock
Closes #2735
Closes #2751
* fixes toast container re-renders (zustand subscriptions)
* fixes auto-closing and added pause auto-closing on hover
* added close all button
* changed to new colours and designs 
Designs: https://www.figma.com/file/EaFndX7sV9CgZOdsE2Ilqp/dAPP-Components?node-id=548%3A15951&t=RxpIUUf83DP4mmb3-0
https://user-images.githubusercontent.com/1980305/216690126-9fff2b62-b69e-46be-bf9b-6c652c7c2056.mov
=> chore(trading): new toasts designs

libs/deal-ticket/src/components/deal-ticket/deal-ticket-button.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/wallet/src/use-vega-transaction-manager.spec.tsx, libs/wallet/src/use-vega-transaction-manager.tsx, libs/wallet/src/use-vega-transaction-updater.tsx, libs/wallet/src/use-vega-transaction.spec.tsx, libs/wallet/src/use-vega-transaction.tsx
Closes #2555 
Detect no service and call disconnect on wallet connection
=> fix(trading): inform the user his connection to wallet is lost

apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx, apps/explorer/src/app/components/txs/details/tx-generic.tsx, apps/explorer/src/app/components/txs/details/tx-issue-signatures.tsx
Closes #2130
Adds a basic view for a rare transaction.
=> feat(explorer): add issuesignatures tx view

.github/workflows/cypress-pr.yml
Closes devops-infra/issues/1730
This PR adds step to upload the vegacapsule log  in the PR runs
=> feat(ci): archive logs in cypres pr run

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/withdraw-key-to-key.cy.ts, apps/trading/components/accounts-container/accounts-container.tsx, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx, libs/accounts/src/lib/transfer-container.tsx
Closes #2615 
The e2e tests for key to key transfers
=> chore(trading): key to key transfers e2e tests

libs/react-helpers/src/lib/generic-data-provider.spec.ts, libs/react-helpers/src/lib/generic-data-provider.ts
=> chore(react-helpers): add generic data provider unit test

apps/token-e2e/src/integration/flow/staking-flow.cy.js, apps/token-e2e/src/integration/view/staking.cy.js, apps/token-e2e/src/support/index.js, apps/token-e2e/src/support/wallet-teardown.functions.js, apps/token-e2e/tsconfig.json, apps/token/src/routes/staking/home/validator-tables/shared.tsx
Closes #2876 
Additional E2E tests for validator mouse hover tooltip
=> test(token): e2e tests for validator tooltips

apps/trading-e2e/src/integration/market-info.cy.ts
Fixed copy prompt alert for chrome
=> chore(trading): fixed copy prompt alert for chrome

apps/token-e2e/src/integration/view/home.cy.js, apps/token-e2e/src/integration/view/token.cy.js, apps/token/src/routes/home/index.tsx
Closes #2877 
Update e2e tests for the new homepage that is no longer `/token`
=> test(governance): update home tests

.github/workflows/cypress-pr.yml, .github/workflows/cypress-run.yml
Closes https://github.com/vegaprotocol/devops-infra/issues/1730
I need to see what are the files to archive in cypress run
=> chore(ci): print logs files in cypress pr workflow

apps/trading-e2e/src/integration/navbar.cy.ts
Added a market wait to fix these tests: Trading should be correctly rendered and  Trading should be correctly rendered
=> test(trading): added waiting for market

apps/trading-e2e/src/integration/markets.cy.ts
Fixed dropdown issue in markets tests.
=> test(trading): fixed dropdown issue in markets tests

apps/token-e2e/src/integration/view/home.cy.js, apps/token-e2e/src/integration/view/validators.cy.js, apps/token-e2e/src/integration/view/wallet-vega.cy.js
Small PR to add test for proposals on homepage and rename `staking` view to `validators`
=> test(governance): check proposals on homepage

apps/token/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx
Closes #2642
Previously, only the consensus validator table had a ranking score. Now, standby and pending validator tables will too.
=> feat(governance): ranking score for all validator types

apps/explorer-e2e/src/integration/asset.cy.js, apps/explorer/src/app/components/assets/assets-table.spec.tsx, apps/explorer/src/app/components/assets/assets-table.tsx, apps/explorer/src/app/components/links/asset-link/asset-link.tsx, apps/explorer/src/app/routes/assets/asset-page.tsx, apps/explorer/src/app/routes/assets/assets-page.tsx, apps/explorer/src/app/routes/assets/index.tsx, apps/explorer/src/app/routes/router-config.tsx
Closes #2940 
https://user-images.githubusercontent.com/1980305/220123626-910855c2-babf-4e7c-9205-630309cd9bef.mov
=> chore(explorer): change asset dialog to details page

libs/ui-toolkit/src/components/checkbox/checkbox.tsx
N/A
Fixes checkbox icon size
Before:
After
=> fix(ui-toolkit): set size properly for checkbox icon

.github/workflows/cypress-live-test.yml, apps/trading-e2e/src/integration/markets.cy.ts, apps/trading-e2e/src/integration/navbar.cy.ts
The Node version has been updated for the live tests workflow, and a wait for the markets in before has also been added for navbar tests.
=> test(trading): node version update for live workflow

apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/navbar.cy.ts
Closes #2864 
Deposit flow from collateral window - e2e tests
=> test(trading): deposit flow from collateral window e2e tests

.github/workflows/cypress-live-test.yml, apps/trading-e2e/src/integration/markets.cy.ts, apps/trading-e2e/src/integration/navbar.cy.ts
Improved a drop-down verification test - renders market list drop down
=> test(trading): improved a dropdown verification test

libs/react-helpers/src/lib/format/number.tsx, libs/react-helpers/src/lib/validate/validate-amount.ts
Closes #2970 
Update toDecimal method
`1/Math.pow(10, 8) is 1e-8`
=> fix(trading): update step on market dp

apps/trading-e2e/cypress.config.js, apps/trading-e2e/src/integration/markets.cy.ts, apps/trading-e2e/src/integration/navbar.cy.ts
Closes #2975 
Added rerun mechanism for cypress  tests
=> test(trading): added rerun mechanism for cypress  tests

apps/trading/client-pages/portfolio/account-history-container.tsx
Closes #2978 
Sort properly markets to make them unique in the dropdown
-
=> chore(trading): make markets in dropdown unique

.github/workflows/process-tranches.yml, scripts/get-tranches.js
=> fix(token): mainnet tranches

libs/market-depth/src/lib/orderbook-row.tsx, libs/react-helpers/src/lib/grid/numeric-cell.spec.tsx, libs/react-helpers/src/lib/grid/price-flash-cell.spec.tsx, libs/react-helpers/src/lib/grid/vol-cell.spec.tsx, libs/react-helpers/src/lib/grid/vol-cell.tsx
N/A
Formats volume cells in order book
=> chore(trading): fix formatting for volume cells in book

apps/trading/client-pages/market/trade-market-header.tsx
N/A
Changes 24h volume tooltip to 'The total number of contracts traded in the last 24 hours.'
=> chore(trading): update tooltip text for 24h volume

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/home.cy.ts, apps/trading/components/footer/footer.spec.tsx, apps/trading/components/footer/footer.tsx, libs/cypress/src/lib/mock-gql.ts, libs/environment/src/hooks/use-node-health.ts
Closes #2681 
- Shows block height in the footer
- Adds minimal style footer button
=> feat(trading): show block height

apps/explorer/src/app/components/markets/market-details.tsx, libs/assets/src/lib/asset-details-dialog.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-button.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-limit-amount.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/market-info/src/components/market-info/info-market.tsx, libs/react-helpers/src/lib/format/number.spec.tsx, libs/ui-toolkit/src/components/form-group/form-group.tsx, libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
=> fix(trading): condense deal ticket & market info price range snags

libs/ui-toolkit/src/components/nav/nav.tsx, libs/ui-toolkit/src/components/toast/toast.tsx
N/A
Removes 'calt' font feature from nav and toasts
=> fix(ui-toolkit): remove calt from nav and toasts

apps/token/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards-table.tsx, apps/token/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.spec.ts, apps/token/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.ts, apps/token/src/routes/rewards/epoch-total-rewards/generate-epoch-total-rewards-list.ts, apps/token/src/routes/rewards/home/Rewards.graphql, apps/token/src/routes/rewards/home/__generated__/Rewards.ts
=> fix(governance): some fixes and tweaks for the rewards tables

apps/trading-e2e/src/integration/capsule.cy.ts
Closes #3028 
Fix two capsule tests:
1) can place and receive an order
2) approved amount is less than deposit
=> test(trading): fixed capsule tests

libs/web3/src/lib/use-ethereum-withdraw-approvals-manager.spec.tsx, libs/web3/src/lib/use-ethereum-withdraw-approvals-manager.tsx, libs/web3/src/lib/use-ethereum-withdraw-approvals-store.tsx, libs/withdraws/src/lib/withdrawals-table.tsx
Closes #2923 
Check chainId before withdrawal transaction
=> chore(trading): add handle wrong chainId in withdrawal

apps/explorer/.env.validator-testnet, apps/governance/.env.validator-testnet
Closes #3034
#3033 fixed this for static assets, but the env vars in token and explorer are still wrong
=> fix(ci): fix environment variable setting validator testnet api endpoint

apps/multisig-signer/.env.validator-testnet
Closes #3054
Adds a .env.validator-testnet file for the multisig-signer
=> feat(governance): new env file for multisig on validator-testnet

apps/trading/.env.validator-testnet
N/A
Fixes env vars for validator-testnet console app
=> fix(trading): env vars for validator testnet

apps/trading-e2e/src/integration/trading-positions.cy.ts, libs/utils/src/lib/apollo-client.ts
Closes #3024 
Improve checking no market data error. 
-
Check error message not path nor extension
=> chore(trading): tweaking catching no market data error

apps/trading/components/banner/banner.tsx, libs/react-helpers/src/hooks/use-resize-observer.ts, libs/utils/src/lib/local-logger.ts
Closes #2579 
Wrap callbacks with requestAnimationFrame for avoiding irrelevant errors throwing 
Tweak logger implementation for better instantiation and reporting 
- 
-
=> chore(react-helpers): improve error catching in useResizeObserver

libs/environment/src/components/node-switcher/row-data.tsx
N/A
Add a 3 second timeout to fail a node in the node switcher if data from a TimeUpdate bus event is not received within that period. Now nodes will correctly be marked as 'failed' and not stuck in a pending state
=> fix(trading): add a timeout to show subscriptions as failed

apps/explorer/src/__mocks__/react-markdown.js, apps/explorer/src/app/components/links/proposal-link/proposal-link.tsx, apps/explorer/src/app/components/txs/details/proposal/Proposal.graphql, apps/explorer/src/app/components/txs/details/proposal/SignatureBundle.graphql, apps/explorer/src/app/components/txs/details/proposal/__generated__/Proposal.ts, apps/explorer/src/app/components/txs/details/proposal/__generated__/SignatureBundle.ts, apps/explorer/src/app/components/txs/details/proposal/proposal-date.tsx, apps/explorer/src/app/components/txs/details/proposal/proposal-status-icon.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle-new.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle-update.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle/bundle-error.spec.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle/bundle-error.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle/bundle-exists.spec.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle/bundle-exists.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle/bundle-icon.spec.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle/bundle-icon.tsx, apps/explorer/src/app/components/txs/details/proposal/signature-bundle/details.tsx, apps/explorer/src/app/components/txs/details/proposal/summary.tsx, apps/explorer/src/app/components/txs/details/shared/tx-details-shared.tsx, apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx, apps/explorer/src/app/components/txs/details/tx-proposal.tsx, apps/explorer/src/app/routes/txs/id/tx-details.spec.tsx, apps/explorer/src/styles.css, package.json, yarn.lock
- feat(explorer): wip proposal view
- feat(explorer): basic proposal overview
- feat(explorer): proposal details
- feat(explorer): expand proposal details component
- feat(explorer): add basic signature bundle component
- chore(explorer): update i18n imports after rebase
- chore(explorer): finish splitting up signature bundle component
Closes #2111. Follow up task #3065 will add more interesting info to the signature bundle panel.
Adds details components for a proposal. Mostly it is a quick overview, and a link to the Governance site with a preview
of some key details.
For proposals that require a signature bundle (update asset, new asset), a separate component will render the state of
that.
=> feat(explorer): proposal transaction view

apps/trading/client-pages/market/trade-market-header.tsx
Closes N/A
Update order on market trade header
=> fix(trading): update order on market trade header

apps/trading/client-pages/market/trade-market-header.tsx
Closes N/A
Update order on market trade header. 
Fixing this:
=> fix(trading): update order on market trade header (#3082)

.github/workflows/cypress-run.yml
Revert nonparallel tests option.
=> test(trading): revert nonparallel tests option

libs/positions/src/lib/positions-table.tsx, libs/utils/src/lib/links.ts
=> fix(trading): add loss socialisation docs links

apps/trading-e2e/src/integration/wallets.cy.ts
Closes #3110 
Cover ACs:
https://github.com/vegaprotocol/specs/blob/master/user-interface/0002-WCON-connect_vega_wallet.md
=> test(trading): increase coverage for 0002 wcon

apps/governance-e2e/src/fixtures/proposals/new-market.json, apps/governance-e2e/src/fixtures/proposals/update-market-old.json, apps/governance-e2e/src/integration/flow/proposal-forms.cy.js, apps/governance-e2e/src/support/governance.functions.js, apps/governance/src/routes/proposals/components/vote-details/vote-details.tsx, libs/cypress/src/index.ts, libs/cypress/src/lib/commands/vega-wallet-submit-liquidity-provision.ts, libs/wallet/src/connectors/vega-connector.ts
Closes #3118 
Adds remaining tests for previously skipped governance proposal tests
=> test(governance): new and update market proposal forms

libs/deposits/src/lib/deposit-form.tsx, libs/deposits/src/lib/faucet-notification.tsx, libs/deposits/src/lib/get-faucet-error.ts
N/A
Updates i18n for faucet flow per designs
=> chore(deposits): update faucet feedback i18n

apps/trading/pages/_app.page.tsx
N/A
Moves the sims banner above the main nav, aligning with other apps
=> chore(trading): move banner above nav

apps/explorer/.env.validator-testnet, apps/governance/.env.validator-testnet, apps/multisig-signer/.env.validator-testnet, apps/static/src/assets/validator-testnet-network.json
N/A
Updates validator testnet nodes
=> chore(trading,explorer,governance): update validator testnet nodes

apps/trading-e2e/src/integration/trading-orders.cy.ts, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx
=> feat(orders): use default filters in orders list

apps/explorer/src/app/components/markets/market-details.tsx, apps/explorer/src/app/routes/markets/market-page.tsx, libs/market-info/src/components/market-info/index.ts, libs/market-info/src/components/market-info/info-market.tsx, libs/market-info/src/components/market-info/market-info-panels.tsx
Closes #2956 
* removes redundant code from explorer
* consolidates market info/details panels into one file
* makes it reusable
=> chore(explorer): market info shared panels

apps/explorer/src/app/components/render-fetched/index.tsx, apps/explorer/src/app/routes/txs/id/index.tsx
Closes #3004 
Displays "Try again" button for tx details page if errored.
=> feat(explorer): try again for tx details

apps/trading-e2e/src/integration/market-info.cy.ts
Fixed settlement asset displayed test
=> test(trading): fixed settlement asset displayed test

apps/explorer/.env.validator-testnet, apps/governance/.env.validator-testnet
N/A
Updates rest and be endpoints to all be on vega.rocks
=> chore(explorer,governance): update be endpoints

apps/governance-e2e/src/fixtures/proposals/new-market.json, apps/governance-e2e/src/fixtures/proposals/update-market.json, apps/governance-e2e/src/support/wallet-teardown.functions.js, libs/cypress/src/lib/capsule/propose-market.ts, libs/wallet/src/connectors/vega-connector.ts
Closes #3203 
Fix failing e2e tests on `v0.69` by including slippage factor in proposals
=> chore(governance): include slippage factor to proposals

apps/static/src/assets/devnet-network.json, apps/static/src/assets/mirror-network.json, apps/static/src/assets/sandbox-network.json, apps/static/src/assets/stagnet1-network.json, apps/static/src/assets/stagnet3-network.json, apps/static/src/assets/testnet-network.json
Closes #3179 
Change domain in node addresses due to cert requirements
-
-
=> chore(static): update domains in network conf files

apps/governance/src/components/page-templates/template-sidebar.tsx
Closes #3186 
Update the announcement banner text.
=> chore(governance): update announcement banner text

apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, libs/ui-toolkit/package.json, libs/ui-toolkit/src/components/button/button.tsx
Relate to vegaprotocol/vegawallet-desktop#525
Allow passing of arbitrary icons to button component
=> feat(ui-toolkit): button icons

apps/trading/client-pages/liquidity/liquidity.tsx, apps/trading/client-pages/market/trade-grid.tsx, apps/trading/client-pages/markets/markets-page.tsx, apps/trading/client-pages/portfolio/portfolio.tsx, libs/react-helpers/src/hooks/use-local-storage.spec.ts, libs/react-helpers/src/hooks/use-local-storage.ts, libs/ui-toolkit/src/components/tabs/tabs.tsx
=> feat(trading): store current tab selection

libs/ui-toolkit/src/components/callout/callout.spec.tsx, libs/ui-toolkit/src/utils/intent.ts, libs/web3/src/lib/web3-connect-dialog.tsx
Replace the pink/yellow with blue for 'Primary' intent. Pink is our danger colour.
Changes the Intent.Primary to blue from neutral,  addresses suggestions from this thread: https://vegaprotocol.slack.com/archives/C8WS7M50E/p1678290959049379
=> chore(ui-toolkit): rework intent colours

apps/trading-e2e/src/integration/trading-accounts.cy.ts, libs/accounts/src/lib/accounts-manager.tsx, libs/accounts/src/lib/accounts-table.tsx
Closes #2824
Pin row collateral row and filter. 
=> feat(trading): pin collateral row

apps/trading-e2e/.env, apps/trading-e2e/src/integration/navbar.cy.ts, apps/trading/.env, apps/trading/.env.capsule, apps/trading/.env.devnet, apps/trading/.env.mainnet, apps/trading/.env.mirror, apps/trading/.env.sandbox, apps/trading/.env.stagnet1, apps/trading/.env.stagnet3, apps/trading/.env.testnet, apps/trading/.env.validator-testnet, apps/trading/components/navbar/navbar.tsx
Closes #2804 
Adds a 'Resources' dropdown to Console's navigation. Dropdown contains links to the feedback repo and the docs site, both URLs are set by env vars
=> feat(trading): add resources dropdown to console nav

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts, apps/trading-e2e/src/integration/wallet-vega.cy.ts, libs/cypress/src/lib/commands/mock-transaction-response.ts
Closes #3129 
Increase coverage for AC: 0003-WTXN Submit Vega transaction
=> test(trading): 0003-WTXN submit vega transaction e2e tests

.dockerignore, .github/workflows/cypress-run.yml, .github/workflows/pr-trigger.yml, .github/workflows/publish-docker-containers.yml, Dockerfile, docker-build.sh, dockerfiles/Dockerfile, entrypoint.sh
closes: https://github.com/vegaprotocol/devops-infra/issues/1761
=> feat(explorer,trading,governance): use nx to know which apps needs building

.github/ISSUE_TEMPLATE/release
Creating a new issue template for our dapp releases
=> chore(ci): add release issue template

libs/deposits/src/lib/approve-notification.tsx, libs/deposits/src/lib/deposit-form.tsx
Closes #3264
If user clicks deposit button approve notification intent changes from warning to danger.
=> fix(trading): handle lack of approval in trading deposit flow

libs/deposits/src/lib/deposit-form.tsx
N/A
Removes the faucet button until user has connected
=> chore(trading): dont show faucet button until connected

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
=> fix(trading): throttle deal ticket submit

libs/ui-toolkit/package.json
Should have included this in #3121
Updates the package.json version of ui-toolkit so we can publish a new version to npm.
=> chore(ui-toolkit): version 0.9.0 - includes healthbar in ui-toolkit

apps/governance-e2e/src/integration/flow/staking-flow.cy.ts, apps/governance-e2e/src/integration/view/pubkey-view.cy.ts, apps/governance-e2e/src/support/wallet-teardown.functions.ts
Closes #3270 
Adds E2E test for my stake feature
=> test(governance): my stake e2e tests

apps/trading-e2e/src/integration/trading-chart.cy.ts, libs/candles-chart/src/lib/candles-chart.tsx, libs/react-helpers/src/lib/index.ts, libs/react-helpers/src/lib/validation.ts, libs/ui-toolkit/src/components/tabs/tabs.tsx
Closes #2761 
Persist state of chart intervals studies and overlays
=> feat(trading): persist state of chart intervals studies and overlays

apps/trading-e2e/src/integration/market-info.cy.ts, libs/market-info/src/components/market-info/info-key-value-table.tsx, libs/market-info/src/components/market-info/market-info-panels.tsx
Closes #3229 
https://user-images.githubusercontent.com/1980305/228273935-bc999661-0a70-4ca7-894c-be79b90f165b.mov
=> fix(trading): volumes formatting

apps/governance-e2e/src/integration/flow/staking-flow.cy.ts, apps/governance-e2e/src/integration/view/pubkey-view.cy.ts
Fixes flakey test failures due to incorrect nonce when associating tokens at start of test
=> chore(cypress): fix error seen in CI for staking test

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/live-env.cy.ts, apps/trading-e2e/src/integration/market-info.cy.ts
Closes #3292 
Update the live e2e tests.
=> test(trading): update live e2e tests

libs/market-depth/src/lib/orderbook-row.tsx
=> feat(market-depth): always show the same number of decimal places in order book

apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts, apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts, apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts, apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts, apps/governance-e2e/src/support/common.functions.ts, apps/governance-e2e/src/support/governance.functions.ts, apps/governance-e2e/src/support/staking.functions.ts
=> chore(governance): additional acs added for governance proposals

apps/trading/client-pages/liquidity/liquidity.tsx, libs/liquidity/src/lib/liquidity-data-provider.ts, libs/utils/src/lib/generic-data-provider.ts
Closes #3309 
Make some memoizations into component for avoid frequent re-renders. Improve `getId` method for rows.
-
-
=> fix(trading): stabilize the liquidity provision table

apps/token/README.md, libs/smart-contracts/src/contracts/staking-bridge.ts, libs/smart-contracts/src/contracts/token-vesting.ts, libs/smart-contracts/src/contracts/token.ts, libs/smart-contracts/src/utils/calc-gas-buffer.ts, libs/smart-contracts/src/utils/index.ts
Closes #3325 
Increase gas limit by 20% on the original gas estimation
=> fix(smart-contracts): add mainnet gas estimation

libs/liquidity/src/lib/MarketLiquidity.graphql, libs/liquidity/src/lib/MarketsLiquidity.graphql, libs/liquidity/src/lib/__generated__/MarketLiquidity.ts, libs/liquidity/src/lib/__generated__/MarketsLiquidity.ts, libs/liquidity/src/lib/liquidity-data-provider.ts
Closes #3309 
Set flag live on true in liquidityProvisionsConnection in market query
-
-
=> chore(trading): liquidity provision, change query for set flag live on true

apps/governance-e2e/.env, apps/governance-e2e/src/integration/view/home.cy.ts, apps/governance/.env.capsule
Adds e2e for banner and github links in footer.
Add config variable to allow banner to show in capsule.
=> test(governance): add e2e tests for banner and footer links

libs/fills/src/lib/fills-table.spec.tsx, libs/orders/src/lib/components/order-list/order-list.spec.tsx, libs/positions/src/lib/positions-table.spec.tsx
Closes #3188 
CLean up some unit test from unnecessary wrappers
-
-
=> chore(trading): add metaKey detection - clean up some unit tests

apps/trading/client-pages/liquidity/liquidity.tsx, libs/liquidity/src/lib/liquidity-data-provider.ts
=> chore(trading): liquidity table DRY

apps/governance/src/config/env.ts, apps/governance/src/contexts/contracts/contracts-provider.tsx, apps/governance/src/routes/token/token-details/token-details.tsx
N/A
Adds a fallback token vesting contract address so that the governance app for the validator testnet network can load and render correctly
=> chore(governance): add hardcoded token vesting contract address

libs/orders/src/lib/components/order-data-provider/Orders.graphql, libs/orders/src/lib/components/order-data-provider/__generated__/Orders.ts, libs/orders/src/lib/components/order-data-provider/order-data-provider.spec.ts, libs/orders/src/lib/components/order-data-provider/order-data-provider.ts, libs/orders/src/lib/components/order-list-manager/use-order-list-data.ts, libs/orders/src/lib/order-hooks/use-pending-orders-volume.ts, libs/positions/src/lib/close-position-dialog/shared.tsx, libs/positions/src/lib/positions-data-providers.ts, libs/positions/src/lib/use-request-close-position-data.ts
Closes #3342
Restore marketId variable in orders query
=> fix(orders): restore filter by marketId

apps/governance/.env.validator-testnet
Closes n/a
add missing config url for announcements
=> fix(governance): add missing announcement config url

libs/smart-contracts/src/contracts/claim.ts, libs/smart-contracts/src/contracts/collateral-bridge.ts, libs/smart-contracts/src/contracts/multisig-control.ts, libs/smart-contracts/src/contracts/staking-bridge.ts, libs/smart-contracts/src/contracts/token-faucetable.ts, libs/smart-contracts/src/contracts/token-vesting.ts, libs/smart-contracts/src/contracts/token.ts, libs/smart-contracts/src/utils/calc-gas-buffer.ts, libs/smart-contracts/src/utils/index.ts
Closes #3370 
Fetches the estimated gas and increases it by 20% to provide more of a buffer on the default gas limit provided by ethers
=> fix(smart-contracts): add increased gas limit estimation

libs/deposits/src/lib/approve-notification.tsx
N/A
Fixes bad grammar on the approval notification
=> chore(trading): fix bad grammar on approval notification

apps/governance/src/routes/staking/PreviousEpoch.graphql, apps/governance/src/routes/staking/__generated__/PreviousEpoch.ts, apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.spec.tsx, apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx, apps/governance/src/routes/staking/node/validator-table.tsx, apps/governance/src/routes/staking/shared.spec.ts, apps/governance/src/routes/staking/shared.ts
Closes #3353
Closes #3162
Correct calculation of overstaking penalty and incorporating more data required from the previous epoch
=> fix(governance): fix incorrect validator penalties

apps/trading-e2e/src/integration/markets.cy.ts, apps/trading/client-pages/markets/proposed.tsx, libs/cypress/src/lib/utils.ts, libs/market-list/src/lib/components/markets-container/market-list-table.tsx, libs/market-list/src/lib/components/markets-container/markets-container.tsx, libs/proposals/src/lib/proposals-list/proposal-list.spec.tsx, libs/proposals/src/lib/proposals-list/proposals-list.tsx, libs/proposals/src/lib/proposals-list/use-column-defs.tsx
Closes #2939 
Add filters to proposal table. Also tweak some markets table filters 
-
=> chore(trading): add filters to the proposals table

apps/trading/client-pages/liquidity/liquidity.tsx, apps/trading/components/liquidity-supplied/liquidity-supplied.tsx, libs/utils/src/lib/links.ts
Closes #3300 
Adding LP docs links. 
=> fix(trading): add liquidity provision docs

libs/deposits/src/lib/use-submit-approval.ts
Closes #3212 
Updates default deposit approval amount to be the max safe uint256 int
=> chore(trading): update approval amount to be max uint256

libs/datagrid/src/lib/cells/cumulative-vol-cell.tsx, libs/market-depth/src/lib/orderbook-manager.tsx
=> fix(market-depth): make market data up to date, use fixed number of decimals in cumulative vol

apps/trading-e2e/src/integration/deposit.cy.ts, libs/deposits/src/lib/approve-notification.tsx, libs/deposits/src/lib/deposit-form.spec.tsx, libs/deposits/src/lib/deposit-form.tsx, libs/deposits/src/lib/deposit-limits.tsx, libs/deposits/src/setup-tests.ts
Closes #3102 
Tweak messages and layout according to amendments design of ux wireframe
=> chore(deposits): impove UX on deposit dialog

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/trading-deal-ticket-submit.cy.ts, apps/trading-e2e/src/integration/trading-deal-ticket-validations.cy.ts, apps/trading-e2e/src/integration/wallet-vega.cy.ts
Closes #3407 
Covered ACs:
// 1001-DEPO-007
// 1001-DEPO-004
// 0002-WCON-016
// 0003-WTXN-008
// 7002-SORD-030
// 0002-WCON-015
// 0002-WCON-009
=> test(trading): increase coverage for the remaining ACs

libs/deposits/src/lib/deposit-form.tsx, libs/deposits/src/lib/deposit-manager.tsx, libs/deposits/src/lib/use-persistent-deposit.spec.ts, libs/deposits/src/lib/use-persistent-deposit.ts
Closes #3413 
Fix wrong logic of evaluating values from the store
-
-
=> fix(deposits): deposit dialog doesn't respect given assetId

apps/trading/lib/hooks/use-vega-transaction-toasts.spec.tsx, apps/trading/lib/hooks/use-vega-transaction-toasts.tsx, libs/orders/src/lib/utils.spec.ts, libs/orders/src/lib/utils.ts
Closes N/A
Update order toast intent and title.
Bug observed:
=> fix(orders): update order toast intent and title 

apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts, apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts, apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts, apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts, apps/governance-e2e/src/support/governance.functions.ts, apps/governance-e2e/src/support/wallet-teardown.functions.ts
Fix several failing nightly tests and small changes to common functions to reduce flaky failures.
=> fix(governance): failing nightly tests

apps/explorer/src/app/components/footer/footer.tsx
Closes #3417
Shows 'Share your feedback' instead of just feedback on medium screens
=> fix(explorer): tweak footer to show more detail on smaller screens

apps/trading-e2e/src/integration/trading-accounts.cy.ts, libs/assets/src/lib/Assets.graphql, libs/assets/src/lib/__generated__/Assets.ts, libs/assets/src/lib/asset-details-dialog.spec.tsx, libs/assets/src/lib/asset-details-dialog.tsx, libs/assets/src/lib/assets.mock.ts
Closes #3415 
Get rid of "ResourceExausted" gql error on asset list
-
-
=> chore(assets): make query for asset list lighter

apps/explorer/.env.capsule, apps/explorer/.env.vegacapsule, apps/governance-e2e/.env, apps/governance-e2e/src/integration/flow/proposal-list.cy.ts, apps/governance-e2e/src/integration/view/home.cy.ts, apps/governance-e2e/src/integration/view/wallet-vega.cy.ts, apps/governance-e2e/src/support/governance.functions.ts, apps/governance-e2e/src/support/wallet-teardown.functions.ts, apps/governance/.env.capsule, apps/trading/.env.capsule
Some changes to wallet teardown used in Governance tests to improve some of the failures
Fixed failing announcement banner test
=> fix(governance): fix flaky tests due to wallet teardown

libs/market-list/src/lib/components/markets-container/market-list-table.tsx
=> fix(trading): amend market list settlement asset column getter

libs/react-helpers/package.json, libs/react-helpers/project.json, libs/tailwindcss-config/package.json, libs/tailwindcss-config/project.json, libs/ui-toolkit/package.json, libs/ui-toolkit/project.json, libs/utils/package.json, libs/utils/project.json
N/A
Publish both CJS and ESM modules for packages.
=> chore(ui-toolkit,react-helpers,utils,tailwindcss-config): add more build targets

apps/trading-e2e/src/integration/trading-fills.cy.ts
Closes #3523 
Tests for ACs - 7005-FILL-fills
// 7005-FILL-001
// 7005-FILL-002
// 7005-FILL-003
// 7005-FILL-004
// 7005-FILL-005
// 7005-FILL-006
// 7005-FILL-007
// 7005-FILL-008
=> test(trading): tests for ac - 7005-FILL-fills

apps/static/src/assets/mainnet-network.json
=> chore(static): remove unusable mainnet data nodes

libs/fills/src/lib/fills-table.spec.tsx, libs/fills/src/lib/fills-table.tsx, libs/types/src/__generated__/types.ts, libs/types/src/global-types-mappings.ts
Closes #3466 
Handle unspecified added for the aggressor. 
=> fix(fills): handle side_unspecified added for the aggresor

apps/trading/components/welcome-dialog/telemetry-approval.tsx
Closes #3557
Change omitted font color style
-
-
=> feat(trading): settings page quick adjust a css

apps/trading-e2e/src/integration/trading-accounts.cy.ts
Closes #3389 
Tests for ACs - 6501-ASSE-assets
// 6501-ASSE-001
// 6501-ASSE-002
// 6501-ASSE-003
// 6501-ASSE-004
// 6501-ASSE-005
// 6501-ASSE-006
// 6501-ASSE-007
// 6501-ASSE-008
// 6501-ASSE-009
// 6501-ASSE-010
// 6501-ASSE-011
// 6501-ASSE-012
// 6501-ASSE-013
=> test(trading): ac for 6501-ASSE-assets - e2e tests

apps/trading-e2e/src/integration/trading-fills.cy.ts, libs/fills/src/lib/fills.mock.ts
Closes #3466 
Handle unspecified side in fills table - e2e tests
=> test(trading): handle unspecified side in fills table - e2e tests

.github/workflows/publish-dist.yml
relates to: https://github.com/vegaprotocol/frontend-monorepo/issues/3603
=> feat(ci): deploy develop to stagnet1

apps/explorer-e2e/src/integration/network.cy.js, apps/governance-e2e/src/integration/view/proposal.cy.ts, apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/live-env.cy.ts
Update of capsule and live tests.
=> test(trading): update of capsule and live tests

apps/explorer-e2e/src/fixtures/net_parameter_format_lookup.json, apps/explorer/src/app/routes/network-parameters/network-parameters.tsx, libs/cypress/src/lib/commands/get-network-parameters.ts
N/A
Fixes broken e2e tests by puting update asset proposal network params into correct fixture lookup sections
=> fix(explorer): network params fixture lookup for updateAsset proposals

apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/support/governance.functions.ts
Closes #3604 
Refactored date format functions used in testing proposal dates to include local time zone.
=> chore(governance): assert proposal dates

apps/explorer/src/styles.css, apps/governance/src/styles.css, apps/trading/pages/styles.css
N/A
Increases the specificity of the selectors for custom properties for ag grid so that borders are rendered correctly
=> fix(datagrid): remove default balham borders

apps/governance-e2e/src/integration/flow/withdrawal-flow.cy.ts
Closes #3552 
Update test to assert withdrawal toasts
=> test(governance): e2e test to include withdrawal toasts

apps/trading/pages/styles.css
Closes #3643 
Fast fix on wrong hover effect.
-
=> fix(trading): wrong hover effect on datagrid

apps/explorer/src/app/routes/parties/id/index.tsx
Closes #3649 
* fixes build error coming from explorer
=> fix(explorer): use data provider import

apps/explorer-e2e/.env.mainnet, apps/explorer/.env.mainnet, apps/governance-e2e/.env.mainnet, apps/governance/.env.mainnet, apps/liquidity-provision-dashboard/.env.mainnet, apps/multisig-signer/.env.mainnet
=> chore(explorer,trading,governance): new data node & explorer service urls

apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx
=> fix(governance): consensus table works without previous epoch

apps/governance/src/app-loader.tsx
Closes #3665
Ensures proper display of contract amounts after the removal of ethers from libs
=> fix(governance): total supply displayed

scripts/make-release.js
=> fix(trading): fix release script for mainnet

apps/explorer/src/app/app.tsx, apps/explorer/src/app/components/footer/footer.tsx, apps/governance/src/app.tsx, apps/governance/src/i18n/translations/dev.json, apps/trading-e2e/src/integration/closed-markets.cy.ts, apps/trading-e2e/src/support/trading.ts, apps/trading/components/app-loader/app-loader.tsx, apps/trading/components/app-loader/index.tsx, apps/trading/components/footer/footer.tsx, apps/trading/pages/_app.page.tsx, apps/trading/stores/global.ts, libs/cypress/mock.ts, libs/environment/src/components/app-failure/app-failure.tsx, libs/environment/src/components/app-failure/index.ts, libs/environment/src/components/index.ts, libs/environment/src/components/node-guard/NodeGuard.graphql, libs/environment/src/components/node-guard/__generated__/NodeGuard.ts, libs/environment/src/components/node-guard/node-guard.mock.ts, libs/environment/src/components/node-guard/node-guard.tsx, libs/environment/src/components/node-switcher/row-data.tsx, libs/environment/src/hooks/index.ts, libs/environment/src/hooks/use-node-switcher-store.ts, libs/network-info/src/network-info.tsx
#3672 
Allows selecting to any node, regardless of start up checks. Added NodeGuard component to allow switching nodes in case your selected node wasn't suitable
=> feat(explorer,governance): always allow selecting a node, add node guard

apps/trading/components/footer/footer.spec.tsx, libs/environment/src/components/node-switcher/row-data.spec.tsx
N/A
Fixes tests after changes to the environment lib
=> chore(environment,trading): fix unit tests for footer and node switcher

.github/workflows/publish-dist.yml, apps/trading-e2e/src/integration/market-info.cy.ts, apps/trading-e2e/src/integration/wallet-eth.cy.ts, libs/datagrid/src/lib/ag-grid/use-column-sizes.ts
Closes #3227 
Show full oracle profile info in markets - e2e tests
=> test(trading): show full oracle profile info in markets test

apps/governance/src/app.tsx
=> fix(governance): more thorough catch for url in error reporting

apps/governance-e2e/src/integration/view/proposal.cy.ts
Closes #3746
Tweak to fix network upgrade proposal e2e test
=> fix(governance): network upgrade proposal e2e test tweak

apps/trading/client-pages/settings/settings-button.tsx, apps/trading/components/navbar/navbar.spec.tsx, apps/trading/components/navbar/navbar.tsx
Closes #3744 
Add flag to the link for make matching links as active in strict mode
-
-
=> fix(trading): match link as active more strictly

apps/governance/src/app.tsx
N/A
Fixes issue where sentry was being activated even if the user had chosen to not opt in
=> fix(governance): check value of telemetry local storage entry

apps/trading/client-pages/market/asset-dropdown.tsx, apps/trading/client-pages/market/market-selector.tsx, apps/trading/client-pages/market/sort-dropdown.tsx, apps/trading/client-pages/market/trade-grid.tsx, libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-cross.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-trend-up.tsx, libs/ui-toolkit/src/components/icon/vega-icons/vega-icon-record.ts, libs/ui-toolkit/src/components/input/input.tsx, libs/ui-toolkit/src/utils/shared.ts
Follow up for #3457 
Makes some additional changes for the market selector
- Add reset buttons and separators for asset filter and sort
- Updates to use ui-toolkit Input.
- Updates ui-toolkit Input styles to match latest designs
- Adds a reset button for search input
- Increase of width of sidebar to match designs
- Updates dropdown trigger styles to match designs
- Updates asset and sort dropdown icons
=> feat(trading): sidebar market list adjustments

apps/trading-e2e/src/integration/trading-orders.cy.ts
Closes #3551 
The tests for pegged orders.
=> test(trading): pegged orders e2e tests

apps/trading/client-pages/market/market-selector.spec.tsx, apps/trading/client-pages/market/use-market-selector-list.spec.tsx, apps/trading/client-pages/market/use-market-selector-list.ts
N/A
Updates filter for market selector to include markets that are in opening auction state
=> chore(trading): show markets in opening auction in market selector

.github/workflows/add-ipfs-notes-to-release.yml
closes: https://github.com/vegaprotocol/devops-infra/issues/1876
=> feat(ci): fix release body

apps/governance-e2e/.env, apps/governance/.env, apps/governance/.env.capsule, apps/governance/.env.devnet, apps/governance/.env.mainnet, apps/governance/.env.stagnet1, apps/governance/.env.testnet, apps/governance/.env.validator-testnet, apps/governance/src/config/env.ts, apps/governance/src/routes/proposals/components/proposal/proposal.spec.tsx, apps/governance/src/routes/proposals/components/proposal/proposal.tsx, apps/governance/src/routes/proposals/proposal/proposal-container.tsx, libs/ui-toolkit/src/components/syntax-highlighter/syntax-highlighter.tsx
TBC
Show JSON based on REST api as Graphql API is missing some data
=> feat(governance): use rest to expose proposal data

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/home-node-network.cy.ts, apps/trading-e2e/src/integration/home.cy.ts, libs/environment/src/components/network-switcher/network-switcher.tsx
Closes #3510 
e2e tests for select network and nodes - 0006-NETW
=> test(trading): e2e test for select network and nodes - 0006-NETW

apps/governance/src/routes/proposals/components/protocol-upgrade-proposals-list-item/protocol-upgrade-proposals-list-item.tsx, apps/governance/src/routes/router-config.tsx, apps/governance/src/routes/routes.ts
=> feat(governance): change url of upgrade proposals

apps/governance-e2e/src/fixtures/proposals/new-market-raw.json, apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts, apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts, apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts, apps/governance-e2e/src/integration/flow/proposal-list.cy.ts, apps/governance-e2e/src/integration/flow/staking-flow.cy.ts, apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts, apps/governance-e2e/src/integration/flow/withdrawal-flow.cy.ts, apps/governance-e2e/src/integration/view/pubkey-view.cy.ts, apps/governance-e2e/src/support/governance.functions.ts, apps/governance-e2e/src/support/proposal.functions.ts, apps/governance-e2e/src/support/wallet-teardown.functions.ts
This PR contains fixes for a lot of governance tests that are failing in the nightly run.
- Follow up work still required to clean up old proposal flows
- Several tests skipped due to above
- Tests updated to include validators self stake
- New function added to allow different proposals to be submitted by raw json
=> test(governance): 3790 proposal tests refactor

apps/governance/src/routes/proposals/components/proposal/proposal.tsx
=> feat(governance): hide proposal details on market proposals

apps/trading-e2e/src/integration/trading-orders.cy.ts, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/orders/src/lib/components/order-list/order-list.spec.tsx, libs/orders/src/lib/components/order-list/order-list.tsx
Closes #3684 
Cancel all orders on all markets
=> fix(orders): cancel all and pegged orders amendable

apps/governance/src/routes/staking/PreviousEpoch.graphql, apps/governance/src/routes/staking/__generated__/PreviousEpoch.ts, apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.spec.tsx, apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx, apps/governance/src/routes/staking/node/validator-table.tsx, apps/governance/src/routes/staking/shared.spec.ts, apps/governance/src/routes/staking/shared.ts
Closes #3700
* performance penalty is taken from rankingScore
* overstaked and overall (total) penalties are being calculated based on the theoretical stake score
* removed stake needed for promotion column
=> fix(governance): penalties calculation

apps/explorer/.env.mainnet, apps/governance/.env.devnet, apps/governance/.env.mainnet, apps/governance/.env.stagnet1, apps/governance/.env.testnet, apps/governance/.env.validator-testnet, apps/trading/.env.devnet, apps/trading/.env.mainnet, apps/trading/.env.stagnet1, apps/trading/.env.testnet, apps/trading/.env.validator-testnet
Closes #3659 
Moves sentry DSNs to env files
=> chore(governance,explorer,trading): move sentry dsn to env files

libs/ui-toolkit/src/components/toast/toast-position-setter.tsx, libs/ui-toolkit/src/components/toast/use-toasts.ts
Closes #3878 
* dismissing a test toast removes it from toasts collection
=> fix(ui-toolkit): test toast configuration

apps/explorer/src/app/components/footer/footer.tsx, apps/explorer/src/app/routes/pages/disclaimer.tsx, apps/explorer/src/app/routes/route-names.tsx, apps/explorer/src/app/routes/router-config.tsx
Closes #3736
Adds info about the reliabiltiy of the data to the footer
=> feat(explorer): footer updates

libs/markets/src/lib/markets-provider.ts, libs/positions/src/lib/positions-data-providers.ts
=> feat(trading): show positions for all markets

apps/trading/components/navbar/navbar.tsx, libs/announcements/src/lib/announcements.tsx, libs/environment/src/components/network-switcher/network-switcher.tsx, libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-arrow-down.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-chevron-down.tsx, libs/ui-toolkit/src/components/icon/vega-icons/vega-icon-record.ts, libs/ui-toolkit/src/components/link/link.tsx, libs/ui-toolkit/src/components/navigation/navigation.tsx
N/A
Style changes to make nav and announcement banner align with designs
**Annoucement banner**
- Change to vega cross icons
- Move close to the right
- Don't use uppercase
**Nav**
- Remove `calt` from nav text
- Adjust dropdown padding and colors
- Change dropdown and external link icon to vega version
- Add chevron for network switcher dropdown
=> chore(ui-toolkit): adjust nav styles and banner

libs/proposals/src/components/proposals-list/proposals-list.tsx
Closes #3889 
Make row counting durable for race conditions
-
-
=> fix(trading): improve data count on proposed markets

libs/deposits/src/lib/deposit-form.spec.tsx, libs/deposits/src/lib/deposit-limits.tsx, libs/deposits/src/lib/use-deposit-balances.ts, libs/deposits/src/lib/use-get-deposit-maximum.ts, libs/smart-contracts/src/contracts/collateral-bridge.ts
Closes #3901 
* displays "Exempt" if exempt
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/747a418e-1a9b-47b8-b795-3994b98a3555
=> feat(deposits): mark remaining deposit allowance as exempt

libs/environment/src/hooks/use-links.ts, libs/withdraws/src/lib/withdraw-form.tsx
* updates the link to the withdrawal limits docs page
=> fix(withdraws): link to the withdrawal limits

apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/integration/flow/rewards-flow.cy.ts, apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts, apps/governance-e2e/src/integration/flow/withdrawal-flow.cy.ts, apps/governance-e2e/src/integration/view/proposal.cy.ts, apps/governance-e2e/src/support/wallet-eth.functions.ts
Fixes for failing nightly tests
=> chore(governance): update nightly tests

apps/governance-e2e/src/integration/flow/rewards-flow.cy.ts, apps/governance-e2e/src/support/staking.functions.ts
Fix for failing e2e reward tests.
=> chore(governance): reward tests passing

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx
N/A
Removes stray console log from vega connect button
=> chore(trading): remove stray log

.github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/user-story.md
N/A
Updates issue templates to include note about adjusting specs
=> chore(trading,governance,explorer): update issue templates to include check in specs repo

apps/trading-e2e/src/integration/capsule.cy.ts, libs/web3/src/lib/withdrawal-approval-dialog.tsx
Closes #3874 
Withdrawal details for extra security e2e tests
=> test(trading): withdrawal details for extra security e2e tests

apps/explorer-e2e/.env, apps/explorer-e2e/.env.devnet, apps/explorer-e2e/.env.mainnet, apps/explorer-e2e/.env.testnet, apps/explorer/.env, apps/explorer/.env.stagnet1
Closes #3974
Fixes an old reference to stagnet3 in an env var that causes the site not to load on stagnet1
=> fix(explorer): fix stagnet1 env

.gitignore, apps/governance-e2e/cypress.config.js, apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts, apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts, apps/governance-e2e/src/integration/view/proposal.cy.ts, apps/governance-e2e/src/support/governance.functions.ts
Closes #3490 #3492 #3498 #3491 #3493 #3499 #3500 #3705 #3714 #3715 
Refactors existing proposal tests to use new proposal flow of downloading proposal json and submitting it in raw proposal form
Adds additional ACs for each proposal
=> chore(governance): 3929 proposal acs

apps/trading-e2e/src/support/trading.ts, libs/cypress/src/lib/mock-gql.ts, libs/network-parameters/src/network-params.mock.ts
Updated the network param mocks methods.
=> test(trading): add network param mocks

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/home-node-network.cy.ts
=> test(trading): reverted node tests

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/trading-accounts.cy.ts, apps/trading-e2e/src/integration/withdraw-key-to-key.cy.ts
Closes https://github.com/vegaprotocol/frontend-monorepo/issues/3509
Adds tests to cover the transfer ACs
=> test(trading): key to key transfer tests

apps/trading-e2e/src/integration/market-all.cy.ts, apps/trading-e2e/src/integration/markets-proposed.cy.ts, apps/trading-e2e/src/integration/markets.cy.ts
Closes #3504 
Closes #3505 
6001-MARK-find_markets e2e tests
=> test(trading): 6001-MARK-find_markets e2e tests

apps/trading-e2e/src/integration/assets.cy.ts, apps/trading-e2e/src/integration/trading-accounts.cy.ts
Closes #4021
E2E tests to cover the ACs of the assets dialog window.
I moved and refactored the previous asset test so that we have a seperate file for all asset window tests.
=> test(trading): 6501-ASSE-assets e2e tests
