apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts
apps/governance-e2e/src/integration/flow/rewards-flow.cy.ts
libs/cypress/src/lib/commands/vega-wallet-top-up-rewards-pool.ts

Fix occasional flaky test failures

chore(governance): fix flaky test failures

---

libs/react-helpers/package.json
libs/ui-toolkit/package.json
libs/utils/package.json

Bump `ui-toolkit`, react-helpers` and `utils` so we can publish updated versions.

chore(ui-toolkit,react-helpers,utils): publish new versions of ui-toolkit, react-helpers and utils

---

apps/static/src/assets/preloader.css
apps/static/src/preloader.scss
libs/ui-toolkit/src/components/loader/loader.module.scss
libs/ui-toolkit/src/components/loader/loader.tsx

N/A
Fixes the gaps in the loader when displayed as large

fix(ui-toolkit): display of loader in large variant

---

apps/trading-e2e/src/integration/trading-positions.cy.ts
libs/positions/src/lib/positions.mock.ts
package.json
yarn.lock

Closes #3502
Adds tests to cover 7004-POSI-positions ACs

test(trading): 3502-POSI-e2e-tests

---

libs/markets/src/lib/components/oracle-full-profile/oracle-full-profile.tsx
libs/markets/src/lib/hooks/use-market-oracle.spec.ts
libs/markets/src/lib/hooks/use-market-oracle.ts
libs/markets/src/lib/hooks/use-oracle-markets.spec.ts
libs/markets/src/lib/hooks/use-oracle-markets.ts

Closes #4032 
Fix oracle - markets matching.
Fix oracle matching based on signed messages from oracle object not from the array of proofs.

fix(trading): oracle markets matching 

---

apps/trading-e2e/src/integration/order-book.cy.ts

Closes #3506 
Coverage for orderbook Acceptance Criteria - https://github.com/vegaprotocol/specs/blob/master/user-interface/6003-ORDB-order_book.md (PR with ACs in review at the moment of creating this PR)

test(trading): #3506 orderbook AC coverage

---

apps/trading-e2e/src/integration/market-liquidity.cy.ts
apps/trading-e2e/src/integration/market-selector.cy.ts
apps/trading-e2e/src/integration/trading-accounts.cy.ts
apps/trading/client-pages/market/market-selector.tsx

test(trading): markets selector ACs update

---

.github/workflows/add-ipfs-notes-to-release.yml
.github/workflows/ci-cd-trigger.yml
.github/workflows/publish-dist.yml

closes: https://github.com/vegaprotocol/devops-infra/issues/1914

feat(ci): align releases for all apps

---

apps/trading/components/app-loader/app-loader.tsx
libs/accounts/src/lib/accounts-data-provider.ts
libs/positions/src/lib/positions-data-providers.ts
libs/trades/src/lib/trades-data-provider.ts

N/A
Adds type/cache policies and a merge function for stats to remove apollo warnings.

chore(trading): clear apollo warnings

---

apps/trading-e2e/src/integration/trading-trades.cy.ts
libs/trades/src/lib/trades.mock.ts

Closes #3508 
Tests for Trades Acceptance criteria - https://github.com/vegaprotocol/specs/blob/master/user-interface/6005-THIS-trade_history.md

test(trading): #3508 tests for Trades ACs

---

apps/trading-e2e/src/integration/trading-deal-ticket-submit-account.cy.ts
libs/accounts/src/lib/accounts.mock.ts
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx

Closes #4017
Check both general and margin account for no collateral validation

feat(deal-ticket): improve no collateral validation

---

apps/trading/client-pages/portfolio/deposits-container.tsx
libs/deposits/src/lib/deposits-table.tsx

N/A
Makes sure the deposit table loading state is rendered correctly
- Makes sure we pass undefined to the grid initially as that is what ag grid uses to determine a 'not yet loaded 'state

fix(trading): deposit table loading state

---

apps/explorer/src/app/components/markets/markets-table.tsx
libs/datagrid/src/lib/type-helpers.ts
libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx
libs/markets/src/lib/components/markets-container/use-column-defs.tsx
libs/positions/src/lib/liquidation-price.tsx
libs/positions/src/lib/positions-data-providers.ts
libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions-table.tsx
libs/utils/src/lib/format/index.ts
libs/utils/src/lib/format/range.spec.ts
libs/utils/src/lib/format/range.ts

Closes #4003
Add liquidation price to positions table

feat(positions): add liquidation to positions view

---

libs/fills/src/lib/fills-data-provider.ts

fix(fills): fix mapping fill update

---

libs/ui-toolkit/package.json
libs/ui-toolkit/src/components/healthbar/healthbar.tsx
libs/utils/package.json

Closes #4118 
Fixes a couple issues with the healthbar component:
* It was incorrectly representing fee levels
* It wasn't passing decimals value through to the segments, so displayed staked amount numbers incorrectly

fix(ui-toolkit): healthbar fee decimals

---

apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts
apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts
apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts
apps/governance-e2e/src/integration/view/wallet-vega.cy.ts
libs/cypress/src/lib/capsule/submit-proposal.ts
libs/cypress/src/lib/commands/vega-wallet-submit-proposal.ts

- Add assertion to market proposal specification 
- Fix failing proposal form tests
- Un-skip proposal form validation tests

test(governance): test market details specifications

---

apps/trading-e2e/src/integration/charts-depth.cy.ts

Closes #4157 
Chart depth e2e tests

test(trading): chart depth e2e tests

---

libs/orders/src/lib/components/order-list/order-list.tsx

Change columns definition to use columnDefs prop in orders list. Fix sorting by size and filled

chore(orders): use columnDefs in orders list, fix sorting by size and filled

---

apps/trading/client-pages/market/market-selector.tsx

fix(trading): avoid items remounting in MarketSelector List

---

apps/governance-e2e/src/fixtures/mocks/previous-epoch.ts
apps/governance-e2e/src/integration/view/validators.cy.ts
apps/governance-e2e/src/integration/view/wallet-vega.cy.ts

Closes #3802 
- Add test for validator multisig penalty error
- Fix flaky vega wallet test

test(governance): 3802 multisig error test

---

libs/liquidity/src/lib/MarketLiquidity.graphql
libs/liquidity/src/lib/__generated__/MarketLiquidity.ts
libs/liquidity/src/lib/liquidity-data-provider.ts
libs/liquidity/src/lib/liquidity-table.tsx

N/A
Uses LiquidityProvision id for the the liquidity table getRowId function and for the update function in the data provider

fix(liquidity): use LiquidityProvision id

---

libs/announcements/.babelrc
libs/announcements/.eslintrc.json
libs/announcements/project.json

#3980 
The output path of the announcements build was incorrect

fix(announcements): update output path for announcements build

---

apps/governance-e2e/src/integration/flow/proposal-details.cy.ts
apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts
apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts
apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts
apps/governance-e2e/src/integration/flow/proposal-list.cy.ts
apps/governance-e2e/src/integration/flow/rewards-flow.cy.ts
apps/governance-e2e/src/integration/flow/staking-flow.cy.ts
apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts
apps/governance-e2e/src/integration/view/proposal.cy.ts
apps/governance-e2e/src/integration/view/rewards.cy.ts
apps/governance-e2e/src/integration/view/token.cy.ts
apps/governance-e2e/src/integration/view/validators.cy.ts
apps/governance-e2e/src/integration/view/vesting.cy.ts
apps/governance-e2e/src/integration/view/wallet-eth.cy.ts
apps/governance-e2e/src/integration/view/wallet-vega.cy.ts
apps/governance-e2e/src/integration/view/withdraw.cy.ts
apps/governance-e2e/src/support/wallet-functions.ts

- Fixes flaky tooltip test
- Fixes staking tests sometimes skipping in nightly run due to wallet not tearing down in after each hook.
- Added wait to fix error which sometimes occurs when Eth transaction has not fully completed cause nonce error. This only happens in tests that use wallet and contract tokens together. 
- Tidied up test ids in test files to be consistent throughout
- Try to fix flaky vega wallet test

test(governance): fix staking tooltip test

---

apps/trading/client-pages/market/trade-grid.tsx

Closes #3997 
Do not apply market filter to fills table.

feat(trading): show fills across all markets

---

libs/ui-toolkit/package.json
libs/ui-toolkit/src/components/healthbar/healthbar.tsx
libs/utils/package.json

Closes #4118 
Specify the text colour for tooltips rendered by the Healthbar.

fix(ui-toolkit): healthbar tooltips text colour

---

libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions-table.tsx

fix(positions): use market decimal places to format realized and unrealized PnL

---

apps/governance-e2e/src/integration/view/proposal.cy.ts

Linked to: #4190 
Add e2e test for proposal filter change

chore(governance): add e2e test for proposal filter changes

---

apps/explorer-e2e/src/integration/asset.cy.js
apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts

Skipping update market test due to #4262

chore(governance): skip test

---

apps/trading-e2e/src/integration/capsule.cy.ts

test(trading): add withdrawal delayed

---

apps/explorer/webpack.config.js
apps/governance/webpack.config.js
apps/trading/README.md

chore(trading): ignore parse source map warnings, fix trading readme

---

apps/trading-e2e/src/integration/capsule.cy.ts

Fix for the capsule test - place order

test(trading): fix capsule place order test

---

apps/governance-e2e/src/integration/view/wallet-vega.cy.ts
apps/governance/src/components/connect-to-vega/connect-to-vega.tsx
apps/governance/src/components/vega-wallet-container/vega-wallet-container.tsx
apps/governance/src/components/vega-wallet-dialogs/vega-wallet-dialogs.tsx
apps/governance/src/components/vega-wallet/vega-wallet.tsx
apps/governance/src/contexts/app-state/app-state-context.ts
apps/governance/src/contexts/app-state/app-state-provider.tsx
apps/governance/src/lib/vega-connectors.ts
apps/governance/src/routes/proposals/components/vote-details/vote-buttons.tsx
apps/governance/src/routes/proposals/hooks/use-vote-information.spec.ts
apps/governance/src/routes/rewards/connect-to-see-rewards.tsx
apps/trading-e2e/src/integration/wallet-vega.cy.ts
apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx
apps/trading/lib/vega-connectors.ts
libs/ui-toolkit/src/components/dialog/dialog.tsx
libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.tsx
libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-chevron-left.tsx
libs/ui-toolkit/src/components/icon/vega-icons/vega-icon-record.ts
libs/wallet/src/connect-dialog/connect-dialog-elements.tsx
libs/wallet/src/connect-dialog/connect-dialog.spec.tsx
libs/wallet/src/connect-dialog/connect-dialog.tsx
libs/wallet/src/connect-dialog/injected-connector-form.tsx
libs/wallet/src/connectors/injected-connector.ts
libs/wallet/src/connectors/vega-connector.ts
libs/wallet/src/provider.tsx
libs/wallet/src/storage.ts
libs/wallet/src/test-helpers.ts
libs/wallet/src/use-injected-connector.spec.tsx
libs/wallet/src/use-injected-connector.ts
libs/wallet/src/use-json-rpc-connect.ts

Closes #3819 
Adds support for the browser wallet
- Updates injected connector with calls to window.vega
- Displays web wallet connection option in connect dialog if window.vega is detected
- Tidies up look and feel of connect dialog (icons, dialog size)

feat(trading,governance,wallet): browser wallet integration

---

.github/workflows/ci-cd-trigger.yml
.github/workflows/console-test-run.yml

Draft PR for getting https://github.com/vegaprotocol/console-test running on PR

feat(trading): run console-test on CICD

---

apps/trading/.env.mainnet
libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions-table.tsx

N/A
Makes pnl columns use correct decimal places

fix(positions): use asset decimals for pnl

---

.github/workflows/ci-cd-trigger.yml

Reverts https://github.com/vegaprotocol/frontend-monorepo/pull/4271

chore(ci): revert run console-test on CICD

---

apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts
apps/governance-e2e/src/integration/view/home.cy.ts
apps/governance-e2e/src/integration/view/pubkey-view.cy.ts

Small changes to governance tests which were previously skipped.

test(governance): un-skip governance tests

---

libs/ui-toolkit/src/components/button/button.tsx
libs/ui-toolkit/src/components/checkbox/checkbox.stories.tsx
libs/ui-toolkit/src/components/checkbox/checkbox.tsx
libs/ui-toolkit/src/utils/shared.ts

Minor UI toolit bugs
- Has error did not highlight border & text with correct colors
- Checkboxes were centre aligned instead of aligned at start when overflowing
- Secondary buttons should always have white text
- Ternary buttons should always have black text

fix(ui-toolkit): toolkit bugs

---

apps/explorer/src/app/routes/parties/id/components/party-block-stake.tsx

Closes #4242 
`Available Stake` 👉🏻  `Associated to key`
`Active Stake` 👉🏻  `Staked to validator`

chore(explorer): align staking terminology

---

apps/trading-e2e/src/integration/closed-markets.cy.ts
apps/trading/client-pages/markets/closed.spec.tsx
apps/trading/client-pages/markets/closed.tsx
libs/markets/src/lib/markets.mock.ts

Closes #4134 
Add cell renderer for successor market

chore(trading): 4134 see if a closed market was succeeded

---

apps/trading-e2e/src/integration/order-book.cy.ts
libs/market-depth/src/lib/orderbook-manager.tsx
libs/market-depth/src/lib/orderbook-row.tsx
libs/market-depth/src/lib/orderbook.spec.tsx
libs/market-depth/src/lib/orderbook.tsx

Closes #3330
Click on the 'cumulative volume' cell in any row to update the deal ticket size

feat(trading): copy order book volume value to deal ticket

---

apps/trading-e2e/src/integration/closed-markets.cy.ts
apps/trading/client-pages/markets/closed.spec.tsx
apps/trading/client-pages/markets/closed.tsx

N/A
Removes user PnL column from closed market list

chore(trading): remove user pnl from closed market list

---

libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions-table.tsx

N/A
A fix for positions pnl was made for mainnet. Cherry picking the change into develop

chore(trading): cherry pick position pnl formatting fix

---

apps/governance-e2e/src/integration/flow/staking-flow.cy.ts
apps/governance-e2e/src/support/staking.functions.ts

Very minor fixes to flaky nightly tests

chore(governance): minor fixes to flaky nightly tests

---

apps/governance-e2e/src/integration/flow/proposal-details.cy.ts
apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts
apps/governance-e2e/src/integration/flow/proposal-list.cy.ts

test(governance): add e2e test and acs for proposal enhancements

---

libs/market-depth/src/lib/orderbook-row.tsx

Change testid to be consistent with other columns in orderbook

chore(trading): move cumulative vol testid in orderbook

---

apps/governance/src/routes/staking/associate/wallet-associate.tsx

Closes #4424
As per console, remove max limit on association

feat(governance): remove max limit on associate function

---

apps/governance-e2e/src/integration/flow/proposal-list.cy.ts
apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts

Fix proposal test that is failing in nightly run
Add e2e test for association 1m+ tokens to test #4424

chore(governance): fix failing proposal test

---

apps/explorer/src/app/hooks/get-txs-data-url.ts
apps/explorer/src/app/hooks/get-txs-data-urls.spec.ts
apps/explorer/src/app/hooks/use-txs-data.ts
apps/explorer/src/app/routes/txs/home/index.tsx

Closes #4435
I neglected to add some tests around the hook for data fetching, and suffered the consequences. Fetching data was broken
in many cases. This PR fixes this - adding tests, then fixing them, so that the correct URLs are generated.

fix(explorer): add tests and fix transactions url generation

---

libs/orders/src/lib/utils.spec.ts
libs/orders/src/lib/utils.ts
libs/web3/src/lib/use-vega-transaction-toasts.tsx
libs/withdraws/src/lib/withdrawals-table.spec.tsx

Closes #4376 
Misleading error message when IOC order stopped

fix(trading): order stopped misleading message

---

apps/trading-e2e/src/integration/market-all.cy.ts
apps/trading/client-pages/markets/markets-page.tsx

Closes #4206 
Replace `All markets` with `Open markets`. 

fix(trading): replace all markets with open markets

---

apps/explorer-e2e/src/integration/proposal.cy.js
apps/trading/.env.mainnet

Add e2e for displaying proposal table on governance page in block explorer

test(explorer): e2e proposal test

---

libs/wallet/src/use-eager-connect.ts

N/A
Fixes eager connection when using the browser wallet

fix(trading,governance): eager connection for browser wallet

---

apps/trading/client-pages/deposit/deposit.tsx
apps/trading/client-pages/deposit/index.ts
apps/trading/pages/client-router.tsx

Closes #4357 
* added a dedicated deposit page to console dapp

feat(trading): deposit page

---

apps/governance-e2e/src/fixtures/proposals/successor-market.json
apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts
apps/governance-e2e/src/support/common.functions.ts

Closes #4131 
Add e2e test for successor market proposal. Acs in separate PR in specs repo

chore(governance): add e2e test for successor market

---

apps/governance-e2e/src/integration/flow/rewards-flow.cy.ts
apps/governance-e2e/src/integration/view/wallet-vega.cy.ts
apps/governance-e2e/src/support/staking.functions.ts

Failing nightly test due to rewards percentage removal as well as issue with approving token test

chore(governance): fix failing tests from nightly run

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx

chore(trading): fix alignment of expire

---

libs/deal-ticket/src/components/deal-ticket/type-selector.tsx

N/A
- Switches the icon in the limit dropdown to use the Vega version

chore(deal-ticket): type dropdown icon

---

apps/trading/components/sidebar/sidebar.tsx

N/A
Removes the hover state from the view as button when its disabled

fix(trading): remove hover state from disabled view as button

---

apps/trading-e2e/src/integration/trading-deal-ticket-basics.cy.ts
apps/trading/components/welcome-dialog/get-started.tsx
apps/trading/components/welcome-dialog/welcome-dialog-content.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.spec.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx

N/A
- Removes connect wallet message from deal ticket and handles it in get-started component

fix(trading): dont show connect wallet message in deal ticket

---

apps/trading-e2e/cypress.config.js
apps/trading-e2e/src/integration/charts-depth.cy.ts
apps/trading-e2e/src/integration/trading-positions.cy.ts
apps/trading-e2e/src/integration/withdraw-key-to-key-validation-fees.cy.ts
apps/trading-e2e/src/integration/withdraw-key-to-key-validation.cy.ts

Update key to key tests
Upadte positions test
Update charts depth test
Add experimentalMemoryManagement flag

test(trading): update cypress tests

---

apps/trading-e2e/src/integration/charts-depth.cy.ts
apps/trading-e2e/src/integration/trading-chart.cy.ts
libs/candles-chart/jest.config.ts
libs/market-depth/jest.config.ts
package.json
yarn.lock

N/A
Update pennant dependency to fix rendering issue in the charts, caused by negative decimal places

chore(trading): update pennant

---

apps/explorer/src/app/components/footer/footer.tsx

Closes #3957
Small tweaks to spacing, links and layout on smaller screens.
Before:
After:

fix(explorer): footer visual tweaks

---

libs/markets/src/lib/SuccessorMarket.graphql
libs/markets/src/lib/__generated__/SuccessorMarket.ts
libs/markets/src/lib/components/market-info/market-info-accordion.tsx
libs/markets/src/lib/components/market-info/market-info-panels.spec.tsx
libs/markets/src/lib/components/market-info/market-info-panels.tsx

Closes #4176 
* added succession line market info panel

feat(markets): succession line

---

libs/orders/src/lib/components/order-list/order-list.spec.tsx
libs/orders/src/lib/components/order-list/order-list.tsx

Closes N/A
Order iceberg fills fix on getters and formatters.

fix(trading): order iceberg fills

---

apps/trading-e2e/cypress.config.js
apps/trading-e2e/src/integration/deposit.cy.ts
apps/trading-e2e/src/integration/trading-positions.cy.ts
apps/trading-e2e/src/integration/withdraw-key-to-key-validation-fees.cy.ts

- skip transfer fees tests (key-to-key test issue)
- fix for view settlement asset test
- fix deposit to trade is visible

test(trading): update cypress tests 

---

commitlint.config-ci.js
specs/6002-MDET-market-details.md

Updated specs regarding the succession line info panel

chore(specs): succession line specs

---

libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions-table.tsx

Closes #4278 
Improve wording for position resolution indicator tooltip.

fix(trading): positions tooltips update

---

apps/trading/client-pages/market/trade-grid.tsx
package.json
yarn.lock

N/A
Fixes an issue where the positions of the top section of the trade grid were not being persisted

fix(trading): fix persitance of resizable grid top section

---

.github/workflows/console-test-run.yml

update to larger runners to match the console-test repo

chore(trading): update console-test runners

---

specs/0007-FUGS-first-use-get-started.md

N/A
Add specs to implemented feature of first use popup
-
-

chore(trading): fulfill spec to 4323

---

apps/governance-e2e/.env
apps/governance-e2e/src/integration/flow/proposal-details.cy.ts
apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts
apps/governance-e2e/src/support/governance.functions.ts
apps/governance-e2e/src/support/proposal.functions.ts
libs/wallet/src/connectors/vega-connector.ts
specs/3003-PMAN-propose_new_market.md

Add e2e test for successor market diff in proposal details page. Moved some assertions from forms to proposal details.

chore(governance): add e2e for successor market diff

---

libs/orders/src/lib/components/order-list/order-view-dialog.tsx
specs/7003-MORD-manage_orders.md

Closes #3394 
Update size formatting on iceberg fields and show side of order

fix(trading): order single view side

---

apps/governance/.env
apps/governance/src/routes/proposals/components/proposal-market-data/proposal-market-data.tsx
apps/governance/src/routes/proposals/components/proposal/proposal.tsx
apps/governance/src/routes/proposals/proposal/proposal-container.tsx

Closes #4276
Fixes oracle data not showing in governance, and brings data request inline with trading
Before:
After:

fix(governance): fixes settlement oracle display in governance

---

libs/orders/src/lib/components/order-list/order-view-dialog.tsx

Remove side from iceberg section of order details

chore(trading): remove iceberg side order details

---

.github/ISSUE_TEMPLATE/feature-epic.md

Just made the title template be FEATURE EPIC instead of just Epic.
Makes it clearer what it is.

chore(trading,governance): update feature-epic.md

---

.github/workflows/cypress-run.yml
apps/governance-e2e/src/integration/flow/withdrawal-flow.cy.ts
apps/governance-e2e/src/support/staking.functions.ts

Fix failing withdrawal test and small change to improve flaky test failures

test(governance): add timeout and fix withdrawal test

---

apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.spec.tsx
apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx
apps/governance/src/routes/proposals/components/proposal/proposal.spec.tsx
apps/governance/src/routes/proposals/components/proposal/proposal.tsx
apps/governance/src/routes/proposals/components/proposals-list-item/proposals-list-item.tsx
apps/governance/src/routes/proposals/components/vote-details/vote-buttons.tsx
apps/governance/src/routes/proposals/components/vote-details/vote-details.tsx

Closes #4422
Ensures the 'you voted' header item updates with a change to vote status

fix(governance): proposal vote status header component

---

apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx
apps/explorer/src/app/components/txs/details/tx-stop-order-cancel.tsx
apps/explorer/src/app/components/txs/tx-filter.tsx
apps/explorer/src/app/components/txs/tx-order-type.tsx

feat(explorer): view 'Cancel Stop Order' Transactions

---

specs/7004-POSI-positions.md

N/A
Updates specs for positions table after changing of columns

chore(positions): spec updates for positions table changes

---

apps/trading-e2e/src/integration/trading-deal-ticket-basic-submit.cy.ts
apps/trading-e2e/src/integration/trading-deal-ticket-submit-account-validation.cy.ts
apps/trading-e2e/src/integration/trading-deal-ticket-submit-account.cy.ts

Split deal ticket account tests

test(trading): split and skip deal ticket account tests

---

apps/governance-e2e/src/integration/view/home.cy.ts
specs/1005-VEST-vesting.md

Closes #3812 
Add test to cover missing ACs for network switcher and removed duplicate AC in vesting

chore(governance): add acs for network nodes

---

libs/announcements/package.json
libs/react-helpers/package.json
libs/types/package.json
libs/ui-toolkit/package.json
libs/utils/package.json

chore(ui-toolkit,react-helpers,announcements): bump versions add react react-dom to peer deps

---

apps/trading-e2e/src/integration/closed-markets.cy.ts
apps/trading-e2e/src/integration/market-all.cy.ts
apps/trading-e2e/src/integration/markets-proposed.cy.ts
apps/trading-e2e/src/integration/trading-orders.cy.ts

Closes #4319 
Added tests for distinguish between product types

test(trading): tests for distinguish between product types

---

.github/workflows/console-test-run.yml

add `--dist loadfile` to console-test run

chore(trading): add dist loadfile to console-test run

---

apps/trading/components/market-banner/market-successor-proposal-banner.tsx
apps/trading/components/market-header/market-header.tsx
apps/trading/components/market-selector/market-selector.spec.tsx
apps/trading/components/market-selector/market-selector.tsx
apps/trading/components/market-selector/sort-dropdown.tsx
apps/trading/components/market-selector/use-market-selector-list.ts
apps/trading/components/navbar/nav-header.tsx
libs/markets/src/lib/market-utils.spec.tsx
libs/markets/src/lib/market-utils.ts

Closes #3970 
* added "Top traded" to the sort dropdown

feat(trading): sort by top traded in market selector

---

apps/explorer-e2e/src/fixtures/mocks/new-asset-proposal.json
apps/explorer-e2e/src/integration/proposal.cy.js
apps/explorer-e2e/src/support/governance.functions.js
libs/cypress/src/lib/capsule/propose-market.ts

test(explorer): add e2e test for asset proposal on explorer

---

apps/trading/components/welcome-dialog/get-started.tsx
libs/ui-toolkit/src/components/icon/vega-icons/vega-icon.tsx

N/A
Small change to align the checkboxes of the get started card

chore(trading): adjust the get started checkboxes slightly

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/components/deal-ticket/expiry-selector.tsx

fix(deal-ticket): show expiresAt field value from state only, add required validation

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/components/deal-ticket/expiry-selector.tsx
libs/deal-ticket/src/utils/map-form-values-to-submission.ts
libs/deal-ticket/src/utils/map-form-values-to-submisstion.spec.ts
libs/deal-ticket/src/utils/time-in-force-persistance.spec.ts
libs/deal-ticket/src/utils/time-in-force-persistance.ts

Closes #4617 
Fixes bug which make impossible to send iceberg order. Uncheck and iceberg checkbox when  TIF is selected to FOK or IOC

fix(deal-ticket): disable iceberg for IOC and FOK

---

apps/trading/pages/styles.css
libs/markets/src/lib/components/last-24h-price-change/last-24h-price-change.tsx
libs/tailwindcss-config/src/theme.js

Closes #4536 
- Updates mono space font family to use system defaults
- Reduces letter spacing of monospace font
- Updates last 24 hour change header stat to _not_ use monospace

feat(trading): change to system monospace font

---

.github/PULL_REQUEST_TEMPLATE.md

N/A
Updates PR template to not close issues on merge

chore(trading,governance,explorer): update pr template to not close issues

---

apps/governance/.env
apps/governance/.env.capsule
apps/governance/.env.devnet
apps/governance/.env.mainnet
apps/governance/.env.mainnet-mirror
apps/governance/.env.stagnet1
apps/governance/.env.testnet
apps/governance/.env.validators-testnet
apps/trading/.env
apps/trading/.env.capsule
apps/trading/.env.devnet
apps/trading/.env.mainnet
apps/trading/.env.mainnet-mirror
apps/trading/.env.stagnet1
apps/trading/.env.testnet
apps/trading/.env.validators-testnet

Issue: #4668 
Fix for outdated links (due to change of url) to Mozilla Store extensions
-
-

fix(wallet): mozilla vega wallet links

---

vegacapsule/config.hcl

Contains fix for capsule failing in the pipeline which has also been occurring with system core tests

chore(ci): update config.hcl file

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.spec.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.spec.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx

Fix Date.now related flaky unit tests

feat(deal-ticket): fix flaky tests

---

specs/0002-WCON-connect_vega_wallet.md
specs/7002-SORD-submit_orders.md

Add  Acs for stop order oco and vega snap

test(trading): add stop order oco spec

---

libs/proposals/src/components/protocol-upgrade-in-progress-notification.tsx
libs/proposals/src/lib/protocol-upgrade-proposals/use-block-rising.ts

Issue: #4666 
* removes uncaught rejection
* skips blocks querying if upgrade info is unavailable

fix(proposals): protocol upgrade notification block querying

---

apps/explorer-e2e/src/integration/oracles.cy.js
apps/explorer/src/app/routes/oracles/home/index.tsx

E2E test to create oracle and verify elements on page

test(explorer): add e2e test for explorer oracles

---

apps/trading/components/market-selector/asset-dropdown.tsx
apps/trading/components/market-selector/index.ts
apps/trading/components/market-selector/market-selector-button.spec.tsx
apps/trading/components/market-selector/market-selector-button.tsx
apps/trading/components/market-selector/market-selector-item.tsx
apps/trading/components/market-selector/market-selector.tsx
apps/trading/components/market-selector/product-selector.tsx
apps/trading/components/market-selector/sort-dropdown.tsx
libs/markets/src/lib/markets-provider.ts
libs/ui-toolkit/src/components/trading-input/input.tsx

Issue: #4606 
Updating trading dropdowns. 

chore(trading): update dropdowns

---

apps/trading-e2e/src/integration/trading-deal-ticket-order.cy.ts
libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx
libs/deal-ticket/src/components/deal-ticket/key-value.tsx
libs/ui-toolkit/src/components/tooltip/tooltip.tsx

Issue: #4359
Make deal ticket margin values section expandable

feat(deal-ticket): make margin values section expandable

---

apps/trading/.env.mainnet
apps/trading/.env.mainnet-mirror
apps/trading/.env.stagnet1
apps/trading/.env.validators-testnet

N/A
Updates trading cosmic elevator flags to include stop orders, successor markets and iceberg orders

chore(trading): update flags for 0.72.14

---

libs/orders/src/lib/components/order-list/order-edit-dialog.tsx
libs/orders/src/lib/components/order-list/order-list.tsx
libs/positions/src/lib/positions-table.tsx
libs/ui-toolkit/src/components/trading-select/select.tsx

N/A
- Updates rich select to use VegaIcon
- Updates order list col width
- Updates edit dialog

chore(trading): minor style changes 2

---

apps/governance/src/i18n/translations/dev.json
apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards-table.spec.tsx
apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards-table.tsx
apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards.tsx
apps/governance/src/routes/rewards/epoch-total-rewards/epoch-total-rewards-table.spec.tsx
apps/governance/src/routes/rewards/epoch-total-rewards/epoch-total-rewards-table.tsx
apps/governance/src/routes/rewards/epoch-total-rewards/epoch-total-rewards.tsx
apps/governance/src/routes/rewards/shared-rewards-table-assets/shared-rewards-table-assets.tsx
libs/network-parameters/src/use-network-params.ts

Closes #3067
Add network parameter into tooltip description

feat: add marketCreationQuantumMultiple into tooltip

---

apps/trading/pages/_document.page.tsx
apps/trading/pages/index.page.tsx

N/A
Removes duplicated tags for scripts, fonts, stylesheets and icons

chore(trading): remove duplicate stylesheet and icon references

---

.github/workflows/console-test-run.yml

Adding self-hosted runner for python console tests.

chore(trading): add console-test runner

---

apps/governance-e2e/src/integration/flow/proposal-details.cy.ts
apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts
apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts
apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts
apps/governance-e2e/src/integration/flow/proposal-list.cy.ts
apps/governance-e2e/src/support/governance.functions.ts
apps/governance-e2e/src/support/staking.functions.ts
apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx
specs/3001-VOTE-vote.md

Closes #3601 
Update existing E2E tests with changes to voting

chore(governance): update tests with vote changes

---

apps/explorer-e2e/src/integration/network.cy.js
specs/0006-NETW-network-and-nodes.md

Issue: #1447 
Add E2E test for network parameter grouping

test(explorer): test for network param grouping

---

libs/wallet/src/connect-dialog/connect-dialog-elements.tsx
libs/wallet/src/connect-dialog/connect-dialog.spec.tsx
libs/wallet/src/connect-dialog/connect-dialog.tsx

Issue: #4674 
Add some extra wording to the connect wallet dialogue to make the benefits of browser vs snap clearer
Chrome:

feat(trading): improve connect wallet description

---

specs/7002-SORD-submit_orders.md

Update ACs for the deal ticket:
- limit of 4 active stop orders per market
- update for submit button

test(trading): update acs for deal ticket 

---

apps/trading/pages/styles.css

Issue: #pennant 909
Increase gaps between bar graphs. Decrease candles strokes

chore(trading): tweak some pennant css var

---

libs/datagrid/src/lib/cells/market-name-cell.tsx
libs/markets/src/lib/components/markets-container/markets-container.spec.tsx
libs/markets/src/lib/components/markets-container/markets-container.tsx
libs/markets/src/lib/components/markets-container/use-column-defs.tsx

chore(trading): market list tweaks

---

apps/trading/components/market-selector/index.ts
apps/trading/components/market-selector/market-selector.spec.tsx
apps/trading/components/market-selector/use-market-selector-list.spec.tsx
apps/trading/components/market-selector/use-market-selector-list.ts
apps/trading/components/welcome-dialog/welcome-dialog-content.tsx
apps/trading/lib/utils/index.ts

Issue: #4750
Replace link to market lists with link to most tradable market

chore(trading): adjust onboarding experience

---

apps/trading/client-pages/market/market.tsx

Issue: #4747 
* deal ticket is opened alway by default on market page
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/82683888-c890-4b4d-a7d8-03eefd0b155b

chore(trading): make deal ticket open on market change

---

apps/trading/.env
libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/components/deal-ticket/key-value.tsx
libs/deal-ticket/src/constants.ts
libs/ui-toolkit/src/components/accordion/accordion.tsx
libs/ui-toolkit/src/components/tooltip/tooltip.tsx

Issue: #4673 
Margin required expandable panel. 

feat(trading): margin required progressive disclosure

---

apps/governance-e2e/src/integration/flow/staking-flow.cy.ts
apps/governance-e2e/src/support/staking.functions.ts

Fix for some of the flaky tests in CI

test(governance): flaky test fixes

---

apps/governance-e2e/src/fixtures/mocks/network-upgrade.ts
apps/governance-e2e/src/integration/view/proposal.cy.ts

Add assertion to check for upgrade proposal numerical sort fix

test(governance): add assert for numerical sort

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.spec.tsx
libs/positions/src/lib/liquidation-price.tsx
libs/positions/src/lib/positions-table.tsx

fix(trading): use asset decimals to format liquidation price in posions table

---

libs/positions/src/lib/positions-table.tsx

N/A
Fixes realised pnl tooltip rendering with out a bg or border

fix(trading): missing styles for tooltip in positions table

---

apps/trading-e2e/src/integration/wallet-vega.cy.ts

Fixes the wallet cypress test.

chore(trading): fix wallet test

---

apps/governance-e2e/src/integration/flow/staking-flow.cy.ts

Minor fix for failing staking test

chore(governance): fix failing staking test

---

.github/workflows/console-test-run.yml
apps/trading-e2e/src/integration/trading-deal-ticket-order.cy.ts
apps/trading-e2e/src/integration/trading-trades.cy.ts

test(trading): fix test for release v0.21.2

---

.github/workflows/ci-cd-trigger.yml

N/A
Prevents any CI if PR is in draft

chore(trading,governance,explorer): prevent jobs if PR is in draft

---

apps/trading/client-pages/market/market-header-stats.tsx
apps/trading/components/funding-container/funding-container.tsx
apps/trading/components/market-header/market-header.tsx

feat(trading): improve funding rate formatting

---

apps/trading/client-pages/markets/market-list-table.tsx
libs/proposals/src/components/proposals-list/proposals-list.tsx

Closes #4811 
Add `resizable` param to configuration
-
-

chore(trading): 4811 make market table columns resizable

---

apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards.tsx

Main branch version of https://github.com/vegaprotocol/frontend-monorepo/pull/4864

fix(governance): mainnet rewards query looping

---

vegacapsule/genesis.tmpl

Updates the genesis file used by vega capsule which should fix capsule failing build in CI

chore(ci): update genesis file

---

.github/workflows/ci-cd-trigger.yml

temporary disable console-test to unblock CI queue

chore(trading): temporary disable console-test to unblock CI queue

---

apps/trading/components/header/header.tsx
apps/trading/pages/styles.css
libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/components/deal-ticket/key-value.tsx
libs/deal-ticket/src/hooks/use-estimate-fees.spec.tsx
libs/deal-ticket/src/hooks/use-estimate-fees.tsx
libs/market-depth/src/lib/orderbook.tsx
libs/markets/src/lib/components/fees-breakdown/fees-breakdown.tsx
libs/markets/src/lib/get-price.ts
libs/ui-toolkit/src/components/tooltip/tooltip.tsx

#4733 
#4822 
#4823 
#4870
#4784 
Merges the above changes back to develop

chore(trading,deal-ticket,market-depth,ci): update develop with mainnet fixes

---

.github/workflows/console-test-run.yml

Relates to: #4886 
Adjust console-test to trigger manually.

chore(trading): add possibility to manualy trigger console-test (#4899)

---

.github/workflows/ci-cd-trigger.yml
.github/workflows/lint-pr.yml

chore(trading): separate workflow for lint-pr

---

.github/workflows/console-test-run.yml

Fix node version for console-test workflow

chore(ci): fix node version (main)

---

apps/explorer-e2e/src/integration/market.cy.js
apps/explorer-e2e/src/support/governance.functions.js
apps/governance-e2e/src/fixtures/proposals/new-market-perpetual-raw.json
apps/governance-e2e/src/fixtures/proposals/new-market-raw.json
apps/governance-e2e/src/integration/flow/proposal-details.cy.ts
apps/governance-e2e/src/integration/flow/proposal-list.cy.ts
apps/governance-e2e/src/support/governance.functions.ts
vegacapsule/genesis.tmpl

- Fixes number of failing tests in both Governance and block explorer
- Add e2e test for perpetual market showing in Governance

test(governance): perpetual market e2e test

---

.github/workflows/console-test-run.yml

chore(ci): fix node version (develop)

---

.github/workflows/ci-cd-trigger.yml
.github/workflows/lint-pr.yml

chore(ci): separate lint pr (main)

---

.github/workflows/cypress-run.yml
.github/workflows/lint-pr.yml
vegacapsule/genesis.tmpl

This is basically PR that merges `main` -> `develop`, but with added fix in genesis.tmpl, as develop is running on the latest core version and need this additional parameter that was removed from `main`.

chore(ci): sync main to develop

---

apps/trading-e2e/src/integration/trading-orders.cy.ts
apps/trading/components/orders-container/orders-container.tsx
apps/trading/components/positions-container/positions-container.tsx
libs/datagrid/src/lib/use-datagrid-events.spec.tsx
libs/datagrid/src/lib/use-datagrid-events.ts
libs/orders/src/lib/components/order-list/order-list.tsx

Closes #4792
Add parameter to `useDataGridEvents` hook for handling autosizing on given columns
vs

chore(trading): add handle of autosizing selected columns - main branch

---

apps/governance/src/routes/proposals/proposal/proposal-container.spec.tsx
apps/trading/components/welcome-dialog/get-started.tsx
apps/trading/components/welcome-dialog/use-get-onboarding-step.ts
apps/trading/components/welcome-dialog/welcome-dialog.tsx
libs/wallet/src/connect-dialog/connect-dialog.tsx

Closes #4774 #4775 #4772
Add connect dialog into onboarding dialog to prevent them being stacked
https://github.com/vegaprotocol/frontend-monorepo/assets/338931/09c0d7da-a2a2-4f06-8384-6aae8dfafac4
-

chore(trading): 4774 put connect dialog  inside onboarding dialog - main branch

---

.github/workflows/lint-pr.yml
.github/workflows/publish-dist.yml
apps/governance/src/routes/proposals/proposal/proposal-container.spec.tsx
apps/trading-e2e/src/integration/trading-orders.cy.ts
apps/trading/components/orders-container/orders-container.tsx
apps/trading/components/positions-container/positions-container.tsx
apps/trading/components/welcome-dialog/get-started.tsx
apps/trading/components/welcome-dialog/use-get-onboarding-step.ts
apps/trading/components/welcome-dialog/welcome-dialog.tsx
libs/datagrid/src/lib/use-datagrid-events.spec.tsx
libs/datagrid/src/lib/use-datagrid-events.ts
libs/orders/src/lib/components/order-list/order-list.tsx
libs/wallet/src/connect-dialog/connect-dialog.tsx

Merge mainnet fixes back to develop
- https://github.com/vegaprotocol/frontend-monorepo/pull/4932/commits/ff2e2574f666c413cfd4714f91e9cf18711d584b
- https://github.com/vegaprotocol/frontend-monorepo/pull/4932/commits/5b5802104eda6093565d154d746c46368ab884c5
- https://github.com/vegaprotocol/frontend-monorepo/pull/4932/commits/478cc9e753a42494d261387b4c67e4a37a3cf4ad
- https://github.com/vegaprotocol/frontend-monorepo/pull/4932/commits/2f0be0bf349312f81c9f3f7a132a4a398727642f

chore(ci,trading): update develop with mainnet fixes

---

.github/workflows/cypress-run.yml

In case of merging main -> develop, we are running self-hosted-runner with latest core, but using code from main. Added condition to run tests on mainnet compatible runner in such case.

chore(ci): add main develop merge condition to runner

---

.github/workflows/cypress-run.yml

Merging following fixes from main:
79cbe62774ad564c27713d473251a3e65870135f
30da1663eb43504ba2b75a35bd478e9559d56699

chore(ci): merge main to develop

---

apps/trading-e2e/src/integration/trading-accounts.cy.ts
libs/assets/src/lib/asset-details-dialog.spec.tsx

Deleting duplicate test and move over ACs

chore(trading): delete duplicate asset details test

---

.github/workflows/ci-cd-trigger.yml
.github/workflows/cypress-run.yml
.github/workflows/publish-dist.yml

- make sure main image is published in docker hub after push
- limit vegacapsule run timeout to prevent getting stuck
- minor fix in checking if e2e should be run
- minor fix in mainnet runner check

chore(ci): fix some minor issues in workflows

---

libs/positions/src/lib/positions-manager.spec.tsx
libs/positions/src/lib/positions-manager.tsx
libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions.mock.ts
libs/utils/src/index.ts
libs/utils/src/lib/constants.ts

Closes #4834 
Add max golang uint64 as size of closing position tx.

feat(positions): close position with max possible size

---

apps/trading/client-pages/market/trade-grid.tsx
apps/trading/components/fills-container/fills-container.tsx
libs/fills/src/lib/fills-manager.tsx

#4933
Show fills for all markets
Do not pass marketId to FillsManager and don't use it in query variables

feat(trading): show fills for all markets

---

apps/governance/.env
apps/governance/.env.mainnet
apps/governance/.env.stagnet1
apps/governance/.env.testnet
apps/trading/.env.mainnet
apps/trading/.env.stagnet1
apps/trading/.env.testnet

Closes N/A
Add wallet connect project ID to all envs.

fix(governance): add wallet connect project ID

---

apps/trading/client-pages/closed-market/closed-market.tsx
apps/trading/client-pages/closed-market/index.ts
apps/trading/client-pages/market/market.tsx
apps/trading/client-pages/markets/closed.tsx
apps/trading/components/layouts/layout-with-sidebar.tsx
apps/trading/components/sidebar/sidebar.tsx
apps/trading/lib/hooks/use-market-click-handler.ts
apps/trading/pages/client-router.tsx

Closes #4947 
Add new route for closed markets
-
-

chore(trading): 4947 cant view settled market main

---

.github/workflows/ci-cd-trigger.yml
.github/workflows/cypress-run.yml

Workflow still misses one case. It might help.

chore(ci): quotes and double brackets change

---

apps/trading-e2e/src/integration/vega-wallet-prompt.cy.ts

Closes https://github.com/vegaprotocol/console-test/issues/96
Remove account test because they were moved to console tests.

test(trading): remove account test

---

.github/workflows/add-ipfs-notes-to-release.yml
apps/governance-e2e/src/integration/view/proposal.cy.ts

In order to make it clearer what issues have been released or not, this workflow should add a label automatically.

chore(ci): add release label on release

---

libs/wallet/src/connect-dialog/connect-dialog.tsx
libs/wallet/src/connectors/snap-connector.ts

N/A
Sets vega snap to version 0.2.0

fix(trading,wallet): set version for vega snap

---

apps/explorer-e2e/src/integration/market.cy.js

Fixes failing explorer market test

chore(explorer): fix failing market test

---

.github/workflows/console-test-run.yml
apps/governance-e2e/src/integration/view/proposal.cy.ts
libs/wallet/src/connect-dialog/connect-dialog.tsx
libs/wallet/src/connectors/snap-connector.ts

- c116762865f632df1aa5966a5cec5fe5a7bbf68a
- 63a6e4ecbdbc4f1ee601d01aaeb01d735cbd5f05
- f433a030ffe089cbb4844081afcadd3e72b05151

chore(ci,governance): update develop with latest main changes

---

.github/workflows/ci-cd-trigger.yml
.github/workflows/console-test-run.yml

b4ca0a839078eeb712b00d8d39e6ca0b980a0599

chore(ci): merge main changes to develop

---

apps/trading/client-pages/portfolio/portfolio.tsx

Closes #4977
Add menu with hide/show closed markets button to positions tab in portfolio.

feat(positions): add closed markets filter to positions in portfolio

---

apps/trading/client-pages/market/trade-grid.tsx
apps/trading/client-pages/market/trade-views.tsx
apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/components/funding-payments-container/funding-payments-container.tsx
apps/trading/components/funding-payments-container/index.ts
libs/cypress/mock.ts
libs/funding-payments/.babelrc
libs/funding-payments/.eslintrc.json
libs/funding-payments/README.md
libs/funding-payments/__mocks__/react-markdown.js
libs/funding-payments/jest.config.ts
libs/funding-payments/postcss.config.js
libs/funding-payments/project.json
libs/funding-payments/src/index.ts
libs/funding-payments/src/lib/FundingPayments.graphql
libs/funding-payments/src/lib/__generated__/FundingPayments.ts
libs/funding-payments/src/lib/funding-payments-data-provider.ts
libs/funding-payments/src/lib/funding-payments-manager.tsx
libs/funding-payments/src/lib/funding-payments-table.spec.tsx
libs/funding-payments/src/lib/funding-payments-table.tsx
libs/funding-payments/src/lib/funding-payments.mock.ts
libs/funding-payments/src/lib/test-helpers.ts
libs/funding-payments/src/setup-tests.ts
libs/funding-payments/tailwind.config.js
libs/funding-payments/tsconfig.json
libs/funding-payments/tsconfig.lib.json
libs/funding-payments/tsconfig.spec.json
libs/types/src/__generated__/types.ts
tsconfig.base.json

Closes #4915
Add funding payment history to trade grid and portfolio

feat(trading): add funding payment history

---

.github/workflows/ci-cd-trigger.yml

There was a condition in one console-test job, that was not always working correctly, should be fixed now.

chore(ci): fix badly written condition in workflow 

---

.github/workflows/ci-cd-trigger.yml

Applies 68b4909dffae260c6c5e9478e168b9c690c7fb47 to develop.

chore(ci): merge main fixes to develop

---

specs/7007-LEEN-ledger-entries.md
specs/7008-FUND-funding-payment.md
specs/README.md

Closes #4915 
- added funding spec
- update ledger entries spec

test(trading): add funding spec

---

CODEOWNERS

N/A
Require a review from both dev and qa team for all code changes

chore(trading,explorer,governance): adjust codeowners to require reviews from both teams

---

apps/trading/components/market-selector/market-selector-item.tsx
apps/trading/components/market-selector/market-selector.spec.tsx
apps/trading/components/market-selector/use-market-selector-list.spec.tsx
apps/trading/components/market-selector/use-market-selector-list.ts
libs/datagrid/src/lib/cells/market-name-cell.tsx
libs/markets/src/lib/__generated__/markets-data.ts
libs/markets/src/lib/markets-data.graphql
libs/markets/src/lib/markets-data.mock.ts

fix(trading): market selector dropdown not updating

---

apps/trading/pages/ssr-loader.tsx
libs/ui-toolkit/src/components/loader/loader.tsx

N/A
Uses pseudoRandom generator to fix ssr-loader hydration error
N/A

fix(trading): hydration error due to loader

---

libs/wallet/src/connectors/snap-connector.ts

chore(trading): update snap version to 0.3.1

---

libs/ui-toolkit/src/components/async-renderer/async-renderer.spec.tsx
libs/ui-toolkit/src/components/async-renderer/async-renderer.tsx

Closes #4970 
Improve conditions under which the error is displayed
-
-

chore(ui-toolkit): 4970 async renderer - improve error handling

---

apps/trading/components/market-banner/market-successor-banner.spec.tsx
apps/trading/components/market-banner/market-successor-banner.tsx
libs/markets/src/lib/market-data-provider.ts

feat(trading): show successor banner if market is settled or successor market exists

---

apps/trading/components/orders-container/orders-container.tsx
libs/candles-chart/src/lib/candles-chart.tsx
libs/market-depth/src/lib/depth-chart.tsx
libs/market-depth/src/lib/orderbook-manager.tsx
libs/market-depth/src/lib/orderbook.tsx
libs/orders/src/lib/components/order-list-manager/order-list-manager.spec.tsx
libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx
libs/orders/src/lib/components/order-list/order-list.tsx
libs/react-helpers/src/hooks/use-theme-switcher.ts

Closes #4970
Handle overlays appearing according to query or filter results

chore(orders): 4970 add no rows and error info

---

apps/governance/src/app.tsx
apps/governance/src/i18n/translations/dev.json
apps/governance/src/routes/restricted/index.tsx
apps/governance/src/routes/router-config.tsx
apps/governance/src/routes/routes.ts

Add restricted page. Similar to #5094

feat(governance): add restricted page

---

apps/trading/client-pages/referrals/apply-code-form.tsx
apps/trading/client-pages/referrals/create-code-form.tsx
apps/trading/client-pages/referrals/error-boundary.tsx
apps/trading/client-pages/referrals/how-it-works-table.tsx
apps/trading/client-pages/referrals/landing-banner.tsx
apps/trading/client-pages/referrals/referral-statistics.tsx
apps/trading/client-pages/referrals/referrals.tsx
apps/trading/client-pages/referrals/tiers.tsx

Epic: #3451 
* makes referrals i18n friendly
N/A
N/A

chore(trading): i18n-friendly referrals

---

apps/explorer/src/app/components/txs/details/tx-transfer.tsx
apps/explorer/src/app/components/txs/tx-transfer.spec.tsx

Adds the deterministic ID to the transfer tx details page
Closes #5111

feat(explorer): add determinsitic id to transfer tx

---

apps/trading-e2e/src/integration/capsule.cy.ts

test(trading): fix capsule test

---

package.json
yarn.lock

Closes #5008
- display 0 label on vertical axis of price chart and line chart
- change colours of horizontal and vertical gride
upgrade pennant@1.14.0

feat(trading): upgrade pennant@1.14.0

---

apps/trading/client-pages/fees/fees.tsx
apps/trading/client-pages/fees/index.ts
apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/components/fees-container/Fees.graphql
apps/trading/components/fees-container/__generated__/Fees.ts
apps/trading/components/fees-container/fees-card.tsx
apps/trading/components/fees-container/fees-container.spec.tsx
apps/trading/components/fees-container/fees-container.tsx
apps/trading/components/fees-container/index.ts
apps/trading/components/fees-container/market-fees.tsx
apps/trading/components/fees-container/stat.tsx
apps/trading/components/fees-container/table.tsx
apps/trading/components/fees-container/use-referral-stats.spec.ts
apps/trading/components/fees-container/use-referral-stats.ts
apps/trading/components/fees-container/use-volume-stats.spec.ts
apps/trading/components/fees-container/use-volume-stats.ts
apps/trading/components/fees-container/utils.ts
apps/trading/components/layouts/layout-with-sidebar.tsx
apps/trading/components/navbar/navbar.spec.tsx
apps/trading/components/navbar/navbar.tsx
apps/trading/lib/links.ts
apps/trading/pages/client-router.tsx
apps/trading/pages/styles.css
libs/network-parameters/src/use-network-params.ts

Closes #5014
Adds a fees tab to the portfolio page

feat(trading): fees page

---

apps/trading/components/fees-container/market-fees.tsx

N/A
Lets you click on a row in the fees table to go to that market

feat(trading): add row click for fees table

---

apps/trading/components/fees-container/fees-container.tsx
apps/trading/components/fees-container/utils.spec.ts
apps/trading/components/fees-container/utils.ts
libs/utils/src/lib/format/number.ts

Closes #5133
Adjusts the formula for calculating the fee percentages after volume and referral discounts and adds a unit test for it

chore(trading): update fee factor with discount calculation

---

apps/explorer-e2e/src/integration/market.cy.js
apps/governance-e2e/src/integration/flow/proposal-details.cy.ts

chore(cypress): fix failing assertions

---

libs/funding-payments/src/lib/funding-payments-data-provider.ts
libs/funding-payments/src/lib/funding-payments-manager.tsx

feat(funding-payments): add load more button to the funding payments table

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx
libs/deal-ticket/src/components/discounts.spec.ts
libs/deal-ticket/src/components/discounts.ts
libs/deal-ticket/src/components/fees-breakdown/fees-breakdown.tsx
libs/deal-ticket/src/hooks/EstimateOrder.graphql
libs/deal-ticket/src/hooks/__generated__/EstimateOrder.ts
libs/deal-ticket/src/hooks/estimate-order.mock.ts
libs/deal-ticket/src/hooks/use-estimate-fees.spec.tsx
libs/deal-ticket/src/hooks/use-estimate-fees.tsx
libs/markets/src/lib/market-utils.spec.tsx
libs/markets/src/lib/market-utils.ts

Closes #4714 
Shows fees with related volume and referral discounts

feat(deal-ticket): calculate fees and discount base on volumeDiscountStats and referralSetStats

---

apps/trading/components/liquidity-header/liquidity-header.tsx
libs/liquidity/src/lib/MarketLiquidity.graphql
libs/liquidity/src/lib/__generated__/MarketLiquidity.ts

Closes #4317
[Show total Liquidity Provision fees paid last epoch across the whole market#4317](https://github.com/vegaprotocol/frontend-monorepo/issues/4317)

feat(trading): show fees paid across whole market

---

libs/deal-ticket/src/hooks/use-estimate-fees.spec.tsx
libs/deal-ticket/src/hooks/use-estimate-fees.tsx

Apply discount only if atEpoch equals currentEpoch - 1

feat(deal-ticket): get discounts for estimation from previous epoch

---

libs/accounts/src/lib/accounts-data-provider.ts
libs/accounts/src/lib/transfer-container.tsx
libs/accounts/src/lib/transfer-form.tsx
libs/datagrid/src/lib/pagination.tsx
libs/trades/src/lib/trades-manager.tsx

N/A
- Removes pagination from trades list for a market
- Removes quotes from data node retention message
- Fixes an issue where the transfer form doesn't render if not connected to a pubkey
- Adds balances to to/from account dropdowns as otherwise you don't know how much you can transfer
- Adds vested and vesting accounts to breakdown table

chore(trading): misc changes to trades and transfer

---

apps/explorer/src/app/routes/network-parameters/network-parameters.tsx

fix(explorer): format new network params correctly

---

apps/explorer/src/app/components/txs/tx-order-type.tsx

Closes #4808
Adds labels for new proposal types, for the sake of improving the Transaction List.

feat(explorer): new labels for proposals

---

apps/trading/components/fees-container/fees-container.spec.tsx
apps/trading/components/fees-container/fees-container.tsx

Closes #5145 
Fixes label on fees page so that it says how many epochs the window length of the volume discount program is

chore(trading): fees page use window length in label

---

libs/environment/src/components/node-switcher/row-data.spec.tsx
libs/environment/src/components/node-switcher/row-data.tsx

Closes #5060
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/a384687b-86b3-443a-b9cc-eda5a81eeab5
I've refactored the code so it relies on the node stats query result and not on the headers as not all of the validators are returning the correct headers.

fix(environment): missing block height in node switcher

---

docker/prepare-dist.sh

Fixes prepare dist for mac OS.

chore(ci): fix prepare dist

---

libs/accounts/src/lib/transfer-container.tsx
libs/accounts/src/lib/transfer-form.spec.tsx
libs/accounts/src/lib/transfer-form.tsx
libs/network-parameters/src/use-network-params.ts

Closes #5202 
- Updates validation to use transfer quantum multiple network param, with special cases to allow for transferring the max amount if transferring from a vested account
- Disables fee inclusion if transferring from a vested account
- Shows no fees for transferring from a vested account
- Disables key selection if transferring from vested account. Can only transfer on the same key

feat(accounts): transfer form improvements to handle transfers from vesting accounts

---

apps/trading/e2e/README.md
apps/trading/e2e/tests/deal_ticket/test_trading_deal_ticket_submit_account.py
apps/trading/e2e/tests/market/test_monitoring_auction_price_volatility_market.py
yarn.lock

Fixes the python tests broken from the i18n PR.

chore(trading): fix tests from i18n

---

apps/explorer/netlify.toml
apps/explorer/project.json
apps/governance/README.md
apps/governance/netlify.toml
apps/governance/project.json
apps/liquidity-provision-dashboard/netlify.toml
apps/liquidity-provision-dashboard/project.json
apps/multisig-signer/netlify.toml
apps/multisig-signer/project.json
apps/static/netlify.toml
apps/static/project.json
apps/trading/netlify.toml
apps/trading/project.json
netlify.toml

chore(ci): remove unused netlify configs

---

apps/trading/e2e/README.md
apps/trading/e2e/actions/utils.py
apps/trading/e2e/tests/chart_depth/test_chart_depth.py
apps/trading/e2e/tests/deal_ticket/test_stop_order.py
apps/trading/e2e/tests/deal_ticket/test_stop_order_oco.py
apps/trading/e2e/tests/deal_ticket/test_trading_deal_ticket_submit_account.py
apps/trading/e2e/tests/market/test_monitoring_auction_price_volatility_market.py
apps/trading/e2e/tests/order/test_order_match.py
apps/trading/e2e/tests/pnl/test_pnl.py
apps/trading/e2e/tests/trade_history/test_trade_history.py
yarn.lock

Removing wait for graphql as it didn't actually work.

chore(trading): remove wait for graphql

---

apps/trading/e2e/conftest.py
apps/trading/e2e/fixtures/market.py

Creates simple perps market to be used in future tests.

feat(trading): perps markets in trading python tests

---

apps/trading/e2e/poetry.lock

Update vega-market-sim to latest

chore(trading): update vega-market-sim

---

apps/trading/components/fees-container/Fees.graphql
apps/trading/components/fees-container/__generated__/Fees.ts
apps/trading/components/fees-container/fees-container.tsx
apps/trading/components/fees-container/stat.tsx
apps/trading/components/fees-container/use-referral-stats.spec.ts
apps/trading/components/fees-container/use-referral-stats.ts
apps/trading/components/fees-container/utils.spec.ts
apps/trading/components/fees-container/utils.ts

Closes #5215 
This has already been fixed on fairground, we need this on mainnet

fix(trading): fees page fixes for mainnet

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx
libs/markets/src/lib/market-utils.ts

#5302 
Hides margin estimations in the deal ticket if the current market is a perpetual market

chore(deal-ticket,markets): dont show margin estimate for perps

---

libs/i18n/src/locales/en/ledger.json
libs/ledger/__mocks__/react-i18next.ts
libs/ledger/src/lib/ledger-download-store.tsx
libs/ledger/src/lib/ledger-export-form.tsx
libs/ledger/src/lib/use-t.jsx

feat(ledger): use i18next

---

libs/i18n/src/locales/en/market-depth.json
libs/market-depth/__mocks__/react-i18next.ts
libs/market-depth/src/lib/depth-chart.tsx
libs/market-depth/src/lib/orderbook.tsx
libs/market-depth/src/lib/use-t.jsx

feat(market-depth): use i18next

---

libs/i18n/src/index.ts
libs/i18n/src/locales/en/trades.json
libs/trades/__mocks__/react-i18next.ts
libs/trades/src/lib/trades-manager.tsx
libs/trades/src/lib/trades-table.tsx
libs/trades/src/lib/use-t.ts

feat(trades): use i18next

---

apps/governance/src/routes/proposals/propose/new-asset/propose-new-asset.tsx
apps/governance/src/routes/proposals/propose/new-market/propose-new-market.tsx
apps/governance/src/routes/proposals/propose/raw/propose-raw.tsx
apps/governance/src/routes/proposals/propose/update-asset/propose-update-asset.tsx
apps/governance/src/routes/proposals/propose/update-market/propose-update-market.tsx
libs/accounts/src/lib/transfer-form.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket-size-iceberg.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deposits/src/lib/deposit-form.tsx
libs/i18n/src/locales/en/utils.json
libs/orders/src/lib/components/order-list/order-edit-dialog.tsx
libs/orders/src/lib/components/stop-orders-table/stop-orders-table.tsx
libs/utils/__mocks__/react-i18next.ts
libs/utils/src/lib/format/trigger.ts
libs/utils/src/lib/markets.ts
libs/utils/src/lib/use-t.ts
libs/utils/src/lib/validate/common.spec.ts
libs/utils/src/lib/validate/common.ts
libs/utils/src/lib/validate/validate-amount.ts
libs/web3/src/lib/use-vega-transaction-toasts.tsx
libs/withdraws/src/lib/withdraw-form.tsx

feat(utils): use i18next

---

libs/accounts/src/lib/accounts-table.spec.tsx
libs/accounts/src/lib/transfer-form.spec.tsx
libs/accounts/src/lib/transfer-form.tsx

Closes #5261
Remove account balance formatting.

fix(trading): remove account balance formatting on use max

---

vegacapsule/config.hcl

Specifying a ganache image to save time getting latest ganache every time.

chore(ci): specific ganache image

---

apps/trading/client-pages/fees/fees.tsx
apps/trading/client-pages/rewards/rewards.tsx

Closes #5301
Update browser title on fees and rewards pages

feat(trading): update title on rewards and fees pages

---

.gitignore
apps/trading/components/settings/settings.spec.tsx
apps/trading/components/settings/settings.tsx

Closes #5343 
Reset console to default.
Clears local storage and hard reloads console.

feat(trading): reset console to default

---

libs/positions/src/lib/positions-manager.spec.tsx
libs/positions/src/lib/positions-manager.tsx

Closes N/A
Temporarily disable close position.

chore(trading): temporarily disable close position

---

apps/trading/components/funding-container/funding-container.tsx
package.json
yarn.lock

feat(trading): show percentage sign on y axis in funding rate chart

---

libs/wallet/src/connect-dialog/use-chain-id.spec.ts
libs/wallet/src/connect-dialog/use-chain-id.ts

Closes #5310
* changes flaky `replace` with correct way of getting urls.
N/A

fix(wallet): empty connect dialog

---

.gitignore
apps/trading/e2e/tests/transfer/test_transfer_key_to_key.py
libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx
libs/positions/src/lib/positions-manager.spec.tsx
libs/positions/src/lib/positions-manager.tsx

N/A
Back merge re-enabling of margin estimate, plus fix some eslint errors

chore(trading): back merge main

---

apps/trading/client-pages/market/market.tsx
apps/trading/client-pages/markets/open-markets.tsx
apps/trading/pages/styles.css

fix(trading): ag-grid styling updates and filter fixes

---

apps/trading/components/ledger-container/ledger-container.tsx
libs/i18n/src/locales/en/ledger.json
libs/ledger/src/lib/ledger-export-form.spec.tsx
libs/ledger/src/lib/ledger-export-form.tsx

Closes #5357
Refactor ledger download form. Use useForm hook to validate form fields.

feat(trading): refactor ledger export form validation

---

apps/trading/pages/styles.css

Closes #5330 
Fixes compactness on ag-grid buttons and filters

fix(trading): ag-grid compactness adjustment

---

apps/trading/pages/styles.css

Closes #5330 
Fix ag-grid transparent filters.

fix(trading): fix ag-grid transparent filters

---

apps/trading-e2e/src/integration/market-proposal-notification.cy.ts
apps/trading/client-pages/market/market-header-stats.tsx
libs/proposals/src/components/market-proposal-notification.tsx
libs/ui-toolkit/src/components/notification/notification.tsx

feat(trading): remove proposal warning from market header

---

apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.spec.tsx
apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx
libs/react-helpers/src/lib/format/number.tsx

Closes #4873
See: https://github.com/vegaprotocol/frontend-monorepo/pull/5332

fix(governance): sensible vote numbers 

---

apps/trading/client-pages/market/market-header-stats.tsx
apps/trading/client-pages/referrals/hooks/use-referral-program.ts
apps/trading/client-pages/referrals/referral-statistics.tsx
apps/trading/client-pages/referrals/tiers.tsx
apps/trading/components/fees-container/fees-container.tsx
libs/datagrid/src/lib/ag-grid/ag-grid-themed.tsx
libs/liquidity/src/lib/liquidity-table.tsx
libs/proposals/src/components/market-proposal-notification.tsx
libs/ui-toolkit/src/components/notification/notification.tsx

chore(trading, datagrid, liquidity, proposals, ui-toolkit): sync main

---

libs/fills/src/lib/fills-table.spec.tsx
libs/fills/src/lib/fills-table.tsx

Closes #5401 
Fees in the fills table were not calculated correctly for the maker.

fix(trading): fills fees fixes for maker

---

apps/trading/client-pages/home/home.tsx
apps/trading/lib/hooks/use-navigate-to-last-market.spec.ts
apps/trading/lib/hooks/use-navigate-to-last-market.ts

chore(trading): don't redirect to inactive markets

---

libs/liquidity/src/lib/liquidity-table.tsx

Merge back live time fraction zero fix from main

fix(trading): live time fraction zero redundant check

---

apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/components/navbar/navbar.spec.tsx
apps/trading/components/navbar/navbar.tsx
apps/trading/components/rewards-container/rewards-container.tsx
apps/trading/pages/client-router.tsx

chore(trading): move rewards to portfolio part 1

---

libs/trades/src/lib/trades-table.tsx

Closes #5422
Disable trades table sorting.
Fixes

chore(trading): disable trades table sorting

---

apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/components/navbar/navbar.spec.tsx
apps/trading/components/navbar/navbar.tsx
apps/trading/components/rewards-container/rewards-container.tsx
apps/trading/pages/client-router.tsx

chore(trading): revert moving rewards container to portfolio 

---

apps/trading/components/fees-container/fees-container.tsx
libs/liquidity/src/lib/liquidity-data-provider.spec.tsx
libs/liquidity/src/lib/liquidity-data-provider.ts

chore(trading): sync main

---

apps/governance/src/contexts/contracts/contracts-provider.tsx
apps/governance/src/routes/proposals/components/proposal-referral-program-details/proposal-referral-program-details.tsx
apps/governance/src/styles.css

Closes #5440
* adds link styling to the proposal rationale description
* fixes errors with referral details in proposal view
* additionally fixes contracts provider issues
There was a nasty issue with contracts on mainnet that I've spotted while playing with gov app, fixed it here.

fix(governance): markdown link styling, referral details type error, contracts provider error

---

libs/environment/src/components/node-switcher/layout-cell.tsx
libs/environment/src/components/node-switcher/node-switcher.tsx
libs/ui-toolkit/src/components/dialog/dialog.tsx
libs/ui-toolkit/src/components/trading-radio-group/radio-group.tsx

Closes #5363 
* fixes mobile view of the node switcher
OCD note: I've added bottom padding to the dialog so it has the same spacing on top and bottom.

fix(environment): node switcher on mobile

---

apps/trading/client-pages/referrals/apply-code-form.tsx
apps/trading/client-pages/referrals/hooks/use-funds-available.ts
apps/trading/client-pages/referrals/landing-banner.tsx
apps/trading/client-pages/referrals/qusd-tooltip.tsx
apps/trading/client-pages/referrals/referral-statistics.tsx
apps/trading/client-pages/referrals/tiers.tsx
apps/trading/components/welcome-dialog/welcome-dialog.tsx
libs/utils/src/lib/format/strings.spec.ts
libs/utils/src/lib/format/strings.ts

* rewording of couple of texts
* omits the welcome dialog on referrals page
* adds qUSD tooltip in spam protection error
* changes `useFundsAvaiable` to use BigNumber instead of numbers to avoid precision issues
* changes errors colour to orange so it's more readable

fix(trading): rewordings in referrals, qusd tooltip, onboarding

---

apps/trading/client-pages/referrals/referral-statistics.tsx
apps/trading/client-pages/referrals/tile.tsx
apps/trading/e2e/actions/utils.py
apps/trading/e2e/actions/vega.py
apps/trading/e2e/fixtures/market.py
apps/trading/e2e/tests/referrals/test_referrals.py
apps/trading/e2e/wallet_config.py

Referrals E2E tests. Not quite ready for review, some of the numbers do not quite makes sense so need to verify with art. Feel free to check over the code in the mean time

test(trading): add referrals tests

---

apps/trading/client-pages/market/market.tsx
apps/trading/components/accounts-container/accounts-container.tsx
libs/deposits/src/lib/deposit-manager.tsx
libs/deposits/src/lib/index.ts
libs/deposits/src/lib/use-persistent-deposit.ts
libs/withdraws/src/lib/use-withdraw-asset.tsx
libs/withdraws/src/lib/withdraw-form.tsx
libs/withdraws/src/lib/withdraw-limits.tsx

Closes #5108 
Always swich to selected asset when deposit buttons are used from collateral table.
Remove delay which switching asset in withdraw form caused by waiting for threshold and delay

feat(trading): improve desposit and withraw asset selection

---

libs/positions/src/lib/liquidation-price.tsx
libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions-table.tsx

Closes #5436
Use radix instead of ag-grid to display tooltips that may have clickable content in positions table.

feat(positions): improve tooltips

---

apps/trading/components/rewards-container/rewards-container.spec.tsx
apps/trading/components/rewards-container/rewards-container.tsx

Closes #5529 
* adds also the vested amount to the total pot
N/A
N/A

fix(trading): reward pot total value

---

tools/ci/define-dist-variables.py

Fix for the validators-testnet pipeline

feat(ci): allow both validators-testnet and validator-testnet for env name

---

tools/ci/define-dist-variables.py

Fix small bug in the validators-testnet release
We tested it here in the pipeline for validators-testnet CI: https://github.com/vegaprotocol/frontend-monorepo/actions/runs/7302398219/job/19900975305

feat(ci): validators testnet deployment

---

apps/trading/e2e/tests/fees/test_fees.py
apps/trading/e2e/tests/market/test_market.py

chore(trading): fix fees tests

---

libs/deposits/src/lib/get-faucet-error.ts

feat(trading): do not show error message if there is no faucet tx error

---

apps/trading/e2e/tests/market/test_market_selector.py

Fix because of the issue https://github.com/vegaprotocol/frontend-monorepo/issues/5465 
- test_market_selector
- test_market_selector_filter

chore(trading): fix volume issue for market selector tests

---

libs/markets/src/lib/components/market-info/market-info-accordion.tsx
libs/markets/src/lib/components/market-info/market-info-panels.tsx

Closes #5576 
Fixing price monitoring bounds and trigger mismatch. 

fix(trading): fix price monitoring bounds and trigger mismatch

---

apps/trading/e2e/tests/liquidity_provision/test_liquidity_provision.py

Issue requiring the skip: https://github.com/vegaprotocol/frontend-monorepo/issues/5581

chore(trading): skip test due to issue

---

apps/trading/client-pages/rewards/rewards.tsx
apps/trading/components/rewards-container/active-rewards.tsx

Closes #5599 
Use tiny scroll for rewards

fix(trading): tiny scroll for rewards

---

.github/workflows/console-test-run.yml

Upload the tmp folder that includes the logs of market-sim.

chore(trading): upload market-sim logs

---

apps/trading/.env.mainnet

Closes #5608 
Enables trading view

chore(trading): enable trading view on mainnet

---

libs/ui-toolkit/src/components/slider/leverage-slider.stories.tsx
libs/ui-toolkit/src/components/slider/leverage-slider.tsx

feat(ui-toolkit): add leverage slider component

---

libs/deposits/src/lib/deposit-form.spec.tsx
libs/deposits/src/lib/deposit-form.tsx
libs/i18n/src/locales/en/deposits.json

feat(deposits): if wrong network dont show the form and prompt switching to the correct network

---

apps/governance-e2e/src/integration/view/pubkey-view.cy.ts
libs/ui-toolkit/src/components/slider/leverage-slider.tsx
libs/ui-toolkit/src/components/slider/slider.tsx

Closes #5631 
Update slider colors  and shapes

feat(ui-toolkit): update slider design

---

libs/markets/src/lib/components/market-info/market-info-panels.tsx

Closes #5681 
Prevents crashing of the "Key details" info panel.
N/A
N/A

fix(markets): key details panel crashing

---

apps/trading/client-pages/competitions/competitions-create-team.tsx
apps/trading/client-pages/competitions/competitions-home.tsx
apps/trading/client-pages/competitions/competitions-team.tsx
apps/trading/client-pages/competitions/competitions-teams.tsx
apps/trading/client-pages/competitions/competitions-update-team.tsx
apps/trading/client-pages/competitions/join-team.tsx
apps/trading/client-pages/competitions/team-form.tsx
apps/trading/client-pages/competitions/update-team-button.tsx
apps/trading/e2e/.env
apps/trading/e2e/tests/teams/test_teams.py
apps/trading/lib/hooks/Team.graphql
apps/trading/lib/hooks/__generated__/Team.ts
apps/trading/lib/hooks/use-team.ts
apps/trading/lib/hooks/use-teams.tsx
libs/i18n/src/locales/en/trading.json
libs/types/src/__generated__/types.ts

- Various fixes for issues/snags outlined above
- Fixes update team TX not working

fix(trading): teams snags

---

apps/trading/components/rewards-container/active-rewards.tsx

Closes #5730 
Updates a filter from https://github.com/vegaprotocol/frontend-monorepo/issues/5587 

fix(trading): active rewards filter

---

apps/trading/lib/hooks/use-teams.tsx

N/A
Make epochs for teams stats 192, around 4 days

chore(trading): make team stats aggregation epochs 192

---

apps/explorer/src/app/components/links/hash.tsx
apps/explorer/src/app/components/links/index.ts
apps/explorer/src/app/components/links/network-parameter-link/network-parameter-link.tsx
apps/explorer/src/app/components/links/proposal-link/proposal-link.tsx
apps/explorer/src/app/components/txs/details/proposal/Proposal.graphql
apps/explorer/src/app/components/txs/details/proposal/__generated__/Proposal.ts
apps/explorer/src/app/components/txs/details/proposal/batch-item.spec.tsx
apps/explorer/src/app/components/txs/details/proposal/batch-item.tsx
apps/explorer/src/app/components/txs/details/proposal/summary.tsx
apps/explorer/src/app/components/txs/details/tx-batch-proposal.tsx
apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx
apps/explorer/src/app/components/txs/tx-filter.tsx

Closes #5560 
- Add batch count to details
- Add batch items to proposal summary
- Add Batch Proposals to TX filter
- Update GraphQL query to handle batch proposals

feat(explorer): batch proposal support

---

libs/trading-view/src/lib/trading-view.tsx
libs/trading-view/src/lib/use-datafeed.ts

fix(trading): trading view on multiple tabs

---

libs/environment/src/components/node-switcher/row-data.spec.tsx
libs/environment/src/components/node-switcher/row-data.tsx
libs/environment/src/hooks/use-environment.spec.ts
libs/environment/src/hooks/use-environment.ts
libs/environment/src/utils/time.spec.ts
libs/environment/src/utils/time.ts

Closes: #5757 
This PR fixes the observed issue and changes the mechanics of the initial node picking in a way that it tests all available nodes, orders them by block height and picks the fastest.
N/A
Moved time measurement from `row-data` component to a util `time.ts`.

fix(environment): pick best node

---

libs/trading-view/src/lib/trading-view.tsx
libs/trading-view/src/lib/use-datafeed.ts

Closes #5737 
See: https://github.com/vegaprotocol/frontend-monorepo/pull/5748

fix(trading): trading view fix on main

---

.github/workflows/console-test-run.yml
apps/trading/e2e/.env
apps/trading/e2e/conftest.py
apps/trading/e2e/tests/deal_ticket/test_basic.py
apps/trading/e2e/tests/deal_ticket/test_stop_order.py
apps/trading/e2e/tests/deal_ticket/test_trading_deal_ticket_submit_account.py
apps/trading/e2e/tests/fees/test_fees.py
apps/trading/e2e/tests/get_started/test_get_started.py
apps/trading/e2e/tests/iceberg_orders/test_iceberg_orders.py
apps/trading/e2e/tests/liquidity_provision/test_liquidity_provision.py
apps/trading/e2e/tests/market/test_closed_markets.py
apps/trading/e2e/tests/market/test_market_info.py
apps/trading/e2e/tests/market/test_markets_proposed.py
apps/trading/e2e/tests/market/test_monitoring_auction_price_volatility_market.py
apps/trading/e2e/tests/navigation/test_navigation.py
apps/trading/e2e/tests/order/test_order_status.py
apps/trading/e2e/tests/orderbook/test_orderbook.py
apps/trading/e2e/tests/positions/test_collateral.py
apps/trading/e2e/tests/referrals/test_referrals.py
apps/trading/e2e/tests/rewards/test_rewards.py
apps/trading/e2e/tests/rewards/test_rewards_activity_tier_0.py
apps/trading/e2e/tests/settings/test_settings.py
apps/trading/e2e/tests/teams/test_teams.py

This PR fixes the issues we were having with running tests in parallel but correctly tearing down between tests.

chore(trading): fix test teardown

---

apps/trading/client-pages/competitions/competitions-create-team.tsx
apps/trading/client-pages/competitions/competitions-update-team.tsx
apps/trading/components/competitions/team-avatar.tsx
libs/i18n/src/locales/en/trading.json

Closes #5196
* adds "Go back to..." links
* aligns update team form successful message with the create team form (same format)
* additionally fixes 404s for avatars
N/A

chore(trading): create and update team form traversing

---

apps/explorer/src/app/components/txs/details/proposal/tx-update-party-profile.tsx
apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx
apps/explorer/src/app/components/txs/tx-filter.tsx

Adds explorer support for the update party profile transaction
- Add transaction component
- Add Update Party Profile to tx filter

feat(explorer): update party profile tx

---

apps/trading/.env.mainnet

- update trading env to use new pokt network endpoint format
Closes #5778

chore(trading): switch eth provider URL

---

apps/explorer-e2e/src/integration/proposal.cy.js
apps/explorer/src/app/components/proposals/proposals-table.tsx

Closes #4730 
This removes a column, nothing more.
Imagine there's no column...
N/A

chore(explorer): remove voting column from proposal table

---

libs/wallet/src/connectors/snap-connector.ts

N/A
V1 of snap was just published, update to use it

chore(trading, governance, explorer): update snap to 1.0.1

---

apps/trading/e2e/tests/deal_ticket/test_trading_deal_ticket_submit_account.py
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/components/deal-ticket/margin-mode-selector.tsx
libs/positions/src/lib/Positions.graphql
libs/positions/src/lib/__generated__/Positions.ts
libs/types/src/__generated__/types.ts

Closes #5781
Rename EstimatePosition argument

feat(deal-ticket): rename EstimatePosition argument

---

apps/trading/client-pages/fees/fees.tsx
apps/trading/client-pages/markets/markets-page.tsx
apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/client-pages/rewards/rewards.tsx
libs/proposals/src/components/protocol-upgrade-in-progress-notification.tsx
libs/ui-toolkit/src/components/notification-banner/notification-banner.tsx
libs/ui-toolkit/src/components/viewing-as-user/index.tsx

N/A
- Fix spacing of fees/rewards titles on mobile
- Use page title hook to reduce number of imports

chore(trading): misc fixes

---

apps/trading/client-pages/competitions/competitions-home.tsx
libs/environment/src/hooks/use-links.ts
libs/i18n/src/locales/en/trading.json

Closes #5728 
This PR changes couple of texts on "Competitions" page.
N/A
N/A

chore(trading): competitions texts

---

apps/trading/client-pages/competitions/competitions-home.tsx
apps/trading/components/competitions/competitions-leaderboard.tsx
apps/trading/components/competitions/games-container.tsx
libs/i18n/src/locales/en/trading.json

fix(trading): competitions font tweaks

---

apps/governance/src/app.tsx
apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx

Closes #5821
Instrument does not have an ID so it needs a custom key field so it can be looked up in the cache

fix(governance): market name component not showing correct instrument code

---

apps/governance/src/components/collapsible-toggle/collapsible-toggle.tsx
apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx
apps/governance/src/routes/proposals/components/proposal-json/proposal-json.tsx
apps/governance/src/routes/proposals/components/proposal-market-changes/proposal-market-changes.tsx
apps/governance/src/routes/proposals/components/proposal/colours.ts
apps/governance/src/routes/proposals/components/proposal/indicator.tsx
apps/governance/src/routes/proposals/components/proposal/market-name.tsx
apps/governance/src/routes/proposals/components/proposal/proposal-change-details.tsx
apps/governance/src/routes/proposals/components/proposal/proposal.tsx
apps/governance/src/routes/proposals/components/proposals-list/proposals-list.tsx
apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx
libs/tailwindcss-config/src/vega-custom-classes.js

Closes #5866
* adds missing information
* minor styling fixes

fix(governance): network paramater change in batch proposals

---

apps/trading/e2e/conftest.py
apps/trading/e2e/tests/deal_ticket/test_basic.py
apps/trading/e2e/tests/deal_ticket/test_fees_margin_estimations.py
apps/trading/e2e/tests/deal_ticket/test_stop_order.py
apps/trading/e2e/tests/navigation/test_navigation.py
apps/trading/e2e/tests/order/test_order_status.py
apps/trading/e2e/tests/settings/test_settings.py

N/A
Reverting this PR which is causing issues with testing

chore(trading): revert reuse vega work

---

apps/trading/components/fees-container/market-fees.tsx

Closes #5726 
Update the fields order on fees by market table.

fix(trading): fees by market fix order

---

apps/governance/.env
apps/governance/.env.capsule
apps/governance/.env.devnet
apps/governance/.env.mainnet
apps/governance/.env.mainnet-mirror
apps/governance/.env.stagnet1
apps/governance/.env.testnet
apps/governance/src/components/vega-wallet/hooks.ts
apps/governance/src/config/env.ts
apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards.tsx
apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.spec.ts
apps/governance/src/routes/rewards/epoch-total-rewards/epoch-total-rewards.tsx
apps/governance/src/routes/rewards/epoch-total-rewards/generate-epoch-total-rewards-list.spec.ts
apps/governance/src/routes/rewards/shared-rewards-table-assets/shared-rewards-table-assets.tsx
apps/governance/src/routes/staking/home/epoch-data.tsx
apps/governance/src/routes/staking/node/nodes-container.tsx
apps/governance/src/routes/staking/node/staking-form.tsx

Closes #5871 
- Fixes rewards not showing for individuals after page 1
- Removes unnecessary columns from rewards table

fix(governance): rewards pagination and columns

---

libs/deal-ticket/src/components/trading-mode-tooltip/trading-mode-tooltip.tsx
libs/proposals/src/lib/proposals-hooks/Proposal.graphql
libs/proposals/src/lib/proposals-hooks/__generated__/Proposal.ts
libs/types/src/__generated__/types.ts

N/A
Fixes the app from crashing when using the trading mode tooltip by accounting for batch proposals when determining the markets enactment date

fix(trading): check for batch proposal in trading mode tooltip

---

apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.spec.tsx
apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx
apps/governance/src/routes/staking/home/validator-tables/shared.tsx
apps/governance/src/routes/staking/node/validator-table.tsx

N/A
Fixes incorrect penalty information in the validators table and on the validators page.

fix(governance): incorrect penalty information in validators table and page

---

apps/governance-e2e/src/integration/flow/staking-flow.cy.ts
apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts
apps/governance-e2e/src/integration/view/home.cy.ts
apps/governance-e2e/src/integration/view/validators.cy.ts
apps/governance-e2e/src/integration/view/wallet-vega.cy.ts
apps/governance-e2e/src/support/common.functions.ts
libs/cypress/src/lib/commands/mock-chain-id.ts
libs/cypress/src/lib/commands/vega-wallet-connect.ts
libs/cypress/src/lib/mock-rest.ts

fix tests due to new wallet connection method

fix(trading): fix tests due to new wallet connection method

---

apps/governance/src/components/notifications/rewards-moved-notification.tsx
apps/governance/src/components/page-templates/app-layout.tsx
libs/environment/src/hooks/use-links.ts
libs/i18n/src/locales/en/governance.json

Closes #5897 
* adds notification as seen below:
N/A

fix(governance): rewards moved to console notification

---

apps/trading/e2e/tests/market/test_market_info.py

N/A
Fix e2e test for market info

fix(trading): market into tab 24hr vol and price fix

---

apps/governance/src/components/notifications/rewards-moved-notification.tsx
apps/governance/src/components/page-templates/app-layout.tsx
apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.spec.tsx
apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx
apps/governance/src/routes/staking/home/validator-tables/shared.tsx
apps/governance/src/routes/staking/node/validator-table.tsx
apps/trading/e2e/tests/market/test_market_info.py
libs/environment/src/hooks/use-links.ts
libs/i18n/src/locales/en/governance.json
libs/i18n/src/locales/en/markets.json
libs/markets/src/lib/components/last-24h-price-change/last-24h-price-change.tsx
libs/markets/src/lib/components/last-24h-volume/last-24h-volume.tsx
libs/markets/src/lib/hooks/use-candles.ts

chore(trading,governance): back merge hotfixes

---

package.json
tools/ci/check-affected.py

fix(trading): fix ci cypress issue

---

apps/trading/components/chart-container/chart-container.tsx
apps/trading/components/chart-container/use-chart-settings.ts
libs/trading-view/src/lib/trading-view-container.tsx
libs/trading-view/src/lib/trading-view.tsx

Closes #5892 
Removes stored state so that the chart renders with the correct market data

fix(trading): stored state causing wrong chart data

---

apps/trading/components/bootstrapper/bootstrapper.tsx
apps/trading/components/navbar/navbar.spec.tsx
apps/trading/components/profile-dialog/profile-dialog.tsx
apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx
apps/trading/components/vega-wallet/vega-wallet-menu.tsx
apps/trading/e2e/tests/rewards/test_rewards_combo_tier_1.py

Closes #5941 
- Fixes alias not updated in dropdown
- Adds alias to mobile wallet menu
- Adds edit icon

fix(trading): party alias snags

---

libs/cypress/src/lib/capsule/create-market.ts
libs/cypress/src/lib/capsule/submit-proposal.ts
libs/cypress/src/lib/utils.ts
libs/wallet/package.json
libs/wallet/project.json
libs/wallet/src/connectors/view-party-connector.ts
libs/wallet/src/utils.ts

N/A
- libs/wallet depended on utils which in turn had a dependency on react. We only depended on one simply function so until the deps of react can be tied I've duplicated it in libs/wallet
- Removed dep on ethers

chore(wallet): reduce bundle size by removing unnecessary deps

---

apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx
apps/governance/src/routes/proposals/components/proposal/proposal-utils.ts
apps/governance/src/routes/proposals/components/proposal/proposal.tsx
apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx
apps/governance/src/routes/proposals/hooks/use-vote-information.ts

Closes #5863 
`develop` PR: #5914

chore(governance): lp votes for batch proposal

---

libs/deal-ticket/src/components/trading-mode-tooltip/trading-mode-tooltip.tsx
libs/proposals/src/lib/proposals-hooks/Proposal.graphql
libs/proposals/src/lib/proposals-hooks/__generated__/Proposal.ts
libs/types/src/__generated__/types.ts

Closes #5977 
* resolved enactment date in tooltip also when a market has been created via a batch proposal
N/A
N/A

fix(trading): crashing tooltip, enactment date from batch proposal

---

libs/markets/src/lib/components/market-info/market-info-panels.tsx
libs/proposals/src/lib/proposals-hooks/Proposal.graphql
libs/proposals/src/lib/proposals-hooks/__generated__/Proposal.ts

N/A
Updates key details panel to account for batch proposals

fix(trading): key details panel throwing error on batch created market

---

libs/datagrid/src/lib/cells/price-change-cell.tsx
libs/markets/src/lib/components/last-24h-price-change/last-24h-price-change.tsx

N/A
Fix price change on new markets

fix(trading): remove invalid candles from price change calc

---

apps/explorer/src/app/components/size-in-asset/size-in-asset.tsx
apps/explorer/src/app/components/txs/details/transfer/Transfer.graphql
apps/explorer/src/app/components/txs/details/transfer/__generated__/Transfer.ts
apps/explorer/src/app/components/txs/details/transfer/blocks/transfer-participants.tsx
apps/explorer/src/app/components/txs/details/transfer/transfer-details.tsx

Closes #3331
Adds a fee display to the transfer details

feat(explorer): fees on transfer component

---

libs/datagrid/src/lib/cells/price-change-cell.tsx
libs/markets/src/lib/components/last-24h-price-change/last-24h-price-change.tsx

fix(trading): remove invalid candles from price change calc (#5983)

---

apps/trading/e2e/tests/order/test_order_status.py

Order sorting has been deleted as this is AG grid functionality.
Order status parked has been deleted and will be added in the future to a test set around tests for markets in auction

chore(trading): refactor order status test

---

libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions-table.tsx

feat(positions): do not show liquidation price if position openVolume is 0

---

libs/deal-ticket/src/components/deal-ticket/key-value.tsx

Closes #6003 
Adds button attribute to prevent form submission

fix(deal-ticket): dont trigger deal ticket submit when clicking margin

---

libs/deal-ticket/src/components/deal-ticket/margin-mode-selector.tsx
libs/positions/src/lib/positions-data-providers.ts
libs/ui-toolkit/src/components/slider/leverage-slider.tsx

feat(deal-ticket): change min and max leverage

---

apps/trading/components/node-health/node-health.spec.tsx

N/A
Removes missing mock warnings

chore(trading): add missing mock for node health

---

apps/trading/pages/_document.page.tsx
apps/trading/pages/index.page.tsx

N/A
Appease nextjs warning about meta tags

chore(trading): move meta tag to remove nextjs warning

---

.github/workflows/console-test-run.yml
apps/trading/e2e/.env
apps/trading/e2e/.env.develop
apps/trading/e2e/poetry.lock

Update the vega version for sim tests 75.1

chore(trading): update the vega version for sim tests 75.1

---

apps/trading/e2e/tests/market/test_continuous_market_to_price_monitoring_auction.py

chore(trading): tests for market to auction

---

apps/trading/components/competitions/games-container.tsx
apps/trading/components/rewards-container/active-rewards.tsx
apps/trading/components/rewards-container/reward-card.tsx
libs/i18n/src/locales/en/trading.json

Closes #5797 
Add the games container search bar. 
Search by dispatch metric, entity scope or asset name.

feat(trading): games container search bar

---

apps/trading/components/competitions/competitions-leaderboard.tsx
apps/trading/components/competitions/team-avatar.tsx

N/A
- Fixes wrong team avatar showing
- Adds cross origin attribute

fix(trading): wrong team image showing

---

apps/trading/client-pages/competitions/competitions-team.tsx

N/A
* makes all date format the same

chore(trading): date format on team profile page

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx

Closes #6001 
Re-align checkboxes in deal ticket

feat(trading): align deal ticket checkboxes

---

libs/markets/src/lib/market-utils.ts

N/A
Quote is a better reflection of 'settlement asset' for spot

fix(markets): use quote asset for settlement in spot markets

---

libs/accounts/src/lib/use-account-balance.tsx
libs/accounts/src/lib/use-margin-account-balance.tsx

Closes #6091 
Removes additional state handling of the margin balance and just derives values directly from the accounts store

fix(accounts): changing key does not update ticket

---

apps/trading/client-pages/markets/use-column-defs.tsx
libs/markets/src/lib/components/last-24h-volume/last-24h-volume.tsx
libs/markets/src/lib/market-utils.spec.tsx
libs/markets/src/lib/market-utils.ts

N/A
Fixes 24h volume calculation using notional

fix(markets): use position decimals in notional calculation

---

apps/trading/client-pages/markets/open-markets.tsx
libs/markets/src/lib/market-utils.ts
libs/markets/src/lib/markets-provider.ts

Closes #6136 
- Reinstates the active markets filter
- Renames functions to be more accurat

fix(markets): open markets list filtering

---

libs/markets/src/lib/market-utils.ts

N/A
Fixes an issue where pending markets were not shown in the open markets list

fix(markets): add pending markets to active market list

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/hooks/use-max-size.spec.ts
libs/deal-ticket/src/hooks/use-max-size.ts
libs/withdraws/src/lib/withdraw-form-container.tsx

feat(deal-ticket): improve maxSize calculation for limit orders in isolated trading mode

---

apps/trading/components/fees-container/fees-container.tsx

fix(trading): show only active markets on fees page

---

apps/governance/src/routes/proposals/components/propose/proposal-form-transaction-dialog.tsx
apps/governance/src/routes/proposals/propose/freeform/propose-freeform.tsx
apps/governance/src/routes/proposals/propose/network-parameter/propose-network-parameter.tsx
apps/governance/src/routes/proposals/propose/new-asset/propose-new-asset.tsx
apps/governance/src/routes/proposals/propose/new-market/propose-new-market.tsx
apps/governance/src/routes/proposals/propose/raw/proposal-raw.spec.tsx
apps/governance/src/routes/proposals/propose/update-asset/propose-update-asset.tsx
apps/governance/src/routes/proposals/propose/update-market/propose-update-market.tsx
libs/proposals/src/lib/proposals-hooks/use-proposal-submit.ts
libs/types/src/global-types-mappings.ts
libs/ui-toolkit/src/components/text-area/text-area.tsx
libs/wallet/src/transaction-types.ts

Closes #5890 
- Unwrap proposal transaction to allow for batch proposals

chore(governance): allow batch proposals

---

apps/trading/e2e/tests/spot_market/test_spot.py

Adjust a market info spot tests

chore(trading): adjust a market info spot tests

---

libs/markets/src/lib/components/market-info/market-info-panels.tsx

fix(trading): spot asset info main

---

libs/accounts/src/lib/Accounts.graphql
libs/accounts/src/lib/__generated__/Accounts.ts
libs/accounts/src/lib/transfer-form.spec.tsx
libs/accounts/src/lib/transfer-form.tsx

Closes #5743 
Transfer form should make use of wallet key aliases

feat(trading): alias transfer display

---

apps/governance/src/routes/proposals/components/proposal/proposal.tsx
apps/governance/src/routes/proposals/components/vote-details/user-vote.tsx
apps/governance/src/routes/proposals/components/vote-details/vote-buttons.tsx
apps/governance/src/routes/proposals/components/vote-details/vote-transaction-dialog.tsx
libs/proposals/src/lib/voting-hooks/use-vote-submit.ts

Closes #6174 
* adds missing `onChange` for the voting dialog
N/A
N/A

fix(governance): allow closing the voting dialog

---

libs/data-provider/src/generic-data-provider.ts
libs/datagrid/src/lib/cell-class-rules.ts
libs/positions/src/lib/positions-table.tsx
libs/trades/src/hooks/use-latest-trade.ts
libs/trades/src/lib/trades-data-provider.ts

feat(positions): use orange for zero open volume only if position was closed out

---

apps/governance/src/hooks/use-vega-wallet-config.ts
apps/trading/lib/hooks/use-vega-wallet-config.ts
libs/wallet/src/chains.ts
libs/wallet/src/index.ts

N/A
Wallet configs were missing mainnet mirror setup

chore(trading,governance): add mirror configuration for wallet

---

apps/governance/src/components/vega-wallet/hooks.ts

Closes #6153 
* makes accounts data retrieval faster
N/A
N/A

fix(governance): slow accounts data retrieval

---

README.md

chore(trading,governance,explorer): release v0.25.17

---

apps/trading/client-pages/market/market.tsx
apps/trading/client-pages/market/trade-grid.tsx
apps/trading/client-pages/market/trade-panels.tsx
apps/trading/client-pages/markets/use-column-defs.tsx
apps/trading/components/accounts-container/accounts-container.tsx
apps/trading/components/market-header/market-header-switch.tsx
apps/trading/e2e/tests/positions/test_position_tp_sl.py
libs/accounts/src/lib/accounts-manager.tsx
libs/accounts/src/lib/accounts-table.spec.tsx
libs/accounts/src/lib/accounts-table.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket-container.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/components/deal-ticket/side-selector.tsx
libs/deal-ticket/src/components/deal-ticket/type-selector.tsx
libs/deal-ticket/src/hooks/use-max-size.spec.ts
libs/deal-ticket/src/hooks/use-max-size.ts
libs/markets/src/lib/market-utils.ts

Closes #6235 
- pin both assets in collateral table
- show no collateral warning base on different asset on sell and buy side
- remove stop order and TP/SL

feat(trading): spot market improvements

---

apps/explorer/src/app/components/oracle-table/index.tsx
apps/explorer/src/app/routes/oracles/components/oracle-markets.spec.tsx
apps/explorer/src/app/routes/oracles/components/oracle-markets.tsx

Closes #6190 
Changes a heading

chore(explorer): change column heading for oracles

---

apps/trading/client-pages/portfolio/index.ts
apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/e2e/tests/transfer/test_transfer_key_to_key.py
apps/trading/pages/client-router.tsx
libs/i18n/src/locales/en/trading.json

Closes #6267 
- Removes sidebar from portfolio page
- Adds pane for deposit/withdraw/transfer

feat(trading): add deposit/withdraw/transfer pane to portfolio

---

libs/utils/src/lib/format/number.spec.ts
libs/utils/src/lib/format/number.ts

Closes #6271
Show more decimal places if to avoid showing 0 when number is not 0.

feat(utils): round to smallest meaningful number  

---

apps/trading/components/liquidity-header/liquidity-header.tsx
apps/trading/components/market-header/market-header.tsx
apps/trading/components/market-header/mobile-market-header.tsx
apps/trading/components/market-selector/market-selector-item.spec.tsx
apps/trading/components/market-selector/market-selector-item.tsx
libs/emblem/src/components/market-emblem.tsx

Closes #5096 
Add icons for markets in console. 

feat(trading): market icons in console

---

apps/trading/components/market-banner/market-monitoring-auction.tsx
apps/trading/components/market-header/market-header.tsx
apps/trading/components/market-selector/market-selector-item.tsx
libs/i18n/src/locales/en/trading.json
libs/utils/src/lib/format/date.ts

Closes #6291 
Auction countdown timezone bug. 

fix(trading): auction countdown

---

apps/trading/components/market-banner/market-monitoring-auction.tsx
libs/utils/src/lib/format/date.ts

Closes #6291 
Auction countdown timezone bug. 

fix(trading): another countdown fix

---

apps/explorer/.env.mainnet
apps/explorer/.env.mainnet-mirror
apps/explorer/.env.validators-testnet
apps/explorer/src/app/components/links/block-link/block-link.tsx
apps/explorer/src/app/components/links/node-link/Nodes.graphql
apps/explorer/src/app/components/links/node-link/node-link.tsx
apps/explorer/src/app/components/links/node-link/tendermint-node-link.tsx
apps/explorer/src/app/components/txs/txs-per-block.tsx
apps/explorer/src/app/hooks/use-tendermint-validators.ts
apps/explorer/src/app/routes/blocks/id/block.spec.tsx
apps/explorer/src/app/routes/blocks/id/block.tsx
apps/explorer/src/app/routes/validators/validators-page.tsx

- **fix(explorer): broken link in oracle details**
- **fix(explorer): validator card should show tendermint pubkey**
- **fix(explorer): show tendermint address on validator**
Closes #5867

fix(explorer): block links and minor fixes

---

apps/trading/client-pages/markets/use-markets-stats.tsx

Closes N/A 
Quantum formatting on balance messes up the calculation

fix(trading): fix quantum formatting tvl

---

apps/trading/client-pages/markets/markets-page.tsx

Closes N/A
Remove TVL card for now. 

fix(trading): remove tvl for now

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/ui-toolkit/src/components/slider/index.ts
libs/ui-toolkit/src/components/slider/leverage-slider.tsx
libs/ui-toolkit/src/components/slider/percentage-slider.stories.tsx
libs/ui-toolkit/src/components/slider/percentage-slider.tsx

Closes #6093 
Add a simple 0%, 25%, 50%, 75%, 100% to the slider so users can click and set it quickly.

feat(trading): add intervals to the slider

---

.github/workflows/add-ipfs-notes-to-release.yml
.github/workflows/ci-cd-trigger.yml
.github/workflows/cypress-run.yml
.github/workflows/generate-queries.yml
.github/workflows/lint-pr.yml
.github/workflows/publish-dist.yml
.github/workflows/publish-npm.yml
.github/workflows/rollback-console.yml
.github/workflows/trading-e2e-test-run.yml

fix(ci): rework conditions triggering publish-dist and previews

---

.github/workflows/ci-cd-trigger.yml

fix(ci): do not execute ci/cd trigger mindlessly

---

apps/trading/client-pages/markets/markets-page.tsx

Closes N/A
Issue observed in market-sim.
Fixes a potential:  

fix(trading): prevent NaN TVL

---

apps/explorer/src/app/components/txs/details/transfer/blocks/transfer-rewards.tsx
apps/governance/src/components/wallet-card/wallet-card.tsx
libs/environment/src/hooks/use-links.ts
libs/i18n/src/locales/en/governance.json

Closes #5679 
Improve vesting rewards tooltip with link and percentage

fix(governance): improve vesting rewards tooltip

---

libs/markets/src/lib/components/market-info/info-key-value-table.tsx

Closes #6318 
* fixes tick size formatting
N/A

fix(trading): tick size formatting

---

libs/wallet-react/src/hooks/use-disconnect.ts
libs/wallet-react/src/hooks/use-vega-wallet.ts

Closes #6080 
Remove key from localstorage on disconnect

fix(trading): remove key from store on disconnect

---

apps/trading/lib/hooks/use-total-volume-locked.ts

N/A
The underlying data node queries error for couple of accounts hence we need to ignore the errors that are coming from the TVL query.
N/A

fix(trading): ignore tvl query errors

---

apps/trading/e2e/conftest.py

Fixes running the e2e tests using local_server and without a console image

chore(trading): fix conftest

---

apps/trading/e2e/README.md

chore(trading,governance,explorer): release v0.25.22

---

apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx
apps/governance/src/routes/proposals/components/proposal/proposal-change-details.tsx
libs/proposals/src/lib/proposals-hooks/Proposal.graphql
libs/proposals/src/lib/proposals-hooks/__generated__/Proposal.ts
libs/proposals/src/lib/proposals-hooks/use-cancel-transfer-proposal-details.ts
libs/proposals/src/lib/proposals-hooks/use-new-transfer-proposal-details.ts

Closes #6385
* fixes the transfer proposals view in batch
N/A

fix(governance): transfer proposals in batch

---

libs/ui-toolkit/src/components/slider/percentage-slider.tsx
libs/ui-toolkit/src/components/slider/slider.tsx
libs/ui-toolkit/src/components/trading-input/input.tsx

Closes #6345 
Add tooltip on hover on percentage slider

feat(ui-toolkit): add tooltip on hover on percentage slider

---

apps/trading/client-pages/markets/markets-page.tsx
apps/trading/client-pages/markets/use-column-defs.tsx
libs/datagrid/src/lib/cells/stacked-cell.tsx
libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-hammer.tsx
libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-monitor.tsx
libs/utils/src/lib/price-change.ts

Closes N/A
Fixes stacked cell issue. 
Attempt for 24h price change. 

fix(trading): stacked cell rendering incorrectly

---

libs/utils/src/lib/price-change.ts

Closes #6443 
Fix first and last candle choice on 24h change

fix(trading): fix first and last candle choice on 24h change

---

apps/trading/components/positions-container/positions-container.tsx
libs/positions/src/lib/positions-table.spec.tsx
libs/positions/src/lib/positions-table.tsx

Closes #6314 
Reduce 'manage TP/SL' column

fix(trading): reduce Manage TP / SL column 

---

apps/trading/components/header/header.tsx
apps/trading/components/liquidity-header/liquidity-header.tsx
apps/trading/components/market-header/market-header.tsx
apps/trading/components/market-selector/market-selector-item.tsx
apps/trading/e2e/tests/market/test_market_selector.py

Closes #6421 
Adjust alignment on market text in market selector and header

feat(trading): market selector and header update

---

apps/governance/src/routes/proposals/components/proposal-asset-details/proposal-asset-details.tsx
apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx
apps/governance/src/routes/proposals/components/proposal/proposal-change-details.tsx

Closes #6402 
* fixes the asset specification collapsible panel for batch proposals
N/A

fix(governance): new asset batch proposal

---

apps/trading/e2e/tests/orderbook/test_orderbook.py
libs/market-depth/src/lib/orderbook-data.ts
libs/market-depth/src/lib/orderbook-manager.tsx
libs/market-depth/src/lib/orderbook-row.tsx
libs/market-depth/src/lib/orderbook.spec.tsx
libs/market-depth/src/lib/orderbook.stories.tsx
libs/market-depth/src/lib/orderbook.tsx

Closes #6224
Show details of the auction in order book

feat(market-depth): show details of the auction in order book

---

apps/trading/e2e/.env
apps/trading/e2e/tests/get_started/test_get_started.py

updating e2e test .env file to use develop as  this is now our "next" branch.

chore(trading): update e2e .env file

---

apps/trading/client-pages/markets/closed.tsx
apps/trading/client-pages/markets/market-code-cell.spec.tsx
apps/trading/client-pages/markets/market-code-cell.tsx
apps/trading/components/fees-container/market-fees.tsx

Closes #6410 
Add icons for market on the fees page

feat(trading): add icons for market on the fees page

---

libs/deposits/src/lib/deposit-container.tsx

N/A
* filters out the Arbitrum assets
N/A
N/A

fix(trading): filter arbitrum assets out of deposit

---

libs/smart-contracts/src/contracts/token.ts

N/A
* add USDT TEST ABI
N/A
N/A

chore(smart-contracts): swap in tether abi on mirror env

---

apps/trading/e2e/tests/transfer/test_transfer_key_to_key.py
apps/trading/e2e/vegahome/genesis.json
libs/deposits/src/lib/deposit-form.tsx

N/A
Prompt wallet to switch chain depending on selected asset

fix(trading): chain switching for deposits

---

apps/governance-e2e/src/integration/view/wallet-vega.cy.ts
apps/trading/e2e/vegahome/genesis.json
libs/wallet/src/connectors/json-rpc-connector.ts

N/A
Change JSON RPC wallet connection name to 'CLI/Desktop Wallet'

chore(wallet): change json rpc connection name

---

apps/trading/client-pages/portfolio/portfolio-sidebar.tsx

Closes N/A
Remove 'Swap' from sidebar

fix(trading): remove swap from sidebar

---

RELEASE.md

chore(ci): add release process guide

---

apps/trading/components/swap/swap-form-elements.tsx
apps/trading/components/swap/swap-form.tsx
libs/accounts/src/lib/accounts-data-provider.ts

fix(trading): swap balance and warnings

---

apps/trading/components/swap/swap-container.tsx
libs/accounts/src/lib/accounts-data-provider.ts

Closes N/A
Rewards and swap balances should use different data providers.

fix(trading): use different data providers

---

vegacapsule/node_set_templates/default/vega_validators.tmpl

- Update config for latest vega changes

feat: update vega configs for the latest version

---

apps/trading/.env.mainnet
apps/trading/.env.testnet
apps/trading/e2e/tests/deal_ticket/test_isolated_cross_margin.py
apps/trading/e2e/tests/iceberg_orders/test_iceberg_orders.py
apps/trading/e2e/tests/swap/test_swap.py
apps/trading/e2e/tests/transfer/test_transfer_key_to_key.py
apps/trading/lib/hooks/use-vega-transaction-toasts.tsx
libs/environment/src/hooks/use-environment.ts
libs/utils/src/lib/is-valid-url.ts

N/A
- Sets default VEGA_URL for testnet and mainnet in env files
- Grabs the url from localStorage if set, otherwise falls back to the default VEGA_URL
- Does not await fetching of node config or to find the healthiest node before rendering. Instead this is now done in the background, unless there is no default node set

chore(environment): speed up start time of app

---

apps/trading/components/layouts/index.ts
apps/trading/components/layouts/layout-with-node-health.tsx
apps/trading/components/navbar/navbar.tsx
apps/trading/components/node-health/node-health.tsx
apps/trading/components/sidebar/sidebar.tsx
apps/trading/pages/client-router.tsx

Closes #6465 
* adds new variant of `<NodeHealthContainer />` component
* adds new layout with compact node health
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/8cb8ac46-cf1c-4103-a998-9f5bf873763c
N/A

feat(trading): compact node health indicator

---

apps/trading/client-pages/market/trade-grid.tsx
apps/trading/components/asset-card/asset-card.tsx
apps/trading/components/header/header.tsx
apps/trading/components/market-header/market-header.tsx
apps/trading/components/sidebar/sidebar-accordion.tsx
apps/trading/components/sidebar/sidebar.tsx
apps/trading/pages/styles.css
libs/ui-toolkit/src/components/tabs/tabs.tsx
libs/ui-toolkit/src/components/tiny-scroll/tiny-scroll.tsx

#6574 
First part of 6574:
- Moves market header into the grid so that the sidebar can take more vertical space
- Changes to styles to match latest designs

feat(trading): increase ticket height

---

apps/trading/e2e/tests/deal_ticket/test_stop_order.py
libs/trading-view/src/lib/Symbol.graphql
libs/trading-view/src/lib/__generated__/Symbol.ts
libs/trading-view/src/lib/use-datafeed.ts

Closes #6233 
This PR fixes the market state indicator inside the TV chart.
N/A

fix(trading): market closed indicator inside trading view chart

---

package.json
yarn.lock

fix(trading,governance,explorer): graphql version resolution

---

apps/trading/components/rewards-container/rewards-container.tsx
apps/trading/e2e/tests/rewards/test_rewards_tier_1.py
libs/accounts/src/lib/index.ts
libs/i18n/src/locales/en/trading.json

Closes #5533 
* makes redeem instant
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/bb4e99c1-b6ac-4ce3-9d2f-9b998be66a15
N/A

feat(trading): quick redeem

---

.github/workflows/publish-dist.yml

N/A
Fixes deployments for validators-testnet, which wasn't working due to being market as an ipfs release in publish-dist.yml workflow

ci(trading,governance,explorer): fix validators-testnet deployments

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/components/deal-ticket/time-in-force-selector.tsx

N/A
Errors for tif were showing squashed due to being rendered directly underneath the dropdown

fix(deal-ticket): layout of tif error

---

.github/actions/run-vegacapsule/action.yml
.github/workflows/ci-cd-trigger.yml
.github/workflows/cypress-run.yml
.github/workflows/trading-e2e-test-run.yml

fix(ci): set of fixes for CI (governance&explorer cypress)

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket.spec.tsx
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/ui-toolkit/src/components/index.ts
libs/ui-toolkit/src/components/ticket-input/index.ts
libs/ui-toolkit/src/components/ticket-input/ticket-input.tsx

N/A
It was hard to determine which field was which due to input caching. This adds labels to make it easier to tell the difference between them

feat(deal-ticket,ui-toolkit): add labels to size, price and notional inputs

---

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/i18n/src/locales/en/deal-ticket.json

Closes #6586 
* adds `max` validation to the deal ticket
N/A
N/A

feat(deal-ticket): max price validation

---

apps/trading/e2e/tests/transfer/test_transfer_key_to_key.py
libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx

N/A
Adds the new ticket input style to stop orders

feat(deal-ticket): use labelled inputs on stop orders

---

.github/actions/run-vegacapsule/action.yml

N/A
Fixes e2e test runs that use capsule

fix(ci): governance test pipeline fix

---

apps/trading/client-pages/market/trade-grid.tsx
apps/trading/components/resizable-grid/use-pane-layout.ts

N/A
Fix incorrect size caching of the bottom pane in the trade grid

fix(trading): trade grid size cache

---

apps/trading/e2e/tests/successor_market/test_succession_line.py
libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
libs/deal-ticket/src/utils/map-form-values-to-submission.ts

Closes #6656 
Fixes the display of size under the deal ticket when in notional mode

fix(deal-ticket): show correct size in info for notional mode

---

apps/trading/components/margin-mode/margin-mode.tsx

chore(trading): margin mode toggle contrast

---

apps/trading/components/margin-mode/margin-mode.tsx

N/A
Fix issue where you could not change margin amount when already in isolated margin mode

fix(trading): allow changing margin when already in isolated mode

---

apps/trading/components/asset-card/asset-card.tsx

fix(trading): allocated (deployed) percentage

---

apps/trading/client-pages/competitions/Scores.graphql
apps/trading/client-pages/competitions/__generated__/Scores.ts
apps/trading/client-pages/competitions/competitions-game.tsx
libs/types/src/__generated__/types.ts

N/A
- Sorts scores by epoch
- Fixes incorrect column key

fix(trading): game page sort and rewards

---

apps/explorer/project.json
apps/explorer/src/app/components/txs/details/amm/amm-liquidity-parameters.tsx
apps/explorer/src/app/components/txs/details/transfer/blocks/transfer-rewards.tsx
apps/explorer/src/app/components/txs/details/tx-amm-amend.tsx
apps/explorer/src/app/components/txs/details/tx-amm-cancel.tsx
apps/explorer/src/app/components/txs/details/tx-amm-submit.tsx
apps/explorer/src/app/components/txs/details/tx-data-submission.tsx
apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx
apps/explorer/src/app/components/txs/details/tx-order-amend.tsx
apps/explorer/src/app/components/txs/tx-filter.tsx
apps/explorer/src/app/components/txs/tx-order-type.tsx
apps/explorer/src/types/explorer.d.ts

Closes #6627
Add TX Details views for submit, amend and cancel AMM txs

feat(explorer): amm tx support

---

apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/components/accounts-container/accounts-container.tsx
apps/trading/components/accounts-container/sidebar-accounts-container.tsx
apps/trading/e2e/.env
apps/trading/e2e/tests/swap/test_swap.py
apps/trading/e2e/tests/transfer/test_transfer_key_to_key.py
libs/accounts/src/lib/account-card.tsx
libs/accounts/src/lib/accounts-actions-dropdown.tsx
libs/accounts/src/lib/accounts-manager.tsx
libs/i18n/src/locales/en/trading.json
libs/ui-toolkit/src/components/tabs/tabs.tsx

Closes #6683
* removes other tabs on Portfolio sidebar
* adds Search field to the assets breakdown
* adds combined deposit button

feat(trading): portfolio assets tab

---

apps/trading/components/ticket/elements/form.tsx
apps/trading/components/ticket/fields/iceberg-min-visible-size.tsx
apps/trading/components/ticket/fields/iceberg-peak-size.tsx
apps/trading/components/ticket/fields/side.tsx
apps/trading/components/ticket/fields/stop-loss.tsx
apps/trading/components/ticket/fields/take-profit.tsx
apps/trading/components/ticket/ticket-default/ticket.tsx

N/A
- Does not rely on baseSymbol for default ticket (this is set from meta data)
- Fixes display of 2 col input layout when validation error is shown
- Fixes error when clicking the already selected side

fix(trading): misc fixes

---

libs/wallet/package.json
libs/wallet/src/transaction-types.ts

Related to https://github.com/vegaprotocol/nebula/issues/29
* adds AMM commands from protos

chore(wallet): amm transaction types

---

apps/trading/client-pages/market/trade-grid.tsx
apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/components/accounts-container/sidebar-accounts-container.tsx
apps/trading/components/orderbook-container/orderbook-container.tsx
apps/trading/components/sidebar/sidebar.spec.tsx
apps/trading/components/sidebar/sidebar.tsx
apps/trading/components/ticket/feedback/deposit-button.tsx
apps/trading/lib/hooks/use-sidebar.ts

N/A
- Moves sidebar related stores/hooks to hooks folder
- Adds hook to change the min width if the squid widget is shown

chore(trading): increase min sidebar width when squid is shown

---

apps/trading/client-pages/markets/markets-page.tsx

Closes #6709 
Allows market filters to wrap

fix(trading): market filters causing page overflow

---

apps/trading/client-pages/markets/markets-page.tsx
libs/ui-toolkit/src/components/dialog/dialog.tsx
libs/wallet-react/src/components/connect-dialog/connect-dialog.tsx
libs/wallet-react/src/components/connect-dialog/connection-options.tsx

Closes #6619 
Ensures the correct dialog elements are rendered for a11y

chore(ui-toolkit): ensure accessible dialog title and content descriptions are rendered

---

apps/trading/components/market-banner/market-update-state-banner.tsx
apps/trading/e2e/tests/market_lifecycle/test_market_lifecycle.py
apps/trading/e2e/tests/perpetual_market/test_perpetuals.py
apps/trading/e2e/tests/teams/test_teams.py

Closes #6626 
Add time to update state market banner

chore(trading): add time to market banner for update state

---

apps/governance/src/routes/proposals/components/proposal/proposal-utils.ts
apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.spec.tsx
apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx
apps/governance/src/routes/proposals/hooks/use-vote-information.spec.ts
apps/governance/src/routes/proposals/hooks/use-vote-information.ts
package.json

Closes #6739
Use the thresholds from the proposal rather than the network parameters

fix(governance): use proposal values for thresholds, not network params

---

libs/browser-wallet/src/frontend/contexts/json-rpc/hooks/create-client.ts
libs/browser-wallet/src/frontend/contexts/json-rpc/hooks/create-server.ts
libs/browser-wallet/src/frontend/contexts/json-rpc/json-rpc-context.ts
libs/browser-wallet/src/frontend/contexts/network/mock-network-provider.tsx

A CI error has resulted in the builds being broken on develop

fix(browser-wallet): build browser wallet

---

libs/wallet/src/transaction-types.ts

N/A
Fixes amm transaction interfaces that are missing the wrapping property

fix(wallet): amm tx interfaces

---

apps/trading/components/asset-activity/withdrawal-status-cell.tsx

N/A
Fixes an issue where assets without a delay threshold were incorrectly shown as delayed

fix(trading): check for asset threshold showing delay information

---

apps/explorer/src/app/components/assets/assets-table.tsx

Closes #6501
Filters out rejected assets from the asset list page

feat(explorer): hide rejected assets from asset list page

---

apps/trading/pages/_app.page.tsx
libs/browser-wallet-backend/src/lib/storage.js
libs/browser-wallet/src/frontend/components/pages/onboarding-page/onboarding-page.tsx
libs/browser-wallet/src/frontend/hooks/redirect-path/index.tsx
libs/browser-wallet/src/frontend/hooks/redirect-path/redirect-path.spec.tsx
libs/browser-wallet/src/frontend/hooks/suggest-mnemonic/index.ts
libs/browser-wallet/src/frontend/lib/create-wallet.ts
libs/browser-wallet/src/frontend/lib/extension-apis.ts
libs/browser-wallet/src/frontend/routes/onboarding/save-mnemonic/index.tsx
libs/browser-wallet/src/frontend/routes/onboarding/save-mnemonic/save-mnemonic.spec.tsx

Related to #6753
Generalise storage to take a map-like interface
Remove session storage from UI as edge case not present within wallet

chore(browser-wallet-backend): generalise storage to take map like interface

---

libs/cypress/src/lib/commands/associate-tokens-to-vega-wallet.ts
libs/cypress/src/lib/commands/create-market.ts
libs/cypress/src/lib/commands/validators-self-delegate.ts
libs/cypress/src/lib/mock-gql.ts
libs/cypress/src/lib/mock-ws.ts

N/A
Removes imports from @vegaprotocol/environment from within cypress tests as webpack was unable to compile

fix(governance,explorer): e2e tests using cypress

---

libs/react-helpers/package.json
libs/tailwindcss-config/package.json
libs/ui-toolkit/package.json
libs/utils/package.json

Get read to publish libs with new tailwind config

chore(ui-toolkit,react-helpers,utils,tailwindcss-config): bump libs for publishing

---

libs/ui-toolkit/src/components/notification/notification.tsx

N/A
Fix notification text color

fix: notification text color

---

apps/trading/client-pages/competitions/competitions-game.tsx

fix(trading): estimated reward

---

apps/trading/components/navbar/navbar.spec.tsx
apps/trading/components/navbar/navbar.tsx
libs/i18n/src/locales/en/trading.json

feat(trading): rename nav title and remove dropdown

---

libs/react-helpers/package.json
libs/tailwindcss-config/package.json
libs/types/package.json
libs/types/project.json
libs/ui-toolkit/package.json
libs/utils/package.json
libs/utils/project.json

N/A
Re-add CJS builds for functional jest testing

chore(trading,react-helpers,utils,tailwindcss-config,ui-toolkit): re add cjs build for modules

---

libs/json-rpc/src/lib/json-rpc-client.ts
libs/json-rpc/src/lib/json-rpc.ts
libs/wallet/src/connectors/in-browser-connector.ts

N/A
Fixing notifications for the wallet backend not sending responses to the frontend, including the disconnect and keys changed events.

chore(json-rpc,wallet): fix notifications from the wallet backend

---

libs/rest/src/paths.ts

fix(rest): remove nodejs paths package

---

apps/trading/.env.mainnet
libs/web3/src/lib/constants.ts

chore: switch ethereum rpc endpoints

---

apps/trading/client-pages/amm/explore.tsx
apps/trading/client-pages/amm/liquidity.tsx
apps/trading/client-pages/amm/pools/index.tsx
apps/trading/client-pages/amm/pools/market/index.tsx
apps/trading/client-pages/amm/pools/market/manage-liquidity.tsx
apps/trading/client-pages/competitions/competitions-game.tsx
apps/trading/components/amm/asset-pill.tsx
apps/trading/components/amm/liquidity-form-schema.ts
apps/trading/components/amm/liquidity-form.tsx
apps/trading/components/amm/stats/liquidity-chart.tsx
apps/trading/components/amm/stats/liquidity-table.tsx
apps/trading/components/transaction-dialog/transaction-dialog.tsx
apps/trading/components/transaction-dialog/transaction-steps.tsx
apps/trading/components/ui/form.tsx
apps/trading/components/ui/input.tsx
apps/trading/lib/i18n/index.ts
apps/trading/lib/use-t.ts
apps/trading/lib/utils/amm.ts
libs/i18n/src/locales/en/trading.json
libs/rest/src/hooks/use-amms.ts
libs/rest/src/index.ts
libs/rest/src/queries/amms.ts

Closes #6838 
- Checks for active amms when preparing form for amm submission
- Removes placeholder chart
- Fixes translations not rendering due to i18n not being initialized
- Fixes incorrect use of i18n.t
- Memoizes coldefs
- Changes form schema setup so that superRefine can be used for conditional validation and so that the schema has the correct translations
- Improves form layout
- Fixes warnings about inputs changing from controlled to uncontrolled
- Fix decimal conversion for tx

fix(trading): amms fixes

---

apps/governance/src/routes/proposals/components/proposal/proposal-utils.ts
apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx
apps/governance/src/routes/proposals/hooks/use-vote-information.ts

fix(governance): batch proposals showing incorrect thresholds

---

apps/trading/components/amm/liquidity-form-schema.ts

N/A
Creates zod schema entirely within function called after app render so translations are loaded

fix(trading): i18n for liq form

---

.github/workflows/cypress-run.yml
apps/explorer/src/i18n/index.ts
apps/governance/src/i18n/index.ts
apps/trading/components/ticket/use-slippage.spec.tsx
apps/trading/lib/i18n/index.ts
package.json
yarn.lock

N/A
Removes locize setup as its not in use

chore(trading,governance,explorer): remove locize

---

apps/trading/client-pages/market/trade-grid.tsx
apps/trading/client-pages/portfolio/portfolio.tsx
apps/trading/components/resizable-grid/resizable-grid.tsx
apps/trading/components/sidebar/sidebar-accordion.tsx
apps/trading/pages/client-router.tsx
apps/trading/pages/styles.css
libs/accounts/src/lib/account-card.tsx
libs/fills/src/lib/fills-table.tsx
libs/tailwindcss-config/src/theme.ts
libs/ui-toolkit/src/components/tabs/tabs.tsx

#6837 
- Allows configurable panel radius
- Uses transparency for bgs of grids

feat(trading): design config for portfolio and trade grid

---

apps/trading/components/asset-option/asset-option.tsx
apps/trading/components/deposit-container/fallback-deposit-form.tsx
apps/trading/components/deposit-container/fields/from-asset.tsx
libs/ui-toolkit/src/components/trading-select/select.tsx

Closes #6843 
* shows "from asset" field that displays the same choice as in "to asset" with the current balance of it

chore(trading): from asset field

---

apps/explorer/.env
apps/explorer/.env.testnet
apps/governance/.env
apps/governance/.env.testnet
apps/trading/.env
apps/trading/.env.capsule
apps/trading/.env.devnet
apps/trading/.env.stagnet1
apps/trading/.env.testnet
apps/trading/.env.validators-testnet
libs/environment/src/hooks/use-environment.ts
libs/environment/src/utils/validate-environment.ts

chore(environment): remove unused hosted wallet env var

---

apps/trading/client-pages/competitions/tabs.tsx
libs/tailwindcss-config/src/theme.ts

N/A
Fixes a problem where the contextual alternative for the default font was applied everywhere

fix(trading,governance,explorer): font contextual alternative being applied everywhere

---

apps/trading/components/deposit-container/deposit-container.tsx
apps/trading/components/squid-container/squid-container.tsx
libs/i18n/src/locales/en/trading.json

Closes #6853 
* blocks deposits

chore(trading): disable deposits

---

apps/trading/components/browser-wallet-dialog/index.tsx
apps/trading/pages/dialogs-container.tsx
libs/browser-wallet-backend/src/src/admin-ns.js
libs/browser-wallet-backend/src/src/client-ns.js
libs/browser-wallet-backend/src/src/tx-helpers.js
libs/browser-wallet/src/frontend/components/modals/transaction-modal/transaction-modal-footer.tsx
libs/browser-wallet/src/frontend/components/modals/transaction-modal/transaction-modal.spec.tsx
libs/browser-wallet/src/frontend/components/modals/transaction-modal/transaction-modal.tsx
libs/browser-wallet/src/frontend/components/splash/splash.spec.tsx
libs/browser-wallet/src/frontend/components/splash/splash.tsx
libs/browser-wallet/src/frontend/routes/auth/auth.tsx
libs/wallet/src/types.ts
libs/web3/jest.config.ts

Closes #6755 
Add popup opening, transaction signing UI fixes, toasts functional, remove tx checker

feat(trading,governance,browser-wallet): pop open, remove tx checker, toasts working, UI fixes

---

apps/trading/components/ticket/elements/slider.tsx
apps/trading/components/ticket/info/slippage.tsx
apps/trading/components/ticket/use-estimate-position.ts
apps/trading/components/ticket/use-slippage.ts

#6879
- Fixes a problem where the armed ticket was not setting the price properly for position estimation
- Fixes a problem where the limit price was not properly set for slippage calculation

fix(trading): ticket slippage and position estimate

---

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx

Closes #6798
This code is slightly ugly. I went with a style attribute, rather than wrangling tailwind arbitrary props/values which seem less readable

fix(trading): allow key list to scroll

---

apps/explorer/src/assets/manifest.json
apps/explorer/src/index.html
apps/governance/src/assets/manifest.json
apps/governance/src/index.html
apps/multisig-signer/src/index.html
apps/static/src/index.html
apps/trading/public/manifest.json
libs/i18n/src/locales/en/script.js
libs/wallet-react/src/components/connect-dialog/connection-options/custom-connector-options/use-derived-wallet.ts

chore(trading,governance,explorer): change protocol name script

---

apps/trading/components/ticket/elements/slider.tsx

fix(trading): slider track colour

---

apps/governance/.env.capsule
apps/governance/.env.devnet
apps/governance/.env.mainnet
apps/governance/.env.mainnet-mirror
apps/governance/.env.stagnet1
apps/governance/.env.testnet
apps/governance/.env.validators-testnet
apps/trading/.env.capsule
apps/trading/.env.devnet
apps/trading/.env.mainnet
apps/trading/.env.mainnet-mirror
apps/trading/.env.stagnet1
apps/trading/.env.testnet
apps/trading/.env.validators-testnet
apps/trading/lib/hooks/use-vega-wallet-config.ts
libs/environment/src/hooks/use-environment.spec.ts
libs/environment/src/hooks/use-environment.ts
libs/environment/src/utils/validate-environment.ts

Allows each type of wallet to be turned on/off for console and governance

feat(governance,trading): allow for configurable wallet connections

---

apps/trading/components/ticket/derivative/ticket.tsx
apps/trading/components/ticket/fields/notional.tsx
apps/trading/components/ticket/fields/price.tsx
apps/trading/components/ticket/fields/stop-loss.tsx
apps/trading/components/ticket/fields/stop-trigger-price.tsx
apps/trading/components/ticket/fields/take-profit.tsx
apps/trading/components/ticket/info/collateral-required.tsx
apps/trading/components/ticket/info/fees.tsx
apps/trading/components/ticket/info/liquidation.tsx
apps/trading/components/ticket/info/notional.tsx
apps/trading/components/ticket/info/slippage.tsx
apps/trading/components/ticket/spot/fields/notional.tsx
apps/trading/components/ticket/spot/ticket.tsx
apps/trading/components/ticket/ticket-context.ts
libs/browser-wallet/src/frontend/routes/onboarding/create-password/create-password.spec.tsx
libs/markets/src/lib/market-utils.ts
libs/positions/src/lib/take-profit-stop-loss.spec.tsx

N/A
Fix to use metadata quote tag rather than product.quoteName

fix(trading): use metadata for quote symbol

---

libs/browser-wallet-backend/src/src/client-ns.js
libs/browser-wallet-backend/src/src/tx-helpers.js

fix(trading,browser-wallet): market order

---

libs/ui-toolkit/src/components/notification/notification.tsx

chore(ui-toolkit): fix error message overflow

---

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx

[6931](https://github.com/vegaprotocol/frontend-monorepo/issues/6931)

chore(trading): remove transfer from key selector dd

---

apps/trading/client-pages/market/trade-grid.tsx
apps/trading/components/market-banner/market-banner.tsx
apps/trading/lib/hooks/use-market-banners.ts

fix(trading): make banner height reactive

---

libs/trading-view/src/lib/trading-view.tsx

fix(trading): trading view localise time

---

apps/trading/pages/maybe-connect-eagerly.tsx
libs/wallet/src/wallet.ts

Closes #6927 
Adds a version for local storage so the stale pubKey version gets cleared

fix(wallet): add version for wallet store

---

apps/trading/components/browser-wallet-dialog/index.tsx

chore(trading): fix import wallet not opening properly

---

apps/trading/client-pages/competitions/competitions-home.tsx
apps/trading/components/card/card.tsx
apps/trading/components/competitions/games-container.tsx
apps/trading/components/rewards-container/simple-reward-card.tsx
apps/trading/components/rewards-container/simple-reward-cards-container.tsx
apps/trading/public/reward-cards.json
libs/rest/src/hooks/index.ts
libs/rest/src/hooks/use-reward-cards.ts
libs/rest/src/index.ts
libs/rest/src/queries/reward-cards.ts
libs/ui-toolkit/src/components/notification-banner/notification-banner.tsx
libs/ui-toolkit/src/components/pill/pill.tsx
libs/ui-toolkit/src/index.ts
libs/ui-toolkit/src/utils/border.tsx
libs/ui-toolkit/src/utils/intent.ts

Closes #6796 
* adds `SimpleRewardCard` component
* adds a new REST query that retrieves the cards from a JSON file; `useRewardCards`
This gets the content from `/public/reward-cards.json`.
The reward description is being parsed as **markdown** so it needs to be formatted correctly.

feat(trading): simple static reward cards

---

apps/trading/components/ticket/elements/submit-button.tsx

fix(trading): remove get started button from the ticket

---

apps/trading/components/market-header/market-header-future.tsx
apps/trading/components/market-header/market-header-perp.tsx

fix(trading): volume in market header should display value in settlement asset

---

apps/trading/client-pages/competitions/team-form.tsx
libs/wallet/src/transaction-types.ts

fix(trading): update team from private back to public

---

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx
libs/wallet-react/src/hooks/use-derived-wallet.ts
libs/wallet-react/src/hooks/use-disconnect.ts
libs/wallet-react/src/hooks/use-vega-wallet.ts
libs/wallet/src/connectors/embedded-connector/quick-start-connector.ts
libs/wallet/src/types.ts
libs/wallet/src/wallet.ts

N/A
Show the eth key an embedded wallet was generated from in the drop down.

feat(trading): derived address in dd

---

apps/trading/client-pages/markets/use-column-defs.tsx

fix(trading): use settlement asset instead of quote asset

---

apps/trading/client-pages/referrals/create-code-form.tsx
apps/trading/client-pages/referrals/referee-statistics.tsx
apps/trading/client-pages/referrals/referrer-statistics.tsx

chore(trading): remove team tiles and create team button from referrals

---

apps/trading/components/share-dialog/share-dialog.tsx

Closes #6928 
* the button triggers now the transaction instead of navigating to the create code page

chore(trading): create referral code from share dialog

---

apps/trading/components/asset-activity/asset-activity.tsx
apps/trading/components/asset-activity/withdrawal-status-cell.tsx
apps/trading/lib/hooks/use-evm-tx.tsx
apps/trading/lib/hooks/use-incomplete-withdrawals.spec.tsx
apps/trading/lib/hooks/use-incomplete-withdrawals.ts
apps/trading/lib/hooks/use-ready-to-complete-withdrawals-toast.tsx
apps/trading/pages/styles.css
libs/environment/src/chains.ts
libs/wallet/src/chains.ts

Closes #7000 
- Change column order of asset activity
- Fix incomplete withdrawal count
- Make ready to withdraw notifications just navigate to portfolio
- Make connecting and completing a single flow within the users wallet

fix(trading): asset activity cols

---

apps/governance/src/components/notifications/rewards-moved-notification.tsx
libs/proposals/src/components/protocol-upgrade-in-progress-notification.tsx
libs/proposals/src/components/protocol-upgrade-proposal-notification.tsx
libs/ui-toolkit/src/components/notification-banner/notification-banner.tsx

N/A
- Fixes banners which passed in an icon name and not an icon component
- Fixes the notification banner height

fix(ui-toolkit): banner icon display and height

---

apps/trading/components/layouts/layout-centered.tsx
apps/trading/pages/_app.page.tsx

N/A
Make the top nav and onboarding header not sticky

fix(trading): make app nav not sticky

---

libs/accounts/src/lib/account-card.tsx
libs/accounts/src/lib/accounts-actions-dropdown.spec.tsx
libs/accounts/src/lib/accounts-actions-dropdown.tsx

N/A
Pass chain Id to explorer link generator so link goes to correct explorer site

fix(trading): no chain link provided for explorer link in account list
