vegaprotocol/frontend-monorepo

apps/explorer/src/app/lib/flags.ts
There was an error because of destructuring off `env` from process, this resolves that issue
=> fix process error

apps/trading/hooks/use-vega-wallet-eager-connect.ts, libs/wallet/src/provider.test.tsx, libs/wallet/src/provider.tsx
- Clears current public key from local storage on disconnect
- Don't throw an error in useEagerConnect if a config is not found
Closes #116
=> Fix/116 Clear current publick key on disconnect

apps/explorer/src/app/routes/txs/id/tx-details.tsx
Transaction is usually `txn` not `tnx`.
- Update label
=> Fix typo in block explorer label

apps/trading-e2e/cypress.json, apps/trading-e2e/src/integration/market-order.feature, apps/trading-e2e/src/support/pages/deal-ticket-page.js, apps/trading-e2e/src/support/pages/markets-page.js, apps/trading-e2e/src/support/step_definitions/market-order.step.js
Currently all the market order tests are failing if the environment does not contain any active markets to place orders.
This PR removes the assertions for placing an order so it's no longer checking for command/sync to the wallet. 
- All of the UI components up to placing the order are still covered
- Should allow tests to pass even when the environment is unstable
In the long term, plan is to revert this change when we have a stable environment that we have control over using Capsule.
=> Remove assertions for placing order in active market

apps/stats/README.md
Add a license field in the stats readme
Really this is a test for the Netlify NX ignore plugin
- Update README.md
=> Add license to stats readme

ignore-netlify-build.js, netlify.toml
Bart, Dex & re-enabled the nx-ignore netlify plugin which successfully does the job.
We thought it broke builds, it doesn't.
- Remove netlify.toml ignore section
- Remove ignore script
=> Remove custom ignore

package.json
Add greater than, unless there is a good reason not to?
nvmrc remains the same
=> change engines to allow anything above 16.14.0

.github/workflows/ipfs.yml
After #244, and setting up the appropriate ENV var, I forgot to explicitly make it available in the build step that needs it.
- Update IPFS action
=> Fix IPFS deploy step

apps/trading-e2e/src/integration/markets-page.feature, apps/trading-e2e/src/support/pages/trading-page.ts, apps/trading-e2e/src/support/step_definitions/markets-page.step.ts, apps/trading-e2e/src/support/step_definitions/trading-page.step.ts, apps/trading-e2e/src/support/trading-windows/trades-list.js, apps/trading-e2e/src/support/trading-windows/trades-list.ts
Add additional assertion to existing step for checking that the trades list is displayed with no missing values.
Once we have capsule running, we could potentially have some more detailed tests to verify specific trades getting updated. One for follow up ticket if possible to do. 
Closes #141
=> Test passing for trades list

package.json, yarn.lock
Closes #287.
* red candles should be filled ([#447](https://github.com/vegaprotocol/pennant/issues/447)) ([69ac677](https://github.com/vegaprotocol/pennant/commit/69ac67794fc1f7ae6ff19a53f35db1686e22e01a))
* use true black for background ([#448](https://github.com/vegaprotocol/pennant/issues/448)) ([852b9ff](https://github.com/vegaprotocol/pennant/commit/852b9ffb884870e9c6b4e7e9295c22eaddc8cc54))
* support multiple studies ([#438](https://github.com/vegaprotocol/pennant/issues/438)) ([e52dcb0](https://github.com/vegaprotocol/pennant/commit/e52dcb0fe022d180982e81f305535c74a72eb81b))
* separate loading and initializing states ([#436](https://github.com/vegaprotocol/pennant/issues/436)) ([4714ed8](https://github.com/vegaprotocol/pennant/commit/4714ed84f0ab3f9655bfdafb45faeeb3555c15b0))
=> chore(deps): update dependency pennant to v0.4.7

apps/trading-e2e/src/integration/markets-page.feature, apps/trading-e2e/src/support/pages/trading-page.ts, apps/trading-e2e/src/support/step_definitions/markets-page.step.ts, apps/trading-e2e/src/support/trading-windows/accounts-list.ts
Add test to validate accounts list 
Currently it's using the test wallet that has tEuro deposited into it. Might require it to be manually topped up if testnet gets restarted. 
Hopefully this won't be needed with Capsule
Related to #185
=> Test for accounts

apps/stats/.fleek.json, apps/stats/project.json
Subresource Integrity breaks CSS for stats
Disabling the NX build option for SRI means the CSS loads correctly. We want SRI, but
having the stats page working is more important. This PR disables SRI. A followup ticket
will be created to work out what was wrong.
- Disable SRI in stats build
- Update fleek build command to match other projects
=> Disable SRI for stats

libs/tailwindcss-config/src/vega-custom-classes.js
Closes #415 
Block Explorer syntax highlighter previously had a green text colour when using the dark theme. The vega colours in theme.js had a name change and this component was refactored incorrectly.
Before fix:
After fix:
=> fix/415 Explorer syntax highlighter text colour broken

apps/token/src/lib/type-policies/proposal.spec.tsx, apps/token/src/lib/type-policies/proposal.ts, apps/token/src/routes/governance/__generated__/ProposalFields.ts, apps/token/src/routes/governance/components/proposal/proposal.tsx, apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx, apps/token/src/routes/governance/proposal-fragment.ts, apps/token/src/routes/governance/proposal/__generated__/Proposal.ts, apps/token/src/routes/governance/proposals/__generated__/Proposals.ts, apps/token/src/routes/governance/test-helpers/generate-proposals.ts, apps/token/src/routes/rewards/home/__generated__/Rewards.ts
Closes #[405](https://github.com/vegaprotocol/frontend-monorepo/issues/405)
Change freeform params to use the rationale field from Proposals.
on STAGNET2:
- following the same as in https://github.com/vegaprotocol/token-frontend/pull/1290
=> Fix/Use the rationale field on Proposals

apps/token-e2e/src/integration/app.test.ts
There is a failing test for token app where the test times out before the page is finished loading. The long load times are not reproducible locally. Timeout is increased to give the page more time to load in CI.
=> test: increase timeout for token test

apps/explorer/src/app/routes/network-parameters/network-parameters.tsx
N/A
Number of decimals for numbers that are in Vega tokens is incorrect in network parameters
N/A
=> fix: correct decimal places in network params table

.gitignore, README.md, apps/trading-e2e/cypress.json, apps/trading-e2e/src/integration/deposits.feature, apps/trading-e2e/src/support/mocks/generate-accounts.ts, apps/trading-e2e/src/support/mocks/generate-orders.ts, apps/trading-e2e/src/support/mocks/generate-positions.ts, apps/trading-e2e/src/support/step_definitions/deposits.step.ts, apps/trading-e2e/src/support/step_definitions/vega-wallet.step.ts, libs/cypress/src/lib/eip1193-bridge.ts
Closes #422 
- Updated Readme to allow people to run Cypress tests locally for the trading app
- Changed Cypress variable so it's easier to use different test wallet
- Added git ignore for local env file
- Added `cypress.env.json` file to 1Password so test team can run tests with shared secrets
- Tests passing locally with above file
=> chore: update readme and allow env file for local variables

apps/explorer-e2e/src/integration/network-page.feature, apps/explorer-e2e/src/support/pages/network-page.ts, apps/explorer-e2e/src/support/step_definitions/network-page.step.ts
Closes #300
Small update to existing Cypress test for network parameters table to check that every field is displayed and not empty
Deleted some tests that were basically doing the same thing as existing test
=> test: update test for network parameters table (#300)

apps/trading/pages/_app.page.tsx, libs/ui-toolkit/src/components/toggle/toggle.tsx
Closes #429 
Fixes z-index.
before:
after:
Scopes the app screen, so the z-indexes defined are not able to affect the dialogs, and other root level elements, portals, etc.
=> Fix/429: app zindex

libs/market-list/src/lib/components/__generated__/index.ts, libs/market-list/src/lib/components/landing/landing-dialog.tsx, libs/market-list/src/lib/components/landing/select-market-list.tsx, libs/market-list/src/lib/components/markets-container/__generated__/MarketDataFields.ts, libs/market-list/src/lib/components/markets-container/__generated__/MarketDataSub.ts, libs/market-list/src/lib/components/markets-container/__generated__/MarketList.ts, libs/market-list/src/lib/components/markets-container/__generated__/Markets.ts, libs/market-list/src/lib/components/markets-container/markets-data-provider.ts, libs/market-list/src/lib/utils/market-list.utils.spec.tsx, libs/market-list/src/lib/utils/market-list.utils.ts
Closes [#448]
When a user first visits the platform, the intention is to get them straight into the trading environment and allow them to see the app as soon as they land - but we also want them to select their preferred market before getting stuck in.
=> fix: [#448] use markPrice if there is no candle last

apps/simple-trading-app/src/app/components/portfolio/index.ts, apps/simple-trading-app/src/app/components/portfolio/portfolio.tsx, apps/simple-trading-app/src/app/routes/router-config.tsx
Closes #340 
Added a temporary component to the portfolio screen of console-lite to display a wallets assets
N/A
=> feat(console-lite): add portfolio screen and accounts container

apps/trading/pages/index.page.tsx, libs/market-list/src/lib/components/landing/landing-dialog.tsx, libs/market-list/src/lib/components/landing/select-market-list.tsx
Closes [#445]
When a user first visits the platform, the intention is to get them straight into the trading environment and allow them to see the app as soon as they land - but we also want them to select their preferred market before getting stuck in.
The default market in the overlay is the oldest market traded in continuous mode.
We want the route to reflect that.
=> fix: [#445] shallow routing from index

apps/simple-trading-app/src/app/components/deal-ticket/deal-ticket-container.tsx, apps/simple-trading-app/src/app/components/deal-ticket/deal-ticket-steps.tsx, apps/simple-trading-app/src/app/components/simple-market-list/simple-market-list.spec.tsx, apps/simple-trading-app/src/app/components/simple-market-list/simple-market-list.tsx, apps/simple-trading-app/src/app/routes/router-config.tsx, apps/trading-e2e/src/support/mocks/generate-deal-ticket-query.ts, libs/deal-ticket/src/__generated__/DealTicketQuery.ts, libs/deal-ticket/src/components/deal-ticket-container.tsx
Closes #446 
Allows the navigation from the market page to the making a trade page. Displays the name in the stepper component.
- Added a new field to the DEAL_TICKET_QUERY in DealTicketContainer
- Ran `nx run types:generate`
=> feat(console-lite): enabling navigation from market to trade

apps/simple-trading-app/src/app/components/deal-ticket/__generated__/PartyBalanceQuery.ts, apps/simple-trading-app/src/app/components/deal-ticket/deal-ticket-balance.tsx, apps/simple-trading-app/src/app/components/deal-ticket/deal-ticket-container.tsx, apps/simple-trading-app/src/app/hooks/use-settlement-account.spec.tsx, apps/simple-trading-app/src/app/hooks/use-settlement-account.ts, apps/trading-e2e/src/support/mocks/generate-deal-ticket-query.ts, libs/deal-ticket/src/__generated__/DealTicketQuery.ts, libs/deal-ticket/src/components/deal-ticket-container.tsx, libs/market-depth/src/lib/__generated__/MarketDepthSubscription.ts
Closes #343 
Displays balance of settlement asset for the selected key and trade
- Added useSettlementBalance Hook and Spec
- Added new fields to query for DealTicketQuery
- Created local DealTicketBalance component
- Regenerated types
- Added PartyBalanceQuery to local DealTicketContainer
=> feat(console-lite): add trade balance component and hook

.github/workflows/process-tranches.yml
Part of https://github.com/vegaprotocol/token-frontend/issues/1295
Updates tranche query processing to occur every 30 mins rather than once a day in order to keep the token website more up to date
=> chore: process tranches workflow cron update to 30 mins

package.json, yarn.lock
Closes #260
We were seeing a blue area on the candlestick chart (where the y-axis is rendered). This was due to a bug in pennant which would only support 6 character hex color codes and not the 3 character shorthand codes.
The bug only appears when running the built version of the trading app. As part of the build css color codes are optimised to their shortest representation. In particular, #ffffff -> #fff which pennant was interpreting as #000fff.
The relevant pennant commit is: https://github.com/vegaprotocol/pennant/commit/2342be2c89a6b1a59b30fc66cb9188b28e7879b3
=> chore(deps): update pennant to v0.4.11

apps/token/src/routes/governance/proposals/proposals-container.tsx
Workaround for #641, ignores request errors, which allows us to render the page again
Due to an API issue in the GraphQL API, the proposals request contains an error if a market update proposal is rejected
because the proposer had insufficient stake. This errorPolicy change allows the page to render again, which is more
useful.
This should be reverted when https://github.com/vegaprotocol/data-node/issues/740 is fixed
=> chore: workaround for #641 - ignoreErrors on governance page

libs/ui-toolkit/src/utils/intent.tsx
Closes #652
The lozenge colours were broken through a merge conflict resolution. We needed dark text added onto the default intent for a lozenge (because it has a white background on dark mode)
=> Fix/652: Broken lozenge dark mode text class

apps/explorer/src/app/components/nav/index.tsx
=> Feat/680: Bring explorer nav colours in line with light theme

libs/tailwindcss-config/src/vega-custom-classes.js
=> Fix/678: Text colour for syntax highlighter light theme

apps/token/src/routes/contracts/index.tsx, apps/token/src/routes/home/token-details/token-details.tsx, libs/web3/src/lib/transaction-dialog/dialog-rows.tsx
N/A
Noticed Etherscan links were opening in same tab and not new tabs. Fix this.
=> fix: etherscan links not opening in new tabs sometimes

.github/workflows/capsule-cypress-nightly.yml, .github/workflows/capsule-cypress.yml
Part of https://github.com/vegaprotocol/devops-infra/issues/1426
GOPROXY is no longer needed after we made repositories publicly available.
Checks in this PR
Nothing extra
=> chore: remove GOPROXY

apps/trading-e2e/src/integration/markets.cy.ts, apps/trading-e2e/src/integration/portfolio-fills.cy.ts, apps/trading-e2e/src/support/mocks/generate-fills.ts, apps/trading/.env, apps/trading/.env.testnet, libs/fills/src/lib/__generated__/Fills.ts, libs/fills/src/lib/fills-data-provider.ts, libs/fills/src/lib/fills-manager.tsx, libs/fills/src/lib/fills-table.stories.tsx, libs/fills/src/lib/test-helpers.ts, libs/types/src/__generated__/globalTypes.ts
Closes N/A
This fixes the fills table
N/A
Query changed from `tradesPaged` to `tradesConnection`. But also some needed to re-add some fields which got removed but are required to calculate various fields in the table. Namely the fee fields/agressor and settlementAsset
=> fix: rename tradesPaged to tradesConnection

libs/market-depth/src/lib/depth-chart.tsx
Closes #774 
The order of the buy side price levels for the depth chart were not sorted correctly leading to visual artefacts.
The buy side data from the API is sorted in decreasing price and the sell side in increasing price. This is also what the Depth Chart component from pennant requires. I have modified a function to take a boolean `reverse` argument to handle the two different sort orders.
=> Fix/774 Insert buy side depth updates correctly

libs/react-helpers/src/lib/grid/cumulative-vol-cell.tsx, libs/react-helpers/src/lib/grid/vol-cell.tsx
Closes #297
Improve orderbook colours in light theme - make bars 40% opacity
=> feat(#297): use 40% opacity colors in white themed orderbook

libs/ui-toolkit/src/components/sparkline/sparkline.tsx
Closes #834 
Adds a class to the svg path element to avoid scaling the stroke width.
See issue for screenshots.
I also fixed passing undefined as a class to the svg element.
=> fix: apply vector-effect: non-scaling-stroke to svg path element

libs/wallet/src/manage-dialog/manage-dialog.tsx
Closes #853 
Show full vega wallet key in Manage dialog when it fits on the screen, and truncate for smaller screens.
=> chore: show full vega wallet key for large screen

apps/explorer/src/app/routes/governance/index.tsx, apps/explorer/src/app/routes/router-config.tsx
Closes #863
Aligns menu and page title with desired 'governance proposals' title
=> Feat/863 Explorer: "Proposals" should say "Governance proposals"

libs/ui-toolkit/src/components/theme-switcher/theme-switcher.tsx
Closes #836
Theme switcher light toggle had white text showing on white background, needed to be black text.
=> Fix/836: Theme switcher - light toggle had wrong text colour

libs/network-info/src/network-info.tsx
Closes #829
The git info urls (i.e. 'https://ropsten.infura.io/v3/4f846e79e13f44d1b51bbd7ed9edefb8') were unable to word-break and so broke the mobile width in Explorer. I added the tailwind class of 'break-all' to allow that url to wrap at any point so the layout is preserved.
=> Fix/829: Git info word length broke responsiveness

apps/token/src/routes/staking/node-list.tsx
Closes #898
If a validator avatarUrl was broken, browsers would handle the broken image tag poorly (and inconsistently between browsers). This fix hides the image in that state.
Simply an onError prop on the image tag, which sets the display property to 'none'.
=> Fix/898: Avatar images now only displaying if avatarUrl is valid

apps/token/src/routes/redemption/home/vesting-table.tsx
Ad hoc little design issue
The broder for the all tranches summary was not white but for individual tranches it was. This PR makes all the borders white.
=> fix: border colour wrong for tranches overview

apps/token/src/routes/staking/node-list.tsx
Closes #900
Validator list pending stake was previously unformatted. This formatting now brings it inline with current stake.
=> Fix/900: Validator list - pending stake formatted as per current stake

apps/explorer/src/app/components/jump-to-block/index.tsx, apps/explorer/src/app/components/jump-to/index.tsx
Closes #687
The Explorer 'jump to block' component was previously accepting negative numbers or 0, which never correlate to a block number. This fix sets the minimum range of the input to 1. 
Provided a way to set both min and max attributes for the 'JumpTo' component
=> Fix/687: Jump to block input should not allow negative block numbers or 0

apps/token/src/components/splash-loader/splash-loader.tsx, apps/trading/pages/_app.page.tsx, libs/ui-toolkit/src/components/splash/splash.tsx
N/A
Fixes display of sun/moon icon now that nav is always dark. Removes text color class on splash and sets it on token specific component.
=> fix: text and theme icon colors

libs/environment/src/components/node-switcher/node-switcher.tsx, libs/environment/src/utils/validate-node.tsx
Fix for #856 (the rest of the points raised on the issue require clarification)
Fixes no 3 from the original issue: "Input fake url and click check twice freezes the modal with the user unable to do anything else"
Disables the clicking the check link while the checks are running for the custom node
=> fix: make check link unclickable while loading

apps/token/src/routes/staking/node-list.tsx
Closes #904
Validators columns were sorting alphanumerically. This changes them to sort numerically. It also fixes the broken default sort.
=> Fix/904: Validators sorting

libs/market-depth/src/lib/orderbook.tsx
Closes #790
Moves "pt-4" classname from main orderbook container to the labels'
=> fix(790): gap between orderbook headers and tabs

apps/token/src/assets/env-config.js, apps/token/src/polyfills.ts, package.json, yarn.lock
Closes #919
Bug was caused by a `global` and not `globalThis` reference in `@walletconnect/socket-transport/dist/esm/index.js`. That's why there's a dirty `global = globalThis` added to the `polyfills.js`
Fixing `global` issue revealed another with missing `Buffer` - *webpack@5+* doesn't include node's polyfills anymore hence I needed to add it manually to the `polyfills.ts`.
=> fix: walletconnect does not work

apps/token/src/components/web3-connector/web3-connector.tsx, apps/token/src/contexts/contracts/contracts-provider.tsx
N/A bug noticed when testing release
Fix intermittent errors with interacting with Ethereum
The async use effect was sometimes resolving in the incorrect order, creating a race condition. There is a hack fix here with a todo that cancels it. We should find a better way of doing this in future however I do not want this to push the release out by a further week so on balance I thought it best to go for the hacky fix now and look into a better solution later.
=> fix: provider sometimes not having signer

libs/market-depth/src/lib/orderbook-manager.tsx
Closes #945 
Solves the first error regarding the orderbook memory leak.
The second leak (ag-grid) is apparently solved by just [updating to react 18](https://github.com/vegaprotocol/frontend-monorepo/pull/952/files), tried it out on that branch, and couldn't reproduce it anymore)
After cancelling the throttle on unmount, wasn't able to reproduce the orderbook leak anymore.
Had a look, and the
=> Fix/945: Orderbook memory leak

libs/wallet/src/wallet-types.ts
Closes #980
Adds validationTimestamp as a required field for new asset proposals
=> Feat/980: New Asset proposals should require validationTimestamp

libs/ui-toolkit/.storybook/preview.js
Closes #589
Reimplements a theme switcher in storybook, with the following:
* Toggle between light, dark and side-by-side modes (dark set as default)
* Dark theme is implemented with a 'dark' class added to the body tag, so modals get correct dark styling (note: this doesn't work with the side-by-side view, which is why dark theme is default)
* Components can override the default theme by providing their own theme parameters in their export like so: `parameters: { theme: 'sideBySide' }`
=> Feat/589: Reimplement theme switcher in storybook

nx.json
Fix NX dependency mapping with this one simple trick (the nx npmScope did not match the path we used to declare deps). This seemed to cause subtle build failures when building from a clean source.
Run the following on `master`:
```bash
rm -rf node_modules && nvm install 16.14.0 && yarn && SKIP_NX_CACHE=true ./node_modules/.bin/nx run token:build:production --source-map=false --skip-nx-cache && cd dist/apps/token && python3 -m http.server 8001
```
and you'll see that it's nearly right, but all the buttons render incorrectly. It seems like `react-helpers` wasn't being built in time, always. Apply the fix, re-run, and it will all work.
Unblocks #596, #597
=> fix: unbreak nx dependency mapping

apps/token/src/hooks/use-search-params.ts, apps/token/src/routes/staking/associate/associate-page.tsx, apps/token/src/routes/staking/disassociate/disassociate-page-no-vega.tsx, apps/token/src/routes/staking/disassociate/disassociate-page.tsx, apps/token/src/routes/staking/staking-form.tsx
N/A
Claim page was broken due to useSearchParams hook bug resulting from stray :any type.
N/A
useSearchParams hook had an any type which resulted in incorrect usage. Hook has been adjusted to return a basic object of url search param keys and values.
Note, we should be using useParams from react-router but this was returning an empty object. This is a quick fix but we should come back and use the react-router provided hook if possible.
=> fix: token app useSearchParams

apps/trading-e2e/src/integration/market-info.cy.ts, libs/deal-ticket/src/components/info-market.tsx
Split settlement asset info out of Instrument section of Market Specification panel
Before:
After:
=> Chore: Split settlement asset into separate market info section

apps/explorer/src/app/routes/txs/id/tx-details.spec.tsx, apps/explorer/src/app/routes/txs/id/tx-details.tsx, libs/ui-toolkit/src/components/copy-with-tooltip/copy-with-tooltip.tsx
Closes #519
Adds a copy button to the transaction details page of explorer, letting a user copy the non-truncated tx to their clipboard. Makes use of the 'copy to clipboard' ui-toolkit component so the user gets a 'copied' tooltip when the button is clicked.
=> Feat/519: Add copy button to transaction content in explorer

apps/token/src/routes/rewards/home/__generated__/Rewards.ts, apps/token/src/routes/rewards/home/index.tsx, apps/token/src/routes/rewards/home/reward-info.tsx
Closes #956
Related to #930
Put back the reward types that were removed to facilitate the release of token from monorepo
=> feat: show correct reward type (#930)

apps/token/src/routes/staking/node-list.tsx
Workaround for https://github.com/vegaprotocol/vega/pull/5898 - 
- Ignore error in GraphQL query during epoch 0
=> Ignore epoch 0 error in node data

apps/explorer-e2e/src/integration/node-switcher.cy.js, apps/token-e2e/src/integration/flow/token-association-flow.cy.js
- Corrected the timeouts in the associate flow tests so they should be retrying correctly now
- Added extra assertion to stop node switch test failing from race condition
=> fix: correct timeouts for associate tests

apps/token/src/app.tsx
Closes #803 
Splash screen is now visible when network is loading or down (error).
Other error messages seem to be ok (see attached screenshots).
Initial splash screen:
Other error messages:
`color` wasn't defined becasue `AsyncRenderer` was outsite of anything definign styles.
=> fix: revealed splash screen informing about loading and error (803)

libs/ui-toolkit/src/components/tooltip/tooltip.tsx
Closes #1052 
Bumped up `z-index` of tooltip's content to `z-20` which is the same as for the dialogs.
doesn't break this:
=> fix: tooltip appears behind trigger (1052)

apps/trading/pages/markets/[marketId].page.tsx, libs/market-list/src/lib/components/select-market.tsx
- Fixes issue where un-memoized since timestamp being used as a variable would fire off a request every render and by the time the request finished the variable had changed causing a fresh request to be made.
- Also fixes the landing dialog only showing when the request for markets had finished. This led to a bad UX because the full page is shown and then a few seconds later the dialog pops up. Now the dialog immediately shows but with a loading state
https://user-images.githubusercontent.com/6803987/186046742-4ef9947e-cfc5-4168-ac5e-7de36fa0dca4.mp4
- Also adds a useMarkets hook to avoid duplication of market fetching logic
=> fix: market dialog query loop, and initial dialog render

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, .github/workflows/capsule-cypress.yml, apps/token-e2e/src/integration/view/staking.cy.js
Update Capsule to use the latest Core 0.54
- Temporary pull latest from Capsule and Vega repo in order to get green builds
- Follow-up with changing to use release tags when they are created
=> fix: update capsule to latest core

apps/token/src/routes/governance/components/proposal-terms-json/proposal-terms-json.tsx, apps/token/src/routes/governance/components/proposal/proposal.tsx, apps/token/src/routes/governance/proposal/proposal-container.tsx
Closes #1128
Ensures individual proposal pages are loading, based on the same data as the other proposal pages.
Individual proposal pages were built early on and relied on the REST endpoint to get the 'terms' data. Fairground was broken for individual proposals because it didn't have an `NX_VEGA_REST` env var, and was (possibly?) using a cached version which pointed at a borked node. The cleanest solution IMO was to remove the unnecessary REST reliance, instead using GQL fully, bringing everything in line.
=> Fix/1128: Individual proposal pages failing to load

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, apps/explorer-e2e/src/integration/node-switcher.cy.js
Alter node switcher test as connecting to SSL is returning NO. 
There's a schema change that is not rolled out to Testnet yet which also requires a fix on FE. Once that's done the test change can be reverted.
- Updated Go version in CI which was missed in last PR
=> chore: update test asserting SSL

libs/market-depth/src/lib/depth-chart.tsx
Closes #1134 
The formatter functions passed to the depth chart were not doing sensible things. I've replaced them with corrected versions.
=> fix: pass correct price and volume formatters to depth chart

apps/token/src/routes/governance/components/proposals-list-item/proposals-list-item-details.tsx
Closes #1152
Rejected proposal details pages incorrectly had '/rejected' in the url, this fix removes it.
=> Fix/1152: Rejected proposal details pages have wrong url

nx.json
Closes #1174. Replaces #1022. Closes #1120 
A previous issue with builds failing due to improper dependency mapping seemed to be fixed in #1022, but wasn't. This 
meant that builds could sometimes fail to build parts (css), or fail to take on environment variable updates. This PR
follows a suggestion over in the NX repo to add environment variables as cache inputs. It *seems* to work.
- Revert change to workspace name, back to 'vegaprotocol' from '@vegaprotocol'
- Add important NX_ environment variables as cache inputs
=> Add env vars as nx-cloud cache inputs

libs/positions/src/lib/positions-table.spec.tsx, libs/positions/src/lib/positions-table.tsx, libs/ui-toolkit/src/components/progress-bar/progress-bar.tsx
Changing colours used by the liquidation/margin visualisations in the positions panel.
Before:
After:
=> Chore: tweak position meter colours

libs/market-depth/src/lib/depth-chart-utils.spec.ts, libs/market-depth/src/lib/depth-chart-utils.ts, libs/market-depth/src/lib/depth-chart.tsx
Closes #1197
Adds unit tests and documentation for functions which parse and update price levels for the depth chart.
Replaces a floating point equality check with a more correct check for absolute difference being within a suitable tolerance.
=> 1197 improve depth chart price level data handling

.github/workflows/capsule-cypress.yml
Adds a condition to check if a PR is in draft before triggering the capsule build and test run. Once its changed to ready for review the run will be triggered
=> ci: check for draft pr for cypress test run

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml
N/A
Noticed after the merge of the config change PR, which changed where the capsule tests config was located. This only changed it for PR runs and not for all runs.
=> test: change config path for overnight run

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, .github/workflows/capsule-cypress.yml
Our pipeline is currently broken with any tests that use the Vegawallet failing. 
- Update workflow to pull from `0.54.0` instead of `develop`
=> Chore/use vega 0.54.0

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, .github/workflows/capsule-cypress.yml
Runners are stuck on queue right now. Revert back to previous runners
=> chore: revert back to using previous ubuntu runners

libs/positions/src/lib/positions-table.spec.tsx, libs/positions/src/lib/positions-table.tsx
Closes #1261
See ticket for a great description. If the market name did not fit what the regex expected,
it was possible to break the whole console for anyone with a position in a 'poorly' named
market.
- Improve market name split
The code naively assumed the market name would split as expected
=> Fix positions table handling of market name

apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/home.cy.ts, apps/trading-e2e/src/support/mocks/generate-deposit-page.ts
Closes #1108 
- Add test to check that non-enabled assets are not selectable in deposits
=> test: add test for filtering assets not enabled

apps/token/.env.capsule
NX_VEGA_ENV changed to CUSTOM in .env.capsule, to avoid network error popup when built locally
=> chore: env changed to custom

apps/trading-e2e/src/integration/markets.cy.ts, apps/trading/.env, apps/trading/components/footer/footer.tsx, apps/trading/components/header/header.tsx, apps/trading/components/icons/vega.tsx, apps/trading/components/navbar/navbar.tsx, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx, apps/trading/pages/markets/trade-grid.tsx, apps/trading/pages/styles.css, libs/environment/src/components/network-switcher/network-switcher.tsx, libs/market-depth/src/lib/orderbook.tsx, libs/market-info/src/components/market-info/info-market.tsx, libs/market-list/src/lib/components/select-market-columns.tsx, libs/market-list/src/lib/components/select-market-table.tsx, libs/market-list/src/lib/components/select-market.tsx, libs/orders/src/lib/components/order-list/order-edit-dialog.tsx, libs/positions/src/lib/positions.tsx, libs/ui-toolkit/src/components/button/button.tsx, libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.tsx, libs/ui-toolkit/src/components/popover/popover.tsx, libs/ui-toolkit/src/components/tabs/tabs.tsx
Follow up from https://github.com/vegaprotocol/frontend-monorepo/pull/1305.
- Removed some tailwind classes that were having no effect.
- Changed trade page to use the Header component.
- Adds custom class `border-default` for border colors so we dont have to repeat `border-neutral-300 dark:border-neutral-600` everywhere.
- Fixes theme switching in orderbook, borders that are rendered conditionally in JS where not using the theme context and therefor not changing value.
- Remove psuedo elements from tabs as they were skewing the text alignment
- Rename fixedBg prop to theme
=> chore: use trading header and tidy tailwind usage

libs/network-stats/src/components/stats-manager/__generated__/NetworkStats.ts, libs/network-stats/src/components/stats-manager/stats-manager.tsx, libs/network-stats/src/config/stats-fields.ts
Closes #1199 
Fixes the uptime pointing to the nodeData rather than statistics
N/A
- regenerated types
- querying upTime in stats instead of network node
=> fix(stats-manager): fix uptime pointing to incorrect field

apps/trading-e2e/src/support/mocks/generate-candles.ts, libs/candles-chart/src/lib/Candles.graphql, libs/candles-chart/src/lib/__generated__/Candles.ts, libs/candles-chart/src/lib/data-source.ts
Closes #1323 
Uses `timestamp` rather than `datetime` when querying for candles. The former is the time at which the candle occurred. The latter is the time the candle data was last updated.
The `timestamp` field represents the UNIX epoch in nanoseconds.
=> fix: use correct graphql candle timestamp field

apps/trading/.env.testnet
`.env.testnet` in trading was most probably outdated resulting with error during build. It's updated now.
=> chore: update trading testnet config

apps/console-lite/src/app/components/portfolio/accounts/accounts.tsx, apps/console-lite/src/app/components/portfolio/accounts/use-column-definitions.tsx, apps/trading-e2e/src/integration/global.cy.ts, apps/trading/pages/_app.page.tsx, apps/trading/pages/markets/[marketId].page.tsx, apps/trading/pages/markets/trade-grid.tsx, apps/trading/pages/portfolio/withdrawals-container.tsx, libs/accounts/src/lib/accounts-table.tsx, libs/assets/src/lib/Asset.graphql, libs/assets/src/lib/__generated___/Asset.ts, libs/assets/src/lib/asset-details-dialog.tsx, libs/deposits/src/lib/deposit-form.tsx, libs/market-list/src/lib/components/markets-container/market-list-table.tsx, libs/market-list/src/lib/components/select-market-columns.tsx, libs/market-list/src/lib/components/select-market-table.tsx, libs/market-list/src/lib/components/select-market.tsx, libs/ui-toolkit/src/components/dialog/dialog.tsx, libs/ui-toolkit/src/components/popover/popover.tsx
Closes #1226 
Added asset details dialog to market select making "Asset" column now clickable.
* added `onCloseAutoFocus` to dialog in order to make sure that focus goes back to the dialog's trigger
* added a handler for popover's `onInteractOutside` which's responsible for not closing itself when a dialog open from within
=> feat: added asset details dialog to market select (1226)

.github/workflows/capsule-cypress-manual-trigger.yml, .github/workflows/capsule-cypress-night-run.yml, .github/workflows/capsule-cypress.yml, .github/workflows/test.yml, apps/trading-e2e/src/integration/global.cy.ts
Two changes in workflows:
- cache node_modules and Cypress runner to be used in other runs, if yarn.lock is not changed
- Download specific binaries version of vega, vegawallet & data-nodes instead of building them each time
It should improve timing in PRs.
=> Chore/use cache in GitHub jobs

apps/trading-e2e/src/integration/home.cy.ts, apps/trading/pages/_app.page.tsx, apps/trading/pages/index.page.tsx, apps/trading/pages/markets/[marketId].page.tsx, apps/trading/pages/markets/index.page.tsx, apps/trading/pages/portfolio/deposit/index.page.tsx, apps/trading/pages/portfolio/index.page.tsx, apps/trading/stores/global.ts, libs/react-helpers/src/lib/format/strings.spec.ts, libs/react-helpers/src/lib/format/strings.ts
Closes #660 
It adds custom titles for "Markets", "Portfolio", "Deposits", "[marketId]" pages.
I've added `pageTitle` to the global store.
=> feat: page title (660)

apps/token/src/routes/governance/propose/freeform/propose-freeform.spec.tsx, apps/token/src/routes/governance/propose/network-parameter/propose-network-parameter.spec.tsx, apps/token/src/routes/governance/propose/new-asset/propose-new-asset.spec.tsx, apps/token/src/routes/governance/propose/new-market/propose-new-market.spec.tsx, apps/token/src/routes/governance/propose/update-market/propose-update-market.spec.tsx
Fixes query naming clash which was erroring during type generation
Query documents were being created in the test itself, so switched to use the export
=> fix: network params query name clash

apps/console-lite/src/app/components/header/header.tsx, apps/trading/components/header/header.tsx, apps/trading/components/navbar/navbar.tsx, libs/environment/src/components/network-switcher/network-switcher.tsx, libs/liquidity/src/lib/liquidity-table.spec.tsx, libs/ui-toolkit/src/components/theme-switcher/theme-switcher.tsx
- Fixes nextjs classname mismatch warning
- Adds dark class to nav to ensure correct styles are inherited and less classname logic and styles are required elsewherere
- Fix trading title alignment on small screens
- Fix broken liquidity table test
=> fix: classname mismatch warning by setting dark class for nav

apps/token/src/i18n/translations/dev.json, apps/token/src/routes/governance/components/proposal-change-table/proposal-change-table.spec.tsx, apps/token/src/routes/governance/components/proposal-change-table/proposal-change-table.tsx, apps/token/src/routes/governance/components/proposal-detail-header/proposal-header.tsx
Closes #1373, Closes #1374 
Hide enacted on freeform proposal details page as this does not exist anymore, generate a better title than just outputting the id which looked like an error
=> fix: hide enacted on proposal details page for freeform proposals

libs/market-list/src/lib/components/select-market.tsx
Makes 'my markets' and 'all markets' in the select market dropdown rendered within the same table element so that the cells align.
Before:
After:
=> fix: align market dropdown cells for both my markets and all markets

libs/governance/src/lib/proposals-hooks/use-proposal-event.ts, libs/governance/src/lib/proposals-hooks/use-proposal-submit.ts, libs/orders/src/lib/order-hooks/use-order-cancel.tsx, libs/orders/src/lib/order-hooks/use-order-edit.tsx, libs/orders/src/lib/order-hooks/use-order-event.ts, libs/orders/src/lib/order-hooks/use-order-submit.tsx, libs/positions/src/lib/use-close-position.ts, libs/positions/src/lib/use-position-event.ts, libs/withdraws/src/lib/use-create-withdraw.ts, libs/withdraws/src/lib/use-withdrawal-event.ts
Ensures that subscriptions started to track vega transactions are cancelled if the dialog is closed
=> fix: ensure sub is cancelled if dialog is closed

apps/trading-e2e/src/support/vega-wallet.ts, libs/market-depth/src/lib/orderbook.tsx, libs/market-depth/src/setup-tests.ts, libs/react-helpers/src/hooks/index.ts, libs/react-helpers/src/hooks/use-mutation-observer.ts, libs/react-helpers/src/hooks/use-resize-observer.ts
Closes #1251 
Closes #1262
1) The orderbook's header and footer are no longer sticky but positioned absolutely because when sticky they were sometimes painted outside of the container or jumping while scrolling or hiding 🥸.
2) The precision dropdown displays now all options from market's decimal places to zero. In the future we may also want to aggregate by 10s or 100s but we've decided with Dan to leave it for now.
https://user-images.githubusercontent.com/1980305/192805973-d109f950-a274-44ef-b1ce-56d613309ac7.mov
https://user-images.githubusercontent.com/1980305/192806535-4e038b92-5152-499c-b16d-b92fa274ea06.mov
https://user-images.githubusercontent.com/1980305/192830744-9f9cb994-5142-4577-815e-c9d444f86fa1.mov
Because of the scroll bar I needed to match the widths of the header and …
=> fix: orderbook sticky behaviour and precision options

package.json, yarn.lock
Closes #1556.
Updates the pennant chart library.
This brings in the following changes.
- sort depth chart data ([#600](https://github.com/vegaprotocol/pennant/issues/600)) ([1d98c3b](https://github.com/vegaprotocol/pennant/commit/1d98c3b142ce4b5bd4e6b71732edc44d84f5c24b))
- show sell side tooltip correctly in depth chart ([#601](https://github.com/vegaprotocol/pennant/issues/601)) ([08c2a30](https://github.com/vegaprotocol/pennant/commit/08c2a30861b8ff2292a8c3ebcfb4a722b2a83b3a))
- improve fill colors for depth chart ([18c28dd](https://github.com/vegaprotocol/pennant/commit/18c28dd2ddc9f4563107de9c1e49bd1119645449))
- better support for color customization ([#572](https://github.com/vegaprotocol/pennant/issues/572)) ([fdf041a](https://github.com/vegaprotocol/pennant/commit/fdf041adb6116e9e …
=> chore(deps): update dependency pennant to v0.4.18

apps/token/src/routes/staking/stake-success.tsx, apps/token/src/routes/staking/staking-form.tsx
Closes #1069
When unstaking if a transaction was rejected and incorrect message to the user stating that the unstake was successful was shown. This fixes that.
=> fix: do not show success state if user cancels tx

apps/explorer/src/app/components/header/header.spec.tsx, apps/explorer/src/app/components/search/detect-search.spec.ts, apps/explorer/src/app/components/search/detect-search.ts, apps/explorer/src/app/components/search/search.spec.tsx, apps/explorer/src/app/components/search/search.tsx
Closes #1411 
Enables party ids to be searched from the main search field on explorer
N/A
- Created detect search utility functions
- Created tests
- Refactored Search.tsx and unit tests
=> fix(explorer): add party to consolidated search

libs/assets/src/lib/asset-details-dialog.spec.tsx, libs/assets/src/lib/asset-details-dialog.tsx
Closes #1403
Use asset decimals to format withdraw limit and threshold. 
```
{
asset(id:"29287681e4d9a6457d02ded602f72002a50f25749c5edfe9e9a58241b8e97ebc"){
source{
...on ERC20{
contractAddress
}
}
decimals
}
}
```
=> fix: 1403 format with asset decimals withdrawal threshold and lifetime limit values

apps/trading/next.config.js
Configure assetPrefix for trading so that IPFS works with subfolder or subdomains
next.js builds static pages, and those static pages reference static assets as `/_next/...`, which works fine if the
site is served from a domain root (e.g. `console.fairground.wtf/`, `made-up-url.ipfs.io`) but breaks down on IPFS
gateways that are still configured to use subfolders (e.g. `ipfs.io/ipfs/made-up-url`). Luckily we can fix this by
using `assetPrefix` to turn `/_next/` in to `./_next/`, which works in both cases.
- Update next.js config for trading
Closes #1613
=> [trading] IPFS deploys do not work for subfolder gateways

apps/token/src/routes/withdrawals/index.tsx, apps/trading/pages/portfolio/withdrawals-container.tsx, libs/ui-toolkit/src/components/ag-grid/index.tsx, libs/withdraws/src/index.ts, libs/withdraws/src/lib/pending-withdrawals-table.spec.tsx, libs/withdraws/src/lib/pending-withdrawals-table.tsx, libs/withdraws/src/lib/use-withdrawals.ts, libs/withdraws/src/lib/withdrawals-table.spec.tsx, libs/withdraws/src/lib/withdrawals-table.tsx
Closes #849
Divided withdrawals into two tables; one for pending, second for the rest.
=> feat: updated withdrawal tab (849)

libs/orders/src/lib/components/order-list/order-list.spec.tsx, libs/orders/src/lib/components/order-list/order-list.tsx
Closes #1642 
Show in order 'type' column if orders are LP or pegged. 
=> fix: 1642 show in type column if order is pegged or LP

apps/trading/pages/_app.page.tsx
reverted because it got filtered out by `next/head`
=> fix: reverted custom page title element

libs/wallet/src/connectors/json-rpc-connector.ts, libs/wallet/src/connectors/rest-connector.ts
Closes #1605
When the wallet responded with an error due to pre-chain validation the error toast was not being shown correctly resulting in users not being able to see why their transaction failed.
In cases of errors from the wallet rest API we were returning null which indicates a user rejected transaction. This causes the form to reset preventing the error messages from showing.
=> fix: wallet errors incorrectly showing as user rejections

libs/market-depth/src/lib/orderbook-data.ts, libs/market-depth/src/lib/orderbook-manager.tsx, libs/market-depth/src/lib/orderbook-row.tsx, libs/market-depth/src/lib/orderbook.spec.tsx, libs/market-depth/src/lib/orderbook.tsx
Closes #1536
Closes #1151
- Remove zero volume rows from orderbook.
- Add option to enable zero volume rows
- Use only newest value per price level from delta 
- Infor console added for debugging purposes (show and hide on dblclick)
Optimized update in data provider by taking into consideration only last value at specific price level `uniqBy(sell?.reverse(), 'price')`
=> feat(#1536): remove zero volume rows from orderbook

apps/token/.env, apps/token/.env.capsule
Closes #1377
The documentation links were already present but because of the environment file changes meant that these were not being rendered.
=> fix: docs URL not showing up correctly

libs/accounts/src/lib/accounts-manager.spec.tsx, libs/accounts/src/lib/accounts-manager.tsx
Closes #1756 
Fix re-creating ag-grid instance after changes of dataProvider variables
Use `reload` method of `use-data-provider` hook
=> chore: accounts-table reload after partyId change

apps/trading-e2e/src/integration/withdraw.cy.ts, libs/deposits/src/lib/deposit-form.spec.tsx, libs/deposits/src/lib/deposit-form.tsx, libs/deposits/src/lib/deposit-limits.tsx, libs/react-helpers/src/lib/format/number.spec.tsx, libs/react-helpers/src/lib/format/number.tsx, libs/withdraws/src/lib/withdraw-form.tsx, libs/withdraws/src/lib/withdraw-limits.tsx
Closes #547
* added new `compactNumber` function which formats big numbers into the human readable form, e.g 123,000,000,000 -> 123B or 123 billion
* changed deposit and withdrawal limits `<table>` into `<KeyValueTable>`
=> chore: format limits (547)

apps/console-lite/src/app/components/portfolio/positions/use-column-definitions.tsx, apps/trading-e2e/src/integration/trading-positions.cy.ts, libs/positions/src/lib/positions-data-providers.ts, libs/positions/src/lib/positions-manager.tsx, libs/positions/src/lib/positions-table.spec.tsx, libs/positions/src/lib/positions-table.tsx, libs/positions/src/lib/use-positions-data.tsx
Closes #1645
* Render a single data grid that fills the positions panel, with all positions not aggregated by asset
* Add settlement asset column
* Split size cell into notional and open volume columns
* Split entry price and liquidation price into separate columns, progress bar can be displayed in liquidation price column
* Margin allocated cell to use single actual value (not percentage)
* Total value across positions gets removed
=> chore: single position table (1645)

apps/console-lite/src/app/components/portfolio/accounts/accounts.tsx, libs/accounts/src/lib/accounts-manager.tsx, libs/fills/src/lib/use-fills-list.ts, libs/orders/src/lib/components/order-list-manager/use-order-list-data.ts, libs/positions/src/lib/use-positions-data.tsx, libs/trades/src/lib/trades-container.tsx
Sometimes ag-grid has undefined api. To address that issue optional chaining is used.
=> chore: use optional chaining for ag-grid api

libs/network-stats/src/components/stats-manager/__generated__/NetworkStats.ts, libs/network-stats/src/components/stats-manager/stats-manager.tsx, libs/network-stats/src/config/stats-fields.ts
Closes #1780 
Cherry picked commit to reference the genesisTime field instead of uptime
N/A
N/A
=> fix(explorer): fix uptime to reference genesisTime field

libs/react-helpers/src/lib/format/number.tsx
=> fix: do no allow min or max fraction digits to go out of range (#1806)

apps/trading-e2e/src/integration/market-summary.cy.ts, apps/trading/pages/portfolio/index.page.tsx
- Fix e2e tests
- Removes redundant positions title above table. Allow table to fill space
=> chore: fix market summary tests and remove positions title

libs/market-info/src/components/market-info/info-key-value-table.tsx, libs/market-info/src/components/market-info/info-market.tsx, libs/orders/src/lib/components/order-list/order-list.tsx
=> fix: 1863 market info reference price should be formatted with asset dp

apps/token/src/i18n/translations/dev.json, apps/token/src/routes/governance/components/shared/proposal-min-requirements.tsx, apps/token/src/routes/governance/propose/new-asset/propose-new-asset.spec.tsx, apps/token/src/routes/governance/propose/raw/proposal-raw-min-requirements.tsx, apps/token/src/routes/governance/propose/raw/proposal-raw.spec.tsx, apps/token/src/routes/governance/propose/raw/propose-raw.tsx
Closes #1666
Based on network params, the raw proposal form will now show either:
The spam protection min requirement amount if it's greater than any proposal min amount ||
A single min requirement amount if the proposal min amounts match and are greater than spam protection min ||
A table detailing required amounts for the proposal types and spam protection
=> Feat/1666: Added min requirements for raw proposal form. Tests failing

apps/token/src/routes/governance/hooks/use-vote-information.spec.ts, apps/token/src/routes/governance/hooks/use-vote-information.ts
Closes #1766
The decimals were not added to the totalYes and totalNo tokens amounts, causing the calculations to become incorrect. Add these in appropriately.
=> fix: token and percentage amounts in vote information

libs/wallet/src/connect-dialog/connect-dialog-elements.tsx, libs/wallet/src/connect-dialog/connect-dialog.tsx, libs/wallet/src/constants.ts
N/A
Updates 'Get a wallet' links in wallet UI to go to vega.xyz/wallet rather than the github releases page
=> chore: update wallet link in wallet UI

libs/withdraws/src/lib/withdraw-form.tsx
Closes #1639
`Use connected` button to populate ETH address in withdrawal dialog. 
=> Fix/1639 use connected button to populate ETH address in withdraw dialog

.github/workflows/cypress-console-lite-e2e.yml, .github/workflows/cypress-explorer-e2e.yml, .github/workflows/cypress-liquidity-provision-dashboard-e2e.yml, .github/workflows/cypress-stats-e2e.yml, .github/workflows/cypress-token-e2e.yml, .github/workflows/cypress-trading-e2e.yml
#1897 
Create separate workflows to run tests for each app.
They are triggered on `workflow_call`. They need to merged before actually using them, to make them available for tests on other branches.
=> test: add separate workflows for each app

apps/liquidity-provision-dashboard/src/app/components/detail/detail.tsx, apps/liquidity-provision-dashboard/src/app/components/detail/providers/providers.tsx
Part of #1355(https://github.com/vegaprotocol/frontend-monorepo/issues/1355)
Replaces the (empty) `GALPS` field with `Equity-like share`, and provides values for this from the aggregated liquidity provider data.
Screenshot of new column with value:
Refactors `apps/liquidity-provision-dashboard/src/app/components/detail/detail.tsx` to use `lpAggregatedDataProvider` rather than `liquidityProvisionsDataProvider` which includes both the currently required values plus the necessary data to introduce Equity-like share.
=> feat(1355): lp dashboard adding equity like share

apps/console-lite-e2e/.env, libs/deal-ticket/src/hooks/use-order-margin.spec.ts, libs/deal-ticket/src/hooks/use-order-margin.ts
Closes #2002
Estimate order query will simply need the order size and price from the user input.
=> fix: use estimate order query with simple order size, no open volume check

.github/actions/install-vega-binaries/action.yml, .github/actions/setup-vegawallet/action.yml, .github/workflows/cypress-console-lite-e2e.yml, .github/workflows/cypress-explorer-e2e.yml, .github/workflows/cypress-token-e2e.yml, .github/workflows/cypress-trading-e2e.yml, README.md
Closes #1892 
This is a prerequisite for using vegawallet v2 in our e2e tests. In normal usage condition vegawallet v2 requires interaction with CLI when making wallet-related actions in dApps. Vegawallet-dummy sorts that out, so e2e tests can be run smoothly. More information - https://github.com/vegaprotocol/vegawallet-dummy
=> test: use vegawallet dummy in e2e test workflows

apps/trading/client-pages/liquidity/liquidity.tsx, libs/deal-ticket/src/components/trading-mode-tooltip/compile-grid-data.tsx, libs/liquidity/src/lib/liquidity-data-provider.ts, libs/liquidity/src/lib/liquidity-table.tsx
Closes #2063 
Liquidity provision entries are unique for any partyId and marketId only if the status is not rejected. 
=> fix(#2063): console liquidity tab keeps adding duplicate rows

apps/trading-e2e/src/integration/market-info.cy.ts, libs/market-info/src/components/market-info/info-market.tsx, libs/react-helpers/src/lib/links/links.ts
Closes #580
Add link to update market proposal
=> feat(#580): add link to update market proposal

apps/trading-e2e/.env, apps/trading-e2e/src/integration/market-summary.cy.ts, apps/trading/.env, apps/trading/.env.devnet, apps/trading/.env.mainnet, apps/trading/.env.stagnet1, apps/trading/.env.stagnet3, apps/trading/.env.testnet
`VEGA_DOCS_URL` was missing in `trading` `.env`s.
=> chore: add vega_docs_url to all trading envs

libs/market-depth/src/lib/depth-chart.tsx
Closes #1883.
The depth chart in the trading app now updates as new data arrives.
I'm not proposing this as the paragon of code clarity but simply as one option to get the component working.
I've replaced a ref representing a throttled function with a memoized function. What I think was happening was that the ref captured the value of `market` when initialised. In particular it captured the value before `market` had a useful value. This lead to the function never doing anything as it returned early due to `!market` evaluating to `true`.
I also changed the meaning of an if condition later on in the file. This may or may not be correct but it looked suspicious to my eyes.
=> fix(#1883): fix depth chart not updating

.github/actions/setup-vegawallet-docker/action.yml, .github/actions/setup-vegawallet/action.yml, .github/workflows/cypress-console-lite-e2e.yml, .github/workflows/cypress-explorer-e2e.yml, .github/workflows/cypress-token-e2e.yml, .github/workflows/cypress-trading-e2e.yml, vegacapsule/config.hcl, vegacapsule/recovery, vegacapsule/wallet-config.toml
Vegawallet needs to be started separately, not in vegacapsule network bootstrap process, in order to use dummy wallet correctly.
=> chore: separate running vegawallet service out of vegacapsule

apps/explorer-e2e/.cypress-cucumber-preprocessorrc, apps/explorer-e2e/src/integration/parties.cy.js
Closes #2060 
Import is being done before the tests starts in workflow. It's not needed to be run in the test itself anymore.
=> chore: remove unnecessary import vega wallet

libs/wallet/src/connectors/json-rpc-connector.ts, libs/wallet/src/vega-transaction-dialog/vega-transaction-dialog.tsx
Allows an error returned by the wallet to be render to the UI, rather than just showing 'Something went wrong'
=> fix: allow error message data from wallet to be displayed

libs/liquidity/src/lib/liquidity-table.spec.tsx, libs/liquidity/src/lib/liquidity-table.tsx
Closes #2151 
Update tooltips on LP table and rename market valuation entry.
=> chore(#2151): rename market valuation entry and change tooltips on LP table

.github/actions/setup-vegawallet/action.yml
Tests are failing setting up vegawallet because the stagnet3 toml url is no longer valid
=> chore(test-fix): update toml url

apps/liquidity-provision-dashboard/src/app/components/dashboard/market-list/market-list.tsx, apps/liquidity-provision-dashboard/src/app/components/detail/providers/providers.tsx, apps/liquidity-provision-dashboard/src/app/components/status/status.tsx
Closes #1358
Introduces Tooltips for column headings on the LP dashboard - both the Market overview/list page and Details pages, and for the `Status` data cell. 
Adds a few new datapoint columns to the market overview page - `Target Stake`, `% Target Stake Met` and `Fee Levels`.
Tooltips:
New columns:
=> feat: add tooltips to headers on the LP dashboard and add some new data points

apps/explorer/src/app/routes/assets/__generated__/assets.ts, apps/explorer/src/app/routes/assets/assets.graphql, apps/explorer/src/app/routes/assets/index.tsx
Closes #2076
Use getNodes helper to avoid having to dig edges { node { out of v2 graphql query
=> fix(explorer): use getnodes to avoid nesting

libs/apollo-client/src/lib/apollo-client.ts, libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx, libs/fills/src/lib/fills-manager.tsx, libs/positions/src/lib/positions-manager.tsx, libs/react-helpers/src/hooks/use-data-provider.ts, libs/ui-toolkit/src/components/async-renderer/async-renderer.tsx, libs/ui-toolkit/src/components/splash/splash.tsx
Closes #2200 
Handles this issue observed in empty stagnet3:
=> fix(#2200): handle NotFound GraphQL errors in async renderer

apps/explorer/.env, apps/explorer/.env.stagnet3
Closes #2192
Fixes some dead URLs in the default .env, just in case any .env.stagnet3 config variables were falling through to .env
=> fix(explorer): remove old urls from default env

apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx, apps/explorer/src/app/routes/blocks/home/index.tsx, apps/explorer/src/app/routes/blocks/id/block.tsx
Closes #2236
Forces no caching of list of blocks (which was preventing some envs from updating the block list page), and forces
caching of block by ID to avoid refetches.
=> fix(explorer): avoid caching block list, cache block by id

apps/trading/client-pages/market/trade-grid.tsx, libs/ui-toolkit/src/components/splash/splash.tsx
N/A
- Fix color of no data message when in light theme
- Add connect button for vega wallet
Before:
After:
=> fix: text color of no data message, add connect buttons to trade grid

apps/trading-e2e/src/integration/market-info.cy.ts, libs/market-info/src/components/market-info/info-market.tsx, libs/market-info/src/components/market-info/tooltip-mapping.tsx
Closes #2239 
Add decimal places in key details in market info
=> feat(#2239): add decimal places in key details in market info

.github/workflows/capsule-cypress.yml
Tests are currently not running on PR. 
This fixes the workflow to correctly trigger tags used by tests
=> chore: fix workflow

libs/withdraws/src/lib/use-create-withdraw.spec.tsx, libs/withdraws/src/lib/use-withdrawal-event.ts
Closes #2283 
Changes to use the correct graphql document for the withdrawal event subscription
=> fix(#2283): use correct GQL document for withdrawal event subscription

apps/token/src/routes/rewards/home/reward-info.tsx
Closes #2293
Was always showing Vega as the reward paid out when in fact it could be any currency.
=> fix: show correct asset in rewards table

apps/liquidity-provision-dashboard/src/app/components/dashboard/market-list/market-list.tsx
Part of  #2190
Replace links to the lp-dashboard details page with links to the Console liquidity page for a market. This already has a bunch of the information we're trying to display.
https://www.loom.com/share/21c744227eab420db23772b7d25d71df
I'm re-using the `useLinks` hook from the environment library, which was super useful.
=> feat(#2190): replace lp dashboard details links with console links 

apps/trading/pages/_app.page.tsx, apps/trading/pages/_document.page.tsx
Updates _document.tsx to use .page.tsx naming convention so its actually picked up. These means we can move font links and scripts out of _app
=> chore: update document page to use page extension

apps/trading/components/app-loader/index.tsx, libs/environment/src/utils/request-node.ts
On console a blank page gets rendered if the start up subscription to determine node suitability never receives a message. This is fixed by ensuring the node switcher dialog is opened if the initial subscription takes longer than 3 seconds. 
- Added setTimeout in requestNode
- Added a "Loading..." message as some fallback UI for the NetworkLoader
=> fix: blank page if startup subscription fails

apps/liquidity-provision-dashboard/src/app/components/dashboard/market-list/market-list.tsx
Part of #2206 
Adds some more data columns to the LP dashboard:
* last/mark price
* 24h price change
* market type
* market code
Changed the title for liquidity committed from 'committed bond' to 'Total staked by LPs'
Re-using `<PriceCellChange>` for the 24h price change
=> feat: add more data columns to lp dashboard

libs/wallet/src/use-json-rpc-connect.ts
In case the network is down, wallet is not able to check for chainID and returns the error. We had similar case before, and we solved that by skipping chainID verification. As the error about chainID is coming now from wallet, I skipped wallet chainID request as well.
=> chore: remove chainID request to wallet in e2e

apps/trading/client-pages/liquidity/liquidity.tsx, apps/trading/client-pages/market/trade-grid.tsx, apps/trading/components/header/header.tsx
Closes #2307 
Make the liquidity provision table more prominent (add another tab)
=> feat(#2307): make liquidity provision table more prominent

apps/trading-e2e/src/integration/trading-orders.cy.ts, apps/trading/client-pages/market/trade-grid.tsx, libs/candles-chart/src/lib/candles-chart.tsx, libs/fills/src/lib/fills-container.tsx, libs/fills/src/lib/fills-manager.tsx, libs/fills/src/lib/use-fills-list.ts, libs/liquidity/src/lib/liquidity-table.tsx, libs/orders/src/lib/components/order-data-provider/Orders.graphql, libs/orders/src/lib/components/order-data-provider/__generated__/Orders.ts, libs/orders/src/lib/components/order-list-container.tsx, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/orders/src/lib/components/order-list-manager/use-order-list-data.ts, libs/orders/src/lib/components/order-list/order-list.tsx
Closes #2273
Make trade grid tabs (orders and fills only) market specific. 
Add market ID filter to orders and fills tabs.
=> feat(#2273): orders and fills on trading page to be market specific

apps/liquidity-provision-dashboard/src/app/components/dashboard/market-list/market-list.tsx
Part of #2216 
Add's a column to the lp-dashboard market list page for market age.
Don't think there's anything of note, but please do shout if we've got date/time convensions that I've not adhered to!
=> feat: add market duration/age to market list page

apps/stats/.env.stagnet3, libs/network-stats/src/config/stats-fields.ts
Closes #2380
Where previously the API gave the duration between blocks as a duration number, it's now a string and can be in seconds or milliseconds. That stats app now accounts for these possibilities and formats the value into seconds for display.
=> fix(2380): fixed block duration field to account for the new api format

apps/trading-e2e/cypress.config.js, apps/trading-e2e/tsconfig.json
Allows jsx to be imported into trading-e2e test files for easier sharing of code. Also deletes the unused cypress component testing configuration
=> chore: allow jsx in trading-e2e

libs/react-helpers/src/hooks/use-theme-switcher.ts
Fixes a problem where the dark class was being removed from the html tag on token, due to the theme switcher state initialization.
=> fix: dark class being removed on token due to theme switcher changes

apps/explorer/src/app/components/txs/txs-per-block.tsx
Closes #2490
Switches the filter used when fetching transactions for a block from relying on a hack to using the correct filter.
=> feat(explorer): use block height filter

apps/token-e2e/src/integration/flow/governance-flow.cy.js
This PR skips one token flow test that has been flakey and blocking PR builds getting merged.
The issue is capsule related and tracked in the ticket here: 
https://github.com/vegaprotocol/vegacapsule/issues/362
Once the issue is resolved the test can be un-skipped.
=> chore: skip flow test

libs/wallet/src/connectors/json-rpc-connector.ts
Fixes wallet connect, save the url to localstorage so that the connection is not los when the page is refreshed.
=> fix: wallet connect save url to config

.github/workflows/capsule-cypress.yml
E2E tests that use capsule in CI are erroring on main branch because it is pulling from latest main branch. 
Change workflow to pull from compatible version of capsule against Vega v0.54.0
Closes #2519
=> chore: pull capsule from v0.2.3

apps/trading-e2e/src/integration/trading-orders.cy.ts, libs/orders/src/lib/components/order-list/order-list.spec.tsx, libs/orders/src/lib/components/order-list/order-list.stories.tsx, libs/orders/src/lib/components/order-list/order-list.tsx, libs/orders/src/lib/order-hooks/index.ts, libs/orders/src/lib/order-hooks/use-has-active-order.ts
Closes #2323 
in draft state because depends on https://github.com/vegaprotocol/vega/issues/7216
Don't allow cancel all if there are no cancellable orders
useHasActiveOrder was added. It runs query to party orders connection to check if there is any active order for the party. If there is any change in party orders (recognised by subscription) query is refetched
=> feat(#2323): don't allow cancel all if there are no cancellable orders

apps/liquidity-provision-dashboard/src/app/components/dashboard/market-list/market-list.tsx, libs/liquidity/src/lib/markets-liquidity-provider.ts
Closes #2216 
Adds a 'closing time' column to the lp-dashboard, populated from the `terms.closingDateTime` field on the governance proposal API.
=> feat: add market close datetime to lp dashboard

libs/types/src/global-types-mappings.ts
N/A
Changes text for TRANSFER_TYPE_WIN to refer to 'gain' rather than 'win'
=> chore: change text for TRANSFER_TYPE_WIN

apps/console-lite-e2e/src/integration/portfolio-page.test.ts, libs/fills/src/lib/fills-table.spec.tsx, libs/fills/src/lib/fills-table.tsx
Closes #845 
Check decimal places and formatting of the amounts. Use asset decimals to format notional value and  fees
Use asset decimals to format notional value and fees
=> chore: update fills tab - add tooltip with fees breakdown

libs/assets/src/lib/asset-details-table.tsx
N/A
Makes contract address in the asset detail dialog a link to etherscan
=> chore: add link to etherscan for asset dialog contract address

apps/token/src/i18n/translations/dev.json
The new validator description text on the governance site used both "candidate" and "pending" for the same validator status. This PR standardises it, and gets rid of unneeded caps.
=> fix: make validator text terminology match

apps/token/src/routes/staking/node/validator-table.tsx, apps/token/src/routes/staking/shared.spec.ts, apps/token/src/routes/staking/shared.ts
Closes #2629
Adjusted the logic behind the overstaked amount calculation. Previously, if a validator was overstaked, the calculation would return it as a negative amount, but we had some extra logic to return 0 if it was negative. An adjustment was needed so that the calculated amount being overstaked was positive.
=> feat(2629): validator table - adjust the overstaked amount calculation

apps/explorer/src/app/app.tsx, apps/explorer/src/app/components/asset-balance/asset-balance.tsx, apps/explorer/src/app/components/links/asset-link/asset-link.tsx, apps/explorer/src/app/components/links/market-link/market-link.tsx, apps/explorer/src/app/components/order-details/Order.graphql, apps/explorer/src/app/components/order-details/__generated__/Order.ts, apps/explorer/src/app/components/order-details/lib/order-labels.tsx, apps/explorer/src/app/components/order-summary/order-summary.spec.tsx, apps/explorer/src/app/components/order-summary/order-summary.tsx, apps/explorer/src/app/components/order-summary/order-tx-summary.spec.tsx, apps/explorer/src/app/components/order-summary/order-tx-summary.tsx, apps/explorer/src/app/components/price-in-market/price-in-market.tsx, apps/explorer/src/app/components/txs/details/batch-submission/batch-amend.tsx, apps/explorer/src/app/components/txs/details/batch-submission/batch-cancel.tsx, apps/explorer/src/app/components/txs/details/batch-submission/batch-order.tsx, apps/explorer/src/app/components/txs/details/chain-response-code/chain-reponse.code.tsx, apps/explorer/src/app/components/txs/details/shared/tx-details-shared.tsx, apps/explorer/src/app/components/txs/details/tx-batch.tsx, apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx, apps/explorer/src/app/routes/parties/id/Party-assets.graphql, apps/explorer/src/app/routes/parties/id/__generated__/Party-assets.ts, apps/explorer/src/app/routes/parties/id/components/party-accounts.tsx, apps/explorer/src/app/routes/parties/id/index.tsx, apps/explorer/src/app/routes/txs/id/tx-details.tsx
- feat(explorer): add basic table for all types in a batch
- feat(explorer): use marketlink for market ids in batch
- feat(explorer): break long batch errors and fix header alignment
- test(explorer): add tests for order summary component
- feat(explorer): split out batch rows for tests
- feat(explorer): add ordersummary
- feat(explorer): improve caching with some slight overfetching and cache config
Closes #2121
Adds a Batch Market Instruction view
=> feat(explorer): batch market instructions

apps/liquidity-provision-dashboard/src/app/components/dashboard/market-list/market-list.tsx
Part of #2168 
Don't show decimal places for `% target stake met` column on the lp-dashboard
=> chore: 0 decimal places for % target stake column

.github/workflows/cypress-token-e2e.yml, .github/workflows/cypress-trading-e2e.yml
to avoid problems with uploading two files with the same name
=> chore: add job name to log file name

.github/workflows/capsule-cypress.yml, .github/workflows/cypress-console-lite-e2e.yml, .github/workflows/cypress-explorer-e2e.yml, .github/workflows/cypress-token-e2e.yml, .github/workflows/cypress-trading-e2e.yml
Resolves the issue when package.json change does not trigger yarn.lock change, but cache is created incorrectly and installs everything at each job.
=> chore: add package json to hash

apps/trading/client-pages/liquidity/liquidity.tsx, apps/trading/client-pages/market/trade-market-header.tsx, apps/trading/components/header/header.tsx, apps/trading/components/select-market/select-market.tsx, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx
Closes #2560 
Show the market code and name in the trading header.
+ Fix navbar wrapping
=> feat(#2560): show market code and name in the trading header

apps/explorer/.env.mainnet, libs/network-stats/src/config/stats-fields.ts
Closes #2453
Adds a new environment variable that is used to fix the number of total nodes reported on explorer when it is connected to older networks.
=> fix(explorer): add workaround for v53 misreporting total node count

apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-cancel.tsx
Closes #2116
Liquidity Cancel events only contain a market ID, so this is a very basic view - just the standard shared header with a market link
=> feat(explorer): add liquidity cancel view

apps/trading/client-pages/liquidity/liquidity.tsx, apps/trading/components/header/header.tsx, apps/trading/components/navbar/navbar.tsx, apps/trading/components/select-market/select-market.tsx
N/A
- Fixes some a small gap appearing under trade header stats
- Adds HeaderTitle component for consistent rendering header title areas
- Adds 'Go to trading' link for LP page
Before:
After:
=> chore: make headers consistent

.github/workflows/cypress-nightly.yml, .github/workflows/cypress-pr.yml, .github/workflows/cypress-run.yml
Correct runner name to specific runner - `self-hosted-runner`. `self-hosted` is a tag that is attached to any runner we create. Additionally, fixed nightly test workflow.
=> chore: correct runner name

apps/explorer/src/app/components/txs/details/liquidity-provision/Explorer-settlement-asset.graphql, apps/explorer/src/app/components/txs/details/liquidity-provision/__generated__/Explorer-settlement-asset.ts, apps/explorer/src/app/components/txs/details/liquidity-provision/components/liquidity-provision-details-row.spec.tsx, apps/explorer/src/app/components/txs/details/liquidity-provision/components/liquidity-provision-details-row.tsx, apps/explorer/src/app/components/txs/details/liquidity-provision/components/liquidity-provision-offset.spec.tsx, apps/explorer/src/app/components/txs/details/liquidity-provision/components/liquidity-provision-offset.tsx, apps/explorer/src/app/components/txs/details/liquidity-provision/liquidity-provision-details.spec.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-cancel.tsx
Closes #2737
- Fixes a bug that meant LP Cancellations never displayed
- Fixed decimal places in LP offsets - it now uses market DPs
- Remove 'normalised from' text on normalised proportions
=> fix(explorer): fix various small lp tx view bugs

libs/market-depth/src/lib/market-depth-provider.spec.ts, libs/market-depth/src/lib/market-depth-provider.ts
This exception occur when subscription is ahead of fetched data. It can happens on data provider initialization and when data is reloaded when there is gap between sequence numbers. It should not be treated as an issue.
=> chore: remove sentry captureException in marketDepthProvider update

apps/trading/lib/hooks/use-ethereum-transaction-toasts.tsx, libs/deposits/src/lib/use-deposits.ts, libs/ui-toolkit/src/components/toast/toast.tsx, libs/web3/src/lib/use-ethereum-transaction-store.tsx
Distinct Complete and Confirmed status of eth transaction in toast notification. 
Deposit transaction requires final confirmation by change in status of deposit from 'open' to 'finalized'. This change delays "Transaction confirmed" toast and displays "Processing deposit" toast until deposit will be finalized
=> feat: add seperate transaction toast for completed eth transaction

apps/trading/client-pages/portfolio/account-history-container.tsx, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.spec.tsx, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx, libs/candles-chart/src/lib/candles-chart.tsx, libs/environment/src/components/network-switcher/network-switcher.tsx, libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.spec.tsx, libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.stories.tsx, libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.tsx
N/A
@radix-ui/react-dropdown-menu version update from 0.1.6 to 2.0.2 changed to not use portals to render menu content by default, resulting in broken UI in some places such as candle studies and pubkey selector. This PR fixes that by making our dropdown component always use protals
=> fix: dropdown menu portals

.github/workflows/cypress-run.yml, apps/trading-e2e/.env, apps/trading-e2e/.env.capsule, apps/trading-e2e/.env.stagnet3, apps/trading-e2e/cypress.config.js
There was some mess with `ETH_WALLET_MNEMONIC` and `ETHEREUM_WALLET_ADDRESS`, that needed clean up. Mnemonic for stagnet3 can be found in 1password, to avoid exposure.
=> chore: correct ethereum releated envs in trading-e2e

apps/explorer/project.json, apps/explorer/src/app/components/links/market-link/market-link.tsx, apps/explorer/src/app/components/links/oracle-link/oracle-link.tsx, apps/explorer/src/app/components/txs/details/tx-order.tsx, apps/explorer/src/app/routes/oracles/Oracles.graphql, apps/explorer/src/app/routes/oracles/__generated__/Oracles.ts, apps/explorer/src/app/routes/oracles/components/oracle-data.spec.tsx, apps/explorer/src/app/routes/oracles/components/oracle-signers.spec.tsx, apps/explorer/src/app/routes/oracles/components/oracle-signers.tsx, apps/explorer/src/app/routes/oracles/components/oracle.tsx, apps/explorer/src/app/routes/oracles/home/index.tsx, apps/explorer/src/app/routes/oracles/id/index.tsx, apps/explorer/src/app/routes/oracles/index.tsx, apps/explorer/src/app/routes/router-config.tsx
Closes #2632
Follow up from a previous PR. This oracles overview page would previously have requested the default max (i.e.: all) 
oracles, which is fine now but could get huge. Similarly it requested all data that had ever been submitted that matched, which is fine now but... you get the point.
- Adds a `/oracles/:id`
- Adds an `<OracleLink id={id} />` component to link to new oracle by id page
- Add new GraphQL query to request oracle info for details page
- chore: bump spec version used to generate types
- Update `<MarketLink />` to add optional prop to prevent re-rendering with market name replacing market ID. This feels like a work in progress - some better solution for showing a market name along with it's ID is required.
- Update original Oracle List graphQL query to request max 1 …
=> fix(explorer): place sensible limits on oracles page queries

apps/trading/components/footer/footer.spec.tsx, apps/trading/components/footer/footer.tsx, libs/apollo-client/src/lib/apollo-client.ts, libs/environment/src/components/network-loader/network-loader.spec.tsx, libs/environment/src/components/network-loader/network-loader.tsx, libs/environment/src/hooks/index.ts, libs/environment/src/hooks/use-config.tsx, libs/environment/src/hooks/use-environment-errors.spec.tsx, libs/environment/src/hooks/use-environment.spec.tsx, libs/environment/src/hooks/use-environment.tsx, libs/environment/src/hooks/use-node-health.spec.tsx, libs/environment/src/hooks/use-node-health.ts, libs/environment/src/hooks/use-nodes.tsx, libs/environment/src/utils/compile-environment.ts, libs/environment/src/utils/request-node.ts, libs/react-helpers/src/hooks/index.ts, libs/react-helpers/src/hooks/use-navigator-online.spec.ts, libs/react-helpers/src/hooks/use-navigator-online.ts, libs/ui-toolkit/src/components/indicator/indicator.tsx
Closes #1791 
Checks a random subset of nodes every 30s to see if the your current nodes block height is up to date. This is shown in the UI by an indicator in the footer along with the text Opertaional, Non operational, X blocks behind or Offline
- Updated to createClient to take a few more options, for retry and connect to dev tools. This tidies up the network quite a bit when attempting connections and also doesn't mess with Apollo dev tools
- Fixed broken/evergreen tests for environment provider. Looks like this has been broken since [this commit](https://github.com/vegaprotocol/frontend-monorepo/commit/71ede25339e7a5cd2c8acd8198d99e72244e9a02#diff-771a20a1909c122b0792e947e22ec89f81061f1b41782d1bf7324536b464d14a)
- Adds useNavigatorOnline hook to detect if browser is connected or not
=> feat(#1791): block height check

apps/trading/components/select-market/select-market.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
=> fix: don't show `my markets` if there are no markets & reset deal ticket price validation before setting price 

apps/explorer/src/app/components/txs/tx-data-view.tsx
Closes #2777
The TX viewer introduced in #2765 did not correctly change when the user switched from JSON to base64. Now it does!
=> fix(explorer): tx viewer dropdown did not correctly represent state

apps/explorer/src/app/hooks/use-txs-data.ts
Closes #2719
The infinite scroll fetcher for party transactions always returned `true` for `hasMoreTransactions`, which resulted in the loader always showing. Now it calculates it based on the number of transactions.
=> fix(explorer): correct calculation for whether party txs list has more txs

apps/trading/client-pages/portfolio/deposits-container.tsx, apps/trading/client-pages/portfolio/withdrawals-container.tsx, apps/trading/components/accounts-container/accounts-container.tsx, libs/accounts/src/lib/accounts-manager.spec.tsx, libs/accounts/src/lib/accounts-manager.tsx, libs/accounts/src/lib/accounts-table.spec.tsx, libs/accounts/src/lib/accounts-table.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/orders/src/lib/components/order-list-container.tsx, libs/orders/src/lib/components/order-list-manager/order-list-manager.spec.tsx, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/orders/src/lib/components/order-list/order-list.spec.tsx, libs/orders/src/lib/components/order-list/order-list.stories.tsx, libs/orders/src/lib/components/order-list/order-list.tsx, libs/positions/src/lib/positions-container.tsx, libs/positions/src/lib/positions-manager.tsx, libs/positions/src/lib/positions-table.spec.tsx, libs/positions/src/lib/positions-table.tsx
Closes #2717
Consolidate `view as` mode.
=> fix(trading): consolidate view as user mode

apps/token/src/routes/staking/node/stake-success.tsx, yarn.lock
Closes #2431
When the 'back to staking' link was clicked from within the staking success modal, the modal would not close properly and the body tag would continue to have its overflow css property locked. This is now fixed.
=> feat(governance): body can scroll again after clicking 'back to staking'

libs/orders/src/lib/components/order-list-manager/order-list-manager.spec.tsx, libs/ui-toolkit/src/components/async-renderer/async-renderer.tsx
Closes N/A
Update `AsyncRenderer` on error
=> fix(trading): update async renderer on error

apps/explorer/.env.stagnet3, apps/explorer/src/app/components/render-fetched/index.tsx, apps/explorer/src/app/components/txs/details/tx-details-protocol-upgrade.tsx, apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-cancel.tsx, apps/explorer/src/app/config/env.ts, apps/trading/.env, apps/trading/.env.capsule, apps/trading/.env.devnet, apps/trading/.env.mainnet, apps/trading/.env.mirror, apps/trading/.env.sandbox, apps/trading/.env.stagnet1, apps/trading/.env.stagnet3, apps/trading/.env.testnet
Closes #2129
Adds a Protocol Upgrade transaction. These are infrequent, but interesting. We're at that point in the transactions list
I suppose. This *could* be expanded with a block height past/future, but given that is easy to calculate in your head
I have not done this in this PR, in favour of MORE TX VIEWS.
Note: it now says 'Upgrade at block' rather than 'Upgrade at'.
=> feat(explorer): add protocol upgrade view

apps/token-e2e/.env, apps/token-e2e/src/integration/flow/token-association-flow.cy.js, apps/token-e2e/src/integration/view/wallet-vega.cy.js, apps/token-e2e/src/support/staking.functions.js, apps/token-e2e/src/support/wallet-teardown.functions.js
Closes #2058 
Adds E2E tests for pending balances.
- Performing an association/disassocation from the application shows the pending balances bar
- Performing an association/disassocation outside of the application shows the same
- Ensure that this works for both vesting contract association and staking contract association
=> test(token): pending balances

apps/explorer/src/app/routes/oracles/__generated__/Oracles.ts, apps/explorer/src/app/routes/oracles/components/oracle.tsx, apps/explorer/src/app/routes/oracles/home/index.tsx
Closes #2850
The explorer oracles section used to be a single page, but was broken up in to 2, and a simpler query
was added for the index. In that refactor I... forgot to regenerate the types, so regenerating them created a different 
type with a missing field.
=> fix(explorer): type generation broken in an oracle refactor

libs/ui-toolkit/src/components/async-renderer/async-renderer.tsx
N/A
Removes sentry capture from body of AsyncRenderer component as its already capturing errors via the Apollo error link
=> chore(trading): remove unnecessary sentry capture from asyncrenderer component

apps/explorer/src/app/components/links/market-link/Market.graphql, apps/explorer/src/app/components/links/market-link/__generated__/Market.ts, apps/explorer/src/app/components/links/market-link/market-link.spec.tsx, apps/explorer/src/app/components/order-details/Order.graphql, apps/explorer/src/app/components/order-details/__generated__/Order.ts, apps/explorer/src/app/components/order-details/amend-order-details.spec.tsx, apps/explorer/src/app/components/order-details/deterministic-order-details.tsx, apps/explorer/src/app/components/order-summary/order-summary.spec.tsx, apps/explorer/src/app/components/order-summary/order-tx-summary.spec.tsx, apps/explorer/src/app/components/price-in-market/price-in-market.spec.tsx, apps/explorer/src/app/components/size-in-market/size-in-market.spec.tsx, apps/explorer/src/app/components/size-in-market/size-in-market.tsx
Closes #2860
Update market queries to fetch positionDecimalPlaces and use that to format size field on orders.
- Update Market queries
- Add `SizeInMarket` component
=> fix(explorer): use position decimal places to format size in order

apps/token/src/routes/proposals/components/propose/proposal-form-transaction-dialog.tsx, apps/token/src/routes/proposals/propose/raw/proposal-raw.spec.tsx, libs/governance/src/lib/proposals-hooks/Proposal.graphql, libs/governance/src/lib/proposals-hooks/__generated__/Proposal.ts, libs/governance/src/lib/proposals-hooks/use-proposal-event.ts, libs/governance/src/lib/voting-hooks/VoteSubsciption.graphql, libs/governance/src/lib/voting-hooks/__generated__/VoteSubsciption.ts, libs/governance/src/lib/voting-hooks/use-vote-event.ts
Closes #2858
Replaces proposal and vote busEvents with subscriptions, as busEvents are causing performance concerns for the core team.
NOTE: this does not replace busEvents for the Trading toast proposal queries.
=> feat(governance): replace proposal and vote busEvents with subscriptions

apps/explorer/src/app/components/table/index.tsx, apps/explorer/src/app/components/txs/details/state-variable/bound-factors.spec.tsx, apps/explorer/src/app/components/txs/details/state-variable/bound-factors.tsx, apps/explorer/src/app/components/txs/details/state-variable/data-wrapper.tsx, apps/explorer/src/app/components/txs/details/state-variable/risk-factors.tsx, apps/explorer/src/app/components/txs/details/state-variable/rist-factors.spec.tsx, apps/explorer/src/app/components/txs/details/state-variable/trading-probability.tsx, apps/explorer/src/app/components/txs/details/state-variable/unknown.tsx, apps/explorer/src/app/components/txs/details/tx-batch.tsx, apps/explorer/src/app/components/txs/details/tx-chain-event.tsx, apps/explorer/src/app/components/txs/details/tx-data-submission.tsx, apps/explorer/src/app/components/txs/details/tx-delegation.tsx, apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx, apps/explorer/src/app/components/txs/details/tx-generic.tsx, apps/explorer/src/app/components/txs/details/tx-hearbeat.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-amend.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-cancel.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-submission.tsx, apps/explorer/src/app/components/txs/details/tx-node-vote.tsx, apps/explorer/src/app/components/txs/details/tx-order-amend.tsx, apps/explorer/src/app/components/txs/details/tx-order-cancel.tsx, apps/explorer/src/app/components/txs/details/tx-order.tsx, apps/explorer/src/app/components/txs/details/tx-proposal-vote.tsx, apps/explorer/src/app/components/txs/details/tx-state-variable-proposal.spec.tsx, apps/explorer/src/app/components/txs/details/tx-state-variable-proposal.tsx, apps/explorer/src/app/components/txs/details/tx-undelegation.tsx, apps/explorer/src/app/components/txs/details/tx-withdraw-submission.tsx, libs/ui-toolkit/src/components/sparkline/sparkline.tsx
- feat(explorer): basic state variable proposal view
- feat(explorer): all known state variables render meaningfully
- feat(explorer): monospace state variable numbers
Closes #2126
Adds a State Variable Proposal transaction view. Renders meaningful views of the three known types, and just dumps JSON out for unrecognised types.
Note: This next one actually has monospaced numbers, but it's a slightly old screenshot
=> feat(explorer): state variable proposal tx

apps/explorer/src/app/components/txs/details/tx-eth-key-rotate.tsx, apps/explorer/src/app/components/txs/details/tx-key-rotate.tsx
Closes #2125. Closes #2128.
Adds two very similar, very simple views. One is when a validator changes Vega key, the other is their Ethereum key
=> feat(explorer): add vega key and eth key rotate views

apps/explorer/src/app/components/order-summary/order-summary.tsx, apps/explorer/src/app/components/order-summary/order-tx-summary.spec.tsx, apps/explorer/src/app/components/order-summary/order-tx-summary.tsx, apps/explorer/src/app/components/size-in-market/size-in-market.spec.tsx, apps/explorer/src/app/components/size-in-market/size-in-market.tsx
Closes #2890
Batch orders used a component, `OrderSummary` and `OrderTxSummary`, which rendered sizes without using `SizeInMarket`. Now they do.
=> fix(explorer): use position decimal places to format size in order summary for batch orders

apps/token/src/components/nav/nav-dropdown.tsx, libs/ui-toolkit/src/components/nav-dropdown/dropdown-menu.tsx
Closes #2656
Closes #2875
Ensures Token dropdown menu opens consistently regardless of where in the link is clicked. Also added the correct cursor (good spot @neildawson) and as it was a one liner, I also fixed the z-index issue with the dropdown itself (#2875)
=> fix(governance): navigation token drop down behaviour

apps/token/src/routes/staking/shared.ts
Closes #2886
Fixed a division by zero error when validators have no stake.
=> fix(governance): overstaked penalty shown as NaN

libs/deal-ticket/src/components/deal-ticket/deal-ticket-limit-amount.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-market-amount.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/components/deal-ticket/expiry-selector.tsx, libs/deal-ticket/src/components/deal-ticket/time-in-force-selector.tsx, libs/deal-ticket/src/components/deal-ticket/type-selector.tsx, libs/ui-toolkit/src/components/input-error/input-error.tsx
Closes #2919 
Revert using notification component instead of input error.
=> fix(trading): re-use input errors instead of notification component

apps/explorer/src/app/components/footer/footer.tsx, apps/explorer/src/app/config/env.ts
Closes #2682
There used to be a feedback link in the footer. Then it went away. Now, it's back.
=> feat(explorer): add feedback link to footer

apps/token/src/hooks/use-pending-balances-manager.spec.ts, libs/governance/src/lib/proposals-hooks/Proposal.graphql, libs/governance/src/lib/proposals-hooks/__generated__/Proposal.ts, libs/governance/src/lib/proposals-hooks/use-update-network-paramaters-toasts.tsx, libs/governance/src/lib/proposals-hooks/use-update-network-parameters-toasts.spec.tsx, libs/types/src/__generated__/types.ts, libs/wallet/src/use-vega-transaction-updater.spec.tsx, libs/wallet/src/use-vega-transaction-updater.tsx, libs/web3/src/lib/use-ethereum-transaction-updater.spec.tsx, package.json, yarn.lock
Closes #2945 
Changes a subscription that is used to open a toast about network parameter proposals to use the bespoke proposal subscription as proposal bus events have been removed
Additionally:
- Added more test coverage to the use-update-network-parameters-toasts hook
- Fixed evergreen test cases in use-vega-transaction-updater.spec.tsx
- Remove remaining usage of @testing-library/react-hooks and remove from package.json
=> chore(trading,governance): remove busEvent for proposals

apps/token/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, apps/token/src/routes/staking/home/validator-tables/shared.tsx, apps/token/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx
Closes #2654
We had the 'tooltipShowDelay' property set to 0 in the 'defaultColDef', which didn't work, even though that's where we define the tooltip component. But providing it as a separate prop to each table works, because ok. Thanks AG Grid.
=> feat(governance): no delay on tooltip for validators table column headers

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/wallets.cy.ts, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deposits/src/lib/deposit-form.spec.tsx, libs/deposits/src/lib/deposit-form.tsx, libs/deposits/src/lib/deposit-limits.tsx, libs/governance/src/components/asset-proposal-notification.tsx, libs/governance/src/components/market-proposal-notification.tsx, libs/ui-toolkit/src/components/notification/notification.tsx
Closes #2823 
Closes #2807 
- Makes the approval step more explicit by removing the amount field.
- Makes connecting an Ethereum account more obvious by providing a connect button in place of the input field.
- Shows approved amount field 
Connect flow with validation:
No amount field if user has never approved:
Re prompt for approval if amount is more than approved
- Removed classname prop from notification to avoid modification of spacing
- Removed default spacing from Notification component, adjust areas where its used to apply the spacing from the parent
=> feat(trading,deposits): disable deposit address

apps/explorer/src/app/components/links/market-link/market-link.tsx
Closes #2967
After the new Market list and Market by ID page came in, we didn't update the MarketLink component to use the new address. 
As a result, if a user clicked on the 'Market' link in an Order TX page (for example) it would taken them to the market
list page and not the specific market page. This is because we moved from anchor links to proper individual pages
=> fix(explorer): incorrect destination in market link components

apps/trading/client-pages/portfolio/AccountHistory.graphql, apps/trading/client-pages/portfolio/__generated__/AccountHistory.ts, apps/trading/client-pages/portfolio/account-history-container.tsx, libs/types/src/__generated__/types.ts
Closes #2847 
Add market dropdown to account history view. All other dropdowns logic should stay consistently:  selecting market should also mange asset selection and selecting asset should check selected market.
=> chore(trading): add market dropdown to account history

libs/market-info/src/components/fees-breakdown/fees-breakdown.tsx, libs/ui-toolkit/src/components/tabs/tabs.tsx
Closes #2965 
fix fees breakdown layout and condense tabs
Before:
After:
Before: 
After:
=> fix(trading): fees breakdown layout and condense tabs

libs/market-depth/src/lib/orderbook-row.tsx, libs/market-depth/src/lib/orderbook.tsx, libs/positions/src/lib/positions-table.tsx, libs/react-helpers/src/lib/grid/cumulative-vol-cell.tsx, libs/react-helpers/src/lib/grid/index.ts, libs/react-helpers/src/lib/grid/numeric-cell.spec.tsx, libs/react-helpers/src/lib/grid/numeric-cell.tsx, libs/react-helpers/src/lib/grid/price-cell.spec.tsx, libs/react-helpers/src/lib/grid/price-cell.tsx, libs/react-helpers/src/lib/grid/vol-cell.tsx, libs/trades/src/lib/trades-table.tsx
N/A
Fixes a few small snags:
- Monospace fonts for PNL values in position tables
- Monospace font and cell decimals text color in cumulative volume cell in order book
- Trades table layout and monospace or size column
Numeric cell component for cumulative volume and monospace:
Trades table date alignment and numeric cell component for size
- Tidies up some inline styles in the order book
- Puts split number text color logic into NumericCell component
=> chore(trading): grid cell fixes

libs/ui-toolkit/package.json, package.json
Didn't realise we'd previously published this package to npm - there are were 7 versions starting with 0.1.0 prior to us publishing 0.0.1 today ( see https://www.npmjs.com/package/@vegaprotocol/ui-toolkit?activeTab=versions )
This bumps us to 0.7.0 - which is ahead of the previously highest 0.6.1, and hopefully will avoid any confusion for consumers of the lib.
=> chore(ci): bump ui-toolkit version to 0.7.0 

apps/token/src/routes/proposals/components/vote-details/use-user-vote.tsx, apps/token/src/routes/proposals/components/vote-details/vote-buttons.spec.tsx, apps/token/src/routes/proposals/components/vote-details/vote-buttons.tsx, apps/token/src/routes/proposals/components/vote-details/vote-details.tsx, libs/governance/src/lib/voting-hooks/use-vote-submit.ts
Closes #2398
Proposal vote updates weren't being rendered. This inadvertently happened when we stopped looking at all votes to determine an individual vote state. To fix, we now check for changes to the finalizedVote object returned from use-vote-submit and write that to state to create the re-render.
=> fix(governance): vote state update fix

apps/static/src/assets/validator-testnet-network.json
This network moved from 0.53 to 0.68 which changes the endpoint
Closes #3034
=> chore(ci): update validator testnet config endpoint

apps/explorer/tsconfig.json, apps/multisig-signer/tsconfig.json, libs/environment/src/hooks/use-environment.spec.ts, libs/environment/src/hooks/use-environment.ts, tsconfig.base.json
Closes #3039 
Fixes a problem where the useEnvironment hook would select a node even if it was down and not responding
- Changes useEnvironment hook to use Promise.any rather than Promise.race. The former will wait for the first fulfilled promise whereas the latter will wait for the first promise to settle (even if promise is rejected).
- Beefed up some missing functionality in unit tests
=> fix(environment): console not finding node

apps/token/src/routes/router-config.tsx
Mainnet on token is spamming requests due to a poorly configured router
The router was nesting two routes incorrectly. Due to the type policy the first would fire off and then the second, which would cause changes to the first query causing it to refetch, repeat infinitely. These did not need to be passing data between each other, and should not have been used together at all as there was a different container for that route, which this PR is now using.
=> fix(token): router incorrectly configured, causing query spamming

apps/explorer/src/app/components/order-details/deterministic-order-details.tsx
Closes #3029
Order size was displayed correctly, but not remaining. Now remaining is too.
=> fix(explorer): add size in market component for remaining order size

apps/explorer/src/app/components/epoch-overview/Epoch.graphql
Closes #2973 
Removes a commented out GraphQL query that breaks a pipeline elsewhere. On one hand, it probably shouldn't break pipelines, on the other hand, this query was more 'Note to self' than essential so it's an easy choice to remove it.
=> chore(explorer): remove commented out query

.github/workflows/publish-npm.yml
#3022 add two more packages for us to publish to npm in order for `@vegaprotocol/ui-toolkit` to be consumable - this PR adds those as options on the manually-triggered publish to npm workflow.
=> chore(ci): add utils and i18n libs as options for publish to npm workflow

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/wallet/src/use-vega-transaction-store.spec.tsx, libs/wallet/src/use-vega-transaction-store.tsx
Closes #2695 
Edit order strikethrough shows correct values.
Same for size:
=> fix(trading): edit order strikethrough

libs/web3/src/lib/use-ethereum-withdraw-approvals-manager.spec.tsx, libs/web3/src/lib/use-ethereum-withdraw-approvals-manager.tsx
Closes #2580
Catch possibly errors from the last stage of creating transaction, when contract endpoints are requested
Add catch to promise and log by logger
=> chore(trading): catch ethereum errors and capture to sentry

apps/trading-e2e/src/integration/capsule.cy.ts, apps/trading-e2e/src/integration/deposit.cy.ts, apps/trading-e2e/src/integration/wallets.cy.ts, apps/trading/lib/hooks/use-ethereum-transaction-toasts.tsx, libs/deal-ticket/src/components/deal-ticket/expiry-selector.tsx, libs/deal-ticket/src/components/deal-ticket/side-selector.tsx, libs/deal-ticket/src/components/deal-ticket/time-in-force-selector.tsx, libs/deal-ticket/src/components/deal-ticket/type-selector.tsx, libs/deposits/src/lib/approve-notification.tsx, libs/deposits/src/lib/deposit-container.tsx, libs/deposits/src/lib/deposit-dialog.tsx, libs/deposits/src/lib/deposit-form.spec.tsx, libs/deposits/src/lib/deposit-form.tsx, libs/deposits/src/lib/deposit-limits.tsx, libs/deposits/src/lib/deposit-manager.tsx, libs/deposits/src/lib/faucet-notification.tsx, libs/deposits/src/lib/use-deposit-balances.ts, libs/deposits/src/lib/use-submit-approval.ts, libs/deposits/src/lib/use-submit-faucet.ts, libs/ui-toolkit/src/components/form-group/form-group.tsx, libs/web3/src/lib/use-ethereum-transaction-store.tsx
Closes #2566 
Updates deposit flow to
- Make connection more obvious via a primary button and validation
- Make choosing which key to deposit to easier by providing a dropdown (as well as manual entry option)
- Show feedback inline for faucet and approve transactions
- Show toasts so the user is notified even if the form dialog is closed
- Connects to the ethereum transaction store so you will also get toasts for deposit TXs
- Updates the ethereum toast manager to not delete the tx on close, but only dismiss
=> feat(deposits): deposit flow

apps/explorer/src/app/components/order-summary/order-cancellation.tsx, apps/explorer/src/app/components/txs/details/batch-submission/batch-cancel.tsx, apps/explorer/src/app/components/txs/details/tx-order-cancel.tsx
Closes #3106
A 'Cancel Order' can optionally:
- *not* specify an order ID, specify a market = cancel all orders in market
- *not* specify an order ID and *not* specify a market = cancel all orders
Previously this was just rendered as a '-' in Order ID and '-' in Market. Now a new component renders a more useful
explanation of the situation
=> feat(explorer): improve display of multi cancellations

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/constants.ts, libs/deal-ticket/src/hooks/use-fee-deal-ticket-details.tsx
=> fix(trading):  deal ticket expiry not wiped out after changing TIF from GTT

apps/explorer-e2e/src/fixtures/net_parameter_format_lookup.json, apps/explorer/src/app/routes/network-parameters/network-parameters.tsx
Closes #3080
`minimumProposerEquityLikeShare` is a percentage, but was being display as a number. Now it's being displayed as a percentage.
=> fix(explorer): format els as percentage in network param view

apps/explorer/src/app/routes/validators/validators-page.tsx
Closes #3096
The validators table view could be quite untidy for a few reasons:
- The old nav used to cause an overflow (fixed in #3069)
- Not all validators have set avatars, but there is always space for it
- On mobile, the avatars squish the interesting content
I tried a variety of approaches but in the end the one that looked best was putting the avatar in to the key value
table row at the bottom. If there is none set, the row doesn't appear. The size and width is limited
=> fix(explorer): neaten validators mobile view

apps/token/src/routes/staking/node-list.tsx
Closes #2692
On the validators list, the compare function would attempt to compare formatted numbers, which were stringified numbers that had been formatted based on user locale. To fix this, we now pass the values to AG Grid without the formatting, and let AG Grid apply the formatting itself, allowing it to correctly sort the original values.
=> fix(governance): validators list comparing stringified numbers

apps/trading/lib/hooks/use-vega-transaction-toasts.tsx
N/A
Adds a link to block explorer in the completed transfer toast.
=> fix(trading): add missing block explorer link for complete transfer

apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, apps/governance/src/routes/staking/home/validator-tables/shared.tsx, apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx
Closes #3175
As per https://github.com/vegaprotocol/frontend-monorepo/pull/3170 (the version for the 'main' branch), this ensures correct sorting of stake values. Values are passed to AG grid in formats it is able to sort, and any further formatting required is done via the 'valueFormatter' (for fields not requiring custom tooltips) or 'cellRenderer' (for those that do)
=> fix(governance): ensure validators tables sorting on develop

libs/market-depth/src/lib/depth-chart-utils.spec.ts, libs/market-depth/src/lib/depth-chart-utils.ts, libs/market-depth/src/lib/depth-chart.tsx, libs/market-depth/src/lib/orderbook-manager.tsx
Closes #3207 
Fix market depth update 
Handle correctly batch updates - reverse and uniqBy price
Clear throttles updates when market Id changes
Calculate market mid price base on price depth, instead of taking it from market data
=> fix(market-depth): fix depth chart data upate, use market depth as mid price source

libs/ui-toolkit/src/components/button/button.tsx
N/A
Anrchor button did not have text centered or the same spacing by default as a standard button. These should be consistent.
=> fix(ui-toolkit): anchor button should be same size as button by default

apps/trading/lib/hooks/use-ethereum-transaction-toasts.tsx
Closes #3226 
Change etherscan link label on toast from tx hash to "view on etherscan"
=> fix(trading): change etherscan link label on toast

apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards.tsx, apps/governance/src/routes/rewards/home/Rewards.graphql, apps/governance/src/routes/rewards/home/__generated__/Rewards.ts
Closes #3275
We had previously been paginating delegations data, but testing exposed that we hadn't been paginating rewards data too. Now we do. We're setting an arbitrary pagination number of 50 for now, as there's a separate ticket to deal with pagination  properly (https://github.com/vegaprotocol/frontend-monorepo/issues/794).
=> fix(governance): paginate rewards as well as delegations data

apps/explorer/.env.validator-testnet
The environment file for validator testnet contains an old URL that no longer works. This updates it.
- Update block explorer api url
Closes #3356
Will require a merge to `releases/validator-testnet` to be complete
=> build(explorer): update validator testnet be url

apps/trading/components/navbar/navbar.tsx, libs/environment/src/hooks/use-links.ts, libs/utils/src/lib/links.ts
Closes #3384 
Fix docs resources in navbar.
Directs you to [docs](https://docs.vega.xyz/testnet/concepts/new-to-vega) depending on env.
=> fix(trading): fix docs resources

libs/environment/src/components/node-switcher/row-data.spec.tsx, libs/environment/src/components/node-switcher/row-data.tsx
N/A
Prevents polling in the node switcher if a stats query fails for a given node. This should help with the number of Sentry alerts
=> chore(trading): prevent node poll if query fails

apps/trading/pages/styles.css
N/A
Changes the sell volume bar color in light theme to match the candle
Before:
After:
=> fix(trading): make light theme sell volume bar match candle color

libs/market-depth/src/lib/orderbook-manager.tsx, libs/market-depth/src/lib/orderbook-row.tsx, libs/market-depth/src/lib/orderbook.spec.tsx, libs/market-depth/src/lib/orderbook.tsx
Closes #3408 
Fix formatting when user clicks on orderbook cell after selecting decimal resolution.
Issue being fixed:
=> fix(trading): fix formatting on clicking on orderbook cell after decimal resolution update

libs/assets/src/lib/asset-details-table.tsx, libs/assets/src/lib/constants.ts, libs/assets/src/lib/index.ts, libs/ui-toolkit/src/components/notification/notification.tsx, libs/withdraws/src/lib/withdraw-form.tsx, libs/withdraws/src/lib/withdraw-limits.tsx, libs/withdraws/src/lib/withdraw-manager.spec.tsx, package.json, yarn.lock
Closes #3103 
- Add a tooltip to "Delayed withdrawal threshold". 
- Show a conditional inline notification when the amount entered exceeds the delayed withdrawal thresholds 
- Hide the delayed withdrawal threshold and adjust the warning copy when the delayed withdrawal threshold is zero
=> feat(withdraws): improve ux surrounding withdraw balances thresholds and delays

apps/trading/lib/hooks/use-vega-transaction-toasts.spec.tsx, apps/trading/lib/hooks/use-vega-transaction-toasts.tsx
Closes #3427 
Bug being fixed: The toasts for order amendments were always green.
On order amendment the toast intent should be selected based on the transaction status. 
For order submission/cancellation the intent can be based on the tx status & order status.
=> fix(trading): fix order toast intent on amendments

apps/explorer/src/app/routes/layout.tsx, apps/governance/src/components/page-templates/app-layout.tsx, apps/governance/src/components/page-templates/template-sidebar.tsx
Closes #3199
Configures Governance and Explorer to make use of the full width nav and announcement banner components
=> feat(governance): full width Governance and Explorer header

libs/orders/src/lib/components/order-data-provider/order-data-provider.ts, libs/utils/src/lib/generic-data-provider.ts
Closes #3349
Update cached Order objects using data from subscription.
=> fix(trading): update cached Order objects

libs/ui-toolkit/package.json
Need to pick up the new version of react-helpers to resolve an import issue. Current latest version on npm points to react-helpers 0.0.1 which doesn't have an exported member referenced in ui toolkit.
=> chore(ui-toolkit): bump ui toolkit to 0.10.0

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.spec.tsx, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx, libs/wallet/src/context.ts, libs/wallet/src/provider.spec.tsx, libs/wallet/src/provider.tsx, libs/wallet/src/use-json-rpc-connect.ts
Closes #3326 
Fetch new keys without re-connecting the wallet.
After creating a new key: 
The console will pick it up as soon as users opens dropdown/drawer to select it.  
=> fix(wallet): fetch new keys without re-connecting the wallet

apps/governance-e2e/src/integration/view/home.cy.ts, apps/governance-e2e/src/integration/view/rewards.cy.ts, libs/ui-toolkit/src/components/pagination/pagination.tsx
Closes #3470 
Adds 2 new e2e tests for pagination. 
Found bug #3471 which is causing one test to fail intermittently so skipped until bug is fixed
=> test(governance): e2e tests for rewards pagination

apps/token/src/routes/governance/components/vote-details/use-user-vote.tsx, libs/wallet/src/wallet-types.ts
Closes #3520 
Fixes casting a vote being broken in the token app. 
The wrong string was being passed in the transaction payload, not picked up on because the types were also incorrect
=> fix: use correct vote value string for casting vote

libs/ui-toolkit/src/components/checkbox/checkbox.tsx
=> fix(ui-toolkit): box size being wrong for multiline check boxes

apps/governance-e2e/src/support/staking.functions.ts, apps/governance/src/app.tsx
Closes #3032
When using react-router-dom's 'Link' component by default, path changes do not scroll the user back to the top of the page. This was confusing for some users in the testing sessions. Now when the path changes, the page jumps immediately to the top, giving the user the visual clue that a change has occurred.
=> fix(governance): scroll to top on route change

apps/governance/src/routes/staking/home/epoch-data.tsx, apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, apps/governance/src/routes/staking/home/validator-tables/shared.tsx, apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx
Closes #3532 
Closes #3286
When originally built, 'my stake' data for the validator tables made use of a version of the staking query that didn't require delegations pagination. When the query was changed, this query didn't get updated.
Also fixes the display of the user stake share percentage
=> fix(governance): validator tables - user staking fixes

apps/explorer/src/app/components/links/asset-link/asset-link.tsx, apps/explorer/src/app/components/order-details/deterministic-order-details.tsx, apps/explorer/src/app/routes/parties/id/components/party-accounts.tsx
- fix(explorer): asset link component could render incorrect links
- fix(explorer): pass null instead of 0 to get latest order version
Closes #3566.
Fixes two minor bugs - one where the asset link on the party page was incorrect, and one where the order component was
using an API parameter that became unsupported in the last release.
=> fix(explorer): fix asset links and deterministic order details

apps/governance/src/components/disconnected-notice/disconnected-notice.spec.tsx, apps/governance/src/components/disconnected-notice/disconnected-notice.tsx, apps/governance/src/components/disconnected-notice/index.tsx, apps/governance/src/components/eth-wallet/eth-wallet.tsx, apps/governance/src/components/web3-connector/web3-connector.tsx, apps/governance/src/contexts/app-state/app-state-context.ts, apps/governance/src/contexts/app-state/app-state-provider.tsx, apps/governance/src/i18n/translations/dev.json, apps/governance/src/routes/proposals/components/list-asset/list-asset.spec.tsx, apps/governance/src/routes/proposals/hooks/use-vote-information.spec.ts
Closes #2996
If a user connects their eth wallet to an unsupported network, they are disconnected automatically, and a notice is displayed in the eth wallet area of the sidebar, but they are otherwise not inhibited in their use of the app. If they wish to initiate a transaction, they can reconnect their wallet, which should automatically connect them to the correct network.
=> feat(governance): eth chain should not inhibit usage

apps/trading/client-pages/settings/settings.tsx, apps/trading/components/constants.ts, apps/trading/components/welcome-dialog/risk-notice-dialog.spec.tsx, apps/trading/components/welcome-dialog/risk-notice-dialog.tsx, apps/trading/components/welcome-dialog/telemetry-approval.spec.tsx, apps/trading/components/welcome-dialog/telemetry-approval.tsx, apps/trading/components/welcome-dialog/welcome-dialog.tsx
Closes #3564 
Adds a generic message to the RiskDialog for networks that are not mainnet
- Updated risk dialog to use useLocalStorage hook
- Updated TelemetryApproval to take a label prop rather than page specific prop
- updated RISK_ACCEPTED_KEY to use underscores to match other vega local storage keys
- Fixed confusing test names
=> feat(trading): add generic welcome message for non mainnet networks

apps/token/src/lib/date-formats.ts, apps/token/src/routes/governance/components/proposal-change-table/proposal-change-table.tsx, package.json, yarn.lock
Closes #3574
Before:
After (notice the BST beside datetime):
=> feat(governance): add time zone abbreviation data to proposal form - mainnet

apps/governance-e2e/src/integration/view/home.cy.ts, apps/governance/src/__mocks__/react-markdown.js, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.spec.tsx, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx, apps/governance/src/routes/proposals/components/proposal/proposal.tsx, apps/governance/src/styles.css
Closes #2998
Renders proposal descriptions as markdown. Note that:
- Images are disallowed
- Embedded HTML is stripped
These could both be made more nuanced (for instance images could be proxied), but this made sense as a starting point. Note that #3605 proposes replacing react-markdown, so this may change.
Also this removes the Proposal Description from the proposal list - it could be changed to trunacate the text, after rendering markdown, but this seemed a good starting point.
=> feat(governance): render markdown in proposal view

apps/explorer/src/app/routes/network-parameters/network-parameters.tsx
Closes #3629
Governance token balances for the updateAsset related proposals were displaying incorrectly. This PR brings them in line with other proposal types.
=> fix(explorer): number formatting for updateasset proposals

apps/governance/src/hooks/use-get-user-balances.ts, apps/governance/src/hooks/use-refresh-associated-balances.ts, apps/governance/src/hooks/use-refresh-balances.ts, apps/governance/src/routes/redemption/hooks.ts, apps/governance/src/routes/staking/associate/wallet-associate.tsx, libs/react-helpers/.eslintrc.json, libs/smart-contracts/src/contracts/staking-bridge.ts, libs/smart-contracts/src/contracts/token-vesting.ts, libs/utils/.eslintrc.json, libs/utils/src/lib/format/number.ts, libs/utils/src/lib/validate/common.spec.ts, libs/utils/src/lib/validate/common.ts
Depends on #3626 
Partially address #3124 
Removes dependency on `ethers` from utils and react-helpers
- Removes use of ethers.utils.isAddress
- Adds test coverage
=> chore(utils): remove ethers deps from ui-toolkit

libs/deal-ticket/src/components/deal-ticket/deal-ticket.spec.tsx, libs/deal-ticket/src/components/deal-ticket/type-selector.tsx, libs/orders/src/lib/order-hooks/use-order-store.ts
Closes #3586 
* swapped order type toggle
* made "Limit" default (with GTC)
=> chore(trading): make limit default order type

apps/explorer/.env.capsule, apps/explorer/.env.devnet, apps/explorer/.env.mainnet, apps/explorer/.env.testnet, apps/explorer/.env.validator-testnet, apps/explorer/.env.vegacapsule
Closes #3620
When Explorer got the Market Info panels from Trading, we neglected to set the environment variable that tells the component
where there block explorer for the current network is. For most instances, in explorer, this can be /. This PR sets a
few more explicitly.
=> fix(explorer): set explorer url env var in explorer

libs/environment/src/hooks/use-environment.ts
Closes #3674 
Show vega data node in list of available nodes if configured. Bust cache for vega data nodes in env switcher as this has now changed.
=> fix(governance, console, explorer): show vega node in list, cache bust

apps/explorer/.env, apps/explorer/.env.stagnet1
Closes #3673 
Recent explorer deploys were missing links in the environment switcher. This PR reinstates two of them.
=> fix(explorer): add envs back to env

apps/governance/src/lib/tranches/tranches-store.tsx, apps/governance/src/routes/redemption/tranche-item.tsx
Closes #3690
Tranche progress calculation required a couple of tweaks:
- Items in the past could have a 'lockedDecimal' greater than 1, resulting in incorrect totals being calculated (negative totals)
- Tranches that finish immediately were being treated as if they were always locked. Added some logic to check if their cliff_start value was in the past, giving them an unlocked value if so.
I also tweaked the layout of the tranche item to make the values more readable. See the 'unlocking starts' and 'fully unlocked' values below:
before:
after:
=> fix(governance): tranches data

apps/governance/src/i18n/translations/dev.json, apps/governance/src/routes/proposals/components/vote-details/vote-buttons.spec.tsx, apps/governance/src/routes/proposals/components/vote-details/vote-buttons.tsx, apps/governance/src/routes/proposals/components/vote-details/vote-details.tsx
Closes #3623
Closes #3668
Adds a link to the voting blog 
'Your vote' instead of 'Cast your vote' on proposals that are no longer open
=> feat(governance): voting blog link and button title

libs/smart-contracts/src/contracts/collateral-bridge.ts, libs/withdraws/src/lib/withdraw-form.tsx, libs/withdraws/src/lib/withdraw-manager.spec.tsx
Closes #3553
The withdrawal form message was configured to show a different message if the threshold for a withdrawal delay was 0, but it wasn't working. Subsequently, you'd see the scenario detailed in #3553.
=> fix(governance): fix time delay notice for withdrawal of 0.00 assets

libs/smart-contracts/src/contracts/claim.ts
Closes https://github.com/vegaprotocol/frontend-monorepo/issues/3725
Hexlify does not accept arbitary strings so need to pass this to toUtf8Bytes first. Confirmed output the same with previous util function that was removed.
=> fix(governance): claim not encoding ascii correctly

apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.ts, apps/governance/src/routes/staking/node/nodes-container.tsx
Closes #3760
Consensus, standby and pending validators have separate rewards returned per epoch. Previously we'd only been working with consensus validators, and we'd not aggregated. This created a confusing mix of randomly rendered results.
=> fix(governance): reward aggregation for validator types

apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards-table.spec.tsx, apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.spec.ts, apps/governance/src/routes/rewards/epoch-total-rewards/epoch-total-rewards-table.spec.tsx, apps/governance/src/routes/rewards/epoch-total-rewards/generate-epoch-total-rewards-list.spec.ts, apps/governance/src/routes/rewards/shared-rewards-table-assets/shared-rewards-table-assets.tsx
Closes #3572
The fee we were originally displaying in the table appears to have been incorrect. This simply changes which fee we display
=> fix(governance): point to correct data for displayed LP rewards

libs/i18n/package.json, libs/react-helpers/package.json, libs/tailwindcss-config/package.json, libs/types/package.json, libs/ui-toolkit/package.json, libs/ui-toolkit/src/components/healthbar/healthbar.tsx, libs/utils/package.json
Adds keys to the segments output by the healthbar component.
Version bumps for ui-toolkit and it's dependent packages so we can use this fix on the website.
=> fix(ui-toolkit): add keys to healthbar segments

apps/governance-e2e/src/integration/view/rewards.cy.ts, apps/governance/src/routes/staking/shared.ts
Closes #3696
Larger changes to how penalties are calculated vs what to show in the table may come later, but for now, just ensure that there's no rendered negative overstaking penalty, as that's just silly.
=> fix(governance): ensure no negative overstaked penalty

.github/workflows/cypress-run.yml, .gitignore, apps/explorer-e2e/cypress.config.js, apps/explorer-e2e/src/support/index.js, apps/governance-e2e/cypress.config.js, apps/governance-e2e/src/integration/view/rewards.cy.ts, apps/governance-e2e/src/support/index.js
The Governance tests in nightly run are timing out as they can take longer than 40 minutes.
Also fixed the test reporter which now works on governance and explorer and also removed redundant project id used by Cypress
=> chore(ci): fix nightly test runner

apps/governance/src/app.tsx, apps/governance/src/components/vega-wallet/hooks.ts, apps/governance/src/lib/party.ts, apps/governance/src/routes/staking/node/nodes-container.tsx
Closes #3085 
- If query errors check, if its a party not found error, if it is clear wallet state
- de-dupe magic strings for error checking
=> fix(governance): clear wallet state if user changes to a non existent party

libs/markets/src/lib/components/market-info/market-info-panels.tsx, libs/markets/src/lib/components/market-info/market-info.mock.ts, libs/markets/src/lib/components/markets-container/oracle-status.tsx, libs/markets/src/lib/components/oracle-banner/oracle-banner.tsx, libs/markets/src/lib/components/oracle-banner/oracle-statuses.ts, libs/markets/src/lib/components/oracle-dialog/index.tsx, libs/markets/src/lib/components/oracle-dialog/oracle-dialog.tsx, libs/markets/src/lib/components/oracle-full-profile/index.ts, libs/markets/src/lib/components/oracle-full-profile/oracle-full-profile.tsx, libs/markets/src/lib/hooks/use-market-oracle.spec.ts, libs/markets/src/lib/hooks/use-market-oracle.ts, libs/markets/src/lib/markets.mock.ts
Change source of data source specs from market info query to markets query in useMarketOracle hook.
If data needed in oracle banner is loading return null instead of no oracle notification
=> feat(trading): do not show oracle banner when data is loading

apps/explorer/src/app/components/txs/details/tx-proposal.spec.tsx, apps/explorer/src/app/components/txs/details/tx-proposal.tsx
Closes #3834
A console error was being thrown on Explorer when viewing some proposal transactions. This was because the logic detecting if the proposal required a signature bundle was flawed. 
- Fix function that decides if signature bundle is required
=> fix(explorer): prevent render of signature component on some proposals

apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.spec.tsx, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx, apps/governance/src/routes/proposals/propose/freeform/propose-freeform.tsx, apps/governance/src/routes/proposals/propose/network-parameter/propose-network-parameter.tsx, apps/governance/src/routes/proposals/propose/new-asset/propose-new-asset.tsx, apps/governance/src/routes/proposals/propose/new-market/propose-new-market.tsx, apps/governance/src/routes/proposals/propose/update-asset/propose-update-asset.tsx, apps/governance/src/routes/proposals/propose/update-market/propose-update-market.tsx
Closes #3835
A proposal had been submitted without a title, resulting in the fallback 'unknown proposal' title. To improve this, I've:
- Set useForm's validation to run when the 'download proposal json' button is clicked (i.e. they'll get notified of required fields) and the button won't work until they're filled in
- Set up some better fallbacks if a user has removed the title from their json (now shows 'New market proposal', 'Update asset proposal' etc instead of 'unknown proposal'
=> feat(governance): avoid showing untitled proposals

apps/trading-e2e/src/integration/closed-markets.cy.ts, apps/trading/client-pages/markets/closed.spec.tsx, apps/trading/client-pages/markets/closed.tsx, apps/trading/client-pages/markets/settlement-price-cell.spec.tsx, apps/trading/client-pages/markets/settlement-price-cell.tsx, libs/markets/src/lib/OracleMarketsSpec.graphql, libs/markets/src/lib/__generated__/OracleMarketsSpec.ts, libs/markets/src/lib/__generated__/markets.ts, libs/markets/src/lib/hooks/use-market-oracle.ts, libs/markets/src/lib/markets.graphql, libs/markets/src/lib/markets.mock.ts
N/A
Fixes an issue where prices were being formatted with market.decimalPlaces and not `numberDecimalPlaces` from the data source filter
- Update main market fragment to include data source filters. Note, these can't be retrieved directly from the oracleSpec even though the graphql schema indicates you can. This is numberDecimalPlaces will only be correct when queried in the context of a market.
=> fix(trading): settlement price of closed markets

apps/trading/client-pages/markets/proposed.tsx, libs/proposals/src/components/proposals-list/proposal-list.spec.tsx, libs/proposals/src/components/proposals-list/proposals-list.tsx, libs/proposals/src/lib/proposals-data-provider/proposals.mock.ts
Closes #3766 
Uses a normal generated query for proposals so I can pass an error policy. Currently the proposals don't show due to some proposals having errors. By using the errorPolicy we can still get data even if some fail
Also adds some height to the table so that the filter dropdown renders properly and isn't cut in half
=> fix(trading): fix proposals not showing

apps/explorer/.env.validators-testnet
The DNS changed recently. This fixes the Blocks view on the validator-testnet deployment.
=> chore(explorer): update be env for validator testnet

apps/governance/src/routes/proposals/protocol-upgrade/protocol-upgrade-proposal.tsx, apps/trading/.env, apps/trading/components/banner/index.tsx, apps/trading/components/banner/upgrade-banner.tsx, apps/trading/pages/_app.page.tsx, libs/environment/src/hooks/index.ts, libs/environment/src/hooks/mocks/github-releases.ts, libs/environment/src/hooks/use-environment.ts, libs/environment/src/hooks/use-releases.spec.ts, libs/environment/src/hooks/use-releases.ts, libs/environment/src/hooks/use-vega-release.spec.ts, libs/environment/src/hooks/use-vega-release.ts, libs/environment/src/hooks/use-vega-releases.spec.ts, libs/environment/src/hooks/use-vega-releases.ts, libs/environment/src/utils/validate-environment.ts
Closes #3641 
* displays notification banner with "upgrade" message
* displays link to the release (tag) on GitHub (protocol upgrade proposal page in Governance)
=> feat(trading): upgrade banner

apps/explorer/src/app/routes/oracles/components/oracle-details-type.spec.tsx, apps/explorer/src/app/routes/oracles/components/oracle-details-type.tsx, apps/explorer/src/app/routes/oracles/components/oracle.tsx
Closes #3752
Due to a potential bugin the GraphQL API, all data sources are in the GraphQL type that indicates they are external. This
caused the block explorer to always list a data source as external. This PR changes the way internal data sources are 
rendered, so the right label is displayed
- Update internal data type detection
=> fix(explorer): change how internal filters are detected

apps/trading/.env, apps/trading/.env.mainnet, apps/trading/components/banner/upgrade-banner.tsx
N/A
- Only renders the upgrade banner if NX_APP_VERSION is set
- Fixes color of copy icon in banner
=> chore(trading): dont show upgrade banner unless APP_VERSION is set

apps/trading-e2e/src/integration/home.cy.ts, apps/trading/client-pages/home/home.tsx
N/A
If not markets are found redirect  to the markets all page, so we aren't on an empty market page
=> fix(trading): redirect to markets all page if no market found

libs/ledger/src/lib/ledger-export-link.tsx
Closes #3893 
Hide download or export all when no ledger entries.
=> fix(trading): hide download or export all when no entries

apps/explorer/src/app/app.tsx
Closes #3891. Closes #3774.
The new nested routing on accounts triggered a React error when navigated in a specific path. The quick fix is to wrap the whole router in React.Suspense with a loading fallback, but this feels like a temporary fix. #3895 is a follow up ticket.
=> fix(explorer): wrap routes in suspense

libs/deposits/src/lib/deposit-form.tsx
Lifetime limit value is now Infinite when exempt
=> fix(deposits): validation with exempt

apps/governance/src/routes/proposals/components/proposals-list/proposals-list.spec.tsx, apps/governance/src/routes/proposals/components/proposals-list/proposals-list.tsx, apps/governance/src/routes/staking/shared.ts
Closes #3832
Enactment date was removed as a sorting param at some point in the past. This reinstates it, falling back to closingDatetime if there is no enactmentDatetime, finally sorting by datetime if there are multiple equal enactmentDatetimes/closingDatetimes.
=> fix(governance): add enactment date to proposal sorting

apps/trading/client-pages/markets/closed.tsx, libs/datagrid/src/lib/ag-grid/use-column-sizes.spec.ts, libs/datagrid/src/lib/ag-grid/use-column-sizes.ts, libs/markets/src/lib/components/markets-container/market-list-table.tsx, libs/proposals/src/components/proposals-list/use-column-defs.tsx
Closes #3900
Disable ag-grid api sizeColumnsToFit callings on small screens
-
=> fix(trading): make grids more responsive - suppress sizeColumnsToFit on small screens

apps/trading/components/market-mark-price/market-mark-price.tsx
Fixes sending query to marketConnection with empty market ID on /#/markets page
=> fix(trading): skip market data query if market not present

apps/governance/src/hooks/use-listen-for-pending-eth-events.ts, apps/governance/src/hooks/use-listen-for-staking-events.ts
Closes #3995 
Prevents starting listening for contract events until the user has connected an Ethereum wallet
=> fix(governance): dont start listening for pending eth events until connected

.github/workflows/add-ipfs-notes-to-release.yml
=> fix(explorer,trading): typo in release notes template

apps/trading/components/app-loader/app-loader.tsx, apps/trading/pages/_app.page.tsx, libs/data-provider/src/generic-data-provider.ts, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/hooks/use-fee-deal-ticket-details.tsx, libs/orders/src/lib/components/order-data-provider/order-data-provider.ts, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/orders/src/lib/components/order-list/order-list.tsx, libs/wallet/src/use-vega-transaction-updater.tsx, libs/web3/src/lib/use-vega-transaction-toasts.tsx
Closes #3788
Improves performance of the app when connected as a party with lots of orders.
- Removes top level subscription for all orders, only subscribing to active orders
- Prevents caching of OrderUpdate types
- Prevents caching of transaction update subscription data
- Prevents caching of estimateFees and estimatePosition queries
=> fix(trading): performance issues with many orders

apps/explorer/src/app/components/txs/tx-order-type.tsx, apps/explorer/src/app/components/vote-icon/vote-icon.spec.tsx, apps/explorer/src/app/components/vote-icon/vote-icon.tsx
Closes #3789
Colourising a proposal vote by Yes or No turned out to be confusing in the transaction list. Using 'red' to mean 'no' looks more like 'error' in that context, as raised by @davidsiska. This PR removes the colours in tx lists.
=> feat(explorer): do not colourise votes in tx list

apps/explorer/src/app/components/txs/details/chain-response-code/chain-reponse.code.tsx
Closes #3360
Makes it clearer which batches are partial error and which are full error
- Add orange coloured tick for partial success/error
- Update full success to a green tick
- Update full error to a red cross
- Add text label for partial success
=> feat(explorer): properly represent batch error 71

apps/explorer/.env
Closes #4028
A missing environment variable meant that the link to release tags on the Protocol Upgrade TX page was broken. This
PR adds the Github address of core, which fixes the issue.
=> fix(explorer): fix broken protocol upgrade tx link

libs/market-depth/src/lib/orderbook-manager.tsx, libs/market-depth/src/lib/orderbook.spec.tsx, libs/market-depth/src/lib/orderbook.stories.tsx, libs/market-depth/src/lib/orderbook.tsx
Closes #4051 
- Adds asset symbol to the mid
- Fixes the layout of the grid in the order book which wasn't taking into account the configured sizes
- Fixes row sizes which resulted in one less row per side being shown, even though there was space for it
- Adds a small 1px gap between rows
- Changed to use some inline styles instead of tailwind as tailwind was not compiling the dynamically created rowHeight, midHeight sizes
=> fix(trading): order book mid

apps/trading-e2e/src/integration/market-info.cy.ts, apps/trading-e2e/src/integration/market-summary.cy.ts, apps/trading-e2e/src/integration/oracle.cy.ts, apps/trading/components/liquidity-supplied/liquidity-supplied.tsx
Closes #3505 
Added test coverage for 6002-MDET-market-details.
Skipped two ACS: 
- 6002-MDET-204
- 6002-MDET-205
as it would require some additional effort with mocking, but we plan to create more Oracle logic test coverage later.
=> test(trading): #3505 add test coverage to 6002-MDET-market-details

apps/governance-e2e/src/integration/flow/staking-flow.cy.ts
Closes #4066
There are issues with flaky staking tests (https://github.com/vegaprotocol/frontend-monorepo/actions/runs/5213432071/jobs/9419229204?pr=4055#step:9:92). I have temporarily skipped these until @jtsang586 can take a look.
=> fix(governance): temporarily skipped flaky staking tests

libs/environment/src/components/network-switcher/network-switcher.spec.tsx, libs/environment/src/components/network-switcher/network-switcher.tsx
Closes #3704 
Uses click handler for menu item to navigate to the new network. This way the expected 'click area' is used
-
-
=> fix(trading): update click area in network switcher

apps/governance/src/routes/proposals/components/proposal/proposal.tsx
Closes #3876
Does what it says on the tin. Freeform proposals have no useful information in their proposal terms details, so no need to show it.
=> feat(governance): hide proposal details for freeform proposals

libs/liquidity/src/lib/liquidity-table.tsx
Closes #4079 
Fixes an issue where some rows where not ordered correctly in LP table. 
Liquidity provisions do not have an ID so we need to construct the row id based on party ID and the status of liquidity provision (because a party might have multiple inactive LPs for a market i.e. cancelled, rejected).
=> fix(liquidity): update liquidity table row id

apps/governance/src/i18n/translations/dev.json, apps/governance/src/routes/proposals/components/proposal/proposal.spec.tsx, apps/governance/src/routes/proposals/components/proposal/proposal.tsx, apps/governance/src/routes/staking/node/node.tsx
Closes #2752
To be consistent with a similar situation with validators, add an 'all proposals' link at the top of a proposal details page.
=> feat(governance): add 'all proposals' link on proposal details page

apps/trading-e2e/src/integration/assets.cy.ts, apps/trading-e2e/src/integration/trading-accounts.cy.ts, apps/trading-e2e/src/integration/trading-deal-ticket-order.cy.ts, apps/trading-e2e/src/integration/trading-positions.cy.ts, apps/trading/client-pages/market/trade-grid.tsx, apps/trading/components/accounts-container/accounts-container.tsx, libs/accounts/src/lib/accounts-manager.tsx, libs/accounts/src/lib/accounts-table.tsx, libs/accounts/src/lib/accounts.mock.ts, libs/accounts/src/lib/breakdown-table.tsx, libs/assets/src/lib/assets.mock.ts, libs/datagrid/src/lib/ag-grid/ag-grid-lazy-themed.tsx, libs/datagrid/src/lib/cells/grid-progress-bar.tsx, libs/ui-toolkit/src/components/tooltip/tooltip.tsx
Closes #2340 
- Adds quantum formatting to the accounts table
- Adds tooltips showing the full value
- Updated accounts table and breakdown table to use col defs
- Use internal update function for data provider (no need for using grid api as the coldefs are memo'd)
- Remove bottomPlaceholderProps
- Simplify progress bar cell.
=> feat(accounts): accounts table quantum formatting

apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards.tsx, apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.spec.ts, apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.ts, apps/governance/src/routes/rewards/home/Rewards.graphql, apps/governance/src/routes/rewards/home/__generated__/Rewards.ts
Closes #3942
In a situation where there are multiple rewards per epoch of the same type and asset, we weren't correctly calculating total percentage earned for an individual's rewards. We now sum the rewards and compare that amount to the total rewarded of that asset in that reward type in that epoch to determine the correct percentage.
=> fix(governance): earned by me reward percentage

apps/governance-e2e/cypress.config.js, apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts, apps/governance-e2e/src/integration/flow/staking-flow.cy.ts, apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts, apps/governance-e2e/src/integration/flow/withdrawal-flow.cy.ts, apps/governance-e2e/src/integration/view/validators.cy.ts, apps/governance-e2e/src/integration/view/wallet-vega.cy.ts
Previously, a staking test was skipped because of flaky failures. I believe that was already fixed in a previous PR. So will un-skip that test and monitor. 
- Added assertion to wallet test which has had flaky failures
- Added 3 additional smoke tests to increase coverage in PR builds - this adds around 2-3 minutes to the build time which I think is worth it for the extra coverage
=> chore(governance): un-skip staking test and increase test coverage for smoke tests

libs/ui-toolkit/package.json, libs/ui-toolkit/src/components/healthbar/healthbar.tsx
Closes #4118 
Integrating #4152 with the website project has identified a few more visual issues with the healthbar.
Remove a now-extra `%` and make sure we're specifying text colours for the tooltip content
Some screenshots post these changes:
=> fix(ui-toolkit): visual fixes for healthbar - % and text colours

apps/governance-e2e/src/integration/view/validators.cy.ts, apps/governance/src/i18n/translations/dev.json, apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, apps/governance/src/routes/staking/home/validator-tables/shared.tsx, libs/ui-toolkit/src/components/tooltip/tooltip.tsx
Closes #3802
Removes the 'total penalties' field inside the validator penalties tooltip, and if there's a multisig error, shows a 'Multisig penalty' of 100%.
=> feat(governance): show multisig penalty in tooltip

apps/trading-e2e/src/integration/market-info.cy.ts, libs/markets/src/lib/components/market-info/info-key-value-table.tsx, libs/markets/src/lib/components/market-info/market-info.mock.ts
Closes #4166 
Market info number formatting. 
formatNumber method was used before with 0 dp 
``` return getNumberFormat(formatDecimals).format(Number(rawValue));```  - it rounded values less < 1 (ex. 0.7) to 1 
format number decimals 0 rounds the number 
=> fix(trading): market info number formatting

libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.tsx
N/A
Removes unused ref warnings from dropdown menu
=> chore(ui-toolkit): remove forwardRef as refs weren't being passed

nx.json
N/A
Re-enables NX cloud as we are now on Nx cloud's open source plan which has unlimted CI pipeline executions per month
=> chore(trading,governance,explorer): re-enable nx-cloud

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
Closes #4189 
The notional size was formatted again with asset dp. 
=> fix(trading): notional size formatting

apps/explorer/src/app/components/txs/details/tx-liquidity-amend.test.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-amend.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-submission.test.tsx, apps/explorer/src/app/components/txs/details/tx-liquidity-submission.tsx
Closes #4188
to input a LiquidityProvision both Submission and Amendment for the fees you need to input 0.0010 for 0.10% - in the explorer it shows 0.0010% - I am not a Developer, I make this pull request to bring up the issue
=> fix(explorer): liquidity provision fee percentage

apps/governance-e2e/src/integration/flow/proposal-list.cy.ts, apps/governance-e2e/src/integration/view/proposal.cy.ts, apps/governance/src/components/collapsible-toggle/collapsible-toggle.spec.tsx, apps/governance/src/components/collapsible-toggle/collapsible-toggle.tsx, apps/governance/src/components/collapsible-toggle/index.ts, apps/governance/src/i18n/translations/dev.json, apps/governance/src/lib/collapsible-toggle-styles.ts, apps/governance/src/routes/proposals/components/proposal-description/proposal-description.tsx, apps/governance/src/routes/proposals/components/proposal-json/proposal-json.tsx, apps/governance/src/routes/proposals/components/proposal-market-data/proposal-market-data.tsx, apps/governance/src/routes/proposals/components/proposal-votes-table/proposal-votes-table.tsx, apps/governance/src/routes/proposals/components/proposal/proposal.spec.tsx, apps/governance/src/routes/proposals/components/proposal/proposal.tsx, apps/governance/src/routes/proposals/components/proposals-list-filter/proposals-list-filter.spec.tsx, apps/governance/src/routes/proposals/components/proposals-list-filter/proposals-list-filter.tsx, apps/governance/src/routes/proposals/components/proposals-list/proposals-list.spec.tsx, apps/governance/src/routes/proposals/components/proposals-list/proposals-list.tsx, apps/governance/src/routes/proposals/components/proposals-list/rejected-proposals-list.tsx, apps/governance/src/routes/proposals/test-helpers/generate-proposals.ts
Closes #4145
- Separates closed governance proposals from closed network upgrade proposals, using a toggle to view.
- Also improved proposal list filter UI, and ensures filters work correctly with network upgrades (first pass here is that network upgrades are hidden when the filter is engaged, as they lack the required fields for filtering)
- As part of testing this work, I realised it would be more useful for rejected proposals to have a link at the top to take the user back to the rejected proposals list, rather than the non-rejected one, so added that
=> feat(governance): add toggle for closed proposals list

apps/governance/src/__mocks__/react-markdown.js, libs/announcements/src/lib/announcements.spec.tsx, libs/environment/src/hooks/use-links.ts, libs/environment/src/hooks/use-vega-release.spec.ts, libs/markets/src/lib/hooks/use-oracle-markets.spec.ts
Tidy up some errors that don't cause failing tests, but noisy output on test runs. It's masked if you're running it through nx test all, but not in CI.
- governance had the same mock declared twice
- libs/market tests had a console.log left in
- libs/announcements needed `act` wrappers around some testing data
- libs/environments needed `act` wrappers around some testing data
- governance failed some tests if not run via NX due to environment variables
=> test(governance,markets): tidy up minor test quibbles

apps/explorer/src/app/components/order-details/amend-order-details.spec.tsx, apps/explorer/src/app/components/order-details/amend-order-details.tsx
Closes #4195
Ages ago, the GraphQL schema for the data node changed the order versions parameter so that 0 no longer provides
the most recent version of an order. Instead, passing no version does this. Block explorer was stuck in the old world.
=> fix(explorer): fix order amend tx view

apps/governance/src/i18n/translations/dev.json, apps/governance/src/routes/proposals/components/proposal-asset-details/index.tsx, apps/governance/src/routes/proposals/components/proposal-asset-details/proposal-asset-details.tsx, apps/governance/src/routes/proposals/components/proposal/proposal.tsx, apps/governance/src/routes/proposals/components/proposals-list/proposals-list.tsx, apps/governance/src/routes/proposals/proposal/proposal-container.tsx, libs/assets/src/lib/asset-details-table.spec.tsx, libs/assets/src/lib/asset-details-table.tsx
Closes #3781
Adds a collapsible section detailing asset specs for new and update asset proposals. It uses the AssetDetailsTable component, which I've updated to receive an optional list of keys to omit as the asset proposals specs do not require all the data the table is able to provide.
=> feat(governance): improve asset proposal details view

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx, libs/ui-toolkit/src/components/copy-with-tooltip/copy-with-tooltip.tsx, libs/ui-toolkit/src/components/dialog/dialog.tsx, libs/ui-toolkit/src/components/dropdown-menu/dropdown-menu.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-tick.tsx, libs/ui-toolkit/src/components/icon/vega-icons/vega-icon-record.ts, libs/web3/src/lib/withdrawal-approval-dialog.tsx, libs/withdraws/src/lib/withdrawals-table.tsx
N/A
- Switch to using vega icons for withdrawals table and wallet dropdown
- Dry up some code by using a useCopyTimeout hook
- Use vega cross icon for dialog close button
Before:
After
=> chore(trading): vega icons for withrawals table and wallet dropdown

apps/governance/src/__mocks__/react-markdown.js
In #4213, I deleted this mock because using `yarn run jest` reported
this as mocked twice. Now tests are failing because this isn't mocked.
- Reinstate deleted mock
=> fix(governance): reinstate deleted mock

apps/explorer/.env.mainnet-mirror, apps/explorer/README.md, apps/governance/.env.mainnet-mirror, apps/governance/README.md, apps/trading/.env.mainnet-mirror, apps/trading/README.md
In order for the front ends to be present for the mainnet mirror environment this PR adds configs for:
- https://explorer.mainnet-mirror.vega.rocks/
- https://console.mainnet-mirror.vega.rocks/
- https://governance.mainnet-mirror.vega.rocks/
=> feat(governance,explorer,trading): add env config for mainnet-mirror apps

libs/proposals/src/lib/proposals-hooks/use-update-network-paramaters-toasts.tsx
Closes #3734 
* added 'break-all' to the param key (it can be really long)
=> fix(proposals): truncated text in network param toast

apps/trading-e2e/src/integration/market-all.cy.ts, apps/trading/client-pages/markets/closed.tsx, apps/trading/client-pages/portfolio/account-history-container.tsx, libs/accounts/src/lib/accounts-actions-dropdown.tsx, libs/accounts/src/lib/transfer-container.tsx, libs/accounts/src/lib/transfer-form.spec.tsx, libs/accounts/src/lib/transfer-form.tsx, libs/assets/src/lib/asset-option.tsx, libs/fills/src/lib/fill-actions-dropdown.tsx, libs/markets/src/lib/components/markets-container/market-table-actions.tsx, libs/markets/src/lib/components/markets-container/use-column-defs.tsx, libs/orders/src/lib/components/order-actions-dropdown/order-actions-dropdown.tsx, libs/positions/src/lib/position-actions-dropdown.tsx, libs/positions/src/lib/positions-table.tsx, libs/proposals/src/components/proposal-actions-dropdown.tsx, libs/ui-toolkit/src/components/dropdown-menu/actions-dropdown.tsx, libs/ui-toolkit/src/components/dropdown-menu/index.ts, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-info.tsx, libs/ui-toolkit/src/components/icon/vega-icons/vega-icon-record.ts, libs/ui-toolkit/src/components/select/select.tsx, libs/withdraws/src/lib/asset-balance.tsx, libs/withdraws/src/lib/withdrawals-table.tsx
Closes #3984
Closes #3911 
Closes #3972
* table actions trigger is now highlighted when dropdown is open
* changed table actions labels
* added info icon to the vega icons collection
* added default asset for account history tab
* chosen asset for account history is not persisted in local storage
* fixed asset selector for transfer dialog
* sorted assets by name in transfer dialog (same as in deposit and withdrawal)
=> chore(trading): dropdown alignments, account history default asset, transfer dialog asset selector

apps/governance/src/routes/proposals/proposal/Proposal.graphql, apps/governance/src/routes/proposals/proposal/__generated__/Proposal.ts, libs/proposals/src/components/proposals-list/proposals-list.tsx
Closes #4052 
Temporary fix for the proposal page in governance. The proposal query errors and does not return any data if the trading termination data source spec is included in the query
- Removes trading termination data source spec from proposals query so that proposals page can still render
- Removes error from noOverlaysTemplate of proposal list in Console so that valid proposals still show
=> fix(governance,trading):  proposals not showing

apps/trading/client-pages/market/trade-grid.tsx, apps/trading/pages/styles.css, libs/accounts/src/lib/accounts-table.tsx, libs/accounts/src/lib/margin-health-chart.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-button.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/market-depth/src/lib/orderbook-row.tsx, libs/markets/src/lib/components/oracle-basic-profile/oracle-basic-profile.tsx, libs/markets/src/lib/components/oracle-full-profile/oracle-full-profile.tsx, libs/tailwindcss-config/src/theme.js, libs/ui-toolkit/src/components/notification-banner/notification-banner.tsx, libs/ui-toolkit/src/components/toggle/toggle.tsx
Follow up for #4104 
- Changes deal ticket to use market red/green instead
- Updates chart volume bars to be muted, matching order book volume bars
- Removes usage of pink in oracle profile and oracle banner
- Uses red for margin and account danger states
=> fix(trading): replace oracle details and deal ticket pink with red

.github/workflows/add_issue_new_projects.yml
part of: https://github.com/vegaprotocol/devops-infra/issues/1960
This PR changes the token used for the add issue to project to one more secure
=> chore: update the PM action secret token

apps/explorer/src/app/components/proposals/proposals-table.tsx
Closes #4356
On Explorer, the two date columns were formatted differently due to a typo. This PR fixes that typo and hopefully makes
the formats the same again.
=> fix(explorer): fix valueformatter in enactment date on proposal table

apps/governance-e2e/src/integration/view/proposal.cy.ts, libs/proposals/src/components/protocol-upgrade-proposal-notification.tsx
Closes #3259 
There's an unknown issue where the network banner does not give an estimate on capsule without several repeated prompts. This seems to be an isolated issue either due to capsule/ mocks or Cypress causing it to not work.
=> chore(governance): add e2e test for network upgrade banner

apps/explorer/src/app/components/txs/details/order/tx-order-iceberg.tsx, apps/explorer/src/app/components/txs/details/tx-order.tsx, apps/explorer/src/app/components/txs/tx-order-type.tsx
Closes #4108
Adds a little visualiser thing for iceberg options if an order has them. Tooltips to explain them.
=> feat(explorer): iceberg details on order tx

apps/governance/.env, apps/governance/.env.capsule, apps/governance/.env.devnet, apps/governance/.env.mainnet, apps/governance/.env.mainnet-mirror, apps/governance/.env.stagnet1, apps/governance/.env.testnet, apps/governance/.env.validators-testnet, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.spec.tsx, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx, apps/trading-e2e/src/integration/market-info.cy.ts, apps/trading-e2e/src/support/trading.ts, apps/trading/client-pages/markets/closed.spec.tsx, libs/markets/src/lib/components/market-info/market-info-panels.tsx, libs/markets/src/lib/components/market-info/tooltip-mapping.tsx, libs/proposals/src/lib/proposals-data-provider/proposals.mock.ts, libs/proposals/src/lib/proposals-hooks/Proposal.graphql, libs/proposals/src/lib/proposals-hooks/__generated__/Proposal.ts, libs/proposals/src/lib/proposals-hooks/index.ts, libs/proposals/src/lib/proposals-hooks/use-successor-market-proposal-details.ts
Closes #4131 
* adds parent market code or id in proposal header (links to the proposal page)
* adds `insurancePoolFraction` to the key details market info panel
* above respect `SUCCESSOR_MARKETS` feature flag
=> feat(governance): successor market proposal details

apps/trading-e2e/src/integration/trading-chart.cy.ts, libs/candles-chart/src/lib/data-source.ts, package.json, yarn.lock
Closes #4328 
Upgrade pennant to v1.10.0.
Pennant now supports an array of price monitoring bounds for a market, i.e. we can now pass more than one bounds to the candlestick chart
=> chore(trading): upgrade pennant to v1.10.0

apps/governance-e2e/src/integration/view/proposal.cy.ts
Closes #4146  #3259 
Add acs to network upgrade tests
=> chore(governance): add acs for network upgrade banner and estimate

apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards-table.tsx, apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.spec.ts, apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.ts
Closes #4436
The current calculation for this percentage is incorrect. Exactly where it is incorrect took longer to discover than
an arbitrary deadline, so instead the percentage is removed.
The complexity for this code is high. While there is a field in the API that, for each reward, returns the percentage
of the total reward, the table that displays this data is potentially aggregating multiple rewards of the same type. 
This should be straightforward, but the perceived value of this value is lower than the time it would take to trace the
logic and find the mistake.
=> fix(governance): remove incorrect individual reward percentage

libs/announcements/package.json, libs/i18n/package.json, libs/react-helpers/package.json, libs/tailwindcss-config/package.json, libs/tailwindcss-config/src/vega-custom-classes.js, libs/types/package.json, libs/ui-toolkit/package.json, libs/ui-toolkit/src/components/healthbar/healthbar.tsx, libs/utils/package.json
Part of https://github.com/vegaprotocol/vega.xyz/issues/706
Adds a dashed 'auction trigger' line to the healthbar.
Additionally cleans up some visuals which weren't updating between dark/
light mode to make sure the size of the healthbar is legible, and the
target stake inidicator is visible.
=> feat(ui-toolkit,tailwindcss-config): healthbar auction level indicator

apps/explorer/src/app/components/txs/tx-filter.tsx, apps/explorer/src/app/components/txs/tx-list-navigation.tsx, apps/explorer/src/app/components/txs/txs-infinite-list-item.spec.tsx, apps/explorer/src/app/components/txs/txs-infinite-list-item.tsx, apps/explorer/src/app/components/txs/txs-infinite-list.spec.tsx, apps/explorer/src/app/components/txs/txs-per-block.tsx, apps/explorer/src/app/hooks/get-txs-data-url.ts, apps/explorer/src/app/hooks/use-txs-data.ts, apps/explorer/src/app/routes/blocks/id/block.spec.tsx, apps/explorer/src/app/routes/parties/id/index.tsx, apps/explorer/src/app/routes/txs/home/index.tsx
- fix(explorer): fixing txsdata fetch
- fix(explorer): working txsdata fetch
- feat(explorer): partial url support
- feat(explorer): url persistence
- feat(explorer): pagination and filters in url for parties
This PR started off as just fixing #4373, which broken in the Block Explorer API in 0.72.4 or 0.72.5, but ended up being enough work that it made sense to rope in #4215 
- TX filter now persisted in URL for `txs/index` and `parties/partyId`
- Cursor before/after now persisted in URL for `txs/index` and `parties/partyId`
- Relpace deprecated `limit` usage with `before`/`after`/`first`/`last` cursor usage
- Closes #4215 
- Closes #4274 
- Closes #4373
- Closes #4237
=> feat(explorer): improve transaction pagination

apps/trading/components/liquidity-container/liquidity-container.tsx, libs/liquidity/src/lib/liquidity-table.tsx, libs/markets/src/lib/markets-provider.ts
N/A
Removes unnecessary use of forwardRef for the liquidity table, which was causing two issues
1. Clicking the liquidity tab was triggering a full page load
2. Clicking the liquidity tab was 'locking' the resizable grid
=> fix(trading): lp table forward ref breaking resize grid

apps/trading/components/welcome-dialog/get-started.spec.tsx, apps/trading/components/welcome-dialog/get-started.tsx
N/A
Fixes an issue where the get started content was rendered even when connected
=> fix(trading): dont render get started if connected

apps/explorer/src/app/components/markets/market-details.tsx, apps/explorer/src/app/components/txs/details/tx-proposal.tsx, apps/explorer/src/app/components/txs/tx-order-type.tsx
- feat(explorer): specific label for successor markets
- feat(explorer): labvel fix and insurance pool details
- feat(explorer): succession line in market details
Closes #4175 
- Add 'Proposal: Successor market' to TX list
- Add to TX page: Insurance Pool Percentage if set
- Add to TX page: previous market if set
- Add to market details page: succession line panel
=> feat(explorer): successor markets

libs/accounts/src/lib/transfer-container.tsx
Closes #4537 
Remove redundant connect wallet button
=> fix(trading): remove redundant connect wallet button

libs/deal-ticket/src/components/deal-ticket/deal-ticket-container.tsx
N/A
Fixes a problem where the get started content is pushed off screen if the market fails to load. As seen below:
=> fix(trading): prevent overflow in deal ticket if market fails to load

apps/explorer-e2e/src/integration/market.cy.js, apps/explorer-e2e/src/integration/proposal.cy.js, apps/explorer-e2e/src/support/common.functions.js, apps/explorer-e2e/src/support/governance.functions.js, apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts, apps/governance-e2e/src/integration/flow/proposal-flow.cy.ts, apps/governance-e2e/src/integration/flow/proposal-forms.cy.ts, apps/governance-e2e/src/integration/flow/proposal-list.cy.ts, apps/governance-e2e/src/integration/flow/rewards-flow.cy.ts, apps/governance-e2e/src/integration/flow/staking-flow.cy.ts, apps/governance-e2e/src/integration/flow/token-association-flow.cy.ts, apps/governance-e2e/src/integration/flow/withdrawal-flow.cy.ts, libs/cypress/src/index.ts, libs/cypress/src/lib/commands/mock-chain-id.ts
- Fix failing e2e tests due to wallet update that required chain id to now be mocked
- Add e2e test for successor market display in block explorer
=> test(explorer): successor market explorer

apps/governance/src/routes/proposals/components/proposal/proposal.tsx, apps/governance/src/routes/proposals/components/vote-details/vega-transaction-dialog.spec.tsx, apps/governance/src/routes/proposals/components/vote-details/vote-buttons.spec.tsx, apps/governance/src/routes/proposals/components/vote-details/vote-buttons.tsx, apps/governance/src/routes/proposals/components/vote-details/vote-details.tsx, apps/governance/src/routes/proposals/components/vote-details/vote-transaction-dialog.tsx
Closes #3522
Closes #3583 
Previously, a generic error message was shown when an error occurred and the vote failed. Now, we are getting the error message from the transaction, and we only fall back to the generic message when the tx error message doesn't exist (which is likely never).
=> fix(governance): better vote error handling

apps/trading/client-pages/market/trade-grid.tsx, apps/trading/client-pages/market/trade-views.tsx, apps/trading/components/positions-container/positions-container.tsx, apps/trading/components/positions-menu/index.ts, apps/trading/components/positions-menu/positions-menu.tsx, libs/positions/src/lib/positions-data-providers.spec.ts, libs/positions/src/lib/positions-data-providers.ts, libs/positions/src/lib/positions-manager.tsx, libs/positions/src/lib/positions-table.spec.tsx, libs/positions/src/lib/positions-table.tsx, specs/7004-POSI-positions.md
#4270 
- Filters out positions on closed markets by default
- Adds menu option to toggle the filter on or off
- Reduces pinned column width for buttons
=> feat(positions): filter closed markets in positions table

apps/trading/pages/_document.page.tsx, apps/trading/pages/index.page.tsx
Closes N/A
Reverts unsuccessful trial. 
Warning: viewport meta tags should not be used in _document.js's <Head>. 
https://nextjs.org/docs/messages/no-document-viewport-meta
=> chore(trading): revert metadata update - viewport meta tags should not be used in _document.js's

libs/proposals/src/lib/proposals-data-provider/proposals-data-provider.tsx
Closes #4473 
Closes #4364 
It can happen that a NewMarket proposal is incomplete and does not contain `futureProduct` details. This PR adds a guard that ignores that error for proposal listings.
Example of "failed" proposal: 57b6a70ff3c17c4002befc03f94fc8e6e5fe917da587c4b36672bb1c404966c9 (TESTNET)
=> fix(proposals): error policy guard for proposal data provider

libs/orders/src/lib/components/order-data-provider/Orders.graphql, libs/orders/src/lib/components/order-data-provider/__generated__/Orders.ts, libs/orders/src/lib/components/order-list/order-list.tsx, libs/orders/src/lib/components/stop-orders-manager/stop-orders-manager.tsx, libs/orders/src/lib/components/stop-orders-table/stop-orders-table.spec.tsx, libs/orders/src/lib/components/stop-orders-table/stop-orders-table.tsx
Closes #4125 
Add actions menu to stop orders table. It's shown only if stop order is triggered and order was created. Two actions are available "Copy order ID" and "View order details", same as in orders table.
=> feat(trading): view stop order history

apps/explorer/src/app/components/txs/details/tx-issue-signatures.tsx
Closes #2947
Issue Signatures component was not rendering the details because the TX was not being parsed properly. This small change fixes it.
=> fix(explorer): properly render issue signatures tx

libs/proposals/src/lib/protocol-upgrade-proposals/use-time-to-upgrade.spec.ts, libs/proposals/src/lib/protocol-upgrade-proposals/use-time-to-upgrade.ts
Closes #4607 
Block duration value is not just a number it can be presented in seconds, milliseconds, nanoseconds, microseconds, minutes and hours. This PR fixes the problem of parsing that value for time estimations.
=> fix(proposals): parsing block duration value

apps/trading/pages/styles.css
N/A
Sets pennant default font to alpha and pennant monospace font to system so we match better with the rest of the app
=> fix(trading): update fonts for pennant

apps/explorer/src/app/components/txs/details/order/tx-order-iceberg.tsx, apps/explorer/src/app/components/txs/details/tx-order.tsx
Closes #4495
The iceberg visualiser in explorer did not format the sizes appropriately for the market. This PR makes it do just that.
=> fix(explorer): format iceberg size according to market

apps/trading/components/accounts-menu/accounts-menu.tsx, apps/trading/components/deposits-menu/deposits-menu.tsx, apps/trading/components/positions-menu/positions-menu.tsx, apps/trading/components/withdrawals-menu/withdrawals-menu.tsx, libs/candles-chart/src/lib/candles-menu.spec.tsx, libs/candles-chart/src/lib/candles-menu.tsx, libs/orders/src/lib/components/open-orders-menu/open-orders-menu.tsx
N/A
- Switches buttons in the pane context areas to be our default gray rather than primary (yellow) intent
- Changes chart dropdowns to using trading variant
=> chore(trading): change pane context buttons color

apps/trading/components/market-selector/market-selector.spec.tsx, apps/trading/components/market-selector/market-selector.tsx, apps/trading/components/market-selector/sort-dropdown.tsx, apps/trading/components/market-selector/use-market-selector-list.spec.tsx, apps/trading/components/market-selector/use-market-selector-list.ts
N/A
Makes top traded the default sort order in the market selector
=> chore(trading): make top traded default sort for market selector

.husky/commit-msg, .husky/pre-commit, .husky/pre-push
Slightly changes the husky approach. These are relatively light touch, but point 3 might irritate some people. ~I'd like unit tests to be run pre-push too, but I'll see if I can start that just for Explorer and then start trying to convince other projects.~
1. `commit-msg` no longer reformats files, so you won't have changes after a commit. `commitlint` still runs
2. `pre-commit` reformats the files, so only formatted versions should be committed (effectively moved from `commit-msg`)
3. `pre-push` now checks formatting and will prevent pushing with unformatted files. This should stop us wasting CI time with pushes that will fail.
4. `pre-push` runs the unit tests for a changed project. `trading` has been explicitly ignored, so this mainly concerns `governance` and `trading`. I've excluded …
=> chore(explorer,trading,governance): reconfigure hooks

apps/explorer/src/app/routes/network-parameters/index.tsx, apps/explorer/src/app/routes/network-parameters/network-parameters.spec.tsx, apps/explorer/src/app/routes/network-parameters/network-parameters.tsx, apps/explorer/src/app/routes/network-parameters/structure-network-params.spec.tsx, apps/explorer/src/app/routes/network-parameters/structure-network-params.tsx
Issue: #1447
An implementation of headings with anchors that uses the network param keys nested structure to render the required headings and subheadings.
=> feat(explorer): add headings and anchors to net params page

apps/governance-e2e/src/integration/view/proposal.cy.ts, apps/governance/src/routes/proposals/components/protocol-upgrade-proposals-list-item/protocol-upgrade-proposals-list-item.tsx, apps/governance/src/routes/router-config.tsx, libs/environment/src/hooks/use-links.ts, libs/proposals/src/components/protocol-upgrade-countdown.tsx, libs/proposals/src/components/protocol-upgrade-in-progress-notification.tsx, libs/proposals/src/components/protocol-upgrade-proposal-notification.tsx
Issue: #4700
Protocol upgrade proposal urls have until now only used the upgrade tag, i.e. /proposals/protocol-upgrade/:tag
This is a problem if multiple proposals are made for the same upgrade version. We have no unique ID for these proposals, so to make proposal urls more unique, we are including the block height, i.e. /proposals/protocol-upgrade/:tag/:blockHeight
This work affects Governance and also the upgrade notification banner, which is displayed across the apps.
=> fix(governance,environment,proposals): network upgrade proposal urls include block height

apps/governance/src/routes/rewards/epoch-total-rewards/epoch-total-rewards.tsx, libs/announcements/package.json, libs/announcements/project.json, libs/i18n/package.json, libs/i18n/project.json, libs/react-helpers/package.json, libs/react-helpers/project.json, libs/tailwindcss-config/package.json, libs/tailwindcss-config/project.json, libs/types/package.json, libs/types/project.json, libs/ui-toolkit/package.json, libs/ui-toolkit/project.json, libs/utils/package.json, libs/utils/project.json, libs/wallet/package.json, libs/wallet/project.json
Issue: #4603 
- Sets rollup configs to not bundle peer deps
- Removes peerDependencies from package.json for libs as its not required
- Bump versions for affected packages
=> fix(trading,governance,explorer): peer deps for published packages

apps/governance/src/routes/proposals/components/proposals-list/proposals-list.tsx
Issue: #4716
Upgrade proposals were being sorted by upgrade block height, but alphanumerically. Now sorted numerically.
=> fix(governance): corrected sorting of upgrade proposals by blockheight

apps/governance/src/app.tsx, apps/governance/src/routes/home/index.tsx, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx, apps/governance/src/routes/proposals/components/proposals-list/proposals-list.tsx, apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx, apps/governance/src/routes/rewards/home/rewards-page.tsx, apps/governance/src/routes/token/index.tsx, apps/governance/src/styles.css
Issue: #4530
Styling tweaks to make Governance more mobile friendly
Examples:
prev:
now:
prev:
now:
prev:
now:
prev:
now:
=> feat(governance): improve the display of Governance app on mobile

libs/candles-chart/src/lib/candles-chart.tsx
Issue: #4727 
Change parameter of displaying candles to get zoom effect on chart
with reduced gaps:
=> chore(candles-chart): show more candles by default

CODEOWNERS
N/A
Adds the new frontend-qa user group to codeowners so that pull requests must be approved by at least one qa
=> chore(trading,governance,explorer): add frontend-qa to codeowners

apps/trading/pages/styles.css, libs/candles-chart/src/lib/candles-chart.tsx
Issue: #4727 
make the number of candles depend on the size of the window (place dedicated for the chart)
=> chore(trading): initial number of candles depended on pane width

apps/trading/pages/styles.css, libs/candles-chart/src/lib/candles-chart.tsx, libs/candles-chart/src/lib/use-candles-chart-settings.ts, package.json, yarn.lock
Issue: #4651 
- Uses new pennant options to reduce candle size
- Updates the candles chart store to persist study pane sizes
=> feat(trading): store and pass study sizes to chart, reduce candles gap

apps/explorer-e2e/.env.devnet, apps/explorer-e2e/.env.mainnet, apps/explorer-e2e/.env.testnet, apps/explorer/.env.capsule, apps/explorer/.env.devnet, apps/explorer/.env.mainnet, apps/explorer/.env.mainnet-mirror, apps/explorer/.env.stagnet1, apps/explorer/.env.testnet, apps/explorer/.env.validators-testnet, apps/explorer/.env.vegacapsule, apps/governance-e2e/.env, apps/governance-e2e/.env.devnet, apps/governance-e2e/.env.mainnet, apps/governance-e2e/.env.testnet, apps/governance/.env.capsule, apps/governance/.env.devnet, apps/governance/.env.mainnet, apps/governance/.env.mainnet-mirror, apps/governance/.env.stagnet1, apps/governance/.env.testnet, apps/governance/.env.validators-testnet, apps/trading-e2e/.env, apps/trading-e2e/.env.capsule, apps/trading/.env.mainnet, apps/trading/.env.stagnet1, apps/trading/.env.testnet, apps/trading/.env.validators-testnet
Closes #4759 
Added `NX_ORACLE_PROOFS_URL` to all environments as it does not get appended from .env
This won’t sort  the issue in explorer but it would fix the oracle profiles in console
=> chore(trading): add oracle proofs url to all envs

apps/trading/components/welcome-dialog/get-started.tsx
Closes #4763 
Uses the correct link for the alternative network prompt
=> fix(trading): correct link for get started prompt

apps/trading/client-pages/market/trade-grid.tsx, libs/ui-toolkit/src/components/tabs/tabs.tsx
Closes #4795 
add overflow hidden to candles tab container
=> fix(trading): add overflow hidden to candles tab container

apps/trading/client-pages/market/trade-grid.tsx, apps/trading/components/layouts/layout-with-sidebar.tsx, apps/trading/pages/styles.css, libs/candles-chart/src/lib/candles-chart.tsx, libs/candles-chart/src/lib/use-candles-chart-settings.ts
Closes #4769 
Tweaks to the layout to make for a better default experience
- Note AgGrid does not adjust header height as the screen is resized. This is calculated and set on load.
=> chore(trading): layout adjustments to accomodate default 13 inch screens

.github/workflows/console-test-run.yml
Cache vega binaries in python console test, to avoid too many direct downloads.
=> chore(trading): cache console test vega binaries

libs/accounts/src/lib/accounts-table.tsx
Closes #4794 
Displays empty no rows label if pinned asset is only asset to display.
=> fix(accounts): hide no rows label when there is only pinned row

.github/workflows/ci-cd-trigger.yml
Temporarily disable console-test run, to unblock runners for other uses.
=> chore(trading): disable console-test run until CI fixed

libs/data-provider/src/helpers.ts, libs/markets/src/lib/components/market-info/market-info-data-provider.ts, libs/markets/src/lib/markets-provider.ts
Closes N/A
`marketConnection` queries comes with all data and an error (that can be safely ignored) when a market is proposed via protos (the UI doesn't let you) without conditions. 
This error not ignored was destroying the UI.
Before the fix:
=> fix(trading): ignore conditions list empty

apps/governance-e2e/src/support/proposal.functions.ts
Fixes failing proposal test due to `performanceHysteresisEpochs` needing to be `> 1`
=> chore(governance): fix failing proposal submission

apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards.tsx
Closes #4862
On the individual rewards page, a query meant to update data when an epoch changes would be triggered by the data being updated, creating a loop. To solve this, I've refined the conditions for when the refetch is called by keeping track of the epochId and only running the refetch when the epochId actually changes.
=> fix(governance): removed loop caused by rewards epoch refresh

libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
Related  to #4870
In deal ticket margin and liquidation price estimation show only worst case value formatted using quantum. In tooltip show range with maximum precision.
=> feat(deal-ticket): show worst case instead of ranges in estimated values

apps/trading/pages/styles.css
Closes #4823 
Makes the volume bar colors match the candle fill colors
=> chore(trading): make volume bars color match candle color

apps/trading/components/header/header.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/deal-ticket/src/components/deal-ticket/key-value.tsx, libs/ui-toolkit/src/components/tooltip/tooltip.tsx
Closes #4733
Remove underline from tooltip trigger by default. Make it parameterized. Merge to `main` branch
-
=> chore(trading): remove underlines on tooltips

apps/trading/components/sidebar/sidebar.tsx
N/A
Prevents ending up in a state where you can be on the deposit page _and_ have the deposit sidebar open at the same time
=> fix(trading): prevent deposit sidebar showing on corresponding standalone page

.github/workflows/cypress-run.yml
Add logic for choosing correct runner for cypress tests depending on base branch.
main -> mainnet-compatible-runner
develop (or others) -> self-hosted-runner
=> chore(ci): add logic for choosing correct runner for cypress tests depending on base branch

apps/explorer-e2e/src/integration/market.cy.js, apps/governance-e2e/.env, apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/integration/flow/proposal-enacted.cy.ts
Closes #4869 
- Remove commented out assertions that are not needed anymore
- Fix failing tests from perpetual market changes
=> chore(governance): remove explorer market diff test

.github/workflows/cypress-run.yml
Some apps release process require push to release branch, and then cypress tests are being run. We need to run mainnet compatible runner for them.
=> chore(ci): add mainnet compatible runner to release mainnet branch push actions

.github/workflows/lint-pr.yml
Sometimes lint-pr is not triggered properly, added sync and reopened to fix that.
=> chore(ci): trigger lint-pr on repoened and sync

apps/explorer/src/app/routes/oracles/home/index.tsx
Closes #4705
Ignores graphql errors on the Oracle page so that the page can render. I will cherry-pick this to develop after approval.
=> chore(explorer): ignore errors on oracle page

.github/workflows/ci-cd-trigger.yml
We don't need to run e2e every time ci/cd job is triggered. Only if:
- pull request to main
- pull request to develop
- push to release branch
Also added push to main as trigger to do ci/cd job, as it didn't produce main image without that.
=> chore(ci): add conditions to run e2e tests

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/hooks/use-position-estimate.ts
Closes #4948 
Add checking price or size are 0 for prevent calls for estimates position
-
-
=> fix(deal-ticket): prevent empty call estimate position

apps/trading/components/market-state/market-state.tsx, apps/trading/lib/utils/index.ts, libs/deal-ticket/src/components/trading-mode-tooltip/trading-mode-tooltip.tsx, libs/environment/src/hooks/use-links.ts
=> fix(trading): update filter for market selector to include suspended via governance

apps/trading/.env
This fixes missing "Wallet Connect" button.
Missing `projectId` was a root cause of this issue, re-adding that in this PR.
=> fix(trading): missing wallet connect button

.github/workflows/ci-cd-trigger.yml, .github/workflows/cypress-run.yml
There was some errors that may be caused by following example:
```
if [ ${{ github.base_ref }} == 'main' ]; then
echo "runner=mainnet-compatible-runner" >> $GITHUB_OUTPUT
```
if `github.base_ref` was emtpy, then error may have occured.
Changed such cases to:
```
if [ '${{ github.base_ref }}' == 'main' ]; then
echo "runner=mainnet-compatible-runner" >> $GITHUB_OUTPUT
```
=> chore(ci): add missing quote marks that may have caused some workflow fails

libs/wallet/src/connect-dialog/injected-connector-form.tsx, libs/wallet/src/connectors/injected-connector.ts
Closes #4441 
Handles user rejection error so resulting UI doesn't show the error state
=> fix(wallet): dont show error state if user rejects connection

libs/accounts/src/lib/breakdown-table.tsx
Sets the usage breakdown to order by market desc, as previously it would flip flop between orders (making testing hard).
=> chore(trading): set default sort order

libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/deal-ticket/src/components/deal-ticket/key-value.tsx
closes #4973
Label and values are wrongly aligned when value is too long to fit in one line
Before
After
=> feat(deal-ticket): fix margin and fees alignment

apps/governance-e2e/src/integration/flow/proposal-details.cy.ts, apps/governance-e2e/src/integration/flow/staking-flow.cy.ts, apps/governance-e2e/src/integration/view/proposal.cy.ts
There's currently an unknown issue with capsule that is causing capsule to fail in the nightly run.
- Some staking tests are temporarily skipped until the cause of the problem is found
- Fixed failing perp test
Related ticket: https://github.com/vegaprotocol/vegacapsule/issues/417
=> test(governance): skip staking test

.github/workflows/console-test-run.yml
Relates to  #4886 
It creates a docker image of trading app on given branch, then pass it to console-test job to run tests against it. As a next step we could reuse images in other jobs in workflow.
=> chore(ci): separate export docker image job in console-test workflow

apps/trading/client-pages/market/market-header-stats.tsx, apps/trading/components/header/header.tsx, apps/trading/components/layouts/layout-with-sidebar.tsx, apps/trading/components/market-header/market-header.tsx
N/A
- Gives the sidebar a background color and a border to make it more integrated to the sidebar. This makes the sidebar work more nicely with layouts that aren't full width
- Reduce gap between market code and market product type in market header
- Make gaps between HeaderStats components consistent for market page and liquidity page. Reduce spacing slightly
=> chore(trading): add background to sidebar and minor tweaks

apps/trading/client-pages/market/trade-grid.tsx, apps/trading/components/funding-payments-container/funding-payments-container.tsx, libs/funding-payments/src/lib/FundingPayments.graphql, libs/funding-payments/src/lib/__generated__/FundingPayments.ts, libs/funding-payments/src/lib/funding-payments-manager.tsx
Closes #5016
Move Funding payments tab to MainGrid, show it only for perp market and show data only for current market
=> feat(trading): adjust layout for funding payments

apps/trading/client-pages/closed-market/closed-market.tsx, apps/trading/client-pages/closed-market/index.ts, apps/trading/client-pages/liquidity/liquidity-sidebar.tsx, apps/trading/client-pages/market/market.tsx, apps/trading/client-pages/markets/closed.spec.tsx, apps/trading/client-pages/markets/closed.tsx, apps/trading/client-pages/markets/markets-sidebar.tsx, apps/trading/client-pages/portfolio/portfolio-sidebar.tsx, apps/trading/components/layouts/layout-with-sidebar.tsx, apps/trading/components/market-header/market-header.tsx, apps/trading/components/navbar/navbar.spec.tsx, apps/trading/components/navbar/navbar.tsx, apps/trading/components/orders-container/orders-container.tsx, apps/trading/components/sidebar/sidebar.spec.tsx, apps/trading/components/sidebar/sidebar.tsx, apps/trading/lib/hooks/use-market-click-handler.ts, apps/trading/lib/links.ts, apps/trading/pages/client-router.tsx
Closes #4961 
- Removes the additional page and redirect for a closed market
- Changes /markets/all to just /markets
N/A
- Refactored routing to 'flatten' the routes and make it easier to manage
- Refactored LayoutWithSidebar to not care about routing and instead take a header and sidebar content has props. This makes managing the sidebar much easier and more declarative. We can simply make a component for the sidebar for each page.
=> fix(trading): remove additional page for closed markets

libs/assets/src/lib/asset-details-table.tsx
Closes #5067
Add missing button for easy copying is of the asset in asset detail dialog 
-
=> chore(trading): add button for copying asset id

apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.spec.tsx, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx
Closes #5085
To avoid this (valid) situation:
We now fall back to the destination type, as we do for the source type if the source field isn't set.
=> feat(governance): transfers destination field can fallback to type

apps/explorer/src/app/routes/layout.tsx, apps/explorer/src/app/routes/restricted/index.tsx, apps/explorer/src/app/routes/route-names.tsx, apps/explorer/src/app/routes/router-config.tsx
Adds a page that can be shown for 451 errors
- Add route
- Add page
Note: no logic for sending users here is contained in the PR. That is done in the infra.
=> feat(explorer): add restricted route

libs/accounts/src/lib/accounts-table.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/positions/src/lib/Positions.graphql, libs/positions/src/lib/__generated__/Positions.ts, libs/positions/src/lib/liquidation-price.spec.tsx, libs/positions/src/lib/liquidation-price.tsx, libs/positions/src/lib/positions-table.tsx
N/A
- Remove preparation (strip decimal places) of open_volume_only value of estimate liquidation query result as its not longer required.
- Set `scaleLiquidationPriceToMarketDecimals` as an un-modifiable query variable and updated commenting around the use of this variable and the resulting required formatting.
- Add a unit test for the liquidation price cell
- Fix misaligned deposit icon and remove unused argument from accounts table
N/A
=> chore(trading,positions): update estimatePosition query to use market decimals for liquidation price

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/environment/src/hooks/use-links.ts
=> feat(trading): add tooltips for iceberg and post or reduce only

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
Closes #5048 
The size should be in quote base unit coming from tags
Fix: 
=> fix(trading): quote base unit for size

apps/trading/client-pages/referrals/referral-statistics.tsx
Closes #5140 
* adds handling for next tier when there's no current tier
* adds next tier number in tiles
* replaces '-' with 'None'
N/A
=> fix(trading): referrals next tier tiles

libs/candles-chart/src/lib/candles-menu.spec.tsx, libs/candles-chart/src/lib/candles-menu.tsx, libs/candles-chart/src/lib/use-candles-chart-settings.ts
Closes #5079 
Combines overlays and studies into a single 'Indicators' dropdown
=> feat(candles-chart): combine overlays and studies into indicators dropdown

libs/data-provider/src/use-data-provider.ts, libs/deal-ticket/src/components/deal-ticket/deal-ticket.spec.tsx, libs/fills/src/lib/Fills.graphql, libs/fills/src/lib/__generated__/Fills.ts, libs/fills/src/lib/fills-manager.tsx, libs/fills/src/lib/fills-table.tsx, libs/orders/src/lib/components/order-data-provider/order-data-provider.ts, libs/orders/src/lib/components/order-list-manager/order-list-manager.spec.tsx, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/orders/src/lib/components/stop-orders-manager/stop-orders-manager.spec.tsx, libs/trades/src/lib/trades-manager.tsx
Closes #4898, #5086
Add option to load another page of trades and orders. Inform how many items where loaded. Make it clear that results are limited by filters applied.
=> feat(trading): show full history of orders, fills and trades

apps/trading/client-pages/referrals/apply-code-form.tsx, apps/trading/client-pages/referrals/hooks/Referees.graphql, apps/trading/client-pages/referrals/hooks/ReferralSetStats.graphql, apps/trading/client-pages/referrals/hooks/__generated__/Referees.ts, apps/trading/client-pages/referrals/hooks/__generated__/ReferralSetStats.ts, apps/trading/client-pages/referrals/hooks/use-referral.ts, apps/trading/client-pages/referrals/referral-statistics.tsx, apps/trading/client-pages/referrals/tiers.tsx, apps/trading/client-pages/referrals/tile.tsx, libs/types/src/__generated__/types.ts
N/A
* adds "My Volume" tile for the referrer view
* adds "(last X epochs)" where X is a program's window lenght
* fixes final commission rate
* moves "Created at" under the code tile
TODO:
=> fix(trading): referrer stats tiles

libs/ui-toolkit/src/components/sparkline/sparkline.stories.tsx, libs/ui-toolkit/src/components/sparkline/sparkline.tsx
N/A
Fixes an edge case where the sparkline can appear to go up even if there is a price decrease, when the market is less than 24h old. This was happening because we were padding the sparkline values with average value instead of using the first value in the data set
=> fix(ui-toolkit): sparkline appearing to go up when the price moved down

libs/liquidity/src/lib/liquidity-data-provider.ts, libs/liquidity/src/lib/liquidity-table.tsx
Closes #5031
[Ensure market LP view can handle Core API changes to liquidity provision status](https://github.com/vegaprotocol/frontend-monorepo/issues/5031)
=> feat(trading): liquidity provision current and pending on update

apps/trading/client-pages/referrals/hooks/use-referral.ts, apps/trading/client-pages/referrals/referral-statistics.tsx, apps/trading/client-pages/referrals/table.tsx, apps/trading/client-pages/referrals/tile.tsx, libs/environment/src/hooks/use-links.ts
Partially addresses #5155 
- Removes next tier indicators
- Show windowLength value for combined set volume on referee view
- Adds tooltips for qUSD
TODO:
=> chore(trading): referrals stats tweaks

apps/trading/.eslintrc.json
N/A
Fixes linting of unnecessary build files
=> chore(trading): ignore .next from lint

libs/datagrid/src/index.ts, libs/datagrid/src/lib/pagination.spec.tsx, libs/datagrid/src/lib/pagination.tsx, libs/fills/src/lib/fills-manager.tsx, libs/funding-payments/src/lib/funding-payments-manager.tsx, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/trades/src/lib/trades-manager.tsx
N/A
- Fixes an issue where if no rows are loaded it just says 'items loaded' and not '0 items loaded'
- Makes a component for rendering logic of pagination
- Changes to use the word 'row' instead of 'item'
Before:
After:
=> fix(trading): empty items loaded text

libs/candles-chart/src/lib/Candles.graphql, libs/candles-chart/src/lib/__generated__/Candles.ts, libs/markets/src/lib/__generated__/market-candles.ts, libs/markets/src/lib/__generated__/markets-candles.ts, libs/markets/src/lib/market-candles.graphql, libs/markets/src/lib/markets-candles.graphql
Closes #5168
By adding `{ pagination: { last: 1000}` to the query we're able to get the latest candles. 
After: 
Before: 
=> fix(trading): pagination limit for candles

apps/governance/src/routes/proposals/components/proposal-referral-program-details/proposal-referral-program-details.spec.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/deal-ticket/src/components/fees-breakdown/fees-breakdown.spec.tsx, libs/deal-ticket/src/components/fees-breakdown/fees-breakdown.tsx, libs/markets/src/lib/market-utils.spec.tsx, libs/utils/src/lib/format/number.spec.ts, libs/utils/src/lib/format/number.ts
Addresses #5165 
- Fixes an issue with the rendering logic of the fee total. If the fee total was 0 we were getting the classic react issue where comparing with && on 0 ended up with the 0 being rendered.
- Fixes an issue where were rounding fee factors to 2 dps resulting in inaccurate information
N/A
=> fix(deal-ticket): fees breakdown rendering issues

apps/explorer/src/app/components/txs/txs-infinite-list-item.spec.tsx, apps/explorer/src/app/components/txs/txs-infinite-list-item.tsx, apps/explorer/src/app/components/txs/txs-infinite-list.tsx, apps/explorer/src/app/routes/types/block-explorer-response.d.ts
- feat(explorer): add time to tx list
- feat(explorer): tweak appearance of columns for small screens
Closes #4236
Now it is available in the API, shows a timestamp on the TX list on larger screens. Hidden on smaller screens because it's quite a long string.
=> feat(explorer): add timestamp to tx list

libs/accounts/src/lib/accounts-data-provider.ts
Closes #5177 
- Removes vesting accounts from the USED_ACCOUNT_TYPES constant so that they don't get totaled up
- Removes filter on accounts for the breakdown, so that all users accounts are shown in the breakdown table
=> fix(accounts): dont add vesting account balances to used total

apps/trading/client-pages/market/trade-panels.tsx
Closes #5166 
Simplest way to hide funding tabs if market is not a perpetual. 
=> fix(trading): hide funding tabs if market is not perp

libs/accounts/src/lib/transfer-container.tsx, libs/accounts/src/lib/transfer-form.spec.tsx, libs/accounts/src/lib/transfer-form.tsx
N/A
Fixes
- Validation for amount was always using the general account. Now the validation will check the currently select 'from account'
- Key selection would default to manual text entry if the user only had one pubkey. Now we always default to using a select dropdown to make same key transfers easier. You can still switch to manual entry if needed
Adds
- Use max button which will set the amount to the maximum of the currently selected from account
=> fix(accounts): fix key selection and validation, and add use max to transfers

apps/trading-e2e/src/integration/market-liquidity.cy.ts, libs/liquidity/src/lib/liquidity-table.spec.tsx, libs/liquidity/src/lib/liquidity-table.tsx
N/A
Make pending values more obvious for `Updating next epoch` records.
=> fix(trading): update LP table on Updating next epoch

apps/governance/src/components/vega-wallet/hooks.ts, apps/governance/src/components/wallet-card/wallet-card.tsx, apps/governance/src/i18n/translations/dev.json, libs/accounts/src/lib/transfer-form.spec.tsx, libs/accounts/src/lib/transfer-form.tsx, libs/environment/src/hooks/use-links.ts, libs/network-parameters/src/use-network-params.ts
Closes #5167 
Closes #5201 
* adds "Vesting" and "Vested" accounts to the wallet card
* sums the balances from general and vested accounts in transfer form
* adds "Redeem" button that navigates to the Console's transfer form
N/A
=> feat(governance,accounts): vesting and vested accound in wallet card, fix transfer form to account

apps/trading/client-pages/transfer/transfer.spec.tsx, apps/trading/client-pages/withdraw/withdraw.spec.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/deal-ticket/src/components/fees-breakdown/fees-breakdown.tsx, libs/fills/src/lib/fills-table.spec.tsx, libs/fills/src/lib/fills-table.tsx
Closes #4408 #4713
Changes in fills table - labels split to fit into tooltip
Changes in deal ticket - fee discount pill moved to the label, intent changed to info
=> feat(trading): fee discounts tweaks

package.json, yarn.lock
Closes #5192 
Updates to the latest version of Pennant which now throttles at 60fps by default. The library has also been updated to take the throttle ms as a prop, so if we run into problems we can increase the throttle time without requiring and additional pennant release
=> chore(candles-chart): update pennant package so chart draws at 60 fps

apps/trading/components/fees-container/Fees.graphql, apps/trading/components/fees-container/__generated__/Fees.ts, apps/trading/components/fees-container/fees-container.tsx, apps/trading/components/fees-container/stat.tsx, apps/trading/components/fees-container/use-referral-stats.spec.ts, apps/trading/components/fees-container/use-referral-stats.ts, apps/trading/components/fees-container/utils.spec.ts, apps/trading/components/fees-container/utils.ts
Closes #5215
* fixed total discount calculation
* removed trailing zeroes from "My trading fees"
* added tooltips:
* explaining 0% when there's no program running (volume or referral)
* explaining how total is being calculated
* replaced the contents of 4th tile with referral info if the connected pubkey is a referrer
* added "no program active" messages to 3rd and 4th tile
* fixed adjusted fee calculation
Adjusted fee formula:
`fee = total_fee * (1 - total_discount)`
=> fix(trading): fees page issues

libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/orders/src/lib/components/order-list/order-list.tsx, libs/web3/src/lib/TransactionResult.graphql, libs/web3/src/lib/__generated__/TransactionResult.ts, libs/web3/src/lib/use-vega-transaction-store.spec.tsx, libs/web3/src/lib/use-vega-transaction-toasts.spec.tsx, libs/web3/src/lib/use-vega-transaction-toasts.tsx, libs/web3/src/lib/use-vega-transaction-updater.spec.tsx
=> feat(trading): close position stopped and IOC behaviour update

libs/markets/src/lib/market-data-provider.ts
Closes #5035
Don't hide funding rate when market in monitoring auction.
=> fix(trading): display funding rate when market in monitoring auction

libs/liquidity/src/lib/liquidity-table.tsx
Closes #5252
Fix percentage formatter rounding in liquidity table.
After:
Before: 
=> fix(trading): fix percentage formatter rounding in liquidity table

apps/trading/components/settings/settings.tsx, apps/trading/next.config.js
N/A
Adds commit hash and tag to settings view
Adds some basic node with execSync to grab the info and put it in the environment
=> chore(trading): add git hash and tag into settings view

apps/trading/client-pages/referrals/apply-code-form.tsx, apps/trading/client-pages/referrals/referral-statistics.tsx
=> feat(trading): referral preview update

apps/explorer/src/app/components/txs/details/chain-events/index.tsx, apps/explorer/src/app/components/txs/details/chain-events/tx-contract-call.spec.tsx, apps/explorer/src/app/components/txs/details/chain-events/tx-contract-call.tsx, apps/explorer/src/app/components/txs/details/tx-chain-event.tsx
- chore(explorer): refactor eth result decoding and contract call view
Closes #5189
Adds more details about the Ethereum source/result contained in Ethereum Contract Call chain events
=> fix(explorer): improve chain event tx view for contract calls

apps/explorer/src/app/components/asset-balance/asset-balance.tsx, apps/explorer/src/app/routes/parties/id/components/party-accounts.tsx
- chore: sort
- fix(explorer): final sort order
Closes #5209. Removes the 'Account breakdown' view of a party's assets, using a simple table of all of the party's accounts instead.
Two examples to demonstrate how the sorting works
=> feat(explorer): simplify party accounts page

libs/liquidity/src/lib/liquidity-table.tsx
Closes #5279 
Fees summed from ACCOUNT_TYPE_LP_LIQUIDITY_FEES were being multiplied by the stakeToCcyVolume network parameter.
=> fix(trading): do not use stakeToCcyVolume to format fees value

apps/trading/client-pages/markets/markets-sidebar.tsx
Closes N/A
Fixes an issue where if a market was in a price monitoring auction the deal ticket isn't shown. This change makes the deal ticket button always show regardless of market state or trading mode
=> fix(trading): show deal ticket in sidebar by default

libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx
Closes #5308 
Re-enable margin estimate UI for perps market since https://github.com/vegaprotocol/vega/pull/10119 and https://github.com/vegaprotocol/vega/pull/10122 are deployed
=> chore(deal-ticket): re-enable margin estimates for perps

.github/workflows/console-test-run.yml
Increasing the number of tests running in parallel to 6. I believe the tests are stable at this number and it saves roughly 2 minutes in workflow time.
=> chore(ci): increase number of tests in parallel

apps/trading/client-pages/markets/market-list-table.tsx, apps/trading/client-pages/markets/use-column-defs.tsx, apps/trading/e2e/tests/market/test_markets_all.py, libs/datagrid/src/lib/ag-grid/ag-grid-themed.tsx, libs/markets/src/lib/__generated__/markets-data.ts, libs/markets/src/lib/markets-data.graphql, libs/markets/src/lib/markets-data.mock.ts, libs/positions/src/lib/positions-data-providers.ts, libs/types/src/__generated__/types.ts
Closes #5270
Closes #5239 
Closes #5019 
Partially Closes #5188 
=> feat(trading): market list snags and disable column removal

apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.spec.tsx, apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx, libs/react-helpers/src/lib/format/number.tsx
Closes #4873 
* compacts votes into units of K, M, B, ...
N/A
```
CompactVotes
✓ compacts 0 to 0 (20 ms)
✓ compacts 1 to 1 (2 ms)
✓ compacts 12 to 12 (1 ms)
✓ compacts 123 to 123 (4 ms)
✓ compacts 1234 to 1.2K (2 ms)
✓ compacts 12345 to 12.3K (1 ms)
✓ compacts 123456 to 123.5K (1 ms)
✓ compacts 1234567 to 1.2M (1 ms)
✓ compacts 12345678 to 12.3M (2 ms)
✓ compacts 123456789 to 123.5M (1 ms)
✓ compacts 1234567890 to 1.2B (2 ms)
```
=> chore(governance): sensible vote numbers

apps/trading/e2e/actions/utils.py
Fixes a weird edge case where if the pub key for the key being switched to had "thinner" letter / numbers then the click would click the copy button rather than the key.
The change keys helper will now grab the child element.
=> chore(trading): fix change keys edge case

apps/trading/client-pages/referrals/create-code-form.tsx, apps/trading/client-pages/referrals/tiers.tsx, libs/environment/src/hooks/use-links.ts
Partially Closes #5176 
Referral initial state when no sets are available.
=> feat(trading): referral initial state when no sets are available

apps/trading/client-pages/referrals/tile.tsx, libs/ui-toolkit/src/components/copy-with-tooltip/copy-with-tooltip.tsx
Closes #5220 
* adds additional button next to the copy button that allows one to copy the shareable link to the apply code page
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/ba5565f2-92dd-47ca-b60a-fdb18e4f2bdb
`CopyWithTooltip` accepts the tooltip's description that shows on hover.
=> feat(trading): copy apply referral link from code tile

libs/datagrid/src/lib/ag-grid/ag-grid-themed.tsx, libs/liquidity/src/lib/liquidity-table.tsx
=> fix(trading): fees accrued tooltip

libs/liquidity/src/lib/liquidity-data-provider.spec.tsx, libs/liquidity/src/lib/liquidity-data-provider.ts
Closes #5450 
The LP table shows `-` for party ID when there was no SLA data. 
We did not have this mismatch before. 
=> fix(trading): missing party ID when there is no SLA data

apps/trading/components/fees-container/fees-container.tsx
Closes #5447 
Shows less than the required volume if the current vol is 0. 
=> fix(trading): required vol shown if current is zero

apps/trading/components/funding-container/funding-container.tsx
=> fix(trading): avoid funding LineChart recreate instance on FundingContainer re-render

apps/explorer/src/app/components/order-details/deterministic-order-details.tsx, apps/explorer/src/app/components/txs/tx-order-type.tsx
Closes #4656
Adds details about an order's type to the TX list and details page. Also tweaks a minor text contrast issue in the deterministic order details view.
=> feat(explorer): add type details to orders in tx list and details

libs/data-provider/src/generic-data-provider.ts, libs/trades/src/lib/trades-data-provider.ts
Closes N/A
Note: this should be used since there is a limit between 1k and 5k records that can be retrieved (i.e. candles query)
=> chore(trading): update generic data provider

.eslintrc.json, apps/trading/client-pages/fees/fees.tsx, apps/trading/client-pages/liquidity/liquidity.tsx, apps/trading/client-pages/market/trade-grid.tsx, apps/trading/client-pages/market/trade-panels.tsx, apps/trading/client-pages/markets/markets-page.tsx, apps/trading/client-pages/portfolio/portfolio.tsx, apps/trading/client-pages/referrals/referrals.tsx, apps/trading/client-pages/rewards/rewards.tsx, apps/trading/components/error-boundary/error-boundary.spec.tsx, apps/trading/components/error-boundary/error-boundary.tsx, apps/trading/components/error-boundary/index.ts, apps/trading/components/sidebar/sidebar.tsx, libs/logger/src/hooks/use-logger.ts, libs/logger/src/lib/local-logger.spec.ts, libs/logger/src/lib/local-logger.ts
Closes #5410 
Adds error boundaries with logging for panes, sidebar components and standalone pages
=> feat(trading): error boundaries for panes, sidebars, pages

apps/trading/e2e/tests/market/test_market_selector.py, apps/trading/e2e/tests/perpetual_market/test_perpetuals.py
The stats in the trading header change per test run. This is due to: https://github.com/vegaprotocol/frontend-monorepo/issues/5465
I may update the tests to be more flexible and just assert displayed for the time being but it does mean we have a gap in our tests.
=> chore(trading): e2e test fix

apps/trading/client-pages/referrals/apply-code-form.tsx, apps/trading/client-pages/referrals/referral-statistics.tsx, apps/trading/components/welcome-dialog/use-get-onboarding-step.ts, apps/trading/components/welcome-dialog/welcome-dialog.tsx, libs/i18n/src/locales/en/trading.json
Closes #5458 
Addresses three issues
- Updates funds required error text when trying to apply code but not meeting the deposit requirement
- Fixes a overflow error when formatting final commission rate on the referrals page
- Adds logic to not open the onboarding dialog for the referrals page
- For the onboarding dialog we've previously had the dialog always set to open initially, but used the `dismiss` value in the store to override the dialog state. Now that we want access to the page in the router, its been set to be closed by default but opened via a useEffect
=> fix(trading): referrals page final commission value and onboarding dialog

libs/candles-chart/src/lib/data-source.ts
Closes #5469
Add candle from subscription only if it's not older than requested range
=> fix(trading): do not add candles if they are older than requested date range

libs/market-depth/src/lib/orderbook.tsx
When there is no orders splash rendered by orderbook covered Orderbook, Trades tabs
=> fix(trading): fix tabs covered by orderbook splash

apps/trading/client-pages/market/market.tsx, apps/trading/client-pages/markets/markets-sidebar.tsx, apps/trading/client-pages/portfolio/portfolio.tsx
When sidebar view was changed it caused MarketPage and Portfolio page to re-render. It caused to re-render all child components and some of them were remounted. This was noticed in liquidation price rendered by positions table when active sidebar section was changed
=> chore(trading): avoid portfolio and market page re-rendering on sidebar view change

libs/markets/src/lib/components/market-info/market-info-panels.spec.tsx, libs/markets/src/lib/components/market-info/market-info-panels.tsx
Closes N/A
The expiry in the top ribbon is correctly formatted, but the one in market info is off by 3 trailing zeros (AKA 54 years)
Fixes: 
=> fix(trading): internal condition timestamp

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx, apps/trading/lib/hooks/use-wallet-disconnected-toasts.tsx, apps/trading/pages/toasts-manager.tsx, libs/wallet/src/connectors/injected-connector.ts, libs/wallet/src/connectors/json-rpc-connector.ts, libs/wallet/src/connectors/snap-connector.ts, libs/wallet/src/connectors/vega-connector.ts, libs/wallet/src/connectors/view-connector.tsx, libs/wallet/src/context.ts, libs/wallet/src/provider.spec.tsx, libs/wallet/src/provider.tsx, libs/wallet/src/use-is-alive.ts
Closes #4717
* closes connection to the wallet if it's unreachable (closed inside wallet, closed process, crashed app, etc.)
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/a5b03c3e-6828-4fcc-bd01-9bda92aa0846
It's way easier to check if the connection is alive rather than responding to the failed transactions (for whatever reason) as it automatically resets the connection if wallet is unreachable.
=> feat(wallet): disconnect if wallet unreachable

apps/explorer/src/app/routes/blocks/id/block.tsx, apps/governance/src/routes/proposals/protocol-upgrade/protocol-upgrade-proposal-container.tsx, libs/proposals/src/lib/protocol-upgrade-proposals/use-block-rising.ts, libs/react-helpers/src/hooks/use-fetch.ts, libs/tendermint/src/lib/use-block-info.ts, libs/tendermint/src/types.ts
Closes #4692 
The useFetch hook obscured tendermint errors, because Tendermint returns an error HTTP status code as well as a body containing an error. This PR passes through the error string.
It feels a little specific to Tendermint, but in reality the useFetch hook is primarily used to access Tendermint RPC endpoints, so it seemed acceptable.
The end result is that the error for future blocks is now rendered on the Block page of Explorer if a future block is accessed.
There are some `//@ts-ignore`s in here, which are from before the PR existed. It feels wrong, but if someone wants to improve on it let me know and we can work on it. The reason these are there is that we're accessing a property in a generic type `T`.
=> fix(explorer): pass through tendermint error responses from usefetch

apps/trading/components/fees-container/fees-container.tsx
Closes #5448
Rollback change on fees page. 
Before:
After: 
=> chore(trading): rollback current traded volume change

apps/trading/e2e/poetry.lock, apps/trading/e2e/tests/fees/test_fees.py, apps/trading/e2e/tests/perpetual_market/test_perpetuals.py
Updates market-sim version to include fixes for minting, that should help with the 500 errors we are seeing in CI.
Also includes fixes for tests failing at the moment.
=> chore(trading): update market-sim

libs/i18n/src/locales/en/markets.json, libs/markets/src/lib/components/market-info/market-info-panels.tsx
=> fix(trading): use correct interpolation prefix in market info label

libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx
N/A
Removes a curly brace from being rendered in the stop order deal ticket button
=> fix(deal-ticket): stray curly in stop order deal ticket

libs/trading-view/src/lib/trading-view.tsx
N/A
Minor tweaks to the trading view chart to align more with the default chart
- Sets volume as study (instead of overlay)
- Removes the market name from the symbol (so its not duplicated below the instrument code in the market header
=> chore(trading-view): minor tv chart tweaks

apps/trading/client-pages/referrals/apply-code-form.tsx, apps/trading/client-pages/referrals/constants.ts, apps/trading/client-pages/referrals/create-code-form.tsx, apps/trading/client-pages/referrals/how-it-works-table.tsx, apps/trading/client-pages/referrals/landing-banner.tsx, apps/trading/client-pages/referrals/layout.tsx, apps/trading/client-pages/referrals/referral-statistics.tsx, apps/trading/client-pages/referrals/referrals.tsx, apps/trading/client-pages/referrals/table.tsx, apps/trading/client-pages/referrals/tiers.tsx, apps/trading/client-pages/referrals/tile.tsx, apps/trading/components/card/card.tsx, apps/trading/components/fees-container/fees-container.tsx, apps/trading/components/fees-container/market-fees.tsx, apps/trading/components/helpers/tag.tsx, apps/trading/components/helpers/tiers.tsx, apps/trading/components/rewards-container/rewards-container.tsx, apps/trading/components/rewards-container/rewards-history.spec.tsx, apps/trading/components/rewards-container/rewards-history.tsx, apps/trading/components/table/index.ts, apps/trading/components/table/table.tsx, apps/trading/e2e/tests/fees/test_fees.py, apps/trading/e2e/tests/market/test_market_selector.py, libs/datagrid/src/lib/cells/stacked-cell.tsx
Closes #5428 
Closes #5427 
* removes unnecessary backgrounds on mobile
* collapses the tier tables on mobile
* pins code / asset to the left
* introduces more compact view on mobile
...
N/A
=> fix(trading): mobile friendly referral and fees views

apps/trading/components/fees-container/fees-container.tsx, apps/trading/components/fees-container/use-referral-stats.ts
Closes #5373 
- Changes fetchPolicy so that on mount the query will execute against the data node (and not just the cache).
- Adds a poll every 15s
=> fix(trading): ensure fees queries always fetch on mount and poll

apps/explorer/src/app/components/links/party-link/party-link.tsx, apps/explorer/src/app/components/order-details/deterministic-order-details.tsx, apps/explorer/src/app/components/signature/signature.tsx, apps/explorer/src/app/routes/layout.tsx
Closes #5456
A minor tidyup of the order details view in explorer. Fixes some elements causing overflow, and the spacing. It's not **pretty** but it's _less ugly_.
=> fix(explorer): minor tidyup of deterministic order view

libs/i18n/src/locales/en/governance.json
Closes #5588
Makes the error message for an incorrectly configured multisig contract clearer. This is going to `main` as it relates to an error currently existing on the mainnet governance site. This change will be 🍒 cherry-picked in to `develop`.
=> fix(governance): improve error message for configuration error

apps/trading/e2e/tests/market/test_monitoring_auction_price_volatility_market.py
currently the test leaves the price monitoring auction with the forward 10s.
The tests still pass as they go into a liquidity auction that has the same error message (which it probably shouldn't but they are being removed in 74 vega).
Removing the forward time in this test means we are testing an actual price monitoring auction state.
=> chore(trading): fix price monitoring test

apps/trading/components/market-selector/market-selector-item.tsx, apps/trading/components/market-selector/market-selector.tsx, apps/trading/components/navbar/nav-header.tsx
Closes #5429 
Update market selector to make it mobile responsive. 
=> feat(trading): mobile responsiveness - market selector

apps/trading/client-pages/markets/closed.tsx, apps/trading/client-pages/markets/market-list-table.tsx, apps/trading/client-pages/markets/markets-page.tsx, apps/trading/client-pages/markets/use-column-defs.tsx, libs/accounts/src/lib/accounts-table.tsx, libs/accounts/src/lib/breakdown-table.tsx, libs/datagrid/src/lib/column-definitions.ts, libs/deposits/src/lib/deposits-table.tsx, libs/fills/src/lib/fills-table.tsx, libs/orders/src/lib/components/order-list/order-list.tsx, libs/orders/src/lib/components/stop-orders-table/stop-orders-table.tsx, libs/positions/src/lib/positions-table.tsx, libs/proposals/src/components/proposals-list/use-column-defs.tsx, libs/ui-toolkit/src/components/dialog/dialog.tsx, libs/ui-toolkit/src/components/toast/toast-position-setter.tsx, libs/ui-toolkit/src/components/toast/toasts-container.tsx, libs/ui-toolkit/src/components/trading-button/trading-button.tsx, libs/wallet/src/connectors/view-connector.tsx, libs/withdraws/src/lib/withdrawals-table.tsx, package.json, yarn.lock
Closes #5433 
On smallest screen possible: **iPhone SE**
=> feat(trading): mobile responsiveness tweaks

apps/trading/client-pages/markets/closed.spec.tsx, apps/trading/e2e/tests/market/test_closed_markets.py, apps/trading/e2e/tests/market_lifecycle/test_market_lifecycle.py, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/i18n/src/locales/en/deal-ticket.json
Closes #5574 
Use `No trading` instead of `Trading terminated` on market trading mode validation.
`Trading terminated` is a market state, however state validation does not bring as much value in this scenario. 
Fix:
=> fix(trading): use `No trading` instead of `Trading terminated`

.github/workflows/console-test-run.yml, apps/trading/e2e/pyproject.toml, apps/trading/e2e/tests/market/test_closed_markets.py, apps/trading/e2e/tests/market_lifecycle/test_market_lifecycle.py, apps/trading/e2e/tests/trade_history/test_trade_history.py, apps/trading/e2e/tests/wallet/test_wallet.py
Market-sim has been updated to include a retry on submit transaction.
This PR updates e2e to use 2 runners instead of 1
=> chore(trading): market-sim branch parralel fix

apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.spec.tsx, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx, libs/environment/src/hooks/use-links.ts, libs/i18n/src/locales/en/governance.json
Closes #5528 
* changes "Market change" to "Update to market ID: .... "
* adds copy to clipboard button
* adds "Open in Console" button
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/55a67af6-b95b-4ec5-ad1a-0b5c894e5d16
N/A
=> feat(governance): update market proposal header with copy and open buttons

apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.spec.tsx, apps/governance/src/routes/staking/home/validator-tables/consensus-validators-table.tsx, apps/governance/src/routes/staking/home/validator-tables/standby-pending-validators-table.tsx, apps/governance/src/routes/staking/node/validator-table.tsx, apps/governance/src/routes/staking/shared.spec.ts, apps/governance/src/routes/staking/shared.ts, libs/utils/src/lib/format/number.spec.ts, libs/utils/src/lib/format/number.ts
Closes #5191
Properly handle null values when calculating total and other penalties. It's not totally clear to me why the value in the test changes, but it seems correct to me.
=> fix(governance): handle null validator scores properly

libs/i18n/src/locales/en/wallet.json, libs/wallet/src/connect-dialog/connect-dialog.tsx
Closes N/A
Translation typo `<0> </0>`
Fixes 
=> fix(trading): vega wallet dialog typo full featured link translation

apps/governance/src/lib/party.test.ts, apps/governance/src/lib/party.ts, apps/governance/src/routes/proposals/components/vote-details/vote-buttons.tsx, apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards.tsx
Closes #5634
Also closes a similar issue with Voting - if a user had no accoutns and went to a single proposal, they would see an error rather than a suggestion to connect a wallet.
If a party has never deposited or traded, they have no accounts and the `parties` API will return an error that the party
does not exit. This was handled poorly, and rendered a 'party does not exist' error instead of simply 'the key you are
looking at does not have any rewards'. This PR filters out the Party Does Not Exist error so that the view renders more
usefully for the user.
=> fix(governance): handle an expected error

libs/accounts/src/lib/breakdown-table.tsx, libs/ui-toolkit/src/components/dialog/dialog.tsx
Closes #5665 
* fix breakdown collateral popup by adjusting one column and 
* make dialogs take full screen width when on mobile
=> fix(trading): adjust full screen for mobile dialogs

libs/markets/src/lib/components/market-info/market-info-panels.tsx
Closes N/A
Fixes text-xs on market id in key details
Fixes this: 
=> fix(trading): market id use text-xs in key details

libs/candles-chart/src/lib/Candles.graphql, libs/candles-chart/src/lib/__generated__/Candles.ts, libs/candles-chart/src/lib/candles.mock.ts, libs/candles-chart/src/lib/data-source.spec.ts, libs/candles-chart/src/lib/data-source.ts
Closes #5675
* `VegaDataSource` ignores candles from before market open date
* it also ignores empty candles which may be returned by `candlesConnection` api
SEE BEFORE FIX in the 🎫 #5675
AFTER FIX:
N/A
=> fix(candles-chart): ignore candles from before market open date

apps/explorer/src/app/components/txs/details/tx-details-wrapper.tsx, apps/explorer/src/app/components/txs/details/tx-update-margin-mode.tsx, apps/explorer/src/app/components/txs/tx-filter.tsx
- feat(explorer): basic view for updatemarginmode tx
- feat(explorer): add updatemarginmode to tx filter
There's not a lot to see in this transaction, but now you can
=> feat(explorer): updatemarginmode tx view

libs/assets/src/lib/assets-data-provider.ts, libs/i18n/src/locales/en/withdraws.json, libs/utils/src/lib/format/ether.spec.ts, libs/utils/src/lib/format/ether.ts, libs/utils/src/lib/format/index.ts, libs/utils/src/lib/format/number.spec.ts, libs/utils/src/lib/format/number.ts, libs/web3/src/index.ts, libs/web3/src/lib/use-gas-price.ts, libs/withdraws/src/lib/withdraw-form.tsx, libs/withdraws/src/lib/withdraw-limits.tsx, libs/withdraws/src/lib/withdraw-manager.spec.tsx, libs/withdraws/src/lib/withdraw-manager.tsx
Closes #5510
This PR adds the gas fee estimation for the `<WitdrawLimits>` component. It colours the prices orange if the amount it between base and max price, and red if it's below the base fee.
Shows in ETH when price is >1e6 gwei:
The withdrawal amount (any asset) is only somewhat comparable to the estimated gas (ETH) fee only if they're both equalised to qUSD. This PR also adds the `useWETH` hook which looks for the `WETH` configuration (quantum is really what's needed) in the Vega's assets (it returns hardcoded values if not found, 1 WETH ~= 2000 qUSD).
=> feat(trading): gas fee estimation for withdraw transaction

apps/trading/client-pages/competitions/team-form.tsx
Closes #5712 
This PR adds "Updated" note next to the "Update" button when tx has been confirmed.
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/af1e32a8-c28c-4676-827e-87e6edbbafdc
N/A
=> fix(trading): mark as updated when tx confirmed

apps/trading/components/competitions/competitions-leaderboard.tsx, apps/trading/lib/hooks/use-teams.tsx
Closes #5729 
* keeps rank when filtering
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/a0d091e6-0f08-4181-bc4d-4169b55cc103
N/A
=> fix(trading): keep leaderboard rank when filtering

apps/explorer/src/app/components/txs/details/proposal/summary.tsx, apps/explorer/src/app/components/txs/details/transfer/Transfer.graphql, apps/explorer/src/app/components/txs/details/transfer/__generated__/Transfer.ts, apps/explorer/src/app/components/txs/details/transfer/blocks/transfer-participants.tsx, apps/explorer/src/app/components/txs/details/transfer/blocks/transfer-rewards.tsx, apps/explorer/src/app/components/txs/details/transfer/blocks/transfer-status.tsx, apps/explorer/src/app/components/txs/details/transfer/transfer-details.tsx, apps/explorer/src/app/components/txs/details/transfer/transfer-rewards.spec.tsx, apps/explorer/src/app/components/txs/details/tx-proposal.tsx, apps/explorer/src/app/components/txs/details/tx-transfer.tsx, apps/explorer/src/app/components/txs/lib/proposal-to-transfer.ts, libs/types/src/__generated__/types.ts
- feat(explorer): extend transfers view
- chore(explorer): more fields for rewards
- feat(explorer): complete transfer status
- chore(explorer): progress on rank table
- chore(explorer): relayout transfers
- chore(explorer): update transfer status query to match latest preview
- test(explorer): add tests for games display
Closes #4306. Closes #5557. See notes below for testing.
Updates the Transfer TX view to display extra information. Firstly, it uses a new API to show the transfer status 
Secondly it revamps the recurring reward transaction view to cover 'games', which is to say recurring transfers with a
dispatch strategy that targets teams. All possible fields for dispatchStrategy are rendered in a hopefully meaningful way,
although there's a limit to how muc explaining this panel can …
=> feat(explorer): transfer status and games overview

apps/governance/src/routes/rewards/epoch-total-rewards/generate-epoch-total-rewards-list.spec.ts, apps/governance/src/routes/rewards/epoch-total-rewards/generate-epoch-total-rewards-list.ts
Closes #5677 
Fixes an issue where new reward types were being rendered in the table, breaking the grid layout. This change checks that the reward type is included in the RowAccountType object before setting the reward data.
=> fix(governance): dont show all reward types in gov rewards table

apps/trading/client-pages/market/trade-panels.tsx
N/A
Depth chart was not added to the mobile view.
=> fix(trading): add depth chart on mobile view

apps/explorer/src/app/components/order-details/amend-order-details.spec.tsx, apps/explorer/src/app/components/order-details/amend-order-details.tsx
- **fix(explorer): fix display of amends with sizedelta**
Closes #5774
`sizeDelta` displayed as the new price, rather than a change to the price. This change changes the label, and displays the actual size more clearly.
- You need an order 
- Then you need to amend the order using the sizeDelta field
- Example: https://explorer.fairground.wtf/txs/0x2ABAE5BCDF7F45BE24CD9599E77AEEED0D281B1F0548429D9041FDC1F15670A1 was size `7000`, then ammended using sizeDelta `-2000` to size `5000`
=> fix(explorer): sizedelta in ammends displayed incorrectly'

apps/trading/lib/hooks/constants.ts, apps/trading/lib/hooks/use-games.ts, apps/trading/lib/hooks/use-team.ts, apps/trading/lib/hooks/use-teams.tsx
N/A
We were not using a consistent epoch number for stats aggregation for teams/competitiosn
=> fix(trading): use same epochs for all games/stats

apps/trading/components/liquidity-container/liquidity-container.tsx
Closes #5852
Update LP data provider reloading - The live time on book was not updating.
N/A
=> fix(trading): lp data provider reload - updating book

apps/governance/src/components/heading/heading.tsx, apps/governance/src/routes/proposals/components/proposal-detail-header/proposal-header.tsx, apps/governance/src/routes/proposals/components/proposal-market-changes/proposal-market-changes.spec.tsx, apps/governance/src/routes/proposals/components/proposal-market-changes/proposal-market-changes.tsx, apps/governance/src/routes/proposals/components/proposal-update-market-state/proposal-update-market-state.spec.tsx, apps/governance/src/routes/proposals/components/proposal-update-market-state/proposal-update-market-state.tsx, apps/governance/src/routes/proposals/components/proposal/colours.ts, apps/governance/src/routes/proposals/components/vote-breakdown/vote-breakdown.tsx
Closes #5855
Partially fixes couple of points from #5838
* removes multiple tags from the proposal header and replaces with one "BatchProposal"
* adds indicators to the vote breakdown
* adds market name to details
* changes UI of vote breakdown
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/294d4358-219c-4d76-85ca-3bf3b12deb39
Fixed alignment:
I've mocked `MarketName` in the unit tests, there's just too much of a hassle to cover the gql mocks.
=> feat(governance): batch proposal indicators, vote breakdown ui changes

apps/governance/.env, apps/governance/.env.capsule, apps/governance/.env.devnet, apps/governance/.env.stagnet1, apps/governance/.env.testnet, apps/governance/.env.validators-testnet, apps/trading/.env, apps/trading/.env.capsule, apps/trading/.env.devnet, apps/trading/.env.stagnet1, apps/trading/.env.testnet, apps/trading/.env.validators-testnet
Closes #5859
As the title and so the link for the firefox extension has changed we need to update the link. This is not the case with chrome as it uses an ID.
=> chore(governance, trading): update links for new beta extension

apps/trading/components/rewards-container/active-rewards.tsx, apps/trading/e2e/tests/teams/test_teams.py, apps/trading/lib/hooks/use-rewards.ts
Closes #5886 
Use `node.transfer.asset` for reward cards. 
Dispatch asset should be used for dispatch metric info. 
=> fix(trading): fix reward card asssets

libs/i18n/src/locales/en/markets.json, libs/markets/src/lib/components/last-24h-price-change/last-24h-price-change.tsx, libs/markets/src/lib/components/last-24h-volume/last-24h-volume.tsx, libs/markets/src/lib/hooks/use-candles.ts
Closes #5885 
Fixes an issue where the 24h price and volume change was not showing in the header due to empty candles
=> fix(trading): 24hr price and volume in header

apps/trading/pages/_app.page.tsx
Closes #4087 
Remove `view as` banner
=> chore(trading): remove view as pubkey banner

apps/trading/lib/hooks/Games.graphql, apps/trading/lib/hooks/__generated__/Games.ts, apps/trading/lib/hooks/use-games.ts, libs/types/src/__generated__/types.ts
Closes #5899 
* adds additional `teamId` variable to the `games` query in order to get the historical results for a team
N/A
=> fix(trading): add team id to games query

apps/trading/e2e/tests/teams/test_teams.py, apps/trading/lib/hooks/use-rewards.spec.ts, apps/trading/lib/hooks/use-rewards.ts
Closes #5898
* removes the "crazy" condition determining the scoped to teams games
N/A
N/A
=> chore(trading): scoped to teams games

apps/governance-e2e/src/integration/view/home.cy.ts, apps/governance/src/app-loader.tsx, apps/governance/src/contexts/contracts/contracts-provider.tsx, apps/trading/e2e/actions/utils.py, libs/i18n/src/locales/en/wallet-react.json, libs/ui-toolkit/src/components/input-error/input-error.tsx, libs/wallet-react/src/components/connect-dialog/connection-options.tsx, libs/wallet-react/src/hooks/use-eager-connect.ts, libs/wallet-react/src/hooks/use-simple-transaction.ts, libs/wallet/src/connectors/injected-connector.ts, libs/wallet/src/connectors/json-rpc-connector.ts, libs/wallet/src/connectors/snap-connector.ts, libs/wallet/src/errors.ts, libs/wallet/src/wallet.spec.ts, libs/wallet/src/wallet.ts
N/A
- Remove polling from snap connector. This was too problematic if a user locked a wallet. Instead if the wallet is locked when a tx is requested you will be prompted to unlock it again
- Fix errors not coming through from injected wallet.
- Fix capitalization and text overflow in InputError
- Show error data in connection dialog if connection fails
- Only eager connect if wallet status is disconnected
- Only refresh keys if connected
=> fix(wallet): wallet connection and error fixes

apps/trading/components/market-selector/use-market-selector-list.ts, libs/ui-toolkit/src/components/sparkline/sparkline.tsx, libs/utils/src/lib/price-change.ts
Closes #5951 
- Filters out empty candles from price change calculations
- Fills in empty candles with previous value for sparkline
=> fix(trading): incorrect top gaining and top losing order

apps/explorer/src/app/components/epoch-overview/epoch.tsx, apps/explorer/src/app/components/links/block-link/EpochByBlock.graphql, apps/explorer/src/app/components/links/block-link/__generated__/EpochByBlock.ts, apps/explorer/src/app/components/links/block-link/block-link.tsx, apps/explorer/src/app/components/links/governance-link/governance-link.spec.tsx, apps/explorer/src/app/components/links/governance-link/governance-link.tsx, apps/explorer/src/app/components/txs/details/shared/tx-details-shared.tsx, apps/explorer/src/app/components/txs/details/tx-transfer.tsx, apps/explorer/src/app/components/txs/tx-order-type.tsx, apps/explorer/src/app/routes/blocks/id/block.tsx, apps/explorer/src/app/routes/treasury/components/network-accounts-table.tsx, apps/explorer/src/app/routes/treasury/components/network-transfers-table.spec.tsx, apps/explorer/src/app/routes/treasury/components/network-transfers-table.tsx, apps/explorer/src/app/routes/treasury/network-treasury.tsx
- **feat(explorer): add epoch by block query and use it in block by id and shareddetails**
Closes #5550
Adds a component and query to get the epoch number for a block. This PR is marked as draft because the query returns an error in 0.73.x, 0.74.1 & 0.74.2, which is every network at the moment. Some tidying will be done with there's a working environment
Bonus (required during development): transfer types are now differentiated in TX overview
=> feat(explorer): add epoch to block pages

libs/wallet/src/connectors/injected-connector.ts, libs/web3/src/lib/use-vega-transaction-toasts.tsx
Closes #5736
- `error.message` was correctly being sent through by the wallet but often useful information in `error.data` was not shown.
- Fix useful message from the wallet not being shown for other methods
=> fix(trading,wallet): improve errors from browser wallet

libs/markets/src/lib/components/market-info/market-info-panels.tsx
N/A
If no sourceChainId is provided for the oracel spec fall back to chain id 1
=> fix(markets,explorer): fallback to ethereum mainnet chain Id if sourceChain is not provided

apps/trading/pages/_document.page.tsx, apps/trading/pages/ssr-loader.tsx
N/A
Fixes a couple annoying issues when running the development server
- Server render mismatch from the client, this was because the seed would not reset between hmr updates
- Preload warning for woff. Because most browsers support woff2 the woff version never gets used resulting in a warning
=> chore(trading): fix ssr loader server mismatch, remove preload

apps/explorer/src/app/components/txs/details/shared/tx-details-shared.tsx, apps/explorer/src/app/components/txs/tx-transfer.spec.tsx, apps/explorer/src/app/routes/oracles/OraclesForMarkets.graphql, apps/explorer/src/app/routes/oracles/__generated__/OraclesForMarkets.ts, apps/explorer/src/app/routes/oracles/components/oracle-eth-source.tsx, apps/explorer/src/app/routes/oracles/components/oracle-filter.spec.tsx, apps/explorer/src/app/routes/oracles/components/oracle-filter.tsx, apps/explorer/src/app/routes/oracles/components/oracle-spec/internal-time-trigger.tsx, apps/explorer/src/app/routes/oracles/components/oracle.tsx
- **feat(explorer): show time trigger on non eth oracles**
- **feat(explorer): parsing abi and args**
- **feat(explorer): tidyup normaliser output**
Closes #5880
Adds missing details to the oracles page:
- Add required confirmations
- Fix time triggers not rendering for some oracle types
- Fix date formatting of triggers for some oracle types
- Add an accordion type view to show ABI, args and normalisers for oracles
=> feat(explorer): add full details to oracle page

libs/markets/src/lib/components/market-info/market-info-panels.tsx
The new link to Explorer, from the Market Info panel, for oracles for a market was incorrect. This PR makes it correct
* Old and broken: https://explorer.fairground.wtf/market/6291cac44e47d8b89af0b6230296ea8024a30d7fa6630a4c1a1ce784df9e7c4f/oracles#0x719abd606155442c21b7d561426d42bd0e40a776
* New and fixed: https://explorer.fairground.wtf/markets/6291cac44e47d8b89af0b6230296ea8024a30d7fa6630a4c1a1ce784df9e7c4f/oracles#0x719abd606155442c21b7d561426d42bd0e40a776
=> fix(markets): fix link to explorer oracle

apps/explorer/src/app/components/txs/tx-filter.tsx
A typo in the filters for Cancel and Amend LP order meant that filtering the TX list for these transactions
resulted in an empty list.
=> fix(explorer): fix lp tx filters

apps/governance/src/hooks/use-vega-wallet-config.ts
N/A
Governance app was hardcoded with a default chain for fairground
=> fix(governance): hard coded default chain in vega wallet

apps/explorer/src/app/components/links/asset-link/asset-link.tsx, libs/emblem/.eslintrc.json, libs/emblem/.swcrc, libs/emblem/README.md, libs/emblem/jest.config.ts, libs/emblem/package.json, libs/emblem/project.json, libs/emblem/src/components/asset-emblem.test.tsx, libs/emblem/src/components/asset-emblem.tsx, libs/emblem/src/components/contract-emblem.test.tsx, libs/emblem/src/components/contract-emblem.tsx, libs/emblem/src/components/emblem-base.test.tsx, libs/emblem/src/components/emblem-base.tsx, libs/emblem/src/components/emblem.test.tsx, libs/emblem/src/components/emblem.tsx, libs/emblem/src/components/lib/type-guard.test.ts, libs/emblem/src/components/lib/type-guard.ts, libs/emblem/src/config/index.ts, libs/emblem/src/index.ts, libs/emblem/src/setup-tests.ts, libs/emblem/tsconfig.json, libs/emblem/tsconfig.lib.json, libs/emblem/tsconfig.spec.json, tsconfig.base.json
Creates an example component for embedding asset icons in a vega frontend. This is for *discussion* at first.
With a simple added component:
You get:
- You need to know the vega chain ID you're currently looking at to use  the`EmblemByAsset` component. It defaults to `mainnet` (i.e. `vega-mainnet-0011`)
- You need to know the external chain ID you're currently looking at to use the `EmblemByContract` component. It defaults to `Ethereum mainnet` (i.e. `1`)
- In future this component might embed the logos, and only fall back to requesting it from `icon.vega.xyz`. Right now it always uses the remote URL.
- Sizes are hardcoded, but match the Tailwind size CSS properties. Overriding the classes will not change the width, but given that we're a single page app I think this is fine.
=> feat(emblem): create example emblem component

apps/governance/src/i18n/index.ts
Closes #5970 
Adds assets and utils to default loaded i18n namespaces. 
Because they weren't included here once the dialog was opened it would fetch the translations, therefore triggering the Suspense component, resulting in the loss of the withdrawals list state
=> fix(governance): withdrawals dissapearing when the withdraw dialog is opened

libs/deal-ticket/src/components/deal-ticket/deal-ticket-container.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-fee-details.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/hooks/use-max-size.ts
Closes #6047
If market is in action markPrice is not available. In that case when calculating max order size use order price for cross margin limit orders
=> feat(deal-ticket): use order price if markPrice is not available in useMaxSize

libs/positions/src/lib/positions-table.tsx
Closes #5754
Gives the actions column in the positions table a colId property as it doesn't accept a specific field
=> fix(positions): getColId error

apps/trading/pages/styles.css, package.json, yarn.lock
Closes #5198 
- Updates pennant to v1.17.0 so the depth chart label bg can be set
- Adds a bg color to the depth chart labels so they are more distinct from the x axis labels
=> fix(trading): add bg color to depth chart labels to clarify numbers

apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.tsx
Closes #6058 
Edit profile not visible on read only. 
=> fix(trading): do not show alias edit on read only

apps/trading/components/bootstrapper/bootstrapper.tsx, libs/i18n/src/locales/en/trading.json
Renders failure instead of loader if config is not provided to the wallet provider
=> fix(trading): remove the apploader from bootstrap

apps/governance/src/components/heading/heading.tsx, apps/governance/src/routes/proposals/components/proposal-market-data/proposal-market-data.tsx, apps/governance/src/routes/proposals/components/proposal/proposal-change-details.tsx, apps/governance/src/routes/proposals/components/proposal/proposal.tsx, apps/governance/src/styles.css
Closese #6059
- Removes gate checking for parent market data
- Obtains newly created market IDs deterministically using sub proposal order
- De-uppercases titles
=> fix(governance): fix market info not showing in proposals

apps/explorer/src/app/routes/oracles/OraclesForMarkets.graphql, apps/explorer/src/app/routes/oracles/__generated__/OraclesForMarkets.ts
Pagination reversed a few versions ago, and this query was still using `last` instead of `first`. On some fairground markets, this could timeout
=> fix(explorer): fix timeout out explorer page for oracles by market

apps/trading/components/market-banner/market-banner.tsx, apps/trading/components/market-banner/market-monitoring-auction.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/i18n/src/locales/en/deal-ticket.json
Part 1 #6112 
Enhance auction features in console
=> feat(trading): enhance auction features - part 1 banner and warnings

apps/trading/client-pages/competitions/competitions-team.tsx, apps/trading/components/competitions/games-container.tsx, apps/trading/components/rewards-container/active-rewards.spec.tsx, apps/trading/components/rewards-container/active-rewards.tsx, apps/trading/components/rewards-container/reward-card.tsx, apps/trading/e2e/tests/rewards/test_reward_group.py, apps/trading/e2e/tests/rewards/test_rewards_combo_tier_1.py, apps/trading/lib/hooks/use-rewards.spec.ts, apps/trading/lib/hooks/use-rewards.ts, libs/i18n/src/locales/en/trading.json, libs/types/src/global-types-mappings.ts, libs/ui-toolkit/src/components/trading-button/trading-button.tsx
Closes #5580 
Closes #6182 
* removed `StakingRewardCard`, added special `dispatchStrategy` for this type of reward,
* added groups (`GroupRewardCard`) of reward cards based on:
- reward asset (usually VEGA),
- reward for (dispatch metric),
- reward scope (teams vs individuals),
- reward distribution strategy
* added dialogs with cards from a group
* excludes scoped to teams rewards from 'Rewards' page
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/bd49af42-ec18-4a90-b18a-bbc4891e713c
Button colours:
=> feat(trading): reward cards grouping

apps/trading/components/market-selector/market-selector.spec.tsx, apps/trading/components/market-selector/market-selector.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-container.tsx, libs/i18n/src/locales/en/trading.json
Closes #6236
A couple small changes to support spot markets
- Don't show margin mode selection when on spot
- Change the no markets found message when filtering the markets by type so that it doesn't include 'coming soon'
=> fix(trading): dont show margin mode selector on spot markets

libs/trades/src/lib/trades-data-provider.ts
Closes #6245 
* reverts MAX_TRADES to 500
N/A
=> fix(trading): revert max trades from 10 to 500

apps/trading/e2e/tests/deal_ticket/test_tp_sl.py
Re enabled tp/sl in the deal ticket test as we now have the vega version to support it.
=> chore(trading): re-enable tpsl deal ticket test

libs/i18n/src/locales/en/positions.json, libs/orders/src/lib/components/order-list-manager/order-list-manager.tsx, libs/positions/src/lib/positions-manager.tsx, libs/positions/src/lib/positions-table.tsx, libs/web3/src/lib/TransactionResult.graphql, libs/web3/src/lib/__generated__/TransactionResult.ts, libs/web3/src/lib/use-vega-transaction-store.spec.tsx, libs/web3/src/lib/use-vega-transaction-store.tsx, libs/web3/src/lib/use-vega-transaction-toasts.spec.tsx, libs/web3/src/lib/use-vega-transaction-toasts.tsx, libs/web3/src/lib/use-vega-transaction-updater.tsx
Closes #5940
Improve close position toast. Remove information about closing order. Show information about remaining open volume and use orange warning color only if position was not closed (open volume is different than 0) 
If transaction was confirmed but position is not closed
If transaction is confirmed (closing order can be stopped) but position was successfully closed
Use subscription to positions to update information about open volume in close position transaction.
=> feat(trading): improve close position transaction handling

libs/accounts/src/lib/Accounts.graphql, libs/accounts/src/lib/__generated__/Accounts.ts, libs/accounts/src/lib/transfer-container.tsx, libs/accounts/src/lib/transfer-form.spec.tsx, libs/accounts/src/lib/transfer-form.tsx
Closes #5743 
Transfer form should make use of **wallet key aliases** instead of **party profile** aliases
Now it is using **wallet alias**
Before it was using **party alias**. 
=> fix(trading): wallet key alias instead of party alias in transfer form

apps/trading/client-pages/competitions/competitions-home.tsx, libs/i18n/src/locales/en/trading.json
Closes #6305 
Remove CAF copy from games page.
=> chore(trading): remove CAF copy from games page

libs/i18n/src/locales/en/markets.json, libs/markets/src/lib/components/market-info/tooltip-mapping.tsx
=> fix(trading): decimal places tooltips

apps/explorer/project.json, apps/explorer/src/app/components/txs/details/proposal/batch-item.tsx, apps/explorer/src/app/components/txs/details/transfer/blocks/transfer-participants.tsx, apps/explorer/src/app/components/txs/details/transfer/blocks/transfer-rewards.tsx, apps/explorer/src/types/explorer.d.ts
Closes #6301
Adds a label for a batch proposal type that was added in 0.76
Note this won't be visible until https://github.com/vegaprotocol/vega/pull/11199 is merged
Note this won't be visible until https://github.com/vegaprotocol/vega/pull/11199 is merged. But then it'll work, and it'll be great.
=> fix(explorer): update types and add label for new asset in batch

apps/explorer/src/app/components/order-details/amend-order-details.tsx
Closes #5823
The amend order view could show the old price in some circumstances (depending on the shape of the amend). Now it doesn't.
=> fix(explorer): fix amend tx view not to show old price

libs/deal-ticket/src/components/deal-ticket-validation/margin-warning.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/hooks/use-max-size.spec.ts, libs/deal-ticket/src/hooks/use-max-size.ts, libs/i18n/src/locales/en/deal-ticket.json
Closes #6272 
Include fee when calculating max size of spot order. Show low balance warning if order estimated size if greater then balance.
=> feat(trading): clean up max size spot orders

apps/trading/components/market-selector/market-selector-item.tsx, apps/trading/components/market-selector/market-selector.tsx
Closes #6346 
Hide 24h vol on mobile in market selector
=> fix(trading): market dropdown on mobile in market selector

apps/trading/client-pages/markets/use-column-defs.tsx
Part of #6316 
Format 2 dp on 24h vol markets page
=> fix(trading): add 2 dp on 24h vol markets page

apps/trading/client-pages/markets/market-icon.tsx, apps/trading/client-pages/markets/use-column-defs.tsx, apps/trading/components/market-selector/market-selector-item.tsx, libs/datagrid/src/lib/cells/market-name-cell.tsx, libs/datagrid/src/lib/cells/stacked-cell.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-closed.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-hammer.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-monitor.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-pause.tsx, libs/ui-toolkit/src/components/icon/vega-icons/vega-icon-record.ts
Closes #6344 
Add market trading mode icons and tooltips to market page
=> feat(trading): market trading mode icons

libs/market-depth/src/lib/orderbook.spec.tsx, libs/market-depth/src/lib/orderbook.tsx
=> feat(market-depth): do not show spread if one side of the orderbook is empty

apps/trading/components/rewards-container/active-rewards.spec.tsx, apps/trading/components/rewards-container/reward-card.tsx
Closes #6312 
Add a new label to the card for "Pays every" and use the value from transferInterval + "epochs"
=> feat(trading): add transfer interval on reward cards

libs/deal-ticket/src/components/deal-ticket/key-value.tsx, libs/ui-toolkit/src/components/trading-button/trading-button.tsx
Closes #6332 
Fixes size overflow on the deal ticket by adding break word on trading button.
Fixes: 
To be:
=> fix(trading): trading button break word

.github/workflows/release-console.yml
Currently the release workflow fails with
> Run BRANCH_NAME="release/main/v0.25.25"
BRANCH_NAME="release/main/v0.25.25"
git reset --hard c19eb034b14a9239ee39c28c3d980618cf3ea97f
git push --force --set-upstream origin $BRANCH_NAME
shell: /usr/bin/bash -e {0}
env:
E2E_TEST_WORKFLOW: ./.github/workflows/trading-e2e-test-run.yml
fatal: Could not parse object 'c19eb034b14a9239ee39c28c3d980618cf3ea97f'.
Error: Process completed with exit code 128.
This change should fix the shallow fetch
=> chore(trading): fix shallow fetch release workflow

libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.spec.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/test-helpers.ts, libs/react-helpers/src/hooks/use-form-values.ts, libs/ui-toolkit/src/components/slider/percentage-slider.tsx
Closes #6187
Allow toggle of size between base and quote asset.
There are no changes in order submission. If quote asset is used size is calculated base on price and notional.
=> feat(deal-ticket): allow toggle of size between base and quote asset

yarn.lock
```
❯ npx update-browserslist-db@latest                                                                                                                       ─╯
Need to install the following packages:
update-browserslist-db@1.0.16
Ok to proceed? (y) y
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
Latest version:     1.0.30001620
Installed version:  1.0.30001561
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ yarn add -W caniuse-lite
warning Resolution field "@storybook/react-docgen-typescript-plugin@1.0.6--canary.9.cd77847.0" is incompatible with requested version "@storybook/react-docgen-typescript-plugin@1.0.6--canary.9.0c3f3b7.0" …
```
=> chore(explorer,trading,governance): update browserlist

apps/trading/client-pages/markets/open-markets.spec.tsx, apps/trading/client-pages/markets/use-column-defs.tsx
Closes N/A
Sort by 24h vol markets active. 
=> fix(trading): sort markets by 24h vol

libs/ui-toolkit/src/components/toast/toasts-container.tsx
Closes #6432 
Increases toast container z-index so that toasts appear over the top of dialog overlays
=> chore(trading): bring toast to the front so it appears on top of dialogs

libs/ui-toolkit/src/components/dialog/dialog.tsx
Closes #6430
- Reduce amount of padding below the dialog content. This was there to ensure you could scroll beneath the dialog but ultimately if the viewport was a specific size (wide but not tall) would cause scroll bars to appear when they weren't necessary
- Remove a useEffect/className toggle that had no effect on functionality
=> fix(ui-toolkit): unnecessary scroll bars appearing due to large padding

nx.json
`nx.json` contains a revoked read/write nx cloud token. This PR replaces it with a read only token
Issue reported via https://vega.xyz/bug-bounties
=> ci(explorer,trading,governance): replace revoked token

.github/workflows/publish-dist.yml, apps/trading/project.json, nx.json
We previously used https://nx.dev/deprecated/runtime-cache-inputs to ensure we didn't cache config between environments. Since upgrading NX, this config has not been doing anything and is distracting.
- remove cache inputs
=> chore(trading,explorer,governance): remove deprecated nx configuration

libs/emblem/src/components/market-emblem.tsx
Closes #6497
The Enbken component for markets, specifically for spot markets, where the chain logos were shown, would use the chain of the quote asset for both chain icons. After this fix, it uses the correct chain for each asset.
- Fix base asset chain logo
=> fix(emblem): fix incorrect base asset chain logo for spot markets

.github/workflows/ci-cd-trigger.yml
N/A
Fixes an problem where mainnet mirror was not deploying
=> chore(trading,governance,explorer): include mainnet-mirror in ci-cd-trigger check

apps/trading/components/rewards-container/reward-card.tsx
Closes #6407 
Games that are ending have a weird 0 on the cards. 
Fixes this: 
=> fix(trading): translation for epochs ends in count

apps/trading/lib/hooks/use-squid-router-config.ts, libs/emblem/src/components/asset-emblem.tsx, libs/emblem/src/components/contract-emblem.tsx, libs/emblem/src/components/lib/url-builder.test.ts, libs/emblem/src/components/lib/url-builder.ts, libs/emblem/src/index.ts
- **fix(trading): allow arbitrum assets to have icons in squid**
- **feat(emblem,trading): add url builder for emblem and use it in squid config**
Closes #6509
The experimental Squid cross-chain deposit widget was incorrectly rendering a blank logo for Arbitrum USDT. This was down to a leftover bit of logic that was easy to remove, but also gave us a chance to standardise the logo generation. Now Emblem and squid config use the same function to build image URLs
- Add url-builder to emblem
- Update squid config to use url-builder
- Remove flag that hardcodes arbitrum logos to be blank
=> feat(emblem,trading): add url builder for emblem

apps/trading/components/sidebar/sidebar.tsx
Closes #6484  
Fix the slider scale being trimmed on the left and right sides. 
=> fix(trading): cropping of sidebar elements

apps/trading/lib/hooks/use-squid-router-config.ts
Closes #6507 
Filters assets provided to the squid router config. Only arbitrum assets are kept, this locks the 'swap to' asset
=> chore(trading): limit swap assets to only arbitrum ones

libs/deal-ticket/src/components/deal-ticket-validation/margin-warning.tsx, libs/deal-ticket/src/components/deal-ticket-validation/not-enough-error.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/constants.ts, libs/i18n/src/locales/en/deal-ticket.json
Closes #6554
Removes use of margin account balances when calculating if there is enough collateral for a spot trade
=> feat(trading): add error type for not enough collateral for spot orders

libs/ui-toolkit/src/components/toast/toasts-container.tsx
Closes #6432 
Enables pointer events for toast container
=> fix(ui-toolkit): ensure toast can be interacted with even when a dialog is open

libs/deposits/src/lib/use-deposit-balances.ts
N/A
Wraps the refetch balances function in useCallback so as not to trigger a render loop
=> fix(deposits): fix render loop after refetching balance

apps/explorer/src/app/routes/validators/validators-page.tsx, apps/governance/src/routes/tranches/tranche.tsx, libs/accounts/src/lib/accounts-actions-dropdown.tsx, libs/assets/src/lib/asset-details-table.tsx, libs/deposits/src/lib/approve-notification.tsx, libs/deposits/src/lib/deposits-table.tsx, libs/deposits/src/lib/faucet-notification.tsx, libs/environment/src/components/block-explorer-link.tsx, libs/environment/src/components/index.ts, libs/environment/src/hooks/use-links.ts, libs/markets/src/lib/components/market-info/market-info-panels.tsx, libs/web3/src/lib/ethereum-transaction-dialog/dialog-rows.tsx, libs/web3/src/lib/use-ethereum-transaction-toasts.tsx, libs/withdraws/src/lib/withdrawals-table.tsx
=> chore(trading): rename external block explorer link

apps/explorer/src/app/components/txs/details/proposal/batch-item.spec.tsx, apps/explorer/src/app/components/txs/details/proposal/batch-item.tsx, apps/explorer/src/app/components/txs/details/proposal/proposal-date.spec.tsx, apps/explorer/src/app/components/txs/details/proposal/proposal-date.tsx, apps/explorer/src/app/components/txs/details/proposal/summary.tsx, apps/explorer/src/app/components/txs/tx-order-type.tsx
Minor improvements to the batch proposal view:
- show title for new market view
- reorganise state updates to be 'verb' 'market name' (e.g. suspend USDT/ETH)
- improve spacing
- add type label for new spot markets (closes #6518)
- fix date parsing
- fix word breaks on batch proposal titles
=> feat(explorer): improve batch proposal summary view

apps/trading/client-pages/portfolio/portfolio.tsx, apps/trading/client-pages/swap/swap.tsx, apps/trading/components/swap/swap-container.tsx, apps/trading/components/swap/swap-form.tsx, libs/deal-ticket/src/components/deal-ticket-validation/zero-balance-error.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx
=> feat(trading):  add deposit and connect prompt to the spot swap UI

apps/trading/components/market-header/mobile-market-header.tsx, libs/emblem/src/components/asset-emblem.tsx
Closes N/A
Adjust asset emblem chain logo.
=> fix(trading): asset emblem chain logo

.github/workflows/cypress-run.yml, .github/workflows/trading-e2e-test-run.yml
- There are new scripts to install vega and capsule on the servers. We should run it before start capsule. It takes like 15s.
=> feat(ci): update runner

libs/accounts/src/lib/accounts-manager.tsx
N/A
Changes sidebar to only show enabled assets, otherwise you get two version of usdt arb showing
=> fix(trading): only show enabled assets in sidebar

apps/trading/components/market-banner/market-update-state-banner.tsx
N/A
Small styling change to ensure the text aligns in the market header
before
after
=> fix(trading): text alignment in market update banner

apps/trading/pages/index.page.tsx
Closes #6595 
Disables input zoom on safari which would break the deal ticket layout
=> fix(trading): input zoom on safari

apps/trading/client-pages/markets/mobile-buttons.tsx
N/A
The mobile view was still using the old depoist ui, this switches to use the new version
=> chore(trading): switch to use new deposit container on mobile

apps/trading/components/margin-mode/margin-mode.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-stop-order.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.spec.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/components/deal-ticket/side-selector.tsx, libs/deal-ticket/src/components/deal-ticket/submit-button.tsx, libs/deal-ticket/src/components/deal-ticket/type-selector.tsx
#6574 
- Changes type selector ui
- Makes a specific deal ticket submit button so it can be shared between stop and normal orders
- Adjusts components to not create spacing with margin (that should be the responsibility of the parent)
=> feat(trading): deal ticket type selector

apps/trading/components/sidebar/sidebar.tsx
N/A
Removes bg color for the asset card accordion trigger, instead letting the header bg color show which includes the hover state.
=> fix(trading): hover color for asset card in sidebar

apps/trading/lib/apollo-client.ts
N/A
Fixes a bug where switching nodes for the trading app would not recreate the apollo client
=> fix(trading): node switch not recreating client

libs/assets/src/lib/asset-details-table.spec.tsx, libs/assets/src/lib/asset-details-table.tsx
Closes #6508
USDTT has a lifetime deposit limit of 115792089237316195423570985008687907853269984665640564039457584007913129639935, which when formatted is a very very long number. This broke the table. This very large number is *effectively* unlimited, so this fix changes it to show that for very very large numbers. It is quite a dumb fix that could break, say if the asset was precise to a very large number of decimal places, but this is not true for any current asset.
=> fix(trading,explorer): show unlimited in asset details for large numbers

apps/trading/components/accounts-container/sidebar-accounts-container.tsx, apps/trading/components/deposit-container/deposit-container.tsx, apps/trading/components/withdraw-container/withdraw-container.tsx, libs/accounts/src/lib/accounts-actions-dropdown.tsx, libs/accounts/src/lib/transfer-form.spec.tsx, libs/accounts/src/lib/transfer-form.tsx, libs/assets/src/lib/asset-option.tsx, libs/ui-toolkit/src/components/trading-select/select.spec.tsx, libs/ui-toolkit/src/components/trading-select/select.stories.tsx, libs/ui-toolkit/src/components/trading-select/select.tsx
N/A
Fixes display of asset dropdown
=> fix(accounts): broken display of asset dropdown in transfer form

apps/trading/components/margin-mode/margin-mode.tsx, apps/trading/e2e/tests/deal_ticket/test_basic.py, libs/datagrid/src/lib/cells/market-name-cell.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket-margin-details.tsx, libs/deal-ticket/src/components/deal-ticket/deal-ticket.tsx, libs/deal-ticket/src/components/deal-ticket/future-cap-info.tsx, libs/i18n/src/locales/en/deal-ticket.json, libs/i18n/src/locales/en/markets.json, libs/i18n/src/locales/en/trading.json, libs/markets/src/lib/components/market-info/market-info-panels.tsx, libs/markets/src/lib/market-utils.ts, libs/markets/src/lib/product.ts, libs/positions/src/lib/positions-data-providers.ts, libs/positions/src/lib/positions-table.tsx, libs/positions/src/lib/positions.mock.ts, libs/types/src/global-types-mappings.ts, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-monitor.tsx, libs/ui-toolkit/src/components/icon/vega-icons/svg-icons/icon-pause.tsx
Closes #6591 
- Properly handles size calculation when in notional mode
- Adds potential return data underneath the ticket
- Always shows cap/binary data in market info
- Shows margin mode in all markets except if fully collateralised
=> feat(trading): changes for fcap markets

.github/workflows/previews.yml
Closes #6217 
Changes preview github action to use mirror by default unless its the next branch
=> ci(trading,explorer,governance): use mirror by default unless next branch

libs/accounts/src/lib/transfer-form.tsx
Closes #6648 
Asset balance was being formatted by decimal places twice
=> fix(accounts): incorrect asset balance shown on transfer form

apps/trading/lib/hooks/use-assets-with-balance.ts
Closes #6652 
Filtering out all assets meant that if your wallet isn't connected we were not showing any assets in the dropdown. By keeping them in the selected asset is always present
=> fix(trading): dont filter out assets without balance in deposit form

apps/explorer/src/app/components/links/market-link/market-link.tsx, libs/ui-toolkit/src/components/breadcrumbs/breadcrumbs.tsx
Closes #6634
Fixes the alignment of Emblems in MarketLinks
=> fix(explorer): emblem alignment

apps/trading/.env.testnet, libs/environment/src/hooks/use-environment.ts
=> chore(trading): use n06 node by default on testnet

.github/actions/run-vegacapsule/action.yml, apps/explorer-e2e/README.md, apps/governance-e2e/README.md, apps/governance/project.json
Changes:
1. Allow dev server for governance to listen on all interfaces not only on 127.0.0.1(localhost) - it helps to debug and allow access from the external network.
2. Cleanup leftover processes before start new vegacapsule network(it looks like sometimes vega wallet - started by GH action - sometimes is not stopped properly)
3. Adding steps to troubleshoot on remote serer.
=> fix(ci): governance tests

apps/trading/components/navbar/navbar.tsx
Closes #6465 
Fixes node health indicator not showing on Safari on ios
=> fix(trading): display of node health on mobile

apps/governance-e2e/src/integration/view/wallet-eth.cy.ts, apps/governance/src/components/vega-wallet/Delegations.graphql, apps/governance/src/components/vega-wallet/__generated__/Delegations.ts, apps/governance/src/components/vega-wallet/hooks.ts, apps/governance/src/components/wallet-card/wallet-card.tsx, apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards-table.spec.tsx, apps/governance/src/routes/rewards/epoch-individual-rewards/epoch-individual-rewards-table.tsx, apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.spec.ts, apps/governance/src/routes/rewards/epoch-individual-rewards/generate-epoch-individual-rewards-list.ts, apps/governance/src/routes/rewards/epoch-total-rewards/epoch-total-rewards-table.spec.tsx, apps/governance/src/routes/rewards/epoch-total-rewards/epoch-total-rewards-table.tsx
Closes #6531 
* adds chain name and icon to the wallet breakdown
* adds icons to rewards page
N/A
=> feat(governance): assets chain names and icons

apps/trading/components/accounts-container/sidebar-accounts-container.tsx, apps/trading/components/deposit-container/deposit-container.tsx, apps/trading/components/sidebar/sidebar.spec.tsx, apps/trading/components/sidebar/sidebar.tsx, apps/trading/e2e/tests/deal_ticket/test_trading_deal_ticket_submit_account.py
Closes #6651 
* `onDeposit` handler opens sidebar inner view instead of navigating away to the standalone page
https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/264cf248-4b7d-4e49-8e30-06f0e7b83f70
N/A
=> chore(trading): deposit prompt to open the sidebar

apps/trading/client-pages/competitions/competitions-game.tsx
N/A
Fix to handle a case where scores are in the last rank
=> fix(trading): last game rank overlap

libs/ui-toolkit/src/components/toast/toasts-container.tsx
N/A
Fix an issue where closing a toast without an onClose handler wouldn't remove it from the store.
=> fix(ui-toolkit): add default on close functionality for toasts

libs/emblem/src/components/emblem-base.tsx
N/A
Gives emblems a bg color that matches the border color to avoid visual overlapping of the svg images
=> fix(emblem): give emblems a bg color

libs/emblem/src/components/emblem-base.test.tsx, libs/emblem/src/components/emblem-base.tsx, libs/emblem/src/components/market-emblem.test.tsx, libs/emblem/src/components/market-emblem.tsx, libs/emblem/src/config/index.ts
Closes #6517. Closes #6564.
Simplify the loading to make it a bit less jumpy. This is particularly for Market emblems, but 
changes the loading of EmblemBase so all should load slightly quicker.
- Add a transparent loading image, rather than the flash-of-black loading image
- Add base64 encoded loading & missing images, rather than loading blank images over the network
- Remove loading/useState listener on EmblemBase
=> feat(emblem): simplify loading and use transparent image instead of black for loading

apps/explorer/src/app/config/env.ts, apps/explorer/src/app/routes/oracles/components/oracle-data.tsx, apps/explorer/src/app/routes/oracles/components/oracle-signers.tsx, apps/explorer/src/app/routes/oracles/components/oracle-verified-status-icon.tsx, apps/explorer/src/app/routes/oracles/components/oracle.tsx, libs/markets/src/index.ts
- **chore(markets): export extra components from market lib to aid consistency**
- **feat(explorer): add oracle logos and verified status to oracle by id page**
Closes #6630
Reuses some of the well-known oracle functionality from Trading/markets lib to display a logo/verification status on the oracle page in explorer.
=> feat(explorer): use well-known oracle data on explorer oracle by id page

libs/accounts/src/lib/account-card.tsx
N/A
Allow account cards to be expanded in read only mode so you can see the account breakdown
=> feat(trading): allow asset card to be expanded even if in read only mode

libs/markets/src/lib/components/market-info/market-info-panels.tsx
Closes #6674
Add the market's insurance account balance to the market details page on Explorer. The Global Insurance Account balance is still present, in the settlement asset panel. 
Note: Vercel build error is unrelated to this PR.
=> feat(markets): add market insurance account to key market details

apps/explorer/src/app/components/txs/details/proposal/summary.tsx, apps/explorer/src/app/components/txs/details/tx-proposal-vote.tsx
Closes #3698
Closing off an easy old ticket. Proposal vote txs now show the proposal rationale (title and description). Previously they showed just a title in the details table at the top.
=> feat(explorer): show the proposal ratioale component on proposal votes

apps/explorer/src/app/routes/validators/validators-page.tsx
Closes #3152
The original issue requested a description for the frequently changing Proposer Priority field. This PR instead just removes it. Proposer priority is only relevant for the Tendermint/CometBFT priority of the validator's place (see: https://docs.cometbft.com/v0.37/spec/consensus/proposer-selection) and the changes are not useful or meaningful for the explorer to display as the results are so short lived. Instead of displaying & explaining it, we're better of just not rendering it.
=> fix(explorer): remove proposer priority chart

apps/trading/components/asset-activity/asset-activity.tsx, apps/trading/components/asset-activity/withdrawal-status-cell.tsx, apps/trading/pages/styles.css, libs/accounts/src/lib/transfers-data-provider.ts
Closes #6101 
- Makes useTransfers just use generated query so that polling does not reset the data causing extra mounts/unmounts
- Remove the connectkit button and instead prompt connection and send tx using the same click handler.
- Replace 'view' button link with info icon
- Change complete button link to secondary button
- Highlight pinned withdraw rows with a light blue background
=> feat(trading): asset activity withdrawal completion flow

.github/workflows/cypress-run.yml
Closes #6810
e2e tests are failing because 0.77.0 is *ancient*. v0.78.0-preview.1 has been tagged for 20 minutes by now
=> ci(governance): update vega and capsule for e2e runs

apps/trading/components/asset-activity/use-asset-activity.ts, apps/trading/components/asset-activity/withdrawal-status-cell.tsx, libs/web3/src/lib/use-vega-transaction-updater.tsx
N/A
- Fixes an issue where it was possible for rejected withdrawals to not be shown rejected in the activity table
- Fixes an issue where rejected withdrawals were not getting updated with the right state due to multiple events being emitted in a single batch
- Fixes rejected withdrawals from being pinned in the table
=> fix(trading): withdrawal issues

apps/trading/pages/styles.css, libs/tailwindcss-config/src/theme.ts
No need to set `border-COLOR dark:border-ABOTHER-COLOR` anymore if the element should have the default border color.
=> chore(trading): default border color

libs/accounts/src/lib/transfers-data-provider.ts
N/A
The polling of transfers was causing the withdrawal status component to unmount and remount thus triggering an rpc call for the withdrawal delay time on every mount.
=> fix(trading): fix too many rpc calls

apps/trading/client-pages/competitions/competitions-game.tsx
Closes #6871 
Fetches scores from the end of the list to ensure the latest results are shown
=> fix(trading): get last score results for historic games

apps/explorer/src/app/components/blocks/blocks-refetch.tsx, apps/explorer/src/app/components/links/external-explorer-link/external-chain-icon.tsx, apps/explorer/src/app/components/size-in-market/size-in-market.tsx, apps/explorer/src/app/components/txs/details/chain-response-code/chain-reponse.code.tsx, apps/explorer/src/app/components/txs/details/tx-amm-amend.tsx, apps/explorer/src/app/components/txs/details/tx-amm-submit.tsx, apps/explorer/src/app/components/txs/tx-filter-label.tsx, apps/explorer/src/app/components/txs/tx-list-navigation.tsx, apps/explorer/src/app/components/txs/tx-order-type.tsx, apps/explorer/src/app/components/txs/txs-infinite-list.tsx, apps/explorer/src/app/components/vote-icon/vote-icon.tsx
Closes #6627
Fixes the feedback on the initial AMM tx views for submit and amend:
- Update `proposedFee` to display as percentage
- Update `slippageTolerage` to display as percentage
- Update `commitmentAmount` to be displayed in the correct asset decimals instead of market decimals
- Update `<SizeInMarket />` component to allow labels to be displayed and asset decimals to be used
=> fix(explorer): improve AMM submit and amend views

apps/trading/components/ticket/fields/notional.tsx, apps/trading/components/ticket/fields/price.tsx, apps/trading/components/ticket/info/notional.tsx
Closes #6896 
* uses `quoteName` instead of settlement asset symbolf for notional and price fields in the deal ticket
=> fix(trading): notional label

apps/explorer/src/app/routes/parties/id/components/party-block-stake.tsx, apps/explorer/src/app/routes/parties/id/components/party-block.tsx
Closes #6893
The 'Staked to Validator' row on a party page was calculated incorrectly. As the method for correctly
calculating this field is too convoluted, I have simply removed it. There is also no good page on 
explorer to link to for a specific party's stake, so I did not add a link out to that.
=> fix(explorer): remove incorrect staked to validator field

apps/explorer/.env
Closes #6924
Fairground explorer is currently broken, as these variables are missing
=> fix(explorer): add missing environment variables

apps/trading/client-pages/competitions/competitions-game.tsx
Closes #6902
The label and epoch display were slightly confusing. They were correct, if you read 'Next payout at'
to mean 'Next payout occurs at the start of epoch XXX'. However issue #6902 seemed to interpret it as
'Next payout occurs at the end of epoch XXX +1' and thus it looked wrong. So this PR simply returns
the current epoch.
An alternative solution would be to change the label to be clearer. But there's not much space.
=> fix(trading): update game next payout epoch to be current

apps/trading/components/navbar/navbar.spec.tsx, apps/trading/components/vega-wallet-connect-button/vega-wallet-connect-button.spec.tsx, libs/wallet-react/src/hooks/use-eager-connect.ts, libs/wallet-react/src/hooks/use-vega-wallet.ts, libs/wallet/src/types.ts, libs/wallet/src/wallet.ts
Related #6927 
Using the pubkey which is persisted to localstorage would allow a component to get the pubkey of the previously connected wallet while the wallet was not actually connected.
Created a previousKey property to be persisted as well that would allow for selecting the previous key without conflating the ideas of the previously connected public key and the currently connected public key.
=> fix(wallet,wallet-react): persisting previous key without pretending to be connected

.github/workflows/previews.yml, .github/workflows/publish-dist.yml, .github/workflows/release-console.yml
Closes #6942
This should make deploy previews for pull requests point at testnet, instead of the now-dead mainnet-mirror.
=> ci(trading,explorer,governance): make deploy previews use testnet

apps/trading/client-pages/invite/step-connect.tsx
N/A
Exits the connect step if its not valid
=> fix(trading): exit invite process if the step connect isn't found

apps/trading/client-pages/competitions/competitions-create-team.tsx
Closes #6790
Hide some additional text that does not make sense when the create team upgrade is for a
'solo team'.
=> fix(trading): do not show existing referees text for solo players

apps/trading/components/ticket/info/fees-breakdown.spec.tsx, apps/trading/components/ticket/info/fees-breakdown.tsx, apps/trading/components/ticket/info/fees.tsx
Closes #6752 
- Formats discount percentage with 2 dps
- Removes maker rebate from ticket fees
=> fix(trading): decimal places for percentage values, remove maker rebate from ticket

libs/browser-wallet/src/frontend/routes/auth/settings/home/sections/export-recovery-phrase-section/export-recovery-phrase-section.tsx
=> fix(trading,browser-wallet): exporting recovery phrase after opening

apps/trading/components/ticket/elements/submit-button.tsx
Closes #6974 
* adds "loading" state to the ticket submit button
* gets the colour based on the side and changes only when needs to Connect or Deposit
https://github.com/user-attachments/assets/e79554b6-e610-48a9-b6bb-144f87455d79
Instead of rendering 3 buttons it is now combined into one to avoid strange flickering
=> fix(trading): ticket submit button

libs/browser-wallet/src/frontend/components/navbar/navbar.spec.tsx, libs/browser-wallet/src/frontend/components/navbar/navbar.tsx, libs/browser-wallet/src/frontend/routes/auth/wallets/home/wallets.spec.tsx, libs/browser-wallet/src/frontend/routes/auth/wallets/home/wallets.tsx
Change title and nav item of wallet to be keys as multi wallet is not a thing
=> fix(trading,browser-wallet): wallet page title and navbar

libs/browser-wallet-backend/src/lib/setup-listeners.js, libs/browser-wallet-backend/src/src/client-ns.js
Fixes the fact auto consent was always disabled due to a syntax error
Enables autoConsent by default
=> feat(trading,browser-wallet): enable auto consent by default, fix auto consent always failing

libs/browser-wallet/src/frontend/components/modals/transaction-modal/sections/raw-transaction.tsx
N/A
Keep transaction details collapsed by default
=> chore(browser-wallet): collapse raw tx by default

apps/trading/client-pages/competitions/competitions-game.tsx
N/A
- Removes formatting decimal places for the targetNotionalVolume value when a games rewards are scaled
- Adds asset symbol for the score unit for relative return games
=> fix(trading): dps for target notional vol

apps/trading/components/asset-activity/withdrawal-status-cell.tsx, apps/trading/components/withdraw-container/withdraw-container.tsx, apps/trading/components/withdrawals-indicator/withdrawals-indicator.tsx, apps/trading/lib/hooks/use-incomplete-withdrawals.ts, libs/smart-contracts/src/abis/erc20_bridge_abi.json
Closes #6836 
- Fix the witthdrawal delay notifications on the withdrawal form
- Fix the count of withdrawals that are ready, as the delay was not being found so being incorrectly reported
- Fix the amount of withdrawals being trippled in copy for no specific reason
The ABIs were out of date and did not include the function defaultWithdrawalDelay. Moreover the contract function calls were still snake case rather than camelCase causing 2 separate issues.
=> chore(trading): fix withdrawal delay notifications, fix incomplete withdrawals notifications

apps/trading/components/browser-wallet-dialog/index.tsx, libs/browser-wallet/src/frontend/components/modals/transaction-modal/transaction-header.spec.tsx, libs/browser-wallet/src/frontend/components/modals/transaction-modal/transaction-header.tsx, libs/browser-wallet/src/frontend/components/modals/transaction-modal/transaction-modal.spec.tsx, libs/browser-wallet/src/frontend/components/modals/transaction-modal/transaction-modal.tsx, libs/browser-wallet/src/frontend/components/receipts/orders/stop-submission/submission.tsx, libs/browser-wallet/src/frontend/components/vega-section/vega-section.tsx, libs/browser-wallet/src/frontend/hooks/persist-location/index.tsx, libs/browser-wallet/src/frontend/hooks/persist-location/persist-location.spec.tsx, libs/browser-wallet/src/frontend/hooks/redirect-path/index.tsx, libs/browser-wallet/src/frontend/routes/auth/transactions/details/transaction-metadata.spec.tsx, libs/browser-wallet/src/frontend/routes/auth/transactions/details/transaction-metadata.tsx, libs/browser-wallet/src/frontend/routes/auth/transactions/home/transactions-list/transactions-list.tsx, libs/browser-wallet/src/frontend/routes/auth/transactions/transaction-state.spec.tsx, libs/browser-wallet/src/frontend/routes/auth/transactions/transactions-state.tsx
Closes #6935
Reduces padding and rearrange tx receipt views to enable most receipts to be rendered without scrollbars.
Includes minor bug fixes:
- Colours for rejected and confirmed txs were nearly invisible
- Show price in terms of asset for stop order receipts 
- Adjust padding on tx list so it looks sensible
=> chore(browser-wallet,trading): make receipts fit on a single screen

apps/trading/components/market-selector/market-selector.tsx
Closes #6975
Add padding to the bottom of the market selector drop down.
=> chore(trading): add padding to drop down

apps/trading/components/ticket/derivative/feedback-stop.tsx, apps/trading/components/ticket/derivative/feedback.tsx, apps/trading/components/ticket/spot/feedback.tsx
Closes #6974
Prevents the ticket from appearing to flash while loading, moving the deal ticket button around sometimes which can look fairly unpleasant.
Do not show anything while loading to prevent previous state from causing flashes on the ticket while reloading.
=> fix(trading): only render feedback after loading has completed
